### ISSUE TITLE
Hook interface

### ISSUE THREAD

**Issue by orens77** [VowpalWabbit/vowpal_wabbit#1413]
Is it possible that the search_hooktask interface is currently broken in master?  

I've been trying build master with python3.6 and I haven't been able to get the python learning-to-search examples to work.  I also tried to run the library/test_search.cc example that also uses the hook interface and found that one was segfaulting too.  

The other tests all seem fine in my build environment but if the hook interface is working properly for everyone else then I'm definitely doing something wrong.

**Comment by floft** [comment]
I'm suspecting this is the same issue. If I run "Learning_to_Search.ipynb" after the "sequenceLabeler = vw.init_search_task(SequenceLabeler)" line I get:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-d9a5c43a2faa> in <module>()
----> 1 sequenceLabeler = vw.init_search_task(SequenceLabeler)

/usr/lib/python3.6/site-packages/vowpalwabbit/pyvw.py in init_search_task(self, search_task, task_data)
    280 
    281         sch.predict = predict
--> 282         num_actions = sch.get_num_actions()
    283         return search_task(self, sch, num_actions) if task_data is None else search_task(self, sch, num_actions, task_data)
    284 

RuntimeError: std::exception
```

**Comment by evalkaz** [comment]
Running [test_search_ldf.py](https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/examples/test_search_ldf.py) example I encounter the same problem:

```
set_structured_predict_hook: trying to set hook when search task is not 'hook'!
Traceback (most recent call last):
  File "test_search_ldf.py", line 55, in <module>
    sequenceLabeler = vw.init_search_task(SequenceLabeler)
  File "/home/evaldas/.conda/envs/ml/lib/python3.6/site-packages/vowpalwabbit/pyvw.py", line 282, in init
_search_task
    num_actions = sch.get_num_actions()
RuntimeError: std::exception
```

**Comment by temcinas** [comment]
I get exactly the same problem as @floft when running the Learning_to_Search.ipynb on python 2.7:
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-d9a5c43a2faa> in <module>()
----> 1 sequenceLabeler = vw.init_search_task(SequenceLabeler)

/home/temcinas/Envs/entities/local/lib/python2.7/site-packages/vowpalwabbit/pyvw.pyc in init_search_task(self, search_task, task_data)
    280 
    281         sch.predict = predict
--> 282         num_actions = sch.get_num_actions()
    283         return search_task(self, sch, num_actions) if task_data is None else search_task(self, sch, num_actions, task_data)
    284 

RuntimeError: std::exception
`

**Comment by HelgeS** [comment]
I have encountered the same issue.

Here is a [Google Colab notebook](https://colab.research.google.com/drive/19i633wxnFGTKN6kK9r3L4d-FHOBkIqmF) to reproduce the error (based on [test_search.py](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/test_search.py)):

**Comment by jprobichaud** [comment]
I'd like to add my "me too" here.  I've reverted to 8.2.1 and it works sightly better.  The whole thing runs but core dumps at the end.

**Comment by jprobichaud** [comment]
With a bit of debugging, I get this message now on master:
```set_structured_predict_hook: trying to set hook when search task is not 'hook'!
```
and hacking the pylibvw to print the actual task name, I get:
```set_structured_predict_hook: trying to set hook when search task is not 'hook' but instead []
```

So somehow, task_name isn't being set...  Is that the only thing not being initialized properly?  Probably not.  Commenting out the content of `verify_search_set_properly` and running the simple POS test example generates a core-dump...

**Comment by jprobichaud** [comment]
Oh, note that I have to go back to 8.2.1 for the L2S interface to be working again

**Comment by lokitoth** [comment]
I have test_search.py working, but test_search_ldf.py is still failing (on assertion in pyvw.py around line 270: `assert oracle > 0, 'multiclass labels are from 1..., please do not use zero or bad things will happen!'`).

My guess is that this is a separate issue from the root bug, so I would like to get the current fixes in, and will reopen a new bug focusing on the LDF issues.

**Comment by JohnLangford** [comment]
Sounds god.
