### ISSUE TITLE
[Python] [sklearn] Text features as input to sklearn interface

### ISSUE THREAD

**Issue by mlisovyi** [VowpalWabbit/vowpal_wabbit#1472]
Hi all,

Is there an example on how to use **text features in the VW sklearn API**? I can not make the `sklearn_vw.tovw()` function work. I'm interested in this function because tovw is used by sklearn_vw.VW to convert the regular input into VW-compatible format. There seems to be 2 separate problems, both related to `sklearn.datasets.svmlight_format.dump_svmlight_file()` usage by `tovw`. The first is a small feature, which can be worked around by additional type casting, but the second is unclear to me.

1). There is a mis-handling of pandas.Series objects as an input, which seems to be due to the dtype being `'object'`. Below is a dummy example to reproduce the problem:
```python
import pandas as pd
import numpy as np
from vowpalwabbit.sklearn_vw import tovw

X = pd.Series(['cat', 'dog', 'cat', 'cat'], name='catdog')
y = pd.Series([-1, 1, -1, -1], name='label')

tovw(X, y)
```
The output is 
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-705a017a4383> in <module>()
      8 y = pd.Series([-1, 1, -1, -1], name='label')
      9 
---> 10 tovw(X, y)

.../vowpalwabbit/sklearn_vw.py in tovw(x, y, sample_weight)
    579     # convert input to svmlight format
    580     s = io.BytesIO()
--> 581     dump_svmlight_file(x, np.zeros(rows), s)
    582 
    583     # parse entries to construct VW format

.../sklearn/datasets/svmlight_format.py in dump_svmlight_file(X, y, f, zero_based, comment, query_id, multilabel)
    445                              % (yval.shape,))
    446 
--> 447     Xval = check_array(X, accept_sparse='csr')
    448     if Xval.shape[0] != yval.shape[0]:
    449         raise ValueError("X.shape[0] and y.shape[0] should be the same, got"

.../sklearn/utils/validation.py in check_array(array, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    431                                       force_all_finite)
    432     else:
--> 433         array = np.array(array, dtype=dtype, order=order, copy=copy)
    434 
    435         if ensure_2d:

ValueError: could not convert string to float: 'cat'
```
This can be resolved by passing a `np.array` or strings, i.e. calling `tovw(X.values.astype(str), y)`. This is not elegant and multiple users will bump into the same problem, but it is resolvable. However, this brings us to the second problem.

2). Giving an array of string as X input still leads to another issue with `sklearn.datasets.svmlight_format.dump_svmlight_file()`:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-42a921e37bc9> in <module>()
      2 y_a = np.array([-1, 1, -1, -1])
      3 
----> 4 tovw(X_a, y_a)

.../vowpalwabbit/sklearn_vw.py in tovw(x, y, sample_weight)
    579     # convert input to svmlight format
    580     s = io.BytesIO()
--> 581     dump_svmlight_file(x, np.zeros(rows), s)
    582 
    583     # parse entries to construct VW format

.../sklearn/datasets/svmlight_format.py in dump_svmlight_file(X, y, f, zero_based, comment, query_id, multilabel)
    476 
    477     if hasattr(f, "write"):
--> 478         _dump_svmlight(X, y, f, multilabel, one_based, comment, query_id)
    479     else:
    480         with open(f, "wb") as f:
.../sklearn/datasets/svmlight_format.py in _dump_svmlight(X, y, f, multilabel, one_based, comment, query_id)
    352             row = zip(np.where(nz)[0], X[i, nz])
    353 
--> 354         s = " ".join(value_pattern % (j + one_based, x) for j, x in row)
    355 
    356         if multilabel:
.../sklearn/datasets/svmlight_format.py in <genexpr>(.0)
    352             row = zip(np.where(nz)[0], X[i, nz])
    353 
--> 354         s = " ".join(value_pattern % (j + one_based, x) for j, x in row)
    355 
    356         if multilabel:

TypeError: only size-1 arrays can be converted to Python scalars
```

**Environmental setup**
Ubuntu 16.04 with conda 4.5.1 and python3.5 
vowpalwabbit  8.5.0 (installed from pypi), scikit-learn 0.19.1, numpy  1.14.2

Any feedback/help would be appreciated.

Cheers,
Misha

**Comment by JohnLangford** [comment]
Thanks Misha for this very detailed explanation.   @gramhagen do you want to take a look at this?

**Comment by Scott-Graham-Bose** [comment]
the tovw() function is not built to accept text input. the expectation is that the user would get the input into a numeric format as would be used for other sklearn models, so in this case you would need to do some vectorization of the input first.

```
>>> import pandas as pd
>>> from sklearn.feature_extraction.text import HashingVectorizer
>>> from vowpalwabbit.sklearn_vw import tovw

>>> X = pd.Series(['cat', 'dog', 'cat', 'cat'], name='catdog')
>>> y = pd.Series([-1, 1, -1, -1], name='label')

>>> hv = HashingVectorizer()
>>> hashed = hv.fit_transform(X)

>>> tovw(x=hashed, y=y)
['-1 1 | 300839:1', '1 1 | 980517:-1', '-1 1 | 300839:1', '-1 1 | 300839:1']
```

**Comment by mlisovyi** [comment]
ah, ok, this was not clear from the in-code documentation, and the main package documentation highlights internal text hashing as an important feature. One would need to have a look, where a remark about it would fit .

**Comment by Scott-Graham-Bose** [comment]
maybe the easiest thing to do here is expand the tovw() method documentation to make this clearer?

**Comment by jackgerrits** [comment]
I've created PR #1999 to address the documentation issue.

See the updated doc hosted here: https://vowpalwabbit.github.io/docs/vowpal_wabbit/python/build/html/vowpalwabbit.sklearn.html
