### ISSUE TITLE
Java API oddity (Contextual Bandits)

### ISSUE THREAD

**Issue by matanster** [VowpalWabbit/vowpal_wabbit#1482]
I might be hallucinating, but it seems that the java API is inconsistent here with regard to the index semantics of the actions:

When reporting costs to the model (method `learn`), it needs to be 1-indexed; otherwise you get: 
> invalid action: 0

However, in the distribution returned when predicting (method `predict`), the actions are clearly 0-indexed, as seen in this example value of the returned distribution object:
> [ActionProb{action=0, probability=0.05}, ActionProb{action=1, probability=0.95}]

This seems to be the case for models initialized with `--cb_explore`, `--epsilon`.

**Comment by palmerlao** [comment]
We've also observed this with `--cb_adf`.

**Comment by matanster** [comment]
@palmerlao thanks for the note. Obviously both our code-bases are already adapted to it, but this makes it a hell when initially developing with the API, not to mention any logging and debug processes....

**Comment by JohnLangford** [comment]
This is an issue that clearly needs fixing.

**Comment by matanster** [comment]
Thanks and just to note that even being a fix, it should probably be treated as a _breaking api change_, in terms of communication upon fixing; to avoid excessive application breakage.

**Comment by JohnLangford** [comment]
I agree.

-John

**Comment by jackgerrits** [comment]
This issue is being tracked by #1841
