### ISSUE TITLE
8.6.0 make test fails

### ISSUE THREAD

**Issue by matanster** [VowpalWabbit/vowpal_wabbit#1538]
```
$make test
```

>cd test && python save_resume_test.py --verbose_on_fail
>Traceback (most recent call last):
>  File "save_resume_test.py", line 8, in <module>
>    from itertools import izip_longest
>ImportError: cannot import name 'izip_longest'
>Makefile:147: recipe for target 'test' failed
>make: *** [test] Error 1

Following the setup procedure described in https://github.com/JohnLangford/vowpal_wabbit/issues/1537

**Comment by JohnLangford** [comment]
It looks like some python module is missing.  Maybe @Scott-Graham-Bose or @denik can comment.

**Comment by denik** [comment]
I guess your system python is version 3. There izip_longest was removed to zip_longest. Try python2 instead.

**Comment by matanster** [comment]
I think, the issue is more that this taints the test suite of the entire framework, not the failure of the specific test. So it should in the least be documented or shown when `make test` is run, that python 2 is required.

**Comment by Scott-Graham-Bose** [comment]
this particular test can be adjusted to support 2 or 3 by using the following
```
from future.moves.itertools import zip_longest
```

and changing the call, happy to make a PR for that and check if any other python 2 specific changes are necessary, though I know for sure if the python bindings are built through make it will also default to using python 2 configuration flags, would be better to just use the default.

**Comment by Scott-Graham-Bose** [comment]
ok, addressing this in #1544

**Comment by jackgerrits** [comment]
Thanks for fixing this! Closing the issue
