### ISSUE TITLE
Parser warnings go to standard output instead of standard error, and corrupt the output of libvw users

### ISSUE THREAD

**Issue by adamnovak** [VowpalWabbit/vowpal_wabbit#1539]
I'm using Vowpal Wabbit as a library in a program that writes structured data to standard out.

That code managed to construct a Vowpal Wabbit example with a NaN in it. This didn't cause any errors (the program ran through successfully), but the output was corrupted, because Vowpal Wabbit injected its own text into it.

It looks like this warning code here, which prints to standard output, really [ought to](https://stackoverflow.com/q/1430956) print to standard error:

https://github.com/JohnLangford/vowpal_wabbit/blob/24233e238c3e957066014d85ce13cd3b67d996e5/vowpalwabbit/parse_example.cc#L78-L83

**Comment by arielf** [comment]
@adamnovak 
Thanks for noticing. I agree errors should go to stderr.
Could you issue a PR changing `cout` to `cerr` ?  That would be cool.
