### ISSUE TITLE
var-info for Contextual Bandits usage question

### ISSUE THREAD

**Issue by matanster** [VowpalWabbit/vowpal_wabbit#1543]
How should one interpret the output of the wonderful [`var-info`](https://github.com/JohnLangford/vowpal_wabbit/wiki/using-vw-varinfo) utility, when dealing with contextual bandits algorithms such as bagging/cover that utilize ensembles? don't we actually have multiple (separate) regression models being created in that case? we seem to get a report for only one model. Would be a great nice-to-have for model interpretability!

Many many thanks in advance!!

**Comment by matanster** [comment]
@arielf My guess would be it's currently only working for those upstream models by mistake

**Comment by arielf** [comment]
Hi @matanster 
I just updated this page:  https://github.com/JohnLangford/vowpal_wabbit/wiki/using-vw-varinfo
Please note the added section:  known issues.  I would love it if someone could look at the cleaner version (vw-varinfo2)

**Comment by matanster** [comment]
@arielf makes sense. Would there currently be a way to have VW output its `--audit` data in machine consumable way rather than as strings? arguably that would make it useful for automating various sanity tests after training a model. It can be done now as well but parsing strings is a bit less stable...

**Comment by arielf** [comment]
Hi @matanster,

Short answer: the need for a cleaner way makes sense, but there's not one that I know of.

I also wish there was a standard read/write model API that one could use to inspect the header, scale/trim weights, etc. in a binary version-independent way. e.g. think of a ad-hoc `--l1` or change number of bits, operation on an existing model.

As John likes to say: this is a "patches welcome" kind of request :)

**Comment by matanster** [comment]
Yep I was going to use that phrase myself actually :-))
Thing is, the core of present time VW is so undocumented that it's hard to walk around the code. Kind of a tradition with C++ mathy code, but nonetheless. Makes it a high barrier for entry to contribute outside the outermost periphery of the codebase.

**Comment by JohnLangford** [comment]
Documentation is certainly iffy.   Partly, I think I don't know how to
write good documentation and partly, this hasn't been a serious focus.  It
is something that I'd like to see improve over time.

If you want to work with VW, I think the most critical files are vw.h (the
current interface), global_data.h (the current top-level datastructure),
and learner.h (the learning reduction datastructure).

-John

**Comment by matanster** [comment]
Thanks a lot. Just that I'm not understood in the wrong way, it's amazing that VW has survived the Yahoo collapse and everything else and is still a well maintained project (!). I'm already using it in amazing projects that reduce novel problems to CB in some experimental ways. For example, in one reduction to CB with VW we have actions that carry monotonous semantics (i.e. action _n+1_ is always worse than action _n_, per context, and we have to find the most minimal _n_ that's good enough per context; we're actually looking for a mathematician to work out adapting/disproving some of the theorems to this scenario if we can).

**Comment by JohnLangford** [comment]
Closing this for now, but flagging as Patches Welcome.
