### ISSUE TITLE
Validator doesn't work with input format example

### ISSUE THREAD

**Issue by langmore** [VowpalWabbit/vowpal_wabbit#156]
The [data format validator](http://hunch.net/~vw/validate.html) output does not agree with the  "Example with a tag" from the [input format](https://github.com/JohnLangford/vowpal_wabbit/wiki/Input-format) page.  If that result is cut-and-paste into the validator, the importance weight "1.0" is not read.  However, if a space is put after the word _zebra_ and before the pipe "|", then the weight is correctly read.  As a result of this discrepancy, it is unclear if a space after zebra is needed.

**Comment by martinbel** [comment]
Is [Base] documented? What's it's purpose?

**Comment by someben** [comment]
According to the tutorial, [Base] is the "baseline prediction": file:///home/ben/Downloads/v6.1_tutorial.pdf

**Comment by martinbel** [comment]
Ok. It's in [tutorial 6.1](https://github.com/JohnLangford/vowpal_wabbit/wiki/v6.1_tutorial.pdf)
Thanks!
