### ISSUE TITLE
(Intervening with Doubly Robust for) Interdependent Action Costs

### ISSUE THREAD

**Issue by matanster** [VowpalWabbit/vowpal_wabbit#1561]
Hi,

I am looking to intervene in the source such as to introduce an experimental option, to assign known costs to actions either following or preceding (actions-vector-wise) the action for which a cost is provided as feedback to the model (during online operation). This should experimentally provide benefit when a cost provided for a context more directly implies the costs for other actions, such as in the scenario of online price discounting. In that scenario and others, it is common that a feedback (cost) _c_ for an action implies the same or higher/lower _c_ for all actions above/below _c_ in the actions vector (i.e., the actions vector carries monotone semantics). 

I'd be extremely happy getting pointers in the source to where to safely introduce this change, in case possible.

Thanks!

**Comment by JohnLangford** [comment]
This is more subtle than it might appear because the total probability of
observing the cost of an action should be used to debias things.

The simplest effective approach is probably to manipulate the mtr
reduction, here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/cb_adf.cc#L113

-John

**Comment by matanster** [comment]
@JohnLangford do you think that the proofs underlying Doubly Robust as well as MTR will still hold? 
We're currently experimenting from outside the VW codebase, exploding the training data and/or the online events, hence the interest in ultimately applying the manipulations inside of VW instead...

**Comment by JohnLangford** [comment]
Yes, as long as you coalesce probabilities of observations effectively.

**Comment by JohnLangford** [comment]
Closing this for now.
