### ISSUE TITLE
Multiworld testing

### ISSUE THREAD

**Issue by matanster** [VowpalWabbit/vowpal_wabbit#1565]
It's unclear what this option is for:

`vw --help`

```
Multiworld Testing Options:
  --multiworld_test arg                 Evaluate features as a policies

  --learn arg                           Do Contextual Bandit learning on <n> 
                                        classes.
  --exclude_eval                        Discard mwt policy features before 
                                        learning

```

Or whether it's intentionally part of the repo v.s. other ones. It sounds useful though.

**Comment by JohnLangford** [comment]
This is an option to do counterfactual evaluation of multiple policies.  

In the longer term, I think we want to break out counterfactual evaluation as a separate library because it's awkward as it exists right now.

**Comment by jackgerrits** [comment]
@eisber is it possible you could whip together a wiki page to give a brief description of this reduction? Or alternatively just explain here and I'll add it.

**Comment by eisber** [comment]
@JohnLangford can you confirm/correct/extend?

From the unit tests. Here's a sample input file. 
https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/test/train-sets/cb_eval2

Each feature represent a policy (:1 :2 are 2 policies, distinguished by feature index (which is implicit 0 and 1) and the first policy chose 1 as the action and the 2nd 2 as the action). The arg to multiworld_test identifies the namespace used for policies.

I think this should also work |f policy1:2 policy2:1

I think --learn would learn a new policy taking the decisions of the existing decision into account. I guess one could add additional features and drop some (though I'm not clear which ones).

**Comment by JohnLangford** [comment]
That sounds right.  The core code is this line:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/mwt.cc#L89

-John
