### ISSUE TITLE
Algorithms details

### ISSUE THREAD

**Issue by sevilaybayatli** [VowpalWabbit/vowpal_wabbit#1572]
Hello,

Is  vowpal_wabbit  just used supervised algorithms? While I was reading this tutorial, I recognized that  all algorithms are supervised. If I am wrong, please correct me? I need to use unsupervised learner and I am happy to use  vowpal_wabbit.

Thanks million for your help.

**Comment by arielf** [comment]
Generally, you are right. Most of `vw` is supervised learning.
In particular, there's no clustering support.

Exceptions:

- There are some matrix decomposition algorithms (`--rank`, `--lrq`, ... options) which are not strictly supervised.
- There's support for active learning (`--active`, `--mellowness`, `--simulation`, ... options) which is semi-supervised.
- There's indirect support for outlier/anomaly detection by real-time introspection of the streaming loss. See `utl/vw-top-errors`

**Comment by JohnLangford** [comment]
LDA is an unsupervised learning algorithm.

-John

**Comment by lokitoth** [comment]
@sevilaybayatli: Has your question been resolved?

If not, could you provide a bit more details about your specific scenario?

**Comment by jackgerrits** [comment]
Closing this issue as it seems like the question is answered. @sevilaybayatli if it is not, please go ahead and reopen it.
