### ISSUE TITLE
--Ojanewton breaks with -b 24

### ISSUE THREAD

**Issue by arielf** [VowpalWabbit/vowpal_wabbit#1592]
In the vw source tree:

```
# takes about 0.25 sec, average loss = 0.089070
vw  --OjaNewton --sketch_size=10 --alpha_inverse=1.0 -d test/train-sets/0002.dat
```

Same command with -b 24:
```
# Takes over 16 seconds, has NaNs in all examples & error jumps to 0.283062
vw  -b 24 --OjaNewton --sketch_size=10 --alpha_inverse=1.0 -d test/train-sets/0002.dat
```

**Comment by arielf** [comment]
Also noticed that `-b 20` still works reasonably well (although slower than default) and the breaking point is `-b 21`.

**Comment by JohnLangford** [comment]
I'm not sure what's wrong here.  A careful examination of the computation is required.  @haipengl do you want to take a look?

**Comment by yannstad** [comment]
The independent sample `r1` in the box-muller transform must be strictly positive. But it is chosen using merand48, that possibly returns 0:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/6ef7676bb222d8f11edaf89165fdb9e925e7b247/vowpalwabbit/OjaNewton.cc#L82
