### ISSUE TITLE
sample is not running under C#, missing Method.. no documentation at all (found)

### ISSUE THREAD

**Issue by andy-soft** [VowpalWabbit/vowpal_wabbit#1604]
Just tried to compile a sample and the method  
ParseLabel is missing on actual import (8.5)

VW.VowpalWabbitExampleBuilder exampleBuilder;

exampleBuilder.ParseLabel("1");

**Comment by jackgerrits** [comment]
Which sample did you try and build? Does the issue still exist if you use the latest master?

**Comment by JohnLangford** [comment]
I'm closing this for lack of response.  Reopen if the issue is outstanding.
