### ISSUE TITLE
vw java pom.xml openjdk11 (update maven-compiler-plugin and maven-javadoc-plugin)

### ISSUE THREAD

**Issue by josepowera** [VowpalWabbit/vowpal_wabbit#1610]
for anyone trying to compile java part in openjdk 11 (we previously run using openjdk8) - to compile java part update in openjdk11 we had to update versions in pom.xml 

maven-compiler-plugin from 3.2 to 3.8.0
maven-javadoc-plugin from 2.8.1  -> 3.0.1

https://github.com/VowpalWabbit/vowpal_wabbit/compare/master...josepowera:master

**Comment by JohnLangford** [comment]
Thanks :-)
