### ISSUE TITLE
Unable to install Python Wrapper for Vowpal Wabbit. No file or directory contains pyvw36.dll 

### ISSUE THREAD

**Issue by aazim-lakhani** [VowpalWabbit/vowpal_wabbit#1619]
Hello,
          I'm trying to install the Python Wrapper for Vowpal Wabbit & i'm facing issues with it. I tried multiple ways to install it. 

1. pip install vowpalwabbit
2. Vowpal Wabbit under an Anaconda environment

The following error stops me from using VW, when i try to install the package. 

**ERROR: error: [Errno 2] No such file or directory: 'C:\\UVic\\ML_Education\\project\\vowpal_wabbit\\python\\bin\\pyvw36.dll'**

I searched & found many others having the same issue. However, there doesn't seem to be a convincing answer. 

I'm using Windows 10 & tried installing it with Python 3.5 & 3.6. There seems to be something amiss in the package, as the file pyvw36.dll should either be present in Github or created during installation, but none happens. Below are a list of packages install prior to vowpal wabbit. It seems to have the dependenies for boost & boost-python. 

![pyvw36 dll not found](https://user-images.githubusercontent.com/3368696/46534813-50a0da00-c85e-11e8-9f25-0ab874aeb1ab.JPG)

Below is the log trace. It warns me that it can't find the *.dll in the bin directory. Unfortunately, it doesn't tell me who is supposed to create it. 

![log trace](https://user-images.githubusercontent.com/3368696/46543824-b1d4a780-c876-11e8-9095-d12662854066.JPG)

**_Few Questions to understand the system_** 

1. Do users of Windows needs to follow along the instructions at https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/README.windows.txt , even though they intend to use the python wrapper ? 

2. Is Visual Studio recommended or the same feature set can be accessed through other development environments, like Jupyter ? It seems like Visual Studio is required to create the *.dll files. 

3. I'm curious to know, why is installation of VW not as straight forward as say scikit-learn, numpy like packages. Just like VW, these are open source projects, but straight forward to install. 

Thank you for making VW & I hope to contribute to the community. But first, I need to get it working. 

Thank You for reading. Hope you could help.

**Comment by JohnLangford** [comment]
I believe there is an outstanding long term issue with python-3 and windows.

**Comment by peterychang** [comment]
A new version of vowpalwabbit has been released for python on pypi and conda. Additionally, binary wheels have been released for python 3.6 and 3.7 for 64-bit python on Windows.

`pip install vowpalwabbit`
should now install a pre-compiled wheel for python (64-bit) 3.6/3.7 on Windows.

To answer your questions:
1. Windows users should follow the instructions at https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Python or https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/README.rst

2. Visual Studio is no longer recommended for python on Windows. Please use cmake and vcpkg instead.

3. Projects like numpy and scikit-learn have pre-compiled binaries for various operating systems and versions of python, we are currently attempting to do the same for vowpalwabbit. As I mentioned above, We've released them for certain versions of python on Windows.
