### ISSUE TITLE
Is there code to get the per-document topic distributions?

### ISSUE THREAD

**Issue by johann-petrak** [VowpalWabbit/vowpal_wabbit#1636]
Is it possible to get/output the per-document topic distributions for documents (instances) in the training set or apply a trained LDA model to new instances? 

If not, could we make this the corresponding feature request?

**Comment by JohnLangford** [comment]
You can apply a trained LDA model to new instances by saving a model and then loading it with -t.  Applying this to the training set should work fine as well.
