### ISSUE TITLE
rename license.txt to LICENSE

### ISSUE THREAD

**Issue by edjez** [VowpalWabbit/vowpal_wabbit#1676]
for better auto license scraping

**Comment by jackgerrits** [comment]
@edjez It is currently named `LICENSE`, do you want it to be called `license.txt` instead?

**Comment by yannstad** [comment]
@edjez  are you speaking about this file maybe? 
https://github.com/VowpalWabbit/reinforcement_learning/blob/master/LICENSE.txt
