### ISSUE TITLE
PyPi is out of date

### ISSUE THREAD

**Issue by chekan-o** [VowpalWabbit/vowpal_wabbit#1680]
Hi,

I can see that most recent version is 8.6.1 while at PyPi it is still 8.5

Version 8.5 have a bug at setup.py with boost library filename for MacOS. It blocks it from installation.
While recent version 8.6.1 installs fine. Could you please update PyPi?

Thanks
Oleg

**Comment by jackgerrits** [comment]
Extra comments from other issue:
> Latest released (on pypi) version is 8.5.0.
> 1. Can it be released on conda as well?
> 2. Can python release pipeline be more automated?

**Comment by peterychang** [comment]
Vowpalwabbit 8.7.0 has been released on pypi.
A conda recipe has also been released
https://github.com/conda-forge/staged-recipes/pull/8696
