### ISSUE TITLE
Create .clang-format file to enforce style consistency across codebase

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1692]

**Comment by palmerlao** [comment]
does some consensus need to be reached here around preferred style or is it a matter of creating a file, reformatting everything, and adding a check to CI?

**Comment by JohnLangford** [comment]
There isn't a strong style preference although there have been attempts in the past to at least standardize style as per some of the commented lines here: https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/utl/new_version

**Comment by jackgerrits** [comment]
I am of the opinion we should go with a commonly accepted style and make modifications as needed for the project. It seems like allman brace style is the majority of the codebase

**Comment by JohnLangford** [comment]
Allman seems fine by me.   Having parens line up vertically seems good.

I think the more tricky thing is imposing a style in a manner which isn't to disruptive.   Previously when we played with this it ended up constantly imposing huge patches because different editors had slightly different interpretations for standardized styles leading to giant spurious changes.

**Comment by jackgerrits** [comment]
The beauty of using clang format is it is completely consistent, it isn’t
up to the editor. And after the initial cleanup change the CI check for
style will mean we won’t get these crazy diffs.

**Comment by JohnLangford** [comment]
Maybe---it would be good to verify in at least emacs and visual studio
before declaring victory :-)

-John

**Comment by jackgerrits** [comment]
clang-format is a command line tool that is run separately. I'm not sure if the editors can read the config

**Comment by palmerlao** [comment]
My understanding of clang-format is similar to @jackgerrits previous comment. On a separate project, I use the following to make emacs format all of my C++ code as I go:

```
(defun clang-format-google ()
  "Call clang-format -style=Google -i $FILE"
  (when (eq major-mode 'c++-mode)
    (shell-command-to-string (format "clang-format -style=Google -i %s" buffer-file-name))
    (interactive) (revert-buffer t t)))

(add-hook 'after-save-hook #'clang-format-google)
```
