### ISSUE TITLE
VW versions behave differently using --cb_type dr

### ISSUE THREAD

**Issue by marco-rossi29** [VowpalWabbit/vowpal_wabbit#1695]
Running in windows cmd the following command:
`vw.exe -d data_file.gz --dsjson --cb_adf --cb_type dr -q Os -q ME -q Oj -q Mj -q Ms -q GE -l 0.01 --power_t 0 -p output.pred -f output.vw` using data log [here](https://personalizr.visualstudio.com/personalizr/_workitems/edit/1417)

Using two different VW versions:
- 8.4.0: Commit: 78e4ae74dbfe2ded584b33376d7ff57af06b9dd4 (and e2e2cd4cb76f914ced19d98395a0094d7a1787f0 behaves equivalently)
- 8.6.1: Commit: 5becde24fd1464e8fc7bbcc02312fbdb8f12891d

produces different prediction files (output.pred) and different vw model files (output.vw), and thus a different average loss. Is one of them behaving correctly? If so, is it the latest?

When testing using --cb_type ips or --cb_type mtr the issue disappear, so the issue seems isolated to `dr`

**Comment by JohnLangford** [comment]
Thinking about this a bit further... Changes in behavior are to be expected as the base learning algorithm improves.    Is there a reason to believe that performance has degraded?  

Looking at: git log test/train-sets/ref/cbe_adf_cover_dr.stderr I see several updates to test results.  

I'll leave this open for now, but it would be good to know if something has degraded, and if not the presumption is that the newer learning algorithms is simply better.
