### ISSUE TITLE
Reward estimators library

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1702]
Estimators
- [x] ips
- [x] weighted ips (aka snips)
- [x] mle 
- [ ] dr
- [ ] dm
- [ ] switch estimators?
- [ ] ...

Components
- [x] Python
- [ ] Testing framework
- [ ] C++
- [ ] C#

Confidence interval

**Comment by jackgerrits** [comment]
@marco-rossi29 do you want to move this issue to the estimators repo?

**Comment by marco-rossi29** [comment]
Sure.
