### ISSUE TITLE
Java 8 is no longer supported and cannot be installed

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1712]
Free public updates for the Java package we install in continuous integration images, and target as the supported Java version are no longer supported as of January 2019. The url used to install the package now returns a 404.
https://unix.stackexchange.com/questions/494694/error-404-on-jdk-download-debian-8
https://en.wikipedia.org/wiki/Java_version_history

```
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get update
sudo apt-get install -y oracle-java8-installer
```

Fails with:
```
--2019-01-16 10:08:39--  https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz?AuthParam=1547651439_86e0f96dcde1e7dcd36cf3119a69f3d3
Connecting to download.oracle.com (download.oracle.com)|184.28.90.72|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-16 10:08:40 ERROR 404: Not Found.

download failed
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
```

This also impacts openjdk
```
sudo apt-get install openjdk-8-jdk
```

Fails with the same error

**Comment by JohnLangford** [comment]
@jmorra @deaktator We are discussing what to do around this.  Should we try to upgrade to java 11?

**Comment by jmorra** [comment]
While I have not used Java 11, Java has traditionally been very good at maintaining backwards compatibility.  The test coverage for Java is pretty good so I wouldn't be surprised if a simple upgrade just works.  Also the pom file still references Java 6.  We could try upgrading this as well.  It very well might make the code run faster as well.

**Comment by jackgerrits** [comment]
I've updated our continuous integration to target Java 11 in #1716
