### ISSUE TITLE
Update new_version script to update version.txt and other instances of version number

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1714]

**Comment by lokitoth** [comment]
Ideally, all the other places should grab the version number from version.txt, wherever possible. Are there situations where this cannot be done?

**Comment by jackgerrits** [comment]
I think the extra ones are mainly AssemblyInfo.*

**Comment by lokitoth** [comment]
There should be a task to generate AssemblyInfo* that I believe is used. We might be able to do a bit of archeology to find it and drive it manually based on this version file.

**Comment by jackgerrits** [comment]
`cs\version.props` also contains the version number and will need to be considered for this

**Comment by jackgerrits** [comment]
https://github.com/VowpalWabbit/vowpal_wabbit/pull/1884/files

`python/docs/conf.py` needs to be updated as well

**Comment by thealphadollar** [comment]
@jackgerrits Is this issue complete?

**Comment by jackgerrits** [comment]
Release management is still something we are working on. The new_version script has issues and as such it has not really been used. Ideally release pipelines will be setup eventually but we need to find time to work that out.
