### ISSUE TITLE
memory issue with ngrams in python implementation

### ISSUE THREAD

**Issue by alexfraze** [VowpalWabbit/vowpal_wabbit#1720]
#### Describe the bug
Using Ngram features in the python implementation seems to prevent correct memory de-allocation

#### To Reproduce
1. Create a vw model with ngrams
2. Train the model on some examples
3. delete the example and the models
4. Check to see if all the memory is freed up

#### Expected behavior
I expect there to be some memory still used by the model and examples

#### Environment
I am running VW in a Kaggle Linux Kernel.

**Comment by JohnLangford** [comment]
Do you have a program that reproduces?

-John

**Comment by alexfraze** [comment]
sorry wasnt a bug with VW. 

Apologies
