### ISSUE TITLE
clang-format should run automatically on PRs

### ISSUE THREAD

**Issue by lokitoth** [VowpalWabbit/vowpal_wabbit#1743]
We recently introduced clang-format to ensure a consistent, agreeable style across the codebase. Unfortunately, the way we have it set up now leads to an odd situation: We have a tool that will only accept one input as non-broken, and is also capable of changing the provided input to match the input it wants, but still have it break the CI, rather than just running the fix and checking in the changes.

It seems desirable for it to just happen, ideally as part of the normal git process. It seems like git hooks might help with that:
   - https://git-scm.com/docs/githooks
   - https://github.com/andrewseidl/githook-clang-format

**Comment by lokitoth** [comment]
We may also want to include updating the documentation to include the need to install nodejs and npm and clang-format as part of the dev tools dependencies.

**Comment by jackgerrits** [comment]
It no longer fails CI if format has issues

**Comment by jackgerrits** [comment]
#1819 was one approach to tackle this. But rather than CI, using a bot may be a more sensible approach

**Comment by lokitoth** [comment]
I do like the bot approach - have it run on a schedule and clang-format automatically.

**Comment by jackgerrits** [comment]
We now have a decently reliable format check that only runs on the diff of the PR, so I think the goal of this issue is addressed.
