### ISSUE TITLE
Tests failures on master

### ISSUE THREAD

**Issue by kumpera** [VowpalWabbit/vowpal_wabbit#1746]
#### Describe the bug
When running the test suite on OSX against master 6dd314d20dfde9211b2d614a8b13d387fd93778d I hit a few issues.

#### To Reproduce
1. `mkdir build; cd build; cmake -GNinja ..; ninja`
1. `cd build/test; ctest --verbose`

#### Expected behavior
All tests passes

#### Observed Behavior
The following tests FAILED:
	  1 - RunTests_pass_1_onethread (Failed)
	  2 - RunTests_pass_2 (Failed)
	  4 - test_race_condition (Failed)

#### Environment
Master 6dd314d20dfde9211b2d614a8b13d387fd93778d
OSX High Sierra
Release build

**Comment by JohnLangford** [comment]
Is this a heisenbug or a reliable fail?

**Comment by kumpera** [comment]
It's a reliable failure. I believe it happens on other OS', still confirming that.

**Comment by JohnLangford** [comment]
That's a relief---it should be much easier to debug.

**Comment by jackgerrits** [comment]
Can you provide the full test failure output - using `make test_with_output`

**Comment by kumpera** [comment]
@jackgerrits https://gist.github.com/kumpera/94bd4727e198e5db88c233163e008830

**Comment by kumpera** [comment]
Links to the failures:

https://gist.github.com/kumpera/94bd4727e198e5db88c233163e008830#file-gistfile1-txt-L183
https://gist.github.com/kumpera/94bd4727e198e5db88c233163e008830#file-gistfile1-txt-L461
```
1: RunTests: test 91: lenient-diff.tmp: line 1: fuzzy-match missing data on one of the sides. Can't compare
1: e^x*f^a:96492:-0.0611589						      <
1: RunTests: test 91: saving lenient diff in 'test-91.lenient-diff' for later inspection
1: --- diff -u --minimal pred-sets/ref/inv_hash.cmp inv_hash.cmp
1: --- pred-sets/ref/inv_hash.cmp	2019-01-30 20:14:23.000000000 -0500
```

https://gist.github.com/kumpera/94bd4727e198e5db88c233163e008830#file-gistfile1-txt-L618
```
test 4
    Start 4: test_race_condition

4: Test command: /anaconda3/bin/python "repeat.py" "1024" "/Users/kumpera/src/vowpal_wabbit/build/test/../vowpalwabbit/vw" "train-sets/rcv1_small.dat" "--holdout_after" "100"
4: Test timeout computed to be: 10000000
4: Traceback (most recent call last):
4:   File "repeat.py", line 13, in <module>
4:     for counter in xrange(1, count + 1):
4: NameError: name 'xrange' is not defined
4/5 Test #4: test_race_condition ..............***Failed    0.05 sec
```

**Comment by kumpera** [comment]
The last error is just due to `repeat.py` not being python 3 compatible. That's a trivial fix.

**Comment by kumpera** [comment]
https://github.com/VowpalWabbit/vowpal_wabbit/pull/1747

**Comment by kumpera** [comment]
Fix a couple of unit tests on OSX: #1776

**Comment by kumpera** [comment]
Once the last two PRs are in, this will be done for now.
We should add CI so we avoid regressing in the future.

**Comment by kumpera** [comment]
OSX is green 🎉
