### ISSUE TITLE
TopK should be a multi line reduction - illegal usage of example field in current state

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1748]
This causes a memory leak as well as undefined behavior when examples are retrieved from the buffer as many of the fields of example have previous values left in them. Therefore if a reduction does not overwrite the prediction field the old value will be used.

https://github.com/VowpalWabbit/vowpal_wabbit/blob/c9110426d9e8585e8410403d12f0194d5e6673fa/vowpalwabbit/parser.cc#L908

**Comment by JohnLangford** [comment]
No deallocation is supposed to happen---instead the memory should be reused.   

VW operates on a principle of zero allocation in steady state example processing.

**Comment by jackgerrits** [comment]
The issue I was seeing was that an example was returned from the pool to be used, the reduction did not set the prediction field on the example and when it was printed the old stale value of prediction was used.

Is this a bug on the reduction not setting the prediction to 0?

**Comment by JohnLangford** [comment]
The reduction should always set the prediction variable.

**Comment by jackgerrits** [comment]
This issue seems to be that TopK was stashing the tag field of the example but was a single line reduction so that example was potentially being returned and reused.
