### ISSUE TITLE
Setup CI for MacOS

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1762]
Can be setup using Azure Devops at the [VowpalWabbit organization](https://vowpalwabbit.visualstudio.com/Vowpal%20Wabbit). Perhaps the other CI checks should be migrated there at the same time as well.

**Comment by JohnLangford** [comment]
I expect we should get CI for MacOS setup, and then see how well that works.  Later, we can make decisions about any CI migrations based on how useful/usable the MacOS experience is.  (Travis has been quite good for us, so I'm hesitant to move there.)

**Comment by jackgerrits** [comment]
I agree 100%, lets not waste that effort especially since Travis is working
well. Also Azure DevOps doesn’t get support caching but they are actively
working on it
