### ISSUE TITLE
Coveralls code coverage analysis is no longer updating

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1763]
The code coverage report has not updated for some time
https://coveralls.io/github/JohnLangford/vowpal_wabbit

**Comment by yannstad** [comment]
The `coveralls` command is not recognized because it is called outside of the docker, that contains all the required dependencies, including coveralls cmd itself. See for example the very end of [these](https://travis-ci.org/VowpalWabbit/vowpal_wabbit/builds/518617063?utm_source=github_status&utm_medium=notification) Travis logs:
```bash
$coveralls --exclude lib --exclude tests --gcov-options '\-lp'
coveralls: command not found
```

I have submitted a PR that fixes this particular issue.
Now there is another error:
```
Couldn't find a repository matching this job
```

I am looking it..

**Comment by yannstad** [comment]
Now there is another error:
```
Couldn't find a repository matching this job
```
From Coveralls [doc](https://docs.travis-ci.com/user/coveralls/), the Github OAuth token must be valid in Coveralls.
@JohnLangford  The coveralls was not run for more than a year. I suspect that the token is not valid anymore. Could you try logging out / in on Coveralls.io to refresh it?

**Comment by JohnLangford** [comment]
Token regenerated.  Try again?

**Comment by yannstad** [comment]
It did not work, showing the same error message `Couldn't find a repository matching this job`.
I wonder how to debug that. The same change in my CI pipeline send the coverall report successfully.

Another thing to try is to setup again Coveralls, from scratch. But **coveralls history will be lost**

**Comment by yannstad** [comment]
@JohnLangford 
Would you mind checking if coveralls is an authorized application in Github?

Coveralls should be listed here https://github.com/settings/applications:

<img width="1152" alt="coveralls" src="https://user-images.githubusercontent.com/4194615/56310411-d1983280-6119-11e9-97ff-bc42918c07c6.png">

**Comment by JohnLangford** [comment]
I see it at this URL...

-John

**Comment by yannstad** [comment]
Coverage reports are back: 
https://coveralls.io/github/VowpalWabbit/vowpal_wabbit
