### ISSUE TITLE
Not same model weight from nodes on cluster mode 

### ISSUE THREAD

**Issue by silverguo** [VowpalWabbit/vowpal_wabbit#1771]
#### Describe the bug
I run VW 8.6.1 with some large dataset on cluster mode, models from each node are not exactly same, but I didn't have this problem with VW 7.7.

#### To Reproduce
For convenience, here I use some toy examples to reproduce this bug.

Here is my workspace,
```
.
├── bin
│   ├── spanning_tree-7.7.macOS
│   ├── spanning_tree-8.6.1.macOS
│   ├── vw-7.7.macOS
│   └── vw-8.6.1.macOS
├── data
│   ├── train.vw.0
│   └── train.vw.1
├── log
│   ├── spanning_tree.7.7.log
│   ├── spanning_tree.8.6.1.log
│   ├── train-7.7-0.log
│   ├── train-7.7-1.log
│   ├── train-8.6.1-0.log
│   └── train-8.6.1-1.log
├── model
    ├── vwmodel.7.7.0.txt
    ├── vwmodel.7.7.1.txt
    ├── vwmodel.8.6.1.0.txt
    └── vwmodel.8.6.1.1.txt
```

I built the binary file for `vw` and `spanning_tree` with release **8.6.1** and **7.7**, then place then in `bin` folder.

`data` contains 2 input file for 2 nodes.
- train.vw.0
```
1.0 |a big long |b bad
-1.0 |a small |b average    
```

- train.vw.1
```
1.0 |a short |b good
-1.0 |a median
```

The script I used to train is,
```bash
VW_VERSION="8.6.1"

bin/spanning_tree-$VW_VERSION.macOS &> log/spanning_tree.$VW_VERSION.log &

for i in {0..1}
do
    bin/vw-$VW_VERSION.macOS -d data/train.vw.$i \
    --readable_model model/vwmodel.$VW_VERSION.$i.txt \
    -q ab \
    --span_server localhost --total 2 --node $i --unique_id 2666 \
    --passes 1 --holdout_off &> log/train-$VW_VERSION-$i.log &
done
```

With VW 8.6.1, I got different readable models,
**vwmodel.8.6.1.0.txt**
```
1000:-0.15735
8068:0.11768
25745:0.11768
53501:0.158008
67504:0.158008
73913:0.11768
81463:-0.15735
116060:-0.00945443
118687:0.158008
151495:0.11768
171199:0.11768
202767:-0.15735
```
**vwmodel.8.6.1.1.txt**
```
1000:-0.15735
8068:0.11768
25745:0.11768
53501:0.158008
67504:0.158008
73913:0.11768
81463:-0.15735
116060:-0.00945443
118687:0.158008
160265:-0.233727
```

But with VW 7.7, I could get exactly same models,
**vwmodel.7.7.0.txt**
```
1000:-0.157350
8068:0.117680
25745:0.117680
31359:-0.157350
53501:0.158008
73913:0.117680
81463:-0.157350
106193:0.117680
116060:-0.009454
118687:0.158008
127577:0.117680
140576:0.158008
160265:-0.233727
```
**vwmodel.7.7.1.txt**
```
1000:-0.157350
8068:0.117680
25745:0.117680
31359:-0.157350
53501:0.158008
73913:0.117680
81463:-0.157350
106193:0.117680
116060:-0.009454
118687:0.158008
127577:0.117680
140576:0.158008
160265:-0.233727
```

#### Expected behavior
The models from each node should be same.

#### Observed Behavior
With VW 8.6.1, I cannot get the same model from each node.

Also, I found with this toy example or the large dataset I used, `vw` can **always** average the feature value with hash code in the first half (0~2^17) of hashing space we used (2^18 in toy example), it seems to be a bug related to bit operation?

#### Environment
VW: `7.7` and `8.6.1`
OS: macOS and linux

Thank!

**Comment by silverguo** [comment]
I just test the toy example above with all recent releases, and I found the versions before `8.2.1` don't have this issue, but all versions after `8.3.1` will produce different models on cluster mode.

**Comment by arielf** [comment]
Good catch.

Shot in the dark: might be a async non-deterministic inconsistency which we experienced in the past in other contexts.

This may be easy to verify/refute.  Does the issue go away when adding the `--onethread` option ?

**Comment by silverguo** [comment]
Thanks @arielf !

I add `--onethread` option but it still produces different models from each node.

Also I found that if we turn off `--adaptive` by adding `--normalized --invariant`, the models could be same. Is there something from `--adaptive` break the model average on cluster mode?

**Comment by silverguo** [comment]
In addition, I did some binary search for the first bad commit between `8.2.1` and `8.3.0`, it seems that [this](https://github.com/VowpalWabbit/vowpal_wabbit/commit/24c68fcc0fb29dc574d39673981e55f45bcdc861) is the first bad commit which leads to different models from each node.

Since it's a very big commit (3034 additions and 1279 deletions), I don't have a very good understanding about it. Does anyone know why it causes this issue?

**Comment by arielf** [comment]
Excellent sleuthing @silverguo . Thank you for all this leg-work!

I hope that the isolation of both the commit-id and the fact that turning off `--adaptive` in clustered-mode fixes the issue, would be helpful for someone to figure this out. @jon-morra-zefr could you space sme cycles on this?

Most of the change in commit https://github.com/VowpalWabbit/vowpal_wabbit/commit/24c68fcc0fb29dc574d39673981e55f45bcdc861 is radded tests and test related code. The question is what has changed beyond testing.

**Comment by jon-morra-zefr** [comment]
@arielf I'm not sure I'm the right person to ask here.  While I committed the Spark stuff I didn't touch the c code too much.

**Comment by JohnLangford** [comment]
This sounds like a real bug, and we should add a test case to avoid it in the future after fixing.

**Comment by silverguo** [comment]
@arielf @JohnLangford @jackgerrits 
Hi, I just send a PR and it might be a fix for this issue, could you take a look at it?
