### ISSUE TITLE
How to model multi actions in contextual bandit scenarios?

### ISSUE THREAD

**Issue by amirj** [VowpalWabbit/vowpal_wabbit#1772]
I'm going to experiment with a set of contextual bandit algorithms (dm, ips and dr) on [Criteo Ad Placement Dataset](http://www.cs.cornell.edu/~adith/Criteo/). The [original paper](http://www.cs.cornell.edu/~adith/Criteo/NIPS16_Benchmark.pdf) evaluated on 1-slot scenario: for each context, we have only one observed action. So the dataset are organized as follows (in each example, the first line contains <action=0,cost,probility>):

> shared 68965824| 1:300 2:600 3_0 4_47 5_1585 6_5 7_0 8_56 9_74 10_0
> **0:0.999:0.0029** | 11_1 12_0 13_0 14_0 15_0 16_4 23_55 24_321 25_155 32_90 35_204
> | 11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_11 24_320 25_151 34_24 35_201
> | 11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_77 24_320 25_151 34_24 35_201
> | 11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_77 24_320 25_151 34_24 35_201

I'm going to experiment on **multiple slots (slots=1,2,3,4,5,6)** scenario; in this case, for each context, we have multiple observed actions. For example, for a 2-slots case:

> shared 68965824| 1:300 2:600 3_0 4_47 5_1585 6_5 7_0 8_56 9_74 10_0
> **0:0.999:0.0029** | 11_1 12_0 13_0 14_0 15_0 16_4 23_55 24_321 25_155 32_90 35_204
> **0:0.001:0.0029** | 11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_11 24_320 25_151 34_24 35_201
> | 11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_77 24_320 25_151 34_24 35_201
> | 11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_77 24_320 25_151 34_24 35_201

It means that in a specific context, we observed two actions, each action has its own cost. 

The problem is that running with the second dataset, I get the following error:

> vw (cb_explore_adf.cc:117): cb_adf: badly formatted example, only one line can have a cost

In [the documents](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Contextual-Bandit-algorithms), clearly stated that "**Each example is also allowed to specify the label information on precisely one action**".

An obvious solution is to leverage only click items as labelled items and remains other observed but not clicked as unlabel actions and skip all unobserved actions:

> shared 68965824| 1:300 2:600 3_0 4_47 5_1585 6_5 7_0 8_56 9_74 10_0
> **0:0.001:0.0029** | 11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_11 24_320 25_151 34_24 35_201
> ~~0:0.999:0.0029~~ | 11_1 12_0 13_0 14_0 15_0 16_4 23_55 24_321 25_155 32_90 35_204
> | ~~11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_77 24_320 25_151 34_24 35_201~~
> | ~~11_0 12_0 13_1 14_0 15_1 18_4 19_13 20_77 24_320 25_151 34_24 35_201~~

But I'm not ensure it's a robust experimental setup in such condition as the original paper leveraged both observed (click/noclick) and unobserved actions.

Thanks.

**Comment by jackgerrits** [comment]
Hi @amirj, for a single CB example only one action can have a reward/cost associated with it. 

We're currently working on conditional contextual bandit (CCB), which is cb over multiple slots and would likely allow you to express the problem you set out here (if it doesn't satisfy it let me know and we can discuss). It is likely to make it into master in the next month or so. Work for it is being merged into [this staging branch](https://github.com/VowpalWabbit/vowpal_wabbit/tree/conditional_contextual_bandit). You'll notice there are several PRs open with **[CCB]** in the title, so you can follow development of it as it happens. There is preliminary information on the input format for CCB [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Contextual-Bandit-algorithms#conditional-contextual-bandit), but please note that this is still in development and may change before it is merged and ready.

**Comment by amirj** [comment]
Thanks @jackgerrits , it's a very nice feature.

**Comment by marco-rossi29** [comment]
@amirj Two things:
- why is the cost of a click positive? in other words, why are you penalizing an action if there was a click?
- To understand better about you observation that all cb_type have same IPS estimate, can you specify what command of vw you are running and look at the predictions by exporting them to a file with -p. If the predictions are the same then IPS estimate is the same.

**Comment by amirj** [comment]
@marco-rossi29 

The original paper defined the following costs:

- Clicked item: 0.001
- Not Clicked:  0.999

You're right, since I removed the cost of not clicked items, it's not reasonable to use 0.001 cost for clicked items. I have to find a way to add not clicked actions into the model. Is it ok to replicate an example by defining a clicked or not clicked action in with the same shared features?

For example, split this example:

> shared 52240655| 1:336 2:280 3_0 4_58 5_12 6_3 7_0 8_75 9_82 10_9
> **0:0.999:0.0001774762** | 11_0 12_1 13_1 14_5 15_1 17_2 17_4 17_2 17_1:2 18_4 19_31 20_55 21_58 21_75 21_58 21_53:2 22_19 22_159 22_19 22_20 22_11 24_400 25_196 33_464 33_741 33_464 33_272:2 34_80 35_252
> **0:0.001:0.0001774762** | 11_1 12_1 13_1 14_5 15_1 16_1 17_2 17_4 17_2 17_1:2 18_4 19_31 20_35 21_58 21_75 21_58 21_53:2 22_35 22_156 22_12 22_33 22_11 23_51 24_2216 25_202 26_138 26_140 26_138 26_139:2 27_30 28_985 29_1420 29_3917 29_1420 29_142:2 30_3 31_1 31_9 31_1 31_0:2 32_79 33_464 33_741 33_464 33_272:2 34_80 35_262

split into the following two examples:

> shared 52240655_1| 1:336 2:280 3_0 4_58 5_12 6_3 7_0 8_75 9_82 10_9
> **0:0.999:0.0001774762**| 11_0 12_1 13_1 14_5 15_1 17_2 17_4 17_2 17_1:2 18_4 19_31 20_55 21_58 21_75 21_58 21_53:2 22_19 22_159 22_19 22_20 22_11 24_400 25_196 33_464 33_741 33_464 33_272:2 34_80 35_252
> 
 
and

> shared 52240655_2| 1:336 2:280 3_0 4_58 5_12 6_3 7_0 8_75 9_82 10_9
> **0:0.001:0.0001774762** | 11_1 12_1 13_1 14_5 15_1 16_1 17_2 17_4 17_2 17_1:2 18_4 19_31 20_35 21_58 21_75 21_58 21_53:2 22_35 22_156 22_12 22_33 22_11 23_51 24_2216 25_202 26_138 26_140 26_138 26_139:2 27_30 28_985 29_1420 29_3917 29_1420 29_142:2 30_3 31_1 31_9 31_1 31_0:2 32_79 33_464 33_741 33_464 33_272:2 34_80 35_262


Also, here is the code which I'm running:

>  vw --random_seed 387 -d ${VW_PREFIX}_train.gz -c --compressed --save_resume -P 500000 --holdout_off --sort_features --noconstant --hash all -b 24 -l ${L} --power_t ${P} --l1 ${Lambda} -f ${Logs}/${method}/${method}_${P}_${L}_${Lambda}.1 --random_weights 1 --id ${method}_${P}_${L}_${Lambda}.1 --cb_adf --cb_type ${method} &> ${Logs}/${method}/${method}_${P}_${L}_${Lambda}.1.train.log

**Comment by jackgerrits** [comment]
@amirj, CCB has now been merged to master. See [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Conditional-Contextual-Bandit) for the wiki page. Let me know if you have any questions.

**Comment by amirj** [comment]
Thank you very much. It's a very useful feature. I will start fitting my dataset to this feature and report if I have any problem. For the moment, I will close this issue. Thanks again.
