### ISSUE TITLE
Modularity problems in the contextual bandit stack

### ISSUE THREAD

**Issue by JohnLangford** [VowpalWabbit/vowpal_wabbit#1782]
From #1779 

--cb_explore_adf should not need to know about the cb_type since that isn't used except in the cb_adf reduction. Hence, there is a modularity failure. This modularity failure involves cover, mtr, and dealing with shared features which together make a mess. The clean way forward here is to break things out into simpler separate reductions which may have potentially different requirements on base. 

The shared features part is easy: we should just break it out into a separate reduction which operates relatively high in the stack.  This will clean up many reductions which constantly need to check to see if there are shared features and which route through csoaa_ldf even when that is not appropriate to get shared features.

The core issue with mtr is that it should be reducing to a different primitive (importance weighted regression) than some of the sibling reductions.    Plausibly all of these contextual-bandit-to-supervised reductions should be broken out as (conceptually separate) reductions, but certainly mtr and dm should be since they reduce to alternate primitives.

Cover has a similar issue with the type access it requires being different from the other reductions.

**Comment by lokitoth** [comment]
Possibly related: #1541

**Comment by peterychang** [comment]
Closed in favor of https://github.com/VowpalWabbit/vowpal_wabbit/issues/2023
