### ISSUE TITLE
No predictions for some arms in contextual bandit

### ISSUE THREAD

**Issue by mmmmaister** [VowpalWabbit/vowpal_wabbit#1783]
Hi,

I'm trying to build contextual bandit model using --cb. My data has 6 actions and 52 variables (please see below for an example). However, when I use CB model for prediction (-p), it always recommends 2 arms at the same time. When I look into the raw prediction (-r), turn out that one of the arms never have cost prediction. Same situation happens for cb_type IPS/DM/DR. 

Could any one explain what's happening? Any hints would be appreciated!

Example:
1 2 3 4 5:-0.0:0.25 6|col_0:0.0  col_1:0.909090909091  col_2:0.0  col_3:0.0  col_4:0.0291400316147  col_5:0.273004337123  col_6:0.273100375235  col_7:0.113636363636  col_8:0.0  col_9:0.0  col_10:0.608695652174  col_11:0.260869565217  col_12:0.0  col_13:0.993112947658  col_14:0.00625111694988  col_15:0.153035624686  col_16:0.0969335017802  col_17:0.0  col_18:0.0  col_19:0.00187676586344  col_20:0.0179032258065 ...

Prediction example (-p):
2 6
2 3
3 6
2 6
3 6

Raw prediction example (-r)
2:-1.47256 3:-1.32619 6
 3
1:-7.50418 2:-9.93879 3:-11.5118 4:-8.62382 5:-4.11915 6
1:-1.13783 2:-1.47256 3:-1.32619 4:-0.981729 5:-0.981051 6
1:-6.92953 2:-9.21329 3:-9.78105 4:-7.30724 5:-4.47286 6

Thanks!

[train_num2k.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/2931822/train_num2k.txt)
[test_num_id5.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/2931825/test_num_id5.txt)

**Comment by kumpera** [comment]
Hey @mmmmaister the issue you're seeing is due to how the VW input format handles example tags.
If you look at https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Input-format#notes it mentions that there must be a space before the first `|` or the string will be considered a tag.

I edited your file and added spaces before the first `|` and it worked as you'd expect.
