### ISSUE TITLE
Same scores independent of action order for cb_explore_adf with Python

### ISSUE THREAD

**Issue by HelgeS** [VowpalWabbit/vowpal_wabbit#1784]
#### Describe the bug
When using `cb_explore_adf` in the Python interface, the returned scores for a prediction appear to be independent of the order the actions were input.
In fact, the scores are in decreasing order (as they are with the commandline interface), but the relation to the corresponding action is lost.

#### To Reproduce
The issue can be reproduced with this script:
```
from vowpalwabbit import pyvw
model = pyvw.vw(cb_explore_adf=True)
ex1 = [model.example("| a b d"), model.example("0:-5:0.5 | a b c")]
model.learn(ex1)

ex2 = [model.example("| a b d"), model.example("| a b c")]
print("| a b d\r\n | a b c", model.predict(ex2))

ex3 = [model.example("| a b c"), model.example("| a b d")]
print("| a b c\r\n | a b d", model.predict(ex3))

# (Shortened) Output:
# ('| a b d\r\n | a b c', [0.9749999642372131, 0.02500000037252903])
# ('| a b c\r\n | a b d', [0.9749999642372131, 0.02500000037252903])
```

#### Expected behavior
The scores should be in the same order as the inputs:
```
# ('| a b d\r\n | a b c', [0.02500000037252903, 0.9749999642372131])
# ('| a b c\r\n | a b d', [0.9749999642372131, 0.02500000037252903])
```
The commandline interface returns the same order as the python calls, but indicates to which action each score belongs (see below).

#### Environment
What version of VW did you use?
What OS or language did you use?

VW (latest development version) on Linux with the Python bindings

#### Additional context
The command line interface behaves correctly
`./vw -d data.txt --cb_explore_adf -p probs.txt`

probs.txt (Output)
```
0:0.5,1:0.5

1:0.975,0:0.025

0:0.975,1:0.025

```

data.txt
```
| a b d
0:-5:0.5 | a b c

| a b d
| a b c

| a b c         
| a b d

```

This issue might be related to #1346

**Comment by pavithraks** [comment]
Hey @HelgeS , thanks for spotting this. The fix is pretty simple. The problem was that the actual scores list was indexed by action. In the python binding,  the index was being ignored. I'm sending in a fix now.
