### ISSUE TITLE
[CI] Add python to our travis script

### ISSUE THREAD

**Issue by kumpera** [VowpalWabbit/vowpal_wabbit#1813]
We currently neither build nor test the python bindings.

We should add it, at the very least, to the linux lane.

**Comment by jackgerrits** [comment]
I just checked and we do actually build and test the Python bindings in the Linux CI. See:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/31859a32385c17511eecf6bf7d0a04f12774a41e/build-linux.sh#L41
