### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [VowpalWabbit/vowpal_wabbit#1846]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [AllReduceSync](https://github.com/VowpalWabbit/vowpal_wabbit/blob/d0c9042ca1057c858c8158d0d4b7335a12abd491/vowpalwabbit/allreduce_threads.cc#L14)
- [parser](https://github.com/VowpalWabbit/vowpal_wabbit/blob/d4cac03c6fee89253e6732d3f9c15164fb7579c4/vowpalwabbit/parser.h#L39)

**Comment by kumpera** [comment]
In AllReduceSync we can replace some of pointers with values.
