### ISSUE TITLE
Proposal: Change int-based enums to enum classes

### ISSUE THREAD

**Issue by peterychang** [VowpalWabbit/vowpal_wabbit#1855]
Rather than using size_t with \#define'd values or const numbers, we should use enum classes, which are more readable and relatively type safe

**Comment by lokitoth** [comment]
Will that impact bindings? In other words, how transparent is this to be used from a C-like (flat, non-mangled) API?

**Comment by peterychang** [comment]
I _believe_ enum classes are mangled in the same way a namespace would be. In fact, I'm pretty sure the following will cause a redefinition compilation error

<code>
enum class Test { TEST1, TEST2, TEST3 };

namespace Test { const int TEST1 = 1; }
</code>

However, even if they aren't, its possible to define the underlying data type to enum classes, which will allow them to be set based on that type (though you need to do a cast to reverse the translation). That would allow us to expose a const int or something on the user end, and work exclusively off enum classes in the library
