### ISSUE TITLE
Merge functionality of all.pairs and all.triples into all.interactions

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1863]
Interactions is the general case of pairs and triples. They should be merged into interactions, this has been partially done but would be good to finish off and remove the extra fields.

**Comment by JohnLangford** [comment]
This would need very careful profiling as I belief it was not merged because of profiling previously.

**Comment by jackgerrits** [comment]
By this I mean merging the fields in global data, not merging the logic when we generate the interactions down in gd. We should definitely keep the special cases for quadratic and cubic because of perf.

**Comment by kumpera** [comment]
This cleanup will make my life easy speeding `-q ::` so I'm doing it
