### ISSUE TITLE
gd_mf_weights.cc has bug in writing out features for the right namespace

### ISSUE THREAD

**Issue by szipkin** [VowpalWabbit/vowpal_wabbit#1871]
### Bug:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/45a8a7f5507015a17d585f7698eab20c963b592b/library/gd_mf_weights.cc#L94

The current code for the right namespace is incorrectly pointing to the left.indices, not right. As a result, it generates wrong output for the right namespace.

    // write out features for left namespace
    features& left = ec->feature_space[left_ns];
    for (size_t i = 0; i < left.size(); ++i)
    { left_linear << left.space_names[i].get()->second << '\t' << weights[left.indicies[i]];

      left_quadratic << left.space_names[i].get()->second;
      for (size_t k = 1; k <= rank; k++)
        left_quadratic << '\t' << weights[(left.indicies[i] + k)];
    }
    left_linear << endl;
    left_quadratic << endl;

    // write out features for right namespace
    features& right = ec->feature_space[right_ns];
    for (size_t i = 0; i < right.size(); ++i)
    { right_linear << right.space_names[i].get()->second << '\t' << weights[left.indicies[i]];

      right_quadratic << right.space_names[i].get()->second;
      for (size_t k = 1; k <= rank; k++)
        right_quadratic << '\t' << weights[(left.indicies[i] + k + rank)];
    }
    right_linear << endl;
    right_quadratic << endl;

### Shouldn't it be like this instead?
    // write out features for right namespace
    features& right = ec->feature_space[right_ns];
    for (size_t i = 0; i < right.size(); ++i)
    { right_linear << right.space_names[i].get()->second << '\t' << weights[right.indicies[i]];

      right_quadratic << right.space_names[i].get()->second;
      for (size_t k = 1; k <= rank; k++)
        right_quadratic << '\t' << weights[(right.indicies[i] + k)];
    }
    right_linear << endl;
    right_quadratic << endl;

**Comment by ataymano** [comment]
Yes, that seems correct. Do you want to send pull request?

**Comment by szipkin** [comment]
It's my first time creating a pull request. Let me know if I didn't do it correctly. Thanks.

**Comment by ataymano** [comment]
Thanks for creating pull request. It looks good.
But I have added one comment there - sorry, haven't noticed one mistake in initial proposal.

**Comment by jackgerrits** [comment]
Looks like #1874 has resolved this. Please reopen if there is still an issue.
