### ISSUE TITLE
Fix cb_adf / softmax test from RunTests (Test 188)

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#1881]
#### Describe the bug
RunTests use empty line as separator between scenarios in the way that the last test is ignored if there is no empty line afterwards (so it have never been executed now). But it is failing actually.

#### To Reproduce
1. Add new line at the end of RunTests
2. Rebuild/rerun tests

#### Expected behavior
All tests should pass

#### Observed Behavior
cb_adf_sm test is failing

#### Environment
Windows, latest master

**Comment by lokitoth** [comment]
This is hidden by #1878 (by adding it to ignores).

I wonder whether there is an inconsistency between the code on Windows / Linux, because the failure is at validation of average loss from summary statistics, because it goes from expected 1.5 to observed 2.0

**Comment by jackgerrits** [comment]
Tested using the run_tests.py driver on Windows this test passes as of 8.10. Closing this issue.
