### ISSUE TITLE
Some CB workflows bypass CSOAA for the reward predictor

### ISSUE THREAD

**Issue by peterychang** [VowpalWabbit/vowpal_wabbit#1889]
#### Describe the bug
In at least one workflow (cb_adf with --cb_type dr) the code path bypasses the normal reduction stack and makes a series of function calls, which results in at least one reduction being bypassed.

This bug was discovered during a small refactor of code relating to how shared examples are being handled https://github.com/VowpalWabbit/vowpal_wabbit/pull/1873

Adding this issue to track any additional workflows that may be impacted

#### To Reproduce
1. Used the command `vw --cb_adf --rank_all -d train-sets/cb_test.ldf -p cb_adf_rank.predict --cb_type dr --audit`
2. Traced the call stack back from the first audit print, observed expected reductions being bypassed

#### Expected behavior
The reduction stack should be used, and components within it should not be calling learn or predict functions of other reductions directly

#### Observed Behavior
The call stack looks like
CB_ADF::do_actual_learning<is_learn==1>
CB_ADF::learn_DR
GEN_CS::gen_cs_example_dr
CB_ALGS::get_cost_pred
* Up until this point, is_learn == 1
But in get_cost_pred, there’s a check
https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/cb_algs.h#L38
in this case, known_cost==nullptr, so now we go down the predict path.
Specifically, get_cost_pred calls scorer->predict() directly, which bypasses the CSOAA component

scorer::predict_or_learn<is_learn==0>
GD::predict<l1==0>

Its been confirmed that interactions between shared and non-shared features are not being taken into account in this instance

#### Environment
the latest Master was used as the baseline
697d4fce57ee3269e299c7e87a2fbe8e1dcc2f7f

#### Additional context
The fork/branch https://github.com/peterychang/vowpal_wabbit/tree/shared_example_merge_reduction should resolve the bug once the change is completed and merged

**Comment by JohnLangford** [comment]
Should be fixed now.
