### ISSUE TITLE
invert_hash not working with bfgs

### ISSUE THREAD

**Issue by agroh1** [VowpalWabbit/vowpal_wabbit#1891]
#### Describe the bug
Using invert_hash with bfgs fails to produce any features in the output file.

#### To Reproduce
First train the model:

vw --holdout_off --loss_function logistic --passes 2   --bfgs   --cache_file=/tmp/bfgs_training/vw.cache_file -f /tmp/bfgs_training/vw.models -d training_data.txt
[training_data.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/3217516/training_data.txt)

Then invert the hash
vw --loss_function=logistic  -t  -i /tmp/bfgs_training/vw.models --invert_hash /tmp/bfgs_training/readable -d training_data.txt

There are no model coefficents in /tmp/bfgs_training/readable

If you change from bfgs to ftrl then model coefficents do work.

This worked in vw 8.5 but is broken in 8.6 and master.

#### Expected behavior
features with their coefficient data in the readable model file

#### Observed Behavior
No features in the model file

#### Environment
VW 8.6 and master on both MacOS and Linux

#### Additional context
I am making a pull request with a fix (mostly just copying the logic from ftrl

**Comment by jackgerrits** [comment]
Thanks for submitting a PR, I'd like to get John to take a look at this.

**Comment by jackgerrits** [comment]
Can you confirm that #1892 fixes this?

**Comment by jackgerrits** [comment]
Closing since the PR is merged, please reopen if the bug is still present
