### ISSUE TITLE
-c creates cache file when pass multiple existing cachefiles

### ISSUE THREAD

**Issue by seanv507** [VowpalWabbit/vowpal_wabbit#1894]
#### Describe the bug
-c causes vw to generate a .cache file if pass multiple cache files via cache_file argument.
Expect cache file only to be generated if cache and parameters (eg bit precision) are out of alignment

#### To Reproduce
`vw -c --cache_file test.cache --cache_file test1.cache`

#### Expected behavior
use test.cache and test1.cache without creating .cache file (=concatenation)
#### Observed Behavior
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using cache_file = test.cache
using cache_file = test1.cache
creating cache_file = .cache
ignoring text input in favor of cache input
num sources = 2
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
1.000000 1.000000            1            1.0   1.0000   0.0000        2
1.285535 1.571069            2            2.0  -1.0000   0.2534        2

[Subsequently if I do vw --predictions predictions.txt -i model_name -c  --cache_file test.cache --cache_file test1.cache, then it generates predictions for test.cache, test1.cache and .cache, so double the original dataset]

#### Environment

 `VW 8.6.1 on Linux `

#### Additional context
generated dummy data
echo "1 | 0" | vw --cache_file test.cache
echo "-1 | 1" | vw --cache_file test1.cache

**Comment by JohnLangford** [comment]
It looks like you can remove -c and get the desired behavior.

**Comment by jackgerrits** [comment]
@seanv507 does this solve your problem?

**Comment by seanv507** [comment]
yes, (and its what I do), but its contrary to the 'recommendation' to always have the c option (to recreate cache if necesssary - change of eg bit_precision)

**Comment by jackgerrits** [comment]
It seems like this is resolved, even though the behavior is a little counter intuitive.
