### ISSUE TITLE
invert hash function is failing

### ISSUE THREAD

**Issue by sharathmalladi** [VowpalWabbit/vowpal_wabbit#1929]
#### Describe the bug
The invert hash option for vw is failing for me.

#### To Reproduce
1. Used this specific command line:
vw --cb_adf -l 0.01 --dsjson --data /tmp/02b82f92-4949-476f-bbcc-3c8b724606f6/cmplx-sl2/cmplx-sl2_merged_data_2018-04-09_2018-04-09.json.gz --quiet --invert_hash out.txt

#### Expected behavior
invert hash file must be created.

#### Observed Behavior
I see the following output on the console and no invert hash file is generated.
vw (/mnt/c/Users/pasrinat/Documents/repos/vowpal_wabbit/vowpalwabbit/cb_adf.cc:137): warning: example headers at position 14: can only have in initial position!

#### Environment
What version of VW did you use? 8.6.1. I got the binary from Pavithra.
What OS or language did you use? Linux

e.g. `VW 8.6.1 on Linux with the Python bindings`

**Comment by jackgerrits** [comment]
This issue is resolved in 8.7.0, specifically by #1878
