### ISSUE TITLE
hashed feature output from vw should output strings that are easy to scrub

### ISSUE THREAD

**Issue by sharathmalladi** [VowpalWabbit/vowpal_wabbit#1935]
[FeatureImportance.zip](https://github.com/VowpalWabbit/vowpal_wabbit/files/3293809/FeatureImportance.zip)
#### Describe the bug
The invert hash strings returned by calling vw with the invert_hash option is returning strings that are difficult to interpret programmatically.

#### To Reproduce
1. Call vw with invert_hash option.

#### Expected behavior
The returned strings must have a delimiter between feature name and hash value. Example:
FromUrl^timeofday=Morning*FromUrl^name=Alice

#### Observed Behavior
Invert hash values that don't have a delimiter between feature name and value. Example:
FromUrl^timeofdayMorning*FromUrl^nameAlice

#### Environment
What version of VW did you use? 8.7.0
What OS or language did you use? Linux

#### Additional context
Attached is a zip file showing output from different examples.

**Comment by rajan-chari** [comment]
This is would be very helpful for @sharathmalladi  from implementing feature importance weight discovery.

**Comment by jackgerrits** [comment]
Just talked to John and the way we want to approach this is to extend the vw input language to accept features in the form <string>:<string>. Up until now we have warned on this. The hash this then <string>:<string>, and works almost exactly as <string>=<string>. The benefit of doing this is that now the use case in JSON you are mentioning can be supported as inserted that colon and we don't need to treat it specially.

**Comment by sharathmalladi** [comment]
Thanks Jack! Any delimiter works for me.
