### ISSUE TITLE
Support for tags in JSON format

### ISSUE THREAD

**Issue by helderm** [VowpalWabbit/vowpal_wabbit#1940]
#### Describe the bug
Tags are currently not supported when using JSON as input format, this is an issue to request it to be added to the parser.

#### Rationale
Tags can be used to join the predictions to a sample identifier. This would help to integrate VW with big data databases like BigQuery that have native support for exporting tables as newline-delimited JSON files.

#### To Reproduce
1. Call `vw` passing `--json` and a JSON configured input file

#### Expected behavior
Tags are printed alongside the prediction output.

#### Observed Behavior
Tags are ignored at parsing.

#### Environment
VW 8.5.0 on Linux

**Comment by lokitoth** [comment]
Tag is supported, but was undocumented in the wiki. I fixed this: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/JSON 

Or is it that you are running into an issue where files with "_tag" do not produce tags?

**Comment by helderm** [comment]
I just tested and it is working perfectly. Thanks for adding it to the wiki!
