### ISSUE TITLE
Move to GitHub apps for continuous integration

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#1953]
GitHub apps are the new way to integrate CI, it provides a richer reporting interface. We should look at migrating our CI to consuming them in this way.

https://github.com/marketplace/coveralls
https://github.com/marketplace/lgtm

**Comment by jackgerrits** [comment]
Azure pipelines is being used as an all. Migrating the other CI's is low pri as they are functioning just fine right now

**Comment by jackgerrits** [comment]
Reopening this for LGTM. They are stopping support for the way we consume it on October 1, 2019. We will need to migrate before then or it will stop working.

@lokitoth FYI

**Comment by jackgerrits** [comment]
@JohnLangford LGTM deprecated the old authentication method, so we need to move to GitHub apps to continue using it. I've requested access, but it might require more attention to get it fixed.

![image](https://user-images.githubusercontent.com/7558482/66128953-e92a8100-e5bc-11e9-99ea-9a85c00367b5.png)

**Comment by JohnLangford** [comment]
(I approved it.)

**Comment by jackgerrits** [comment]
Looks like it's fixed, thanks!
