### ISSUE TITLE
--classweight option bug

### ISSUE THREAD

**Issue by serjioteh** [VowpalWabbit/vowpal_wabbit#1967]
#### Describe the bug
After upgrade to 8.7.0 --classweight option with argument '-1:0.5' gives an error:
unrecognised option '---1'
vw (options_boost_po.cc:152): unrecognised option '---1'
#### To Reproduce
vw mail_train.vw -f model.vw --link=logistic --loss_function=logistic --passes 30 -c -k --classweight -1:0.5

#### Observed Behavior
Doesn't run
unrecognised option '---1'
vw (options_boost_po.cc:152): unrecognised option '---1'

#### Environment
VW 8.7.0
Ubuntu 16

#### Additional context
VW runs with --classweight 0:0.5
Something wrong with minus symbol.

**Comment by jackgerrits** [comment]
This is a problem with the argument parsing and definitely a bug, thanks for reporting it.

In the meantime to mitigate this please use the option as: `--classweight=-1:0.5`
