### ISSUE TITLE
Feature order is affecting prediction with cubic interaction

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2027]
#### Describe the bug
Ordering of features is affecting the prediction value. The model file includes an interaction `8FF`, when I provide a different interaction via the command line as `8F`, then the outputted predictions are identical.

It seems to me there is a bug in the way that self interactions are computed causing this difference.

#### To Reproduce
1. `./vw .-d /badcase-inference.txt --dsjson -p stdout --quiet -t -i ./model-string.model.txt`
2. Notice that the printed predictions are different
```
0:1,6:0,3:0,4:0,1:0,9:0,7:0,5:0,8:0,2:0

6:1,0:0,4:0,1:0,7:0,9:0,8:0,5:0,3:0,2:0
```
#### Expected behavior
Outputted predictions should be the same

```
6:1,2:0,3:0,0:0,4:0,8:0,9:0,5:0,1:0,7:0

6:1,2:0,3:0,0:0,4:0,8:0,9:0,5:0,1:0,7:0
```
#### Environment
What version of VW did you use?
8.7.0 (git commit: fb87d97b)
What OS or language did you use?
Ubuntu 18.04 command line

[badcase-inference.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/3503307/badcase-inference.txt)
[model-string.model.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/3503310/model-string.model.txt)

**Comment by JohnLangford** [comment]
I'm not sure what's up, but for efficiency reasons, the self interaction of features A B in a self interacting namespace F include AB but not BA by default.  The theory here is that AB contains the same information as BA so there is no need for about half the interactions.

**Comment by jackgerrits** [comment]
After looking into this further, this is expected behavior. When doing interactions, order of features matter as that is what composes the hash index of the interacted feature. The reason why the predictions differ here is because there exists weights in the model for only one ordering of the interacted features.

If you are operating in a situation where this would be a problem, then you can supply the command line option `--sort_features`, which will ensure in the internal example representation features are sorted and thus the hash is consistent.

**Comment by darkgraviton** [comment]
Thanks for looking into this. --sort_features sounds a good mitigation. My personal view as an external user is to have this behavior hidden from user, and vw internally considers a deterministic/consistent reordering of features; I would have expected that context/features to be unordered collection and behave like dictionary. I feel otherwise if a user is not careful, it could lead to incorrect inference, which impacts the inference performance   I'm curious to know the reason to treat it as an ordered list.

**Comment by JohnLangford** [comment]
The issue here is that imposing an order is O(n log n) while VW is O(n).  The extra log n is noticeable, as you'll see when using --sort_features with a significant number of features/example.

**Comment by kumpera** [comment]
Couldn’t we use a commutative operation to compute the hash of interacted features?

IE, instead of hash(AB) we could do something like hash(hash(A) + hash(B)) which would address the issue while keeping it linear.

**Comment by JohnLangford** [comment]
The only commutative op that's fast enough is bitwise xor.   I've avoided that because it's relatively easy to get systematic collisions with xor.
