### ISSUE TITLE
Nan prediction in ccb_explore_adf

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#2033]
#### Describe the bug
ccb_explore_adf returns Nan prediction sometimes.

#### To Reproduce
Data to reproduce: \\ATAYMANO-Z8\shared\ccb_failure\repro
vw --dsjson --ccb_explore_adf --epsilon 0.2 -d A.json     - everything is ok
vw --dsjson --ccb_explore_adf --epsilon 0.2 -d B.json     - everything is ok
type A.json B.json > AB.json
vw --dsjson --ccb_explore_adf --epsilon 0.2 -d AB.json     - NAN prediction in example 9014, forcing 0.000000

#### Expected behavior
Last call should be succesfull as well (since first two were succesfull => input data is valid)

#### Environment
Latest master (8.7.0) on windows

**Comment by jackgerrits** [comment]
Thanks Alexey, I’ll look into it
