### ISSUE TITLE
Unable to use default CMake + vcpkg to build in Ubuntu 18.04 

### ISSUE THREAD

**Issue by rajan-chari** [VowpalWabbit/vowpal_wabbit#2051]
#### Describe the bug
Building vw in Ubuntu 18.04 using default cmake produces boost errors

#### To Reproduce
1) Clean WSL Ubuntu 18.04 install (checked with lsb_release -a)
2) Installed vcpkg and required libraries including boost
3) Use CMake to build

#### Expected behavior
Should be able to build vw with the default CMake in Ubuntu 16.  Ideally Ubuntu 14.

#### Observed Behavior
See CMake Output below:

#### Environment
master branch - following commit
https://github.com/VowpalWabbit/vowpal_wabbit/commit/57cd4f51df65100c2ecbfd215196542534f17225 
OS: WSL Ubuntu 18.04 

CMake error:
maryam@DESKTOP-21AEI01:/mnt/c/Users/maryam majzoubi/Desktop/vowpal_wabbit/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DVALGRIND_PROFILE=On -DCMAKE_TOOLCHAIN_FILE=/home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)
-- The C compiler identification is GNU 7.4.0
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCCompiler.cmake:192 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)
-- The CXX compiler identification is GNU 7.4.0
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:190 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:72 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:65 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)
-- VowpalWabbit Version: 8.7.0
-- Found Git: /usr/bin/git (found version "2.17.1")
-- Git Version: 1acbe2d2
-- Number of processors: 4
CMake Error at /usr/share/cmake-3.10/Modules/CheckIncludeFile.cmake:46 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindThreads.cmake:121 (CHECK_INCLUDE_FILE)
  /home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:256 (_find_package)
  CMakeLists.txt:126 (find_package)
-- Looking for pthread.h
-- Looking for pthread.h - found
CMake Error at /usr/share/cmake-3.10/Modules/CheckSymbolExists.cmake:79 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CheckSymbolExists.cmake:48 (__CHECK_SYMBOL_EXISTS_IMPL)
  /usr/share/cmake-3.10/Modules/FindThreads.cmake:134 (CHECK_SYMBOL_EXISTS)
  /home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:256 (_find_package)
  CMakeLists.txt:126 (find_package)
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:220 (_find_package)
  CMakeLists.txt:143 (find_package)
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:220 (_find_package)
  CMakeLists.txt:143 (find_package)
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
**Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:220 (_find_package)
  CMakeLists.txt:143 (find_package)
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:220 (_find_package)
  CMakeLists.txt:143 (find_package)
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:220 (_find_package)
  CMakeLists.txt:143 (find_package)
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /home/maryam/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:220 (_find_package)
  CMakeLists.txt:143 (find_package)**

**Comment by jackgerrits** [comment]
See line that says: `New Boost version may have incorrect or missing dependencies and imported
targets`

CMake can only find up to a certain version of Boost based on its own version. For CMake 3.10 being used here it can find up to and including Boost 1.66. You can inspect the [FindBoost](https://github.com/Kitware/CMake/blob/v3.10.3/Modules/FindBoost.cmake) file to see this.

Because you used vcpkg to install Boost, and it doesn't really have a version story, it just pulled in the latest. Currently the latest version of vcpkg pulls in Boost 1.70, which CMake will not be able to find. To mitigate in your case you need to either use a newer CMake version or an older Boost version.

This is not really something we can handle. Using system installed CMake + Boost will work, provided they meet minimum requirements. On Windows the default CMake installation is usually much more recent (because you install from the site), and so this problem is less prevalent.

**Comment by rajan-chari** [comment]
In that case so we need to checkin vcpkg into our repo and bootstrap from there? We can freeze the boost version there... which seems like their recommended strategy.

**Comment by jackgerrits** [comment]
If we want to be able to freeze different dependencies at different versions then forking under the vw org would work

**Comment by rajan-chari** [comment]
It seems reasonable to freeze 3rd party dependencies and periodically refresh them as needed.

**Comment by jackgerrits** [comment]
Closing this as the supported way of installing dependencies on Ubuntu is apt-get.

See: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies
