### ISSUE TITLE
Consider consuming fmt library

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2066]
VW does a lot of string formatting and printing. Sometimes this is with streams, sometimes with printf. `fmt` is a library that just does formatting, it's fast and very high quality. It has been merged into the standard in 20, as `std::fmt`.

It is faster than `sprintf` and streams:
![](https://user-images.githubusercontent.com/576385/54883977-9fe8c000-4e28-11e9-8bde-272d122e7c52.jpg)
[Image taken from readme](https://github.com/fmtlib/fmt#speed-tests)

It also produces a smaller binary than using streams. [See source](https://github.com/fmtlib/fmt#compile-time-and-code-bloat)

https://github.com/fmtlib/fmt

**Comment by olgavrou** [comment]
Considered, implementing logging with spdlog
