### ISSUE TITLE
Reduce number of platform checks required by codebase

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2072]
There are many platform checks present (`#ifdef _WIN32`). They are used for many reasons but a common patterns is for sockets and file IO using OS functions. If those functions are moved behind an interface we reduce the amount of platform checks required.

**Comment by arielf** [comment]
I once started working on this, creating a file `vw_platform.h`
Attaching it here (as *.txt) in the hope it could help.

[vw_platform.h.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/3567664/vw_platform.h.txt)

**Comment by jackgerrits** [comment]
Thanks @arielf that's helpful!

**Comment by jackgerrits** [comment]
Closing this issue as it is unactionable as it is currently. However, reduction of platform checks is ongoing and things like the io lib refactor is an example of this.
