### ISSUE TITLE
Allow overriding the --epsilon value when there is already a value stored in the model

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2101]
Plan:
1. Change epsilon to a list of values
2. Always use the last value in the list as the epsilon value
3. Check: When a command line and model are loaded which both specify the value, the command line value should take precedence
4. When serializing the value, only save the last value in the list

**Comment by lokitoth** [comment]
Per discussion offline and comments in PR: This is a bigger change that the plan suggested, as it involves changing how options merging happens when loading the file. Will push in after 8.8.0, and stabilize for 8.Next or 9
