### ISSUE TITLE
Combining --no_predict and --cb_sample (or --ccb_explore_adf) causes a segfault

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2110]
Since a prediction is not produced, cb_sample is not able to sample from the range and currently crashes.

Repro: `ccb_test.txt --ccb_explore_adf  --epsilon 0.8 --onethread --ring_size 7 --no_predict`

[ccb_test.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/3713744/ccb_test.txt)

**Comment by lokitoth** [comment]
Is the right thing to do here to error out because the combination of --no_predict and --cb_sample is undefined?
