### ISSUE TITLE
Incorrect predictions after loading model

### ISSUE THREAD

**Issue by ankane** [VowpalWabbit/vowpal_wabbit#2120]
Hi, thanks for this awesome library 👍

#### Describe the bug

I'm seeing incorrect predictions after loading a model with the Scikit-learn API.

#### To Reproduce

```python
from vowpalwabbit.sklearn_vw import VWRegressor

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [1, 2, 3, 4]

model = VWRegressor(l=100)
model.fit(X, y)
print(model.predict(X)) # [1. 2. 3. 4.]

model.save("/tmp/train.model")

model2 = VWRegressor(l=100)
model2.load("/tmp/train.model")
print(model2.predict(X)) # [1. 1. 1. 1.]
```

#### Expected behavior

The same predictions for both models: `[1. 2. 3. 4.]`

#### Observed Behavior

Different predictions for the loaded model: `[1. 1. 1. 1.]`

#### Environment

Master branch on MacOS 10.14.6 with the Python bindings

**Comment by jackgerrits** [comment]
It seems to me that what may be happening here is that the Sklearn code is not capturing complete state when it saves and loads. In particular it seems that the adaptive weights are being lost and perhaps that is influencing the different output? I am not sure if they should actually matter at predict time though.

I am wondering if there may also be something weird going on here to do with sparse vs dense weights.

The Sklearn wrapper functions for save and load are:
```Python
    def save(self, filename):
        """Save model to file"""
        joblib.dump(dict(params=self.get_params(), coefs=self.get_coefs(), fit=self.fit_), filename=filename)

    def load(self, filename):
        """Load model from file"""
        obj = joblib.load(filename=filename)
        self.set_params(**obj['params'])
        self.set_coefs(obj['coefs'])
        self.fit_ = obj['fit']
```

Audit:
You'll notice in this audit that the weights are the same before and after loading. But the @ssgrad value differs.
```sh
# Learn
0
        0:0:1:0@0       1:1:2:0@0       Constant:116060:1:0@0
2
        0:0:3:0.333333@4        1:1:4:0.166667@16       Constant:116060:1:0.333333@4
3
        0:0:5:0.333333@4        1:1:6:0.166667@16       Constant:116060:1:0.333333@4
4
        0:0:7:0.333333@4        1:1:8:0.166667@16       Constant:116060:1:0.333333@4
-----
# Predict before load
1
        0:0:1:0.333333@4        1:1:2:0.166667@16       Constant:116060:1:0.333333@4
2
        0:0:3:0.333333@4        1:1:4:0.166667@16       Constant:116060:1:0.333333@4
3
        0:0:5:0.333333@4        1:1:6:0.166667@16       Constant:116060:1:0.333333@4
4
        0:0:7:0.333333@4        1:1:8:0.166667@16       Constant:116060:1:0.333333@4
[1. 2. 3. 4.]
# Predict after load
1
        0:0:1:0.333333@0        1:1:2:0.166667@0        Constant:116060:1:0.333333@0
1
        0:0:3:0.333333@0        1:1:4:0.166667@0        Constant:116060:1:0.333333@0
1
        0:0:5:0.333333@0        1:1:6:0.166667@0        Constant:116060:1:0.333333@0
1
        0:0:7:0.333333@0        1:1:8:0.166667@0        Constant:116060:1:0.333333@0
[1. 1. 1. 1.]
```

**Comment by ankane** [comment]
Hey @jackgerrits, thanks for looking into it. Do you know why the Scikit-learn class uses a different save format than the `vw` class?

**Comment by jackgerrits** [comment]
I'm not sure why the sklearn bindings do it this way, @Scott-Graham-Bose do you have context?

**Comment by lokitoth** [comment]
From offline discussion:
It is possible issue here is not writing header (including min/max values, which would cause it to truncate?)
