### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [VowpalWabbit/vowpal_wabbit#2121]
Hi, thanks for this awesome library! Thanks to the C API, there are now [Ruby bindings](https://github.com/ankane/vowpalwabbit) for Vowpal Wabbit. Addresses #1324. Feel free to create an issue on the project if you have any feedback.

A few notes:

- The API was easy to follow 🎉 
- It'd be great if the `--strict_parse` flag didn't raise an uncaught exception (which terminates the program) - I believe #2004 was created to address this
- I couldn't find a way to pass file paths with spaces to the `--data` option via `VW_InitializeA`. I tried shell escaping and quoting but no luck. Is there a way to do this? For example:
  ```
  VW_InitializeA("--data /path/with/sp ace.txt")
  ```

**Comment by jackgerrits** [comment]
> It'd be great if the --strict_parse flag didn't raise an uncaught exception (which terminates the program) - I believe #2004 was created to address this

I think the problem here is that the exception is being raised internally and is not being caught before hitting the C boundary. This is a problem for sure, since it breaks error handling over the boundary. Will definitely look into fixing this soon.

> I couldn't find a way to pass file paths with spaces to the --data option via VW_InitializeA. I tried shell escaping and quoting but no luck. Is there a way to do this?

Thanks for bringing this up, this is definitely an API issue.

PRs are definitely welcome 😄

**Comment by jackgerrits** [comment]
Do you have any feedback on usability of the C API? Things you wish it supported? etc?

**Comment by ankane** [comment]
Hey @jackgerrits, thanks for the response. I don't have any feedback at the moment besides the above.

Re `--data` option and spaces: it looks like the issue referenced is about the C boundary.

**Comment by jackgerrits** [comment]
Thanks for pointing that out, fixed up the tracking issues.

**Comment by ankane** [comment]
Great, thanks!
