### ISSUE TITLE
Parsing of negative values is messed up

### ISSUE THREAD

**Issue by JohnLangford** [VowpalWabbit/vowpal_wabbit#2161]
#### Describe the bug

vw --quiet --min_prediction -20
Error: unrecognised option '---2'
unrecognised option '---2'
vw (/home/jl/programs/vowpal_wabbit/vowpalwabbit/options_boost_po.cc:152): unrecognised option '---2'

#### Expected behavior
The min prediction should be set to -20.

#### Environment
What version of VW did you use?  8.6.1, but it's also in the latest master.
What OS or language did you use? Linux

**Comment by jackgerrits** [comment]
I just tested this in the latest master and I wasn't able to repro. Could you make sure you have commit 87798f4ed4ebfc7d597beac9184feed924de7848 locally and let me know if it still reproduces?

**Comment by JohnLangford** [comment]
Confirmed!
