### ISSUE TITLE
Investigate/remove parser dependency on shared_data 

### ISSUE THREAD

**Issue by peterychang** [VowpalWabbit/vowpal_wabbit#2178]
The intended purpose of shared_data appears to be a piece of memory thats shared across multiple processes in daemon mode.

It doesn't look like the parser needs shared_data, the few pieces of data it actually reads/writes in shared_data doesn't seem to need to be in there.
This task will involve:
- Investigate if the parser needs _anything_ in shared_data
- Pull irrelevant members out of shared_data
- Make parser usage of these variables consistent
- Refactor function interfaces

This will need to be done after https://github.com/VowpalWabbit/vowpal_wabbit/pull/2117 is merged

**Comment by TheLethalCode** [comment]
@peterychang Are you working on this?

**Comment by jackgerrits** [comment]
There was a dependency on shared data for count label which was removed here: #3404

The remaining dependency is for `VW::named_labels`. This is required but seems to be fine since it is a specific dependency and is not modified in the parser.
