### ISSUE TITLE
Python test failure for python 3.6 on Windows

### ISSUE THREAD

**Issue by peterychang** [VowpalWabbit/vowpal_wabbit#2183]
__________________________________________________________________________________________________ TestVW.test_predict_not_fit __________________________________________________________________________________________________
 
self = <test_sklearn_vw.TestVW object at 0x000002BAFC9C3C18>
data = Dataset(x=array([[ 1.62434542e+00, -6.11756384e-01, -5.28171778e-01,
        -1.07296860e+00,  8.65407646e-01, -2.3015... -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,
       -1., -1.,  1.,  1., -1., -1.,  1., -1., -1.]))
 
    def test_predict_not_fit(self, data):
        model = VW(loss_function='logistic')
        with pytest.raises(ValueError):
>           model.predict(data.x[0])
E           Failed: DID NOT RAISE <class 'ValueError'>
 
python\tests\test_sklearn_vw.py:75: Failed

**Comment by peterychang** [comment]
It looks like this is due to a change in sklearn 0.22's `check_is_fitted()` function

https://scikit-learn.org/stable/modules/generated/sklearn.utils.validation.check_is_fitted.html

The `attributes` parameter is now deprecated and is ignored

**Comment by jackgerrits** [comment]
Fixed in #2208
