### ISSUE TITLE
undefined behavior in shared_data in daemon mode

### ISSUE THREAD

**Issue by peterychang** [VowpalWabbit/vowpal_wabbit#2188]
When running VW in daemon mode, all.sd is being mmap'd with the MAP_SHARED flag.
Additionally, the members of all.sd are being read and modified with no synchronization, which will result in race conditions for every read and store operation.

Assuming locking and/or synchronizing every operation will be infeasible due to its high cost, we'll need to design a way to keep the data in an unambiguous (and preferably reproducible) state .

**Comment by peterychang** [comment]
It appears futexes can be used to synchronize across process boundaries at a relatively low cost
https://eli.thegreenplace.net/2018/basics-of-futexes/

The windows equivalent to futex is `WaitOnAddress`

**Comment by jackgerrits** [comment]
Spoke to @JohnLangford about this. Essentially the lack of synchronization in daemon mode is intended behavior. This particular paper is relevant to the approach: [HOGWILD!: A Lock-Free Approach to Parallelizing Stochastic Gradient Descent](https://arxiv.org/abs/1106.5730). Making updates during daemon mode should only be done if you understand what dangers that comes with. Any races during prediction should not affect the prediction and only counters/accounting. Patches welcome here though.
