### ISSUE TITLE
CB --cb_explore_adf segmentation fault

### ISSUE THREAD

**Issue by AlexFridman** [VowpalWabbit/vowpal_wabbit#2191]
#### Describe the bug
Hello!

I'm constantly getting
- "NAN prediction for example"
- "segmentation fault"

 on Linux and OS X (built from sources) with my data using Python bindings.
I've prepared a simple [example](https://gist.github.com/AlexFridman/013c7bb7391c277b3c3e122f9f3ee2e4) to reproduce. Maybe I have a misunderstanding of data format, so please correct me.
I'm trying to reproduce  ["Simulating Content Personalization with Contextual Bandits "](https://vowpalwabbit.org/tutorials/cb_simulation.html) tutorial.

#### To Reproduce
Script and data file are placed [here](https://gist.github.com/AlexFridman/013c7bb7391c277b3c3e122f9f3ee2e4).
1. Download both files from gist and place them in a folder.
2. Run script.py

#### Observed Behavior

> NAN prediction in example 69, forcing 0.000000
NAN prediction in example 69, forcing 0.000000
NAN prediction in example 70, forcing 0.000000
NAN prediction in example 70, forcing 0.000000
NAN prediction in example 70, forcing 0.000000
Segmentation fault (core dumped)

From gdb:

> Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffd147bb26 in void VW::cb_explore_adf::greedy::cb_explore_adf_greedy::predict_or_learn_impl<false>(LEARNER::learner<char, st
d::vector<example*, std::allocator<example*> > >&, std::vector<example*, std::allocator<example*> >&) ()
   from /home/alex/.virtualenvs/adv/lib/python3.6/site-packages/vowpalwabbit-8.8.0-py3.6-linux-x86_64.egg/pylibvw.so

#### Environment
VW 8.8.0 (git commit: f83c0e30)
Ubuntu 16
Python

**Comment by jackgerrits** [comment]
Hi @AlexFridman,

When you use `parse` on its own, then once you are done with the parsed examples you need to return them to the vw instance with `vw.finish_example(example)`. You also need to specify the contextual bandit label when using this data. Unfortunately I've just discovered that `predict` and `learn` don't support passing the label type right now (#2192). This can be mitigated by using parse directly as you've done. You also need to call del or finish on the vw instance when you are done to clean up, although it seems there is an issue with calling finish on its own when reusing a cell (issue created, #2193).

Even with these two issues your script can be changed to follows to make it work:
```Python
from vowpalwabbit import pyvw

vw = pyvw.vw('--cb_explore_adf --epsilon 0.2 --ring_size 4000')
with open('data.txt') as f:
    examples = f.read().strip().split('\n\n')

for example in examples:
    pred_example = vw.parse(example, pyvw.vw.lContextualBandit)
    pmf = vw.predict(pred_example)
    vw.finish_example(pred_example)

    learn_example = vw.parse(example, pyvw.vw.lContextualBandit)
    vw.learn(learn_example)
    vw.finish_example(learn_example)

del vw
```

**Comment by AlexFridman** [comment]
@jackgerrits , thank you very much for the quick reply! It's working.
