### ISSUE TITLE
del and finish are behaving differently in Python (del causes crash)

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2193]
Running the following in a cell in a Jupyter notebook twice fails:
```Python
from vowpalwabbit import pyvw

vw = pyvw.vw('--cb_explore_adf --epsilon 0.2 --ring_size 4000')
with open('data.txt') as f:
    examples = f.read().strip().split('\n\n')

for example in examples:
    pred_example = vw.parse(example, pyvw.vw.lContextualBandit)
    pmf = vw.predict(pred_example)
    vw.finish_example(pred_example)

    learn_example = vw.parse(example, pyvw.vw.lContextualBandit)
    vw.learn(learn_example)
    vw.finish_example(learn_example)

vw.finish()
```

Whereas the following works:
```Python
from vowpalwabbit import pyvw

vw = pyvw.vw('--cb_explore_adf --epsilon 0.2 --ring_size 4000')
with open('data.txt') as f:
    examples = f.read().strip().split('\n\n')

for example in examples:
    pred_example = vw.parse(example, pyvw.vw.lContextualBandit)
    pmf = vw.predict(pred_example)
    vw.finish_example(pred_example)

    learn_example = vw.parse(example, pyvw.vw.lContextualBandit)
    vw.learn(learn_example)
    vw.finish_example(learn_example)

del vw
```
The only difference is the last line.

**Comment by AlexFridman** [comment]
Hi, @jackgerrits! I've faced with another (I guess) issue of the Python wrapper.
If I do not set --ring-size parameter to the big enough value (in my case 400k) I'm getting these errors:
python:

> RuntimeError: cb_adf: badly formatted example, only one line can have a cost

stderr:

> NAN prediction in example 207, forcing 0.000000  

I found 400k multiplying 4000 from your example by 10 a few times))
Could you please explain this parameter? Is it expected behavior?
This issue can be reproduced with my data from #2191 and your final script setting --ring-size to 256.

**Comment by jackgerrits** [comment]
Can you please provide data.txt?

**Comment by jackgerrits** [comment]
@AlexFridman can you please provide data.txt? If I can repro I can look into this

**Comment by jackgerrits** [comment]
I've opened #2197 to track this new issue

**Comment by AlexFridman** [comment]
> I've opened #2197 to track this new issue

@jackgerrits , but does it cover my issue with the ring size? It looks like to separate ones...

**Comment by jackgerrits** [comment]
The ring size issue shows up as `vw (shared_feature_merger.cc:41): cb_adf: At least one action must be provided for an example to be valid` right? I removed the `--ring_size` parameter because the default is 256

**Comment by AlexFridman** [comment]
I have a bigger data file and without setting ring_size to a large value it fails with segmentation fault.

**Comment by jackgerrits** [comment]
Can you provide a repro of that?

**Comment by AlexFridman** [comment]
sure. in a few hours.

**Comment by AlexFridman** [comment]
@jackgerrits , I've updated the message bellow with a link to the data. In case if you missed it.

**Comment by jackgerrits** [comment]
What is the command line you are using in this case? Can you also please provide the output of `vw --version`?

**Comment by AlexFridman** [comment]
> (adv) alex@desktop:/mnt/data/adv$ vw --version
8.8.0 (git commit: f83c0e30)

actually, with command line it's working with any ring_size.
BUT: this script fails if you set ring-size=4000 instead of rinf-size=400000

`from vowpalwabbit import pyvw
vw = pyvw.vw('--cb_explore_adf --epsilon 0.2 --ring_size 400000')
with open('data.txt') as f:
    examples = f.read().strip().split('\n\n')
for example in examples:
    pred_example = vw.parse(example, pyvw.vw.lContextualBandit)
    pmf = vw.predict(pred_example)
    vw.finish_example(pred_example)
    learn_example = vw.parse(example, pyvw.vw.lContextualBandit)
    vw.learn(learn_example)
    vw.finish_example(learn_example)
del vw`

**Comment by jackgerrits** [comment]
Okay thanks for providing that, I have a repro. I am in fact getting a segfault with the default ring size of 256

**Comment by AlexFridman** [comment]
exactly, but what is ring size? There is a pool of size=ring_size being created? And all new arriving examples should supplant old examples?

**Comment by jackgerrits** [comment]
Ring_sized has changed a little bit recently, it is the initial size of a pool of examples used in a queue. These examples are reused, and if they are left in a bad state we see issues like this. That is my suspicion right now. I am not sure why we cannot get this issue to reproduce through the command line though.

**Comment by AlexFridman** [comment]
Maybe because in python it operates like in "streaming" mode, but in command like it more looks like a "batch". Just train and that's all...
Just an idea.

**Comment by jackgerrits** [comment]
Perhaps, but when using the `parse` function it utilizes the same pool and so I expected to see the same behavior. I am working on cleaning up the part of the example data structure that is most often to blame for these issues but its a way out. I'll try and get to the bottom of this issue. It may also be related to the other issue you saw (#2197)

**Comment by jackgerrits** [comment]
@AlexFridman all of these Python issues seem related. I have a fix out in PR @2206
