### ISSUE TITLE
--invert_hash does not include all features when reading from a list of files 

### ISSUE THREAD

**Issue by cheng-tan** [VowpalWabbit/vowpal_wabbit#2226]
#### Describe the bug
When input is a list of files, `--invert_hash` only includes the features in the last file. For the features only exist in previous files they are ignored in invert_hash file.

#### To Reproduce
1. Datasets:
    1) 100k.json contains 100k events
    2) split 100k.json into 2 files, 50k_0.json and 50k_1.json
2. Generate model and invert hash for 100k.json
     1) vw --cb_adf -l 0.01 --power_t 0 --dsjson -d 100k.json --invert_hash 100k.invert.txt -f 100k.vw --readable_model 100k.readable.txt
3. Generate model and invert hash for 50k.json
     1) vw --dsjson -d 50k_0.json --cb_adf -l 0.01 --power_t 0 -f 50k_0.vw --save_resume --preserve_performance_counters
     2)  vw --dsjson -d 50k_1.json --cb_adf -l 0.01 --power_t 0 -f 50k_combined.vw  --save_resume --preserve_performance_counters -i 50k_0.vw --invert_hash 50k_combined.invert.txt --readable_model 50k_combined.readable.txt

#### Expected behavior
hash exists in 100k.invert.txt should be in 50k_combined.invert.txt as well. Readable model and invert hash should be consistent between a large file and a large file breaking into small chunks.

#### Observed Behavior
if features only exist in 50k_0.json, it doesn't exist in 50k_combined.invert.txt, but exist in readable model.

#### Environment
What version of VW did you use?
8.7.0

What OS or language did you use?
Linux, C++

**Comment by jackgerrits** [comment]
Repro:

1. Create two files:
    1. data1.txt
    ```
    1 | feature_first_run_one feature_first_run_two
    2 | feature_first_run_one feature_first_run_three
    ```
    2. data2.txt
    ```
    1 | feature_first_run_one feature_second_run_one
    0.5 | feature_second_run_two
    ```
1. Run: `vw data1.txt -f model1.vw --noconstant`
2. Run: `vw data2.txt -i model1.vw --readable_model readable.txt --invert_hash inv.txt --noconstant`

inv.txt:
```
Version 8.8.0
Id 
Min label:0
Max label:2
bits:18
lda:0
0 ngram:
0 skip:
options:
Checksum: 955426453
:0
feature_first_run_one:123312:0.696285
feature_second_run_one:51985:0.187343
feature_second_run_two:144690:0.278967
```

readable.txt:
```
Version 8.8.0
Id 
Min label:0
Max label:2
bits:18
lda:0
0 ngram:
0 skip:
options:
Checksum: 955426453
:0
39524:0.253423
51985:0.187343
123312:0.696285
144690:0.278967
212398:0.294434
```

inv.txt only has 3 feature names, instead of the full 5 that are present as weights in the model. The missing values are the ones only present int data1.txt and not in data2.txt. The weights should exist in the invert_hash file, but just without names as that data is not available.

The expected output is:
```
Version 8.8.0
Id 
Min label:0
Max label:2
bits:18
lda:0
0 ngram:
0 skip:
options:
Checksum: 955426453
:0
:212398:0.294434
:39524:0.253423
feature_first_run_one:123312:0.696285
feature_second_run_one:51985:0.187343
feature_second_run_two:144690:0.278967
```
