### ISSUE TITLE
libvw and exception visibility

### ISSUE THREAD

**Issue by kumpera** [VowpalWabbit/vowpal_wabbit#2234]
In 2019 we changed vw's default visibility to hidden. It's important as it's faster and avoid exposing internal symbols to users of libvw. 

Recent versions of clang as early as Apple clang version 11.0.0 (clang-1100.0.33.17), now enforce visibility rules to vtables and RTTI. This means that exceptions thrown from libvw can't be caught by programs even if they use them same headers. This happens because all of VW's exception classes have hidden visibility.

We need to decide whether we want to expose those classes or have users left being able to catch std::exception only.

I'm of the opinion that we should not expose them and change the C API to never throw exceptions.

**Comment by thealphadollar** [comment]
@jackgerrits I believe this issue has been fixed via 354967c.

**Comment by jackgerrits** [comment]
I believe this was fixed in https://github.com/VowpalWabbit/vowpal_wabbit/pull/3856 by marking the exception types as `VW_EXPORT_EXCEPTION`
