### ISSUE TITLE
NAN issue when importance weight of an example is small

### ISSUE THREAD

**Issue by rajan-chari** [VowpalWabbit/vowpal_wabbit#2241]
#### Describe the bug
When the importance weight of an example is extremely small, it causes the gradient to go to inf. 
This then causes a NAN during predict() in gd.

#### To Reproduce
Found when building a new reduction (continuous_offset_tree)

#### Expected behavior
When importance, weight falls below a certain threshold it should be modified.

#### Environment
What version of VW did you use?
master

What OS or language did you use?
all

**Comment by jackgerrits** [comment]
Can you please provide a repro?

**Comment by rajan-chari** [comment]
I don't have context on this anymore.  There were some issues fixed around importance weight when working on cats.  Closing it.
