### ISSUE TITLE
When running in inferencing mode, vw failed on parsing input json if label is NaN or probabilities contains NaN

### ISSUE THREAD

**Issue by zli12** [VowpalWabbit/vowpal_wabbit#2253]
#### Describe the bug
When running vw in inference mode using json format input, label probability information is not needed. Therefore, NaN in labels (_label_probability) should be ignored, so as NaNs in probabilities ("p").

Also, failing to parse NaN probability in one sample should not fail other valid samples in same batch.

#### To Reproduce
1. Command line 
`vw --dsjson -t -i  model_file -d data.json`
2. Used `model_file` with arguments: 
`--cb_adf --cb_explore_adf --cb_type mtr --csoaa_ldf multiline --csoaa_rank --epsilon 0.200000002980232 --lambda 0.100000001490116 --quadratic Fi --quadratic Fi --quadratic Fi --softmax`
3. Used `data.json`: 
cooked log json with "_label_probability":NaN and "p": ["NaN","NaN","NaN"]
4. Got error:
`vw example #0(parse_example_json.h:1160): JSON parser error at 38: Invalid value.. Handler: State: LabelSingleProperty`
`vw (parse_example_json.h:1160): JSON parser error at 38: Invalid value.. Handler: State: LabelSingleProperty`
5. if add double quoted to NaN ("_label_probability":"NaN") result in following error:
`vw example #0(parse_example_json.h:1160): JSON parser error at 43: Terminate parsing due to Handler error.. Handler: Unexpected token: string('NaN' len: 3)State: LabelSingleProperty`
`vw (parse_example_json.h:1160): JSON parser error at 43: Terminate parsing due to Handler error.. Handler: Unexpected token: string('NaN' len: 3)State: LabelSingleProperty`

#### Expected behavior
1. Label probability is ignored because it's not used in inferencing mode.
2. When parsing error error occurs, display warning/error, skip the invalid example, and move on to next one.

#### Observed Behavior
Stack trace provided above.

#### Environment
'VW 8.8 on Windows'

#### Additional context
None

**Comment by zli12** [comment]
[data.zip](https://github.com/VowpalWabbit/vowpal_wabbit/files/4173307/data.zip)
attaching the cooked log in json format for repro, the issue can be repro'd without a model file.

**Comment by jackgerrits** [comment]
Can be reproduced with:
```
vw --dsjson -d data.json
```

There are two issues here:
1. "NaN" should be parsed as a float NaN even though it is a string.
2. We should improve the parser behavior so that it properly skips over examples on failure

I am going to address 1 as part of this issue and since 2 is a larger amount of work which will take longer it will be tracked by a separate issue. (#2255)
