### ISSUE TITLE
segmentation fault in mac os catalina

### ISSUE THREAD

**Issue by XuandongZhao** [VowpalWabbit/vowpal_wabbit#2254]
#### Describe the bug
I have successfully install the package. But when I want to run examples in vowpal_wabbit/python/examples/ there is always segmentation fault.

#### To Reproduce
os: mac os 10.15.3
python:  which python
/Users/zhaoxuandong/opt/anaconda3/bin/python
it is python 3.7.4 via anaconda

#### Expected behavior
when I use python to run pyvw, there is an error:
for example
>>> from vowpalwabbit import pyvw
>>> vw = pyvw.vw("--quiet -f test.model")
>>> ex = vw.example("1 |x a b |y c")
[1]    7191 segmentation fault  python

#### Observed Behavior
How did VW behave? 

[1]    7191 segmentation fault  python or 
[1]    7136 segmentation fault  python test.py or other segmentation fault
#### Environment
What version of VW did you use? vowpalwabbit-8.8.0
What OS or language did you use? mac os 10.15.3

**Comment by arielf** [comment]
Might be the recurring binary incompatibility of anaconda's and Ubuntu's compiled libraries
See e.g. https://github.com/VowpalWabbit/vowpal_wabbit/issues/1095

**Comment by XuandongZhao** [comment]
> Might be the recurring binary incompatibility of anaconda's and Ubuntu's compiled libraries
> See e.g. #1095

I followed his steps and reinstall vowpalwabbit. But the segmentation error still exist.

**Comment by arielf** [comment]
Reinstalling vowpal wabbit won't help if the anaconda distro was built with a different (ABI) compiler, or different versions of C++ libraries (e.g. libboost.*), than the ones you're building vowpalwabbit with. These are inherently and fundamentally _binary_ incompatible.  You need to rebuild everything (incl anaconda itself) from _source_ with the exact same compiler and libraries to make it work.

**Comment by jackgerrits** [comment]
If you're able to not use Anaconda, you can workaround this by using the system Python. So if you install vowpalwabbit outside of conda environment it might work

**Comment by XuandongZhao** [comment]
> If you're able to not use Anaconda, you can workaround this by using the system Python. So if you install vowpalwabbit outside of conda environment it might work

Yes, it works well without anaconda.

**Comment by XuandongZhao** [comment]
I install successfully in my laptop. But when I use same instructions on my iMac, it still output segmentation fault. 
My python is /usr/local/bin/python3 it is python 3.7.6.
vowpalwabbit version is 8.8.0
os: mac os 10.15.3

**Comment by arielf** [comment]
Also sounds like the same (or very similar) issue as  https://github.com/VowpalWabbit/vowpal_wabbit/issues/2100

anaconda is very sensitive to C++ incompatibilities, it locks you into a full ecosystem (compiler, compilation options, libs) which are often incompatible with other compiled software written in C++.

@peterychang (thanks) has done a great job explaining the issue in #2100 and giving some guidance on how to solve it. HTH.
