### ISSUE TITLE
Parser should skip examples in cmdline where it encountered an error

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2255]
When parsing, if an error is encountered then there is a message printed out and VW actually continues on. It is treated like a warning. This means that a malformed example is used as part of learning/inference.
If you wish to fail on malformed examples you can pass `--strict_parse`. This will cause the warning to become a throw and VW will exit on malformed examples. This is useful but not the whole solution.
 
I believe VW’s normal parsing mode for command line needs to be updated, so that if an error is encountered VW actually skips that entire example and moves on. Then in strict mode, instead of skipping it exits the entire program.

If using this in library mode then the error needs to propagate out of the call and be handled by the library user.

**Comment by TheLethalCode** [comment]
@jackgerrits I'd like to work on this if the issue is free.

**Comment by jackgerrits** [comment]
This is a duplicate as it will be addressed in #3234
