### ISSUE TITLE
C# bindings on .NET core 3.1

### ISSUE THREAD

**Issue by marat-turaev** [VowpalWabbit/vowpal_wabbit#2272]
Starting with .NET core 3.1, it's possible for C++/CLI projects to target .NET core on windows (source: https://docs.microsoft.com/en-us/dotnet/core/porting/cpp-cli).

Related: #1685

**Comment by marat-turaev** [comment]
#2273 is ready for review.

**Comment by lalo** [comment]
Closing as completed via https://github.com/VowpalWabbit/vowpal_wabbit/pull/3969
