### ISSUE TITLE
NaN prediction in example

### ISSUE THREAD

**Issue by marco-rossi29** [VowpalWabbit/vowpal_wabbit#2274]
>vw.exe --ccb_explore_adf --epsilon 0.2 -d 20200214192500_data_2020_02_19_0.json --coin --clip_p 0.2 --dsjson -P 100000 --ignore s -c -q pc
creating quadratic features for pairs: pc
ignoring namespaces beginning with: s
Enabling FTRL based optimization
Algorithm used: Coin Betting
ftrl_alpha = 4
ftrl_beta = 1
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
creating cache_file = 20200214192500_data_2020_02_19_0.json.cache
Reading datafile = 20200214192500_data_2020_02_19_0.json
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
-0.000037 -0.000037       100000       100000.0 2:0.000000,8:0.000000,... 2,8,6,...      516
-0.000045 -0.000053       200000       200000.0 2:0.000000,8:0.000000,... 2,8,6,...      520
-0.000052 -0.000066       300000       300000.0 2:0.000000,8:0.000000,... 2,8,6,...      526
-0.000056 -0.000069       400000       400000.0 26:0.000000,27:0.000000,... 26,27,2,...      498
-0.000056 -0.000053       500000       500000.0 0:0.000000,17:0.000000,... 0,17,26,...      498
-0.000055 -0.000054       600000       600000.0 2:0.000000,8:0.000000,... 2,8,6,...      498
**NAN prediction in example 633770, forcing 0.000000**

Source code:
https://github.com/marco-rossi29/vowpal_wabbit/pull/new/marossi/skipInvalidJson

**Comment by ataymano** [comment]
Fixed in #3007
