### ISSUE TITLE
Python examples doesn't support recent version of scikit-learn i.e. 0.22

### ISSUE THREAD

**Issue by adityauser** [VowpalWabbit/vowpal_wabbit#2281]
#### Describe the bug
Example in https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/sklearn_vw.ipynb use outdated terminology(Look at the 2nd cell):
`RandomizedSearchCV `module is now under `sklearn.model_selection`, and not any more under `sklearn.grid_search`  .
Onwards scikit-learn version 0.18.1 `grid_scores_` is no longer in use. We can use `cv_results_` to get the results, which is similar to `grid_scores_` . 
#### To Reproduce

Run the ipython notebook. 

#### Observed Behavior
How did VW behave? Please include any stack trace, log messages or crash logs.
```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-55-3d5c4d474787> in <module>()
      1 from operator import itemgetter
      2 from time import time
      3 from sklearn.grid_search import RandomizedSearchCV
      4 from scipy.stats.distributions import uniform
      5 

ModuleNotFoundError: No module named 'sklearn.grid_search'

```
#### Environment
What version of VW did you use?
What OS or language did you use?

`VW 8.8.0 on Linux with the Python bindings`

#### Additional context
Do you want me to make a PR for this.

**Comment by Smit-create** [comment]
It is also related to #2240

**Comment by thealphadollar** [comment]
@jackgerrits I would love to work on this. I hope this issue is free :smile:

**Comment by jackgerrits** [comment]
Yes this issue is free, please feel free to work on it
