### ISSUE TITLE
Badly Formatted Example

### ISSUE THREAD

**Issue by Shivanshmundra** [VowpalWabbit/vowpal_wabbit#2291]
#### Describe the bug
 cb_adf: badly formatted example, only one line can have a cost
![image](https://user-images.githubusercontent.com/25545489/75324095-2f4ded00-589c-11ea-80f5-b2902cdee33b.png)

#### To Reproduce
I have uploaded my code in a collab notebook [here](https://colab.research.google.com/drive/1tVbOULvH3oM5bMe5pRR381izYdTE1JQz).
Although, collab crashes when it faces that error. You can try running the same code locally.

#### Expected behavior
Data should be uploaded as it is for Contextual Bandit Problem.

#### Observed Behavior
![image](https://user-images.githubusercontent.com/25545489/75324235-8358d180-589c-11ea-8951-33700e346334.png)

#### Environment
`VW 8.8.0 on Linux with the Python bindings`

#### Additional context
Also discussed in #1821

**Comment by jackgerrits** [comment]
I had different issues running this off 8.8.0, which may be related. It did not repro for me on current master though. Could you please try running your notebook based on master?

You can install the pip package from latest master with:
```
pip install git+https://github.com/VowpalWabbit/vowpal_wabbit.git#egg=vowpalwabbit
```

**Comment by Shivanshmundra** [comment]
@jackgerrits It says Requirements are already satisfied. I guess master branch is on `8.8.0`.

**Comment by jackgerrits** [comment]
You will need to uninstall the existing package first or force the installation. Version numbers get updated when we move to the next version.

**Comment by Shivanshmundra** [comment]
@jackgerrits Thanks, this solved the issue. Closing this issue for now.
