### ISSUE TITLE
Issue with dependency parsing demo

### ISSUE THREAD

**Issue by Casperfrc** [VowpalWabbit/vowpal_wabbit#2292]
#### Describe the bug
The demo is in the following directory:
_vowpal_wabbit/demo/dependencyparsing/_

Following the _README.md_, that gets posted after running the Makefile, I try to run the following command:
_make dep.perf_

This returns:
`/bin/bash: ../../vowpalwabbit/vw: No such file or directory `

I have tried changing the path to a lot of different parts of that directory but with no luck. I have also tried shying away from the _README.md_ by trying to run _make dep.model_ but with no luck.

**In conclusion**
I don't know how to run the dependency parsing demo.

#### To Reproduce
1. `git clone https://github.com/VowpalWabbit/vowpal_wabbit.git`
2. `cd vowpal_wabbit/demo/dependencyparsing`
3. `make -f Makefile`
4. `make dep.perf`

#### Expected behavior
I was expecting this to make a test parse, as described in the Makefile

#### Observed Behavior
As mentioned earlier, the gotten message is:
`/bin/bash: ../../vowpalwabbit/vw: No such file or directory`
`Makefile:29: recipe for target 'dep.model' failed`
`make: *** [dep.model] Error 127`

When trying to run make dep.model basically the same message is gotten:
`/bin/bash: ../../vowpalwabbit/vw: No such file or directory`
`Makefile:29: recipe for target 'dep.model' failed`
`make: *** [dep.model] Error 127`

#### Environment
**What version of VW did you use?**
I've tried on the latest commit: a6d5e91
And on 960f6cc

**What OS or language did you use?**
I've tried on the Ubuntu Subsystem on the newest version of Windows, Windows itself and on Ubuntu 18.04

#### Additional context
I'm aware of the latest commit having affected this exact code being from 2015, so I have tried playing around with it myself first, but I simply cannot crack it.

**Comment by jackgerrits** [comment]
Thanks for pointing this out. It looks like the issue is it can’t find the vw binary to use. If you’re using an installed vw binary then you should be able to change line 2 of the makefile to
```
VW=vw
```

If you built it yourself then you need to point it to the build output dir
```
VW=../../build/vowpalwabbit/vw
```

**Comment by Casperfrc** [comment]
Hey @jackgerrits,

Thanks a lot, it worked like a charm and thanks for the work you guys are doing with this library.

Have a great day!

- Casper

**Comment by jackgerrits** [comment]
@Casperfrc you're welcome, glad it was a quick fix!
