### ISSUE TITLE
Python cbandit_label str function provides incorrect output

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2295]
The `cbandit_label` type provides a str function to convert the object back to a string representation. That is currently structured as:
```python
' '.join([str(c.label) + ':' + str(c.cost) for c in self.costs])
```

I would expect this output to match the input form for these labels, which can be found [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Logged-Contextual-Bandit-Example). The use of the word `label` is also is misleading. It is actually the action, so a variable name of `action` would be clearer.

**Comment by Smit-create** [comment]
I would like to work on it and I will submit a PR soon.
