### ISSUE TITLE
[Documentation Improvement] CMake error: Could not Find ZLIB error while using make

### ISSUE THREAD

**Issue by mritunjaysharma394** [VowpalWabbit/vowpal_wabbit#2298]
#### CMake error: Could not Find ZLIB error while using make

After the use of `make` command (while configuring and building vw), CMake error propped up with the following message:
`CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message) : Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR)`

![Screenshot from 2020-02-15 04-34-54](https://user-images.githubusercontent.com/45476902/75508460-3eeb4400-5a0a-11ea-92c0-0b1df5302a50.png)

This error can originate in two cases:
i) Either the zlib module itself is not installed
or
ii) This is a multilib issue and when zlib1g-dev:i386 is installed then the `make` commands run successfully. The problem might be that CMake for some reason does the check with the 32 bit toolchain rather than the 64 bit one.

![Screenshot from 2020-02-15 04-36-04](https://user-images.githubusercontent.com/45476902/75509392-668fdb80-5a0d-11ea-8293-d7ac9cbe570f.png)

#### Solution

Installing zlib1g-dev:i386

#### To install zlib1g-dev:i386
```sudo apt-get install zliblg-dev:i386``` 

The link of the resolution to the above problem and updated wiki (forked-repo) is : 

https://github.com/mritunjaysharma394/vowpal-wiki/blob/master/Dependencies.md

In order to merge it, find below the link of forked and updated repo:

https://github.com/mritunjaysharma394/vowpal-wiki.git

Hey, @jackgerrits, I think this can be a good Documentation improvement. Please do have a look of it

#### To Reproduce the Error: 
1. `git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git
cd vowpal_wabbit`
2. Install the dependencies mentioned in the existing wiki.
3. Enter `make`.

#### Environment
VW 8.8.0
OS : Linux (Ubuntu 18.04) 64-bit processor

**Comment by jackgerrits** [comment]
Was this on a 64 bit install of Ubuntu? Did you run `sudo apt install zlib1g-dev`?

I'm wondering how it would fail to pick up zlib, but I don't think directing users to install the 32bit variant is the correct course of action here.

**Comment by mritunjaysharma394** [comment]
> @mritunjaysharma394 Was this on a 64 bit install of Ubuntu? Did you run `sudo apt install zlib1g-dev`?
> 
> I'm wondering how it would fail to pick up zlib, but I don't think directing users to install the 32bit variant is the correct course of action here.

Yes, this was on a 64 bit install of Ubuntu and I tried it to fix it earlier with ```sudo apt install zlib1g-dev``` . However it did not fix the error, so I had to install the i386 variant and then it worked

**Comment by jackgerrits** [comment]
This is really odd. I understand that installing the i386 variant fixed things for you, but this isn't normal behavior as far as I can tell and it's definitely not something we should be directing our users to do as part of setting up their environment.

Do you have any ideas as to what may have caused your environment to get in this state? Is it a fresh install of Ubuntu 18.04?

**Comment by mritunjaysharma394** [comment]
> This is really odd. I understand that installing the i386 variant fixed things for you, but this isn't normal behavior as far as I can tell and it's definitely not something we should be directing our users to do as part of setting up their environment.
> 
> Do you have any ideas as to what may have caused your environment to get in this state? Is it a fresh install of Ubuntu 18.04?

While the Ubuntu 18.04 install is not a fresh one, I can say that the issue here is with CMake which can create problem in some machines (my friend also faced the same issue). While trying to find a fix, I found that the ZLIB header was found, but the library itself was not (one if is executed, the other isn't). Thus both `find_library calls` in the `FindZLIB.cmake` fail for some reason. Unfortunately, I have no idea why this happens. The only possible culprit I can think of is multiarch/multlib support. CMake in some machines is doing the check with 32-bit toolchain rather than 64-bit ones. One solution was to install i386 variant and the other one can be to create this `CMakeLists.txt` :
``` CMake
 cmake_minimum_required(VERSION 3.5) 

 find_package(ZLIB REQUIRED) 
```
I think this can be a better option (and it works too). Making slight changes in the Documentation Improvement I suggested, what we can do is that instead of asking all the users to do either of the above steps, We can write it somewhere else for the people facing the issue due to problem in CMake?

**Comment by jackgerrits** [comment]
Installing the 32 bit variant cannot be the official instruction as if it is used it will cause crashes.

This issue discusses something similar: https://github.com/mesonbuild/meson/issues/4812. I want to try and get a better understanding of your environment to see if we can work out the root cause and fix this. Can you do these things for me?
1. What is the output of `cmake --find-package -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST -DNAME=ZLIB`?
2. Can you please edit the root CMakeLists.txt file and add this after the `project` call and then try running CMake again:
    ```
    if(NOT CMAKE_SIZEOF_VOID_P GREATER 0)
      message(FATAL_ERROR "CMake failed to determine the bitness of the target platform.")
    endif()
    ````
3. What is the output of `apt list --installed`?
4. What is the output of `ls /usr/lib/i386-linux-gnu/` and `ls /usr/lib/x86_64-linux-gnu/`?

**Comment by mritunjaysharma394** [comment]
> Installing the 32 bit variant cannot be the official instruction as if it is used it will cause crashes.
> 
> This issue discusses something similar: [mesonbuild/meson#4812](https://github.com/mesonbuild/meson/issues/4812). I want to try and get a better understanding of your environment to see if we can work out the root cause and fix this. Can you do these things for me?
> 
> 1. What is the output of `cmake --find-package -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST -DNAME=ZLIB`?

**Output**
`ZLIB found.`

> 2. Can you please edit the root CMakeLists.txt file and add this after the `project` call and then try running CMake again:
>    ```
>    if(NOT CMAKE_SIZEOF_VOID_P GREATER 0)
>      message(FATAL_ERROR "CMake failed to determine the bitness of the target platform.")
>    endif()
>    ```
**Output**
``` 
-- VowpalWabbit Version: 8.8.0
-- Setting build type to 'Release' as none was specified.
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using C++ standard: 11
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Git Version: 7cc5b245
-- Number of processors: 12
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   system
--   thread
--   unit_test_framework
--   chrono
--   date_time
--   atomic
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Submodule update
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mritunjay/Documents/vowpal_wabbit
```
> 3. What is the output of `apt list --installed`?

**Output**
[list.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/4289545/list.txt)

> 4. What is the output of `ls /usr/lib/i386-linux-gnu/` and `ls /usr/lib/x86_64-linux-gnu/`?

**Output** for `ls /usr/lib/i386-linux-gnu/`

[i386.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/4289560/i386.txt)

**Output** for `ls /usr/lib/x86_64-linux-gnu/`

[x86_64.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/4289565/x86_64.txt)

**Comment by jackgerrits** [comment]
So it looks like `apt list --installed` indicates that only the 64 bit version of zlib is installed. However, looking at the contents of the two lib directories, both libs are present. CMake also detected and used the 64 bit version and not the 32 bit version.

**Comment by mritunjaysharma394** [comment]
If this is the case, then what is your analysis of this unusual behaviour that occurred in my system? As far as the Documentation is concerned, I think it's fine then to make no changes there. This discussion in itself can work as a reference for anyone who faces the issue
