### ISSUE TITLE
[IMPROVEMENT] Remove Outputs From Existing Python Examples

### ISSUE THREAD

**Issue by thealphadollar** [VowpalWabbit/vowpal_wabbit#2303]
Some of the examples (for instance [Contextual_Bandit_Example_with_VW_Python_Wrapper](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/Contextual_Bandit_Example_with_VW_Python_Wrapper.ipynb)) do not have the corresponding output with them. We should add outputs since,

- The output provide a base expected result and if something is an amiss user trying the example can easily note.
- It makes it readable without running the notebook locally which is useful for intuition based learning.

@jackgerrits Please give your views and, thereafter, I'll add the output to all of the python examples.

**Comment by jackgerrits** [comment]
The problem with outputs is it makes the already very hard to review notebook file even harder. I think it is better to have outputs left cleared.

**Comment by jackgerrits** [comment]
I think the ideal way would be to reduce the friction to run the notebooks. We have a [separate repo](https://github.com/VowpalWabbit/jupyter-notebooks) for use with Binder so notebooks are easy to run. I would prefer we invest in that than check in evaluated notebooks. Some of the notebooks under python/examples need a bit of love which is why they haven't been migrated

**Comment by thealphadollar** [comment]
Sounds good to me. What about removing output from existing ones, like https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/poisson_regression.ipynb

Shall I help with that?

**Comment by thealphadollar** [comment]
Also the one I'm attaching below is very creator specific and requires some files to be present in a particular directory. What can we do about this?

**Comment by jackgerrits** [comment]
Yeah, go ahead and clear the outputs, that would be helpful thanks.

I'm not sure what to do about that one at the moment. I think what's best would be to make it generic. It's reading a pred file, I'm just not quite sure which prediction type it is right now.

**Comment by thealphadollar** [comment]
@jackgerrits If you can somehow (if possible) provide me the file it is trying to access, I'll update it accordingly :)

**Comment by jackgerrits** [comment]
That's the thing, it was last edited 4 years ago. I don't know what it was run against.

**Comment by thealphadollar** [comment]
Noted. IMO either we should remove it or try to find an alternative input file. Now, finding an input file to fit an already written notebook could be tough, I guess. Although I would be in favor of removing (or marking it in a manner that depicts it doesn't work), I would surely try to find a suitable input if you think it's worth investing time in.

**Comment by jackgerrits** [comment]
Agreed, I would like to avoid removing it though. It's just about finding the time to work it out :)

**Comment by thealphadollar** [comment]
Cool. It's quite late here in India but I'll certainly see if I can try to fix it tomorrow. Thanks for the help :) and quick responses.

**Comment by thealphadollar** [comment]
Hey @jackgerrits , as you must be knowing the attached example, which we discussed briefly, has files missing from the example. Very apparently, one file `pred_original.out` are outputs on some data (again unknown) after ground truth  which is also not available to us (I may be wrong here). Then there is `pred_with_ce_original.out` which seems to be the output before ground truth method was applied.

I tried to look for some context of the data or anything similar which I could use to fill in the missing files. I couldn't find any. I would recommend that we remove the example or replace it with a completely new one which demonstrates the similar application. What would you say? Shall we remove it?

I believe, in anyway, we are going to create new better examples of core functionality during RL Open Source fest.


https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/Uncertainty_Scores_and_Prediction_Errors.ipynb
