### ISSUE TITLE
Pandas load and save from VW text format

### ISSUE THREAD

**Issue by RituRajSingh878** [VowpalWabbit/vowpal_wabbit#2308]
I try to work around this and would love to contribute. But I don't understand precisely the expectations of the VW community with this. So if anyone can explain it more clearly, it will be very helpful. As I realized, I have to add a class that will be going to read the VW formate data and will convert it so that pandas can read and then we can do what panda can do inside the VW.  

Maybe something like this-
https://github.com/dask/fastparquet/blob/8731b4aaebb48326a62631cadd0e3302253bb75a/fastparquet/api.py#L348

**Comment by thealphadollar** [comment]
I guess something similar would be cool. What I think is that one alternate could be actually contributing to the Pandas community and adding a method to read our data format just in a manner that they have `read_csv`. This can later on be extending to loading from new formats as well that we go on to support.

@jackgerrits What do you think about it?

**Comment by RituRajSingh878** [comment]
@jackgerrits anything here?

**Comment by jackgerrits** [comment]
Well part of this project is designing how it will look. Pandas is pretty much just a table, (correct me if I'm wrong). But VW has more rich descriptions that must captured when doing this work, such as namespaces/feature groups and labels. Working out how to best make that work in a pandas based scheme will be an interesting challenge. Before we consider contributing anything to Pandas it needs to be mature here, and given labels are updated and added upstreaming that change may be more trouble than its worth.

**Comment by thealphadollar** [comment]
Sounds reasonable. Correct me if I'm wrong, this is one of the crucial parts of project 5 for open source fest.

**Comment by RituRajSingh878** [comment]
> Well part of this project is designing how it will look. Pandas is pretty much just a table, (correct me if I'm wrong). But VW has more rich descriptions that must captured when doing this work, such as namespaces/feature groups and labels. Working out how to best make that work in a pandas based scheme will be an interesting challenge. Before we consider contributing anything to Pandas it needs to be mature here, and given labels are updated and added upstreaming that change may be more trouble than its worth.

@jackgerrits  It is a table representation but contains reach information of the data set. Also, We can keep the feature of the VW format dataset with pandas. The more important thing is, We can get more information which we can't see directly from the data set using pandas as it is capable of doing almost any type of manipulation with data. Also, we can change the given data into many formats of the dataset(other formates) using pandas, so I think the VW type should also be there.  And What I know, most of the data is in table form(CSV form) so it will be very easy to work on them without losing any property of VW. I am proposing that We should have both from pandas to VW and VW to pandas. Also, It is a part of the implementation of a project in RL fest `Improve VW’s Python experience`, So before submitting a proposal, I would like to make my self clear.
Thanks

eg.
```julia
In [12]: import pandas as pd                                                                             

In [13]: file = pd.read_csv('xyz.csv')                                                                   

In [14]: VW_file = file.to_VW()                                                                                    

In [15]: VW_file                                                                                         

In [16]: csv_file = VW_file.to_csv()                                                                     


```

**Comment by etiennekintzler** [comment]
Hello !

I am facing the same issue, having no way to directly transform a `pandas.DataFrame` to the suitable Vowpal Wabbit format. I am **willing to contribute** to this issue as well.

The destination format could be specified as a formula, in the same fashion as the python module [patsy](https://patsy.readthedocs.io/en/v0.1.0/formulas.html). In the present case, the formula would follow the [Input Format of the VW wiki](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Input-format) .

Let's say the data shown in ["Vowpal Wabbit with Python"](https://vowpalwabbit.org/tutorials/python_first_steps.html) was present in a the following `household_dataset.csv`:
```
need_new_roof, price, sqft, age, year_build
0, .23, .25, .05, 2006
1, .18, .15, .35, 1976
0, .53, .32, .87, 1924
```
Then to get the VW friendly format:
```
0 | price:.23 sqft:.25 age:.05 2006
1 | price:.18 sqft:.15 age:.35 1976
0 | price:.53 sqft:.32 age:.87 1924

```
we would write  :
```python
import pandas as pd
from vowpalwabbit import pyvw
df = pd.read_csv("house_dataset.csv")
vw_input = py.vw(df, "need_new_roof | price:price sqft:sqft age:age year_built")
```

Also, more complex example (feature renaming, namespaces, etc.) would also be possible, such as in :
```python
vw_input = py.vw(df, "need_new_roof |Imperial:0,092 msq:sqft |AgeFeatures age_of_house:age year_built")
```
What do you think of this solution @jackgerrits , @RituRajSingh878  ?

**Comment by jackgerrits** [comment]
Closing as Pandas->VW is done, but VW->Pandas is out of scope.
