### ISSUE TITLE
[IMPROVEMENT] Python Version And Dependency Management

### ISSUE THREAD

**Issue by thealphadollar** [VowpalWabbit/vowpal_wabbit#2310]
As evident from #2307 failing tests, and numerous problems with not fixating on versions for various python dependencies; we should adopt `Pipenv` which will help us limit python version as well as very minutely manage the dependency versions we would be using. It offers numerous benefits which are listed in [this amazing article](https://opensource.com/article/18/2/why-python-devs-should-use-pipenv). Below are few prominent ones:

- Pipfile and Pipfile.lock provide granular level management of dependency versions.
- A versioned requirements.txt can be created anytime from Pipfile.
- There can be separate dev and install dependencies.

I would like to implement this system of management of Python version and dependencies with Pipenv. 

@jackgerrits Do you think it'll be a worthwhile addition? I believe you'd have greater insight on the problems we face and we could face.

**Comment by jackgerrits** [comment]
The issue seen in #2307 is from using a private method that isn't part of the API, and as such there are no compatibility requirements between versions. Simply enforcing this particular version is not a good way forward as it means we cannot upgrade dependency versions without breaking code.

Given the small number of dependencies of VW I do not see the benefit of using a system such as Pipenv.

**Comment by thealphadollar** [comment]
I certainly understand. My apologies, I intended to mean the difference in versions of the SKLearn package.

Also, I totally understand the intuition behind a choice of not adopting Pipenv since it'll be another part where we'd have to maintain up to date information. What do you think about updating the current versions of packages in `requirements.txt` to newer ones?

I can test everything with new versions and update the requirements file accordingly.

**Comment by peterychang** [comment]
In general, we should be trying to maintain compatibility with the latest version of all our dependencies. Any maximum version exclusions should be a temporary measure while we work on the changes required to become compatible.
A good example of that would be setting sklearn < 0.24 until we can find a fix for #2240.

We should strive to make VW work with as many versions of our dependencies as possible, as different uses will have different requirements for their projects. Any version incompatibilities should be viewed as a bug, and so I think the current requirements.txt file should be enough.

This might be something to revisit if dependency management becomes a big problem in the future though

**Comment by thealphadollar** [comment]
Sounds perfect to me. @peterychang Shall we update the requirements.txt file?

**Comment by jackgerrits** [comment]
I believe @peterychang just suggested we should **not** update the requirements.txt file as we want to maintain compatibility with as many versions as possible.

**Comment by peterychang** [comment]
@thealphadollar no, sklearn is only on 0.22, there's no reason to prematurely restrict the sklearn version. Issue #2307 is attempting to use functionality thats already been deprecated, which we should not be doing

**Comment by thealphadollar** [comment]
Understood. Thank you for the clarification and discussion. I will close the issue then, for now.
