### ISSUE TITLE
Memory leak in vw_dll_parse_escaped unit test

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2317]
This unit test ensures that an exception is thrown with this line:
```C++
  BOOST_CHECK_THROW(VW_InitializeA("-d test\\ --nonexistent_option --quiet"), VW::vw_unrecognised_option_exception);
```

However, it seems that this operation is not exception safe causing Valgrind to report leaks in this test.

Once this is fixed we should turn on unit tests in the Valgrind CI.

Related to #2122

**Comment by lokitoth** [comment]
I am concerned that we are throwing an exception across an `extern "C"` boundary. 

Is it even valid to do this?

This may not just be a test-issue.

**Comment by jackgerrits** [comment]
Yep it's a **big** issue with the C API right now. But we can't fix it without breaking it because we don't actually have a mechanism to communicate errors. It is valid to throw in this case IFF the function is used in a C++ program. If this were linked and called as a C function it would bring down the program (which we have seen reports of before: #2121).

**Comment by jackgerrits** [comment]
Technically we could mitigate this function with nullptr - which we probably should do. But there are plenty of other functions in the C API which cannot communicate errors because of `void` return values.
