### ISSUE TITLE
[IMPROVEMENT] Add Pre-Commit Hook To Impose Python Coding Standards

### ISSUE THREAD

**Issue by thealphadollar** [VowpalWabbit/vowpal_wabbit#2329]
Currently, we have the following three code linting methods which need to be run before we commit in order to ensure that the code formatting is correct as we want it to be.

- `python3 -m yapf -i python/vowpalwabbit/*.py`
- `python3 -m mypy vowpalwabbit/*.py --ignore-missing-imports`
- `python3 -m pylint vowpalwabbit/*.py`

While YAPF automatically implements basic linting, mypy and pylint give report to the user if something seems off.

The issue is that it is very easy to forget running the linters before we make a commit. Essentially, these are tasks that should be run before any python code is committed. This is the exact cause for which we can use [`pre-commit`](https://github.com/git/git/blob/master/templates/hooks--pre-commit.sample) hook that would run each time someone tries to commit code and will only be allowing to commit if all the actions return EXIT 0 (this can be relaxed).

@jackgerrits Do you think this is a worthwhile task? Alongside Python, we can also implement hooks for linting other language codes, and not just linting but other tasks can also be made automatic in order to make code reviewing easier.

**Comment by jackgerrits** [comment]
In my experience pre commit hooks are troublesome because they only work if the user actually installs and uses them. CI that gates PR's has been more reliable and easier to use

**Comment by thealphadollar** [comment]
I see. I would have preferred to add it in our `travis.yml` but I believe that CI tests should fail for stricter reasons. But I do have a great idea, can we please add [PEP8Speaks](https://pep8speaks.com/) to our repository and set it rules so that the user can get it checked.

There are multiple similar linters which can detect the change in particular language files and accordingly run pipelines for checking the linting.

There is one more solution we can approach; we can write a single script to run linters for all concerned languages and run it via Travis. Although again this should be used for more serious failures but having it as a pre-install command will be fine in my opinion.

**Comment by thealphadollar** [comment]
@jackgerrits What do you think we should move forward with?

**Comment by jackgerrits** [comment]
Travis is on the deprecated path, all new CI should be added to the existing azure pipelines

**Comment by jackgerrits** [comment]
Closing this as pre-commit hooks are not on the roadmap CI-wise
