### ISSUE TITLE
Passing "--ring_size" with 0 as an argument, stucks the execution

### ISSUE THREAD

**Issue by adityauser** [VowpalWabbit/vowpal_wabbit#2335]
#### Describe the bug
Passing `--ring_size` with 0 as an argument, stucks the execution

#### To Reproduce
Run command:
`vw -d train_adf.txt --cb_explore_adf --ring_size 0`

#### Expected behavior
`--ring_size` shouldn't take 0 as an argument.
I think we need to switch `--ring_size` to its default value, and a relevent warning should be displayed, whenever 0 is passed as an argument.

#### Observed Behavior
execution got stuck for an undefined time

#### Environment
What version of VW did you use?
8.8.0
What OS or language did you use?
Linux with python

**Comment by RituRajSingh878** [comment]
@jackgerrits I was thinking that we can implement a `check_arg` function for core `VW`. Which will check the validation of all args we have.  I am seeing this type of issue frequently(I don't know if we have already then why this is happening).

**Comment by jackgerrits** [comment]
I think the options framework could reasonably be extended to support enforcing constraints on inputted argument values.

**Comment by adityauser** [comment]
@jackgerrits could you guide me on how this could be done? Earlier in PR #2337 I was trying to some change in boost options po, but I couldn't make it.
