### ISSUE TITLE
Python documentation version should be automatically fetched

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2349]
Python documentation version is currently outdated and hardcoded in this file: https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/docs/source/conf.py

It should be automatically read from https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/version.txt which is the central location to determine current version number.

**Comment by Smit-create** [comment]
Hi @jackgerrits 
I would like to work on this.

**Comment by Smit-create** [comment]
```
diff --git a/python/docs/source/conf.py b/python/docs/source/conf.py
index cf60bf61..b0e99222 100644
--- a/python/docs/source/conf.py
+++ b/python/docs/source/conf.py
@@ -25,7 +25,11 @@ copyright = u'2019, John langford et al'
 author = u'John langford et al'
 
 # The short X.Y version
- version = u''
+ path = os.getcwd()
+ path = path.replace('python/docs/source', '') + 'version.txt'
+ for line in (open(path)).readlines():
+    v = line.strip()
+ version = v
 # The full version, including alpha/beta/rc tags
 release = u'8.6.1'

```
Do I need to change `release` to auto-update or only just `version`?
Also if the above diff looks good, I will commit it.

**Comment by jackgerrits** [comment]
rather than iterating over the lines can you instead grab the 0th line? If an extra newline accidentally gets checked in the above change will break

**Comment by Smit-create** [comment]
Sure.
