### ISSUE TITLE
How to install VW on a new environment?

### ISSUE THREAD

**Issue by bmdy** [VowpalWabbit/vowpal_wabbit#2370]
I failed to install VW on my new environment.

The new environment is as follows:
(1) A server with Linux version 4.9.93.
(2) Python 3.6.8 with [GCC 7.3.0] on linux.
(3) Miniconda3. 

How can I install VW on this environment? I've tried several ways following the instructions on this page **https://pypi.org/project/vowpalwabbit/**, but all failed. 

The details I that ran are as follows:

$ git clone https://github.com/VowpalWabbit/vowpal_wabbit.git
# create conda environment if necessary
$ conda create -n vowpalwabbit
$ source activate vowpalwabbit
# install necessary boost dependencies
$ conda install -y -c conda boost 
$ pip install -e vowpal_wabbit

The errors are as follows:

Looking in indexes: https://mirrors.aliyun.com/pypi/simple, https://pypi.antfin-inc.com/simple
Obtaining file:///ossfs/workspace/vowpal_wabbit
Installing collected packages: vowpalwabbit
  Running setup.py develop for vowpalwabbit
    ERROR: Command errored out with exit status 1:
     command: /root/miniconda3/envs/vowpalwabbit/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/ossfs/workspace/vowpal_wabbit/setup.py'"'"'; __file__='"'"'/ossfs/workspace/vowpal_wabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /ossfs/workspace/vowpal_wabbit/
    Complete output (70 lines):
    running develop
    running egg_info
    writing python/vowpalwabbit.egg-info/PKG-INFO
    writing dependency_links to python/vowpalwabbit.egg-info/dependency_links.txt
    writing top-level names to python/vowpalwabbit.egg-info/top_level.txt
    reading manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'rapidjson'
    warning: no files found matching 'python/*.dll' under directory 'python/bin'
    warning: no files found matching 'python/packages.config' under directory 'python/windows*'
    warning: no files found matching 'python/*.vcxproj*' under directory 'python/windows*'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    cmake -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.8 -DBUILD_PYTHON=On -DBUILD_TESTS=Off -DWARNINGS=Off -DBoost_NO_BOOST_CMAKE=ON -DBOOST_ROOT=/root/miniconda3/envs/vowpalwabbit -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/ossfs/workspace/vowpal_wabbit/python /ossfs/workspace/vowpal_wabbit
    -- VowpalWabbit Version: 8.8.0
    -- Using C++ standard: 11
    -- Git Version: 2239eec3
    -- Number of processors: 2
    CMake Warning at /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
      Imported targets not available for Boost version 107100
    Call Stack (most recent call first):
      /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:174 (find_package)
    
    
    CMake Warning at /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
      Imported targets not available for Boost version 107100
    Call Stack (most recent call first):
      /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:174 (find_package)
    
    
    CMake Warning at /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
      Imported targets not available for Boost version 107100
    Call Stack (most recent call first):
      /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:174 (find_package)
    
    
    CMake Warning at /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
      Imported targets not available for Boost version 107100
    Call Stack (most recent call first):
      /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:174 (find_package)
    
    
    -- Boost version: 1.71.0
    -- Found the following Boost libraries:
    --   program_options
    --   system
    --   thread
    --   unit_test_framework
    CMake Error at /usr/local/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
    Call Stack (most recent call first):
      /usr/local/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
      /usr/local/share/cmake-3.8/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:175 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/ossfs/workspace/vowpal_wabbit/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    See also "/ossfs/workspace/vowpal_wabbit/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
    error: command 'cmake' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/miniconda3/envs/vowpalwabbit/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/ossfs/workspace/vowpal_wabbit/setup.py'"'"'; __file__='"'"'/ossfs/workspace/vowpal_wabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
(vowpalwabbit) 

Thank you very much for helping.

**Comment by peterychang** [comment]
I see at least 2 problems from the logs
1.
>CMake Warning at /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
Imported targets not available for Boost version 107100

You are using boost 1.71 with cmake 3.8. Those are incompatible, you need cmake version >= 3.15.3 for boost 1.71. Please update your cmake

2.
>CMake Error at /usr/local/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)

It looks like you're missing zlib as well. Did you install all the required libraries? (the list is found under the Troubleshooting section of the pypi page you linked)

**Comment by bmdy** [comment]
> I see at least 2 problems from the logs
> 1.
> 
> > CMake Warning at /usr/local/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
> > Imported targets not available for Boost version 107100
> 
> You are using boost 1.71 with cmake 3.8. Those are incompatible, you need cmake version >= 3.15.3 for boost 1.71. Please update your cmake
> 
> 
> > CMake Error at /usr/local/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
> > Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
> 
> It looks like you're missing zlib as well. Did you install all the required libraries? (the list is found under the Troubleshooting section of the pypi page you linked)

Thank you very much!

1. I'm trying to update my cmake.

2. I installed the following as suggested by the pypi page.
# install necessary boost dependencies
$ conda install -y -c anaconda boost 
What else should I install?

**Comment by peterychang** [comment]
The full list is
> libboost-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev libboost-math-dev libboost-test-dev libboost-python-dev zlib1g-dev cmake

**Comment by bmdy** [comment]
> The full list is
> 
> > libboost-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev libboost-math-dev libboost-test-dev libboost-python-dev zlib1g-dev cmake

Sure. I will try to install all of them and then go back to you.

**Comment by peterychang** [comment]
I'm not sure what your system setup looks like, nor am I familiar with the package list/format for your package manager/OS version. The list I gave describe the required packages reasonably well. It looks like you have most of the boost packages installed already, but the process failed before the check for boost-python (boost-python3 may be a separate package, I'm not really sure). You are also certainly missing zlib (listed as zlib1g-dev).

It will be up to you to find and install the specific package names that need to be installed

**Comment by bmdy** [comment]
> I'm not sure what your system setup looks like, nor am I familiar with the package list/format for your package manager/OS version. The list I gave describe the required packages reasonably well. It looks like you have most of the boost packages installed already, but the process failed before the check for boost-python (boost-python3 may be a separate package, I'm not really sure). You are also certainly missing zlib (listed as zlib1g-dev).
> 
> It will be up to you to find and install the specific package names that need to be installed

Thank you very much! Sorry for the delay to respond to you. 

I've successfully installed VW in my environment. I updated cmake and installed some other dependency packages. Then ran an additional rebuild that you told me before. 

I'm going to test some more characteristics of VW and may propose some possible new questions to you later. So this does not need to be closed.

Thank you again!

**Comment by peterychang** [comment]
In order to track the current status of our issues, I'll close this one out. If you have any additional questions, please feel free to either reopen this issue or create a new one.

**Comment by bmdy** [comment]
> In order to track the current status of our issues, I'll close this one out. If you have any additional questions, please feel free to either reopen this issue or create a new one.

Sure!

**Comment by bmdy** [comment]
> In order to track the current status of our issues, I'll close this one out. If you have any additional questions, please feel free to either reopen this issue or create a new one.

I encountered a new problem. My default Python in the deployment environment is 3.6.8. And I've successfully installed VW by running  the following commands.

$ git clone https://github.com/VowpalWabbit/vowpal_wabbit.git
# create conda environment if necessary
$ conda create -n vowpalwabbit
$ source activate vowpalwabbit
# install necessary boost dependencies
$ conda install -y -c anaconda boost
$ pip install -e vowpal_wabbit

But the command "$ conda install -y -c anaconda boost" will install a new Python 3.8, making me fail to use VW under my default environment. How to fix this issue?

Thank you for answering.

**Comment by peterychang** [comment]
you need to reinstall VW in the conda environment. In general, your system python and conda python should be treated as completely separate things. Sharing packages between them can result in undefined behavior

Since you now have multiple pip instances, you'll want to run `pip uninstall vowpalwabbit` until you get an error message saying the package vowpalwabbit is not installed. Then you can install it again while in your desired conda environment

**Comment by bmdy** [comment]
> you need to reinstall VW in the conda environment. In general, your system python and conda python should be treated as completely separate things. Sharing packages between them can result in undefined behavior
> 
> Since you now have multiple pip instances, you'll want to run `pip uninstall vowpalwabbit` until you get an error message saying the package vowpalwabbit is not installed. Then you can install it again while in your desired conda environment

I see it. I will try to reinstall VW in my environment and go back to you later.
