### ISSUE TITLE
Proposal: rename ::vw to VW::workspace

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2391]
In order to make progress in the area of namespacing and code organization I would like to make the following proposal:

- Rename `::vw` object to `VW::context`
    - https://github.com/VowpalWabbit/vowpal_wabbit/blob/17dad786022c6f56b8ee567d4e7b654a07780b89/vowpalwabbit/global_data.h#L361
- Support a compat.h header that exposes `::vw` as a type inherited from `VW::context`. This should assist existing users to migrate

I do not think there is a way to move the object out of the global namespace without some breakage but we will do a best effort at minimizing this cost.

Motivations:
- The `vw` object, which we often call all, is in the global namespace. Namespacing is an important part of organizing a library and is something we should resolve sooner rather than later.
- Renaming the object is also desired as, while possible, it is not a great idea to name a type the same as a namespace.

There has been existing discussion of the larger issue here: https://github.com/VowpalWabbit/vowpal_wabbit/issues/1769, but this issue is a targeted proposal.

**Comment by jackgerrits** [comment]
Decisions from discussion:
- Name will be VW::workspace
- Existing initialize functions will be moved to compat header
- New functions will be constructor based, or maybe factory

**Comment by peterychang** [comment]
Keep in mind the object will need to be completely opaque in the C API (handled as a `void*`). Any migrations we force the user to make now will be throw-away work once the official API is in place

**Comment by jackgerrits** [comment]
The primary motivation of this change is to make it possible to fix the namespaces. Since the inherited object is only used for the name, the object layout will be identical.
