### ISSUE TITLE
Passing a list of strings to pyvw.predict fails in an unclear way

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2397]
#### Describe the bug
Passing a list of string to predict or learn will cause a cryptic crash. The string needs to be joined with newlines for it to work. This should either work as expected or fail in a clear way.

#### To Reproduce
```python
from vowpalwabbit import pyvw
examples = ["| a", "| b"]
vw = pyvw.vw()

vw.predict(examples)
```

#### Expected behavior
This should either work or a clear error should be raised.

#### Observed Behavior
How did VW behave? Please include any stack trace, log messages or crash logs.

Cryptic error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jackgerrits/.local/lib/python3.6/site-packages/vowpalwabbit-8.8.0-py3.6-linux-x86_64.egg/vowpalwabbit/pyvw
.py", line 424, in predict
    pylibvw.vw.predict_multi(self, ec)
TypeError: No registered converter was able to produce a C++ rvalue of type boost::shared_ptr<example> from this Python
object of type str
```

#### Environment
What version of VW did you use? Latest master
What OS or language did you use? WSL, Ubuntu

**Comment by Smit-create** [comment]
I am working on this.

**Comment by Smit-create** [comment]
This also raises similar error with `vw.learn(examples)`
