### ISSUE TITLE
Running Dependency Parser demo and running out of memory

### ISSUE THREAD

**Issue by Casperfrc** [VowpalWabbit/vowpal_wabbit#2428]
#### Describe the bug
I've tried expanding on your Dependency Parser demo by giving it a harder dataset to crunch than the wsj. More specifically this dataset: https://github.com/UniversalDependencies/UD_English-GUM

To do this, I've had to add several more tags to the "tag" file and I've had to modify the Makefile's vw command as follows:
@$(VW) --passes 1 -d $< -k -c --search_rollin mix_per_roll --search_task dep_parser --search 44 --search_alpha 1e-5  --search_rollout oracle  --holdout_off -f $@ --search_history_length 3 --search_no_caching -b 30 --root_label 44 --num_label 44 --nn 5 --ftrl

As can be seen, we are using quite a few more labels here. 44 to be exact. I'll link the GUM data files and tag file we are using.
[tags.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/4574292/tags.txt)
[full_custom_training.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/4574294/full_custom_training.txt)
[full_custom_test.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/4574296/full_custom_test.txt)

The issue I run in to, is that I cannot run this with more than one pass without running out of memory. I have 16 GBs of ram.

I've written about memory in here before, is there some kind of "example.finish()" I am missing in this too?

#### To Reproduce
1. clone vw repo
2. copy the vw line into your makefile
3. copy the datafiles into your cloned project.
4. run the command "make dep.perf"

#### Expected behavior
I believed I would be able to run with more passes than 1 through some sort of cleaning up the memory.

#### Observed Behavior
It crashes with the following message:
"Makefile:14: recipe for target 'dep.base.model' failed
make: *** [dep.base.model] Killed"
(I renamed the model "dep.base.model")

#### Environment
What version of VW did you use?
8.5.0

What OS or language did you use?
I'm on Ubuntu 18.04

**Comment by Casperfrc** [comment]
I found a PC with 32 gigs of ram that was able to run the configuration and it ended up taking up about 18 gigs of ram at the peak. What I find weird is the result. I do not know if we have made a mistake with how we added the more than 3 times as many tags.

[The tags file](https://github.com/VowpalWabbit/vowpal_wabbit/files/4575610/tags.txt)
[The predictions file](https://github.com/VowpalWabbit/vowpal_wabbit/files/4575608/dep.test.predictions.txt)
[The oracle file](https://github.com/VowpalWabbit/vowpal_wabbit/files/4575602/full_custom_test.txt)

And what you can see in these two files is that if you compare them, that VW finds the pattern, it just puts the wrong label. A great example is with CONJ and CASE. Nearly every time the oracle says there should be "CASE" VW predicts CONJ. 
Same with NMOD -- predicts --> NMOD, PUNCT -- predicts --> FLAT, AMOD -- predicts--> EXPL,  --AUX -- predicts --> ROOT(when root is not on an id of 0)

Any ideas of if we should have modified something in "evaluate.py" before adding more tags?

By forehand thanks for looking into this issue!

**Comment by lokitoth** [comment]
Hi @Casperfrc, when you were running with 32 GB, were you still using VW 8.5, or did you use a newer version?

**Comment by JohnLangford** [comment]
I'm resolving this.  It seems quite possible there is some issue in the learning, but without being able to reproduce I don't see a way to debug it.  Patches are welcome, and note that a fix for a different search dependency issue is here: https://github.com/VowpalWabbit/vowpal_wabbit/pull/3637
