### ISSUE TITLE
segment fault when run pyvw.vw 

### ISSUE THREAD

**Issue by vingovan** [VowpalWabbit/vowpal_wabbit#2436]
#### Describe the bug
I installed vowpal_wabbit. When I import pyvm and run pyvw.vw, I got error segment fault

#### Environment
- MacOS 10.15.2
- Install vowpal_wabbit use conda
- VW 8.8.1
- Python 3.8.2

Thanks

**Comment by jackgerrits** [comment]
Hi @vingovan,

This is a known issue to do with Conda on MacOS. It is a problem with the libraries Conda links against. You can find the full discussion in the tracking issue here: #2100 

To mitigate, if it is possible for you to do so, you can use the package with Pip directly, outside of the Conda environment.

```sh
brew install cmake boost boost-python3 zlib
pip install vowpalwabbit
```
