### ISSUE TITLE
Contextual bandits with a neural network

### ISSUE THREAD

**Issue by waral** [VowpalWabbit/vowpal_wabbit#2444]
### Description

I'm using the vw python wrapper and I would like to use a neural network as the policy of a contextual bandit. I couldn't find any related example/tutorial or information about it in the documentation. Running, for example, `--cb_explore_adf --cb_type mtr --epsilon 0.01 --nn 10` doesn't give any errors. I also checked the human readable model with `--invert_hash` and it seems reasonable, but I still don't know whether neural networks are meant to be used (and work as desired) with contextual bandits. 

Could someone clarify this and/or add it to the documentation?

**Comment by pmineiro** [comment]
Short answer: yes this is supposed to work.

Reductions are modular and are intended to compose.  Inability to compose is a bug.  So, for instance, if we release a new base learning algorithm (e.g., `--coin`), it is intended to work with all existing reductions (e.g., `--search`) and we don't explicitly state this.

Reductions are diagrammed here: https://vowpalwabbit.org/features.html

**Comment by jackgerrits** [comment]
Closing this as it looks like Paul answered the Q. Please reopen if you need more info.
