### ISSUE TITLE
CMake error during build "Could NOT find Boost"

### ISSUE THREAD

**Issue by calebtuttle-lp** [VowpalWabbit/vowpal_wabbit#2445]
I'm having difficulty installing vowpalwabbit for python use. I've tried installing both from source and with pip.
OS: Ubuntu 20.04
Python: 3.6.8 (
g++: 9.3.0
cmake: 3.16.3

To build from source, I followed the installation guide for in the wiki. Everything works fine. When I try to build the python wrapper with setup.py, I get the following output:

running build
running build_py
running egg_info
writing python/vowpalwabbit.egg-info/PKG-INFO
writing dependency_links to python/vowpalwabbit.egg-info/dependency_links.txt
writing top-level names to python/vowpalwabbit.egg-info/top_level.txt
reading manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/*.bat'
warning: no files found matching 'python/*.dll' under directory 'python/bin'
warning: no files found matching 'python/packages.config' under directory 'python/windows*'
warning: no files found matching 'python/*.vcxproj*' under directory 'python/windows*'
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
running build_ext
cmake -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.6 -DBUILD_PYTHON=On -DBUILD_TESTS=Off -DWARNINGS=Off -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/lib.linux-x86_64-3.6 /home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit
-- VowpalWabbit Version: 8.8.1
-- Using C++ standard: 11
-- Git Version: 5bf2bca4
-- Number of processors: 8
-- Submodule update
-- help2man not found, please install it to generate manpages
-- Python 3.6 will be used for VowpalWabbit Python bindings
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: python36) (found version "1.71.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  python/CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1

I went into setup.py and changed '-DBoost_NO_BOOST_CMAKE=OFF' to '-DBoost_NO_BOOST_CMAKE=ON' which gives me the following output:

running build
running build_py
running egg_info
writing python/vowpalwabbit.egg-info/PKG-INFO
writing dependency_links to python/vowpalwabbit.egg-info/dependency_links.txt
writing top-level names to python/vowpalwabbit.egg-info/top_level.txt
reading manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/*.bat'
warning: no files found matching 'python/*.dll' under directory 'python/bin'
warning: no files found matching 'python/packages.config' under directory 'python/windows*'
warning: no files found matching 'python/*.vcxproj*' under directory 'python/windows*'
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
running build_ext
cmake -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.6 -DBUILD_PYTHON=On -DBUILD_TESTS=Off -DWARNINGS=Off -DBoost_NO_BOOST_CMAKE=OFF -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/lib.linux-x86_64-3.6 /home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit
-- VowpalWabbit Version: 8.8.1
-- Using C++ standard: 11
-- Git Version: 5bf2bca4
-- Number of processors: 8
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options system thread unit_test_framework 
-- Submodule update
-- help2man not found, please install it to generate manpages
-- Python 3.6 will be used for VowpalWabbit Python bindings
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/boost_python-1.71.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python38.so.1.71.0 (3.8, Boost_PYTHON_VERSION=3.6)

  * libboost_python38.a (3.8, Boost_PYTHON_VERSION=3.6)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  python/CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1

#### Additional context
Not sure whether this is relevant, but I'm using pyenv to run python3.6. Python3.8 came preinstalled on with Ubuntu.

**Comment by jackgerrits** [comment]
The currently implementation of the Python bindings uses Boost Python, that ships binaries for linking against specific versions of Python. It looks like boost on Ubuntu 20.04 only ships the binaries requried for Python 3.8. can you confirm for me by running: `ls /usr/lib/x86_64-linux-gnu | grep boost`.

You may be able to get this working by explicitly installing an older version of Boost. This **may** work:
```
sudo apt install libboost1.67-dev libboost-thread1.67-dev libboost-program-options1.67-dev libboost-system1.67-dev libboost-math1.67-dev libboost-test1.67-dev libboost-python1.67-dev
```

Alternatively, using Python3.8 should work.

**Comment by calebtuttle-lp** [comment]
I appreciate the quick reply. 
`ls /usr/lib/x86_64-linux-gnu | grep boost` produces this output:
`libboost_atomic.a
libboost_atomic.so
libboost_atomic.so.1.67.0
libboost_atomic.so.1.71.0
libboost_chrono.a
libboost_chrono.so
libboost_chrono.so.1.67.0
libboost_chrono.so.1.71.0
libboost_container.so.1.71.0
libboost_context.so.1.71.0
libboost_coroutine.so.1.71.0
libboost_date_time.a
libboost_date_time.so
libboost_date_time.so.1.67.0
libboost_date_time.so.1.71.0
libboost_fiber.so.1.71.0
libboost_filesystem.so.1.71.0
libboost_graph_parallel.so.1.71.0
libboost_graph.so.1.71.0
libboost_iostreams.so.1.71.0
libboost_locale.so.1.71.0
libboost_log_setup.so.1.71.0
libboost_log.so.1.71.0
libboost_math_c99.a
libboost_math_c99f.a
libboost_math_c99f.so
libboost_math_c99f.so.1.67.0
libboost_math_c99f.so.1.71.0
libboost_math_c99l.a
libboost_math_c99l.so
libboost_math_c99l.so.1.67.0
libboost_math_c99l.so.1.71.0
libboost_math_c99.so
libboost_math_c99.so.1.67.0
libboost_math_c99.so.1.71.0
libboost_math_tr1.a
libboost_math_tr1f.a
libboost_math_tr1f.so
libboost_math_tr1f.so.1.67.0
libboost_math_tr1f.so.1.71.0
libboost_math_tr1l.a
libboost_math_tr1l.so
libboost_math_tr1l.so.1.67.0
libboost_math_tr1l.so.1.71.0
libboost_math_tr1.so
libboost_math_tr1.so.1.67.0
libboost_math_tr1.so.1.71.0
libboost_mpi_python38.so.1.71.0
libboost_mpi.so.1.71.0
libboost_numpy38.a
libboost_numpy38.so
libboost_numpy38.so.1.71.0
libboost_prg_exec_monitor.a
libboost_prg_exec_monitor.so
libboost_prg_exec_monitor.so.1.67.0
libboost_prg_exec_monitor.so.1.71.0
libboost_program_options.a
libboost_program_options.so
libboost_program_options.so.1.67.0
libboost_program_options.so.1.71.0
libboost_python27.so.1.67.0
libboost_python38.a
libboost_python38.so
libboost_python38.so.1.67.0
libboost_python38.so.1.71.0
libboost_random.so.1.71.0
libboost_regex.so.1.71.0
libboost_serialization.a
libboost_serialization.so
libboost_serialization.so.1.67.0
libboost_serialization.so.1.71.0
libboost_stacktrace_addr2line.so.1.71.0
libboost_stacktrace_backtrace.so.1.71.0
libboost_stacktrace_basic.so.1.71.0
libboost_stacktrace_noop.so.1.71.0
libboost_system.a
libboost_system.so
libboost_system.so.1.67.0
libboost_system.so.1.71.0
libboost_test_exec_monitor.a
libboost_thread.a
libboost_thread.so
libboost_thread.so.1.67.0
libboost_thread.so.1.71.0
libboost_timer.so.1.71.0
libboost_type_erasure.so.1.71.0
libboost_unit_test_framework.a
libboost_unit_test_framework.so
libboost_unit_test_framework.so.1.67.0
libboost_unit_test_framework.so.1.71.0
libboost_wave.so.1.71.0
libboost_wserialization.a
libboost_wserialization.so
libboost_wserialization.so.1.67.0
libboost_wserialization.so.1.71.0`

I installed the earlier versions that you listed, but I got this error after running `sudo make install` in build: 
`/usr/bin/ld: CMakeFiles/vw-unit-test.out.dir/cb_explore_adf_test.cc.o: in function `_GLOBAL__sub_I__ZN47cb_explore_adf_should_throw_empty_multi_example11test_methodEv':
cb_explore_adf_test.cc:(.text.startup+0x14c): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/usr/bin/ld: CMakeFiles/vw-unit-test.out.dir/ccb_parser_test.cc.o: in function `_GLOBAL__sub_I__Z11parse_labelR12label_parserP6parserN5boost17basic_string_viewIcSt11char_traitsIcEEERN3CCB5labelE':
ccb_parser_test.cc:(.text.startup+0xfa): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/usr/bin/ld: ccb_parser_test.cc:(.text.startup+0x1a2): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/usr/bin/ld: ccb_parser_test.cc:(.text.startup+0x24a): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/usr/bin/ld: CMakeFiles/vw-unit-test.out.dir/ccb_test.cc.o: in function `_GLOBAL__sub_I__ZN25ccb_generate_interactions11test_methodEv':
ccb_test.cc:(.text.startup+0xfa): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/usr/bin/ld: CMakeFiles/vw-unit-test.out.dir/ccb_test.cc.o:ccb_test.cc:(.text.startup+0x1a2): more undefined references to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [test/unit_test/CMakeFiles/vw-unit-test.out.dir/build.make:409: test/unit_test/vw-unit-test.out] Error 1
make[1]: *** [CMakeFiles/Makefile2:746: test/unit_test/CMakeFiles/vw-unit-test.out.dir/all] Error 2
make: *** [Makefile:141: all] Error 2`

**Comment by jackgerrits** [comment]
It shouldn't be trying to build the tests for Python. Can you please delete the build directly and the run the Python install again.

```sh
rm -rf build
python3 setup.py install --user
```

Also just to confirm that we now have the required libs can you please paste `ls /usr/lib/x86_64-linux-gnu | grep boost` after you did the apt install of the older boost libs.

**Comment by calebtuttle-lp** [comment]
sudo make install works again. This is the output from the grep search: 
libboost_atomic.a
libboost_atomic.so
libboost_atomic.so.1.67.0
libboost_atomic.so.1.71.0
libboost_chrono.a
libboost_chrono.so
libboost_chrono.so.1.67.0
libboost_chrono.so.1.71.0
libboost_container.so.1.71.0
libboost_context.so.1.71.0
libboost_coroutine.so.1.71.0
libboost_date_time.a
libboost_date_time.so
libboost_date_time.so.1.67.0
libboost_date_time.so.1.71.0
libboost_fiber.so.1.71.0
libboost_filesystem.so.1.71.0
libboost_graph_parallel.so.1.71.0
libboost_graph.so.1.71.0
libboost_iostreams.so.1.71.0
libboost_locale.so.1.71.0
libboost_log_setup.so.1.71.0
libboost_log.so.1.71.0
libboost_math_c99.a
libboost_math_c99f.a
libboost_math_c99f.so
libboost_math_c99f.so.1.67.0
libboost_math_c99f.so.1.71.0
libboost_math_c99l.a
libboost_math_c99l.so
libboost_math_c99l.so.1.67.0
libboost_math_c99l.so.1.71.0
libboost_math_c99.so
libboost_math_c99.so.1.67.0
libboost_math_c99.so.1.71.0
libboost_math_tr1.a
libboost_math_tr1f.a
libboost_math_tr1f.so
libboost_math_tr1f.so.1.67.0
libboost_math_tr1f.so.1.71.0
libboost_math_tr1l.a
libboost_math_tr1l.so
libboost_math_tr1l.so.1.67.0
libboost_math_tr1l.so.1.71.0
libboost_math_tr1.so
libboost_math_tr1.so.1.67.0
libboost_math_tr1.so.1.71.0
libboost_mpi_python38.so.1.71.0
libboost_mpi.so.1.71.0
libboost_numpy38.a
libboost_numpy38.so
libboost_numpy38.so.1.71.0
libboost_prg_exec_monitor.a
libboost_prg_exec_monitor.so
libboost_prg_exec_monitor.so.1.67.0
libboost_prg_exec_monitor.so.1.71.0
libboost_program_options.a
libboost_program_options.so
libboost_program_options.so.1.67.0
libboost_program_options.so.1.71.0
libboost_python27.a
libboost_python27.so
libboost_python27.so.1.67.0
libboost_python38.a
libboost_python38.so
libboost_python38.so.1.67.0
libboost_python38.so.1.71.0
libboost_python3.a
libboost_python3-py38.a
libboost_python3-py38.so
libboost_python3.so
libboost_python.a
libboost_python.so
libboost_random.so.1.71.0
libboost_regex.so.1.71.0
libboost_serialization.a
libboost_serialization.so
libboost_serialization.so.1.67.0
libboost_serialization.so.1.71.0
libboost_stacktrace_addr2line.so.1.71.0
libboost_stacktrace_backtrace.so.1.71.0
libboost_stacktrace_basic.so.1.71.0
libboost_stacktrace_noop.so.1.71.0
libboost_system.a
libboost_system.so
libboost_system.so.1.67.0
libboost_system.so.1.71.0
libboost_test_exec_monitor.a
libboost_thread.a
libboost_thread.so
libboost_thread.so.1.67.0
libboost_thread.so.1.71.0
libboost_timer.so.1.71.0
libboost_type_erasure.so.1.71.0
libboost_unit_test_framework.a
libboost_unit_test_framework.so
libboost_unit_test_framework.so.1.67.0
libboost_unit_test_framework.so.1.71.0
libboost_wave.so.1.71.0
libboost_wserialization.a
libboost_wserialization.so
libboost_wserialization.so.1.67.0
libboost_wserialization.so.1.71.0

**Comment by jackgerrits** [comment]
Okay that’s good. Does that mean you are now unblocked?

**Comment by calebtuttle-lp** [comment]
Tried running 'python setup.py build' again and got what looks like the same error:
running build
running build_py
running egg_info
writing python/vowpalwabbit.egg-info/PKG-INFO
writing dependency_links to python/vowpalwabbit.egg-info/dependency_links.txt
writing top-level names to python/vowpalwabbit.egg-info/top_level.txt
reading manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/*.bat'
warning: no files found matching 'python/*.dll' under directory 'python/bin'
warning: no files found matching 'python/packages.config' under directory 'python/windows*'
warning: no files found matching 'python/*.vcxproj*' under directory 'python/windows*'
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
running build_ext
cmake -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.6 -DBUILD_PYTHON=On -DBUILD_TESTS=Off -DWARNINGS=Off -DBoost_NO_BOOST_CMAKE=OFF -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/lib.linux-x86_64-3.6 /home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit
-- VowpalWabbit Version: 8.8.1
-- Using C++ standard: 11
-- Git Version: 5bf2bca4
-- Number of processors: 8
-- Submodule update
-- help2man not found, please install it to generate manpages
-- Python 3.6 will be used for VowpalWabbit Python bindings
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: python36) (found version "1.67.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  python/CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/caleb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vowpal_wabbit/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1

After installing the older versions of the packages, I ran 'make' inside vowpal_wabbit/ and then 'sudo make install' in build/. Then I ran setup.py. Am I missing a step?

**Comment by jackgerrits** [comment]
So I looked into this a bit more. It looks like both the 1.67 and 1.71 apt packages for Boost on Ubuntu 20.04 only provide libs for Python 3.8. I have no idea why Boost is not bundling other versions. So using the apt installed binaries will only work for Python 3.8. I'm going to do a bit of research to see how we can mitigate this because undoubtedly people will want to use versions other than 3.8... In the meantime is it possible for you to consume the bindings with Python 3.8?

**Comment by peterychang** [comment]
Would it be possible to use anaconda?
I believe Conda has boost binaries for every version of python it supports, so it should solve your binary dependency issues.

I think the following `create` call will create a new conda environment and install all the conda dependencies required to build and run the python tests
`conda create -n <env_name> python=3.6 pytest pandas numpy boost py-boost zlib scipy scikit-learn six joblib`

If you don't need to run the tests, the following should suffice
`conda create -n <env_name> python=3.6 boost py-boost zlib`

**Comment by calebtuttle-lp** [comment]
Conda provided the fix. I installed miniconda and created the environment as suggested. Then a simple 'pip install vowpalwabbit' worked beautifully. Thank you @jackgerrits and @peterychang for your help

**Comment by jackgerrits** [comment]
Awesome, I'm glad that resolved it! Going to go ahead and close, feel free to reopen or create a new one if you face further issues.

**Comment by YiQ-Zhao** [comment]
Hi,

I am encountering a similar issue for MacOS but it's not easy for me to switch to conda. I have other dependencies in the current venv.
I'm using py37 while `brew install boost-python3` has py38 as dependency. I can't find a way to install an earlier version of boost-python3.

>Calling Installation of boost-python3 from a GitHub commit URL is disabled

Below is the full error message:

```
  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python38-mt.dylib (3.8, Boost_PYTHON_VERSION=3.7)

  * libboost_python38-mt.a (3.8, Boost_PYTHON_VERSION=3.7)

  * libboost_python38.dylib (3.8, Boost_PYTHON_VERSION=3.7)

  * libboost_python38.a (3.8, Boost_PYTHON_VERSION=3.7)
```


Any help would be appreciated.

**Comment by mainguyenanhvu** [comment]
Hi @YiQ-Zhao, have you found solution? Please help me. Thank you very much.

**Comment by AlejandroAttento** [comment]
Hey, I had the same issue recently and solved it by installing vowpal_wabbit using `conda`.
