### ISSUE TITLE
Getting raw predictions using Python wrapper

### ISSUE THREAD

**Issue by oleg131** [VowpalWabbit/vowpal_wabbit#2447]
## Short description
I usually run Vowpal Wabbit from command line, where I can get prediction scores using `-r` argument. However, I can't seem to find this option in the Python wrapper. 

This line https://github.com/VowpalWabbit/vowpal_wabbit/blob/388d5516cca7aad00de7a0958d800a293e3dc9ab/python/vowpalwabbit/pyvw.py#L149
suggests that `pDECISION_SCORES` may be the needed prediction type, but this parameter is absent (i.e. there is no attribute `pyvw.vw.pDECISION_SCORES`)

I know there is `probabilities` option, however such option produces different results. It seems that the predictions are capped at -1, 1. E.g. these are prediction I get with calling `model.predict` with default settings:
```
model = pyvw.vw(initial_regressor='model')
model.predict(ex) # where `ex` are read from `data` file
>>
[-1.0,
 0.6366648077964783,
 -1.0,
 1.0,
 -0.7182058691978455,
 -1.0,
 -1.0,
 -1.0,
 0.47461384534835815,
 -1.0]
```
and these are predictions I get using command `vw --initial_regressor model -d data -r scores`

```
-1.737777
0.636665
-2.001380
4.879733
-0.718206
-1.437312
-2.942628
-2.087057
0.474614
-2.950264
```

Is there a possibility to reproduce the last result in Python?

**Comment by Smit-create** [comment]
Hi @oleg131, 

> there is no attribute `pyvw.vw.pDECISION_SCORES`

I agree this will produce attribute error as it should be `pylibvw.vw.pDECISION_SCORES` . Can you try using the following way if it produces the expected results?
```python
>>> import pylibvw
>>> pylibvw.vw.pDECISION_SCORES 
8
>>> model.predict(ex, prediction_type = pylibvw.vw.pDECISION_SCORES)
# I expect this will produce the desired output
```

**Comment by oleg131** [comment]
@Smit-create 

`pDECISION_SCORES` still can't be found:

```
In [8]: import pylibvw                                                                                                                                          

In [9]: pylibvw.vw.pDECISION_SCORES                                                                                                                             
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-0e932e7ea8f2> in <module>
----> 1 pylibvw.vw.pDECISION_SCORES

AttributeError: type object 'vw' has no attribute 'pDECISION_SCORES'
```

If I pass `8` as argument, I get this:
```
In [11]: model.predict(exs[1], 8)                                                                                                                               
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-4f5768e4f867> in <module>
----> 1 model.predict(exs[1], 8)

/vowpal_wabbit/python/vowpalwabbit/pyvw.py in predict(self, ec, prediction_type)
    207 
    208         if isinstance(ec, example):
--> 209             prediction = get_prediction(ec, prediction_type)
    210         else:
    211             prediction = get_prediction(ec[0], prediction_type)

/vowpal_wabbit/python/vowpalwabbit/pyvw.py in get_prediction(ec, prediction_type)
     63         pylibvw.vw.pMULTICLASSPROBS: ec.get_scalars
     64     }
---> 65     return switch_prediction_type[prediction_type]()
     66 
     67 

KeyError: 8
```

However, e.g. `0` works as expected:
```
In [12]: model.predict(exs[1], 0)                                                                                                                               
Out[12]: 0.6366648077964783
```

**Comment by Smit-create** [comment]
> /vowpal_wabbit/python/vowpalwabbit/pyvw.py in get_prediction(ec, prediction_type)
>      63         pylibvw.vw.pMULTICLASSPROBS: ec.get_scalars
>      64     }
> ---> 65     return switch_prediction_type[prediction_type]()
>      66

I see that the python wrapper isn't updated. Try updating it as in current master we now provide `pylibvw.vw.pDECISION_SCORES` as a key. Can you please try it on the current master?

https://github.com/VowpalWabbit/vowpal_wabbit/blob/388d5516cca7aad00de7a0958d800a293e3dc9ab/python/vowpalwabbit/pyvw.py#L133-L178

**Comment by oleg131** [comment]
Tried master branch, I get this
```
In [4]: pylibvw.vw.pDECISION_SCORES                                                                                                                          
Out[4]: 8
In [8]: model.predict(exs[0], 8)                                                                                                                             
Segmentation fault
```
And then the python process crashes.

This also happened before I switched to master, for some other predictions types.

**Comment by jackgerrits** [comment]
Hi @oleg131,

Can you please provide the entire script, model file and input file that is resulting in that segfault?

I installed 8.8.1 and was able to execute the following:
```Python
>>> from vowpalwabbit import pyvw
>>> pyvw.pylibvw.vw.pDECISION_SCORES
8
```

I have seen issues in the past where pip installs several versions of the same package side by side and the importing script gets the wrong version.

**Comment by oleg131** [comment]
@jackgerrits 
Yes,`pyvw.pylibvw.vw.pDECISION_SCORES` argument works on master for me too. But could you try using it in predicting? This is what I get

```
In [3]: from vowpalwabbit import pyvw                                                                                                                        

In [4]: pyvw.pylibvw.vw.pDECISION_SCORES                                                                                                                     
Out[4]: 8

In [5]: model = pyvw.vw(quiet=True) 
   ...:                                                                                                                                                      

In [6]: train_examples = [ 
   ...:   "0 | price:.23 sqft:.25 age:.05 2006", 
   ...:   "1 | price:.18 sqft:.15 age:.35 1976", 
   ...:   "0 | price:.53 sqft:.32 age:.87 1924", 
   ...: ]                                                                                                                                                    

In [7]: for example in train_examples: 
   ...:     model.learn(example) 
   ...:                                                                                                                                                      

In [8]: model.predict(train_examples[0])                                                                                                                     
Out[8]: 0.040764134377241135

In [9]: model.predict(train_examples[0], 8)                                                                                                                  
Segmentation fault
```

**Comment by jackgerrits** [comment]
Explicitly providing the prediction_type when calling predict is rarely required, and often when it is passed it is easy to get wrong.

In your case, in the example you provided you are using the default VW label format, and passing your examples to the default learner, scorer and GD. This setup produces predictions as floats. However, when you then specified `8` or `pyvw.pylibvw.vw.pDECISION_SCORES` you are reinterpreting that float as a decision scores object. This is incorrect and results in a segfault. A better error than this would have helped I'm sure.

In order to actually get decision scores you need to use a reduction that produces them. One such reduction is Conditional Contextual Bandit [(you can read more about it here)](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Conditional-Contextual-Bandit).
```Python 
from vowpalwabbit import pyvw

model = pyvw.vw(quiet=True, ccb_explore_adf=True)

train_examples = [
    "ccb shared |User b",
    "ccb action |Action d",
    "ccb action |Action e",
    "ccb slot 0:0:0.2 |Slot h",
]

model.learn(train_examples)

print(model.predict(train_examples))
print(model.predict(train_examples, 8))
print(model.predict(train_examples, pyvw.pylibvw.vw.pDECISION_SCORES))
```
Output:
```
[[(0, 0.5), (1, 0.5)]]
[[(0, 0.5), (1, 0.5)]]
[[(0, 0.5), (1, 0.5)]]
```

In your original question you were loading a model, so it's quite possible CCB was loaded correctly there. In that case you should still be able to omit the explicit prediction type and get the output automatically. It's not super clear how to pipe the `raw_prediction` value out here. There is the `partial_prediction` (not accessible to Python at the moment) but I am not sure it will always be the value you are looking for.

**Comment by oleg131** [comment]
@jackgerrits In that case I'm not sure that decision scores are what I'm looking for. The model I used for training was SGD, with the following arguments,

```
--loss_function hinge  --passes 60 --hash all  --initial_t 1.0  --invariant --adaptive --normalized -- --holdout_off
```

However, as mentioned, default output via Python wrapper is different from `-r` output. Is there any workaround for accessing `-r` values from Python? I could running prediction via subprocess, like you mentioned, but it just induces IO overhead.

**Comment by jackgerrits** [comment]
I see, so raw_prediction generally corresponds to the value of `partial_prediction` which is the raw output of the base learner before clamping and before reductions convert to their own representation. It is possible to get this value in Python.

You should be able to retrieve the raw prediction like so:
```Python
from vowpalwabbit import pyvw

model = pyvw.vw(quiet=True)

train_examples = [
    "0 | price:.23 sqft:.25 age:.05 2006",
    "1 | price:.18 sqft:.15 age:.35 1976",
    "0 | price:.53 sqft:.32 age:.87 1924",
 ]

for example in train_examples:
    model.learn(example)

# To get the partial_prediction you need access to the example object post predict
pred_ex = model.parse("| price:1000 sqft:.95 age:1.3 1976")
print("Prediction: {}".format(model.predict(pred_ex)))
print("Raw prediction: {}".format(pred_ex.get_partial_prediction()))
```

**Comment by oleg131** [comment]
Seems that `get_partial_prediction` agrees with `-r` but not always. Would you happen to know what are the steps between the two?

E.g. I have the following from `-r`:
```
-1.737777 
0.636665 
-2.110936 
4.733659 
-0.791243 
-1.474367 
-3.016738 
-2.197685 
0.401040 
-3.004169 
```
and the following from `get_partial_prediction`
```
-1.7377768754959106
0.6366648077964783
-2.001380443572998
4.879732608795166
-0.7182058691978455
-1.4373120069503784
-2.9426283836364746
-2.087057113647461
0.47461384534835815
-2.950263500213623
```

Full code for the latter
```
f = open('sample')       
e = f.readlines()  
for i in e: 
  j = i.strip() 
  k = model.parse(j) 
  model.predict(k) 
  print(k.get_partial_prediction()) 
```

**Comment by jackgerrits** [comment]
I'm not aware of what could be causing the difference in behavior here. Can you please provide full code/command lines for how you produced both results? I want to make sure there are no differences that would cause this.

**Comment by oleg131** [comment]
Command line:
`vw -i m -d sa -r sc`

```
> more sc
-1.737777 a
0.636665 b
-2.110936 c
4.733659 d
-0.791243 e
```

Python:
```
from vowpalwabbit import pyvw                                                                                                                                                                       

model = pyvw.vw(i='m')                                                                                                                                                   

with open('sa') as f: 
    sa = f.readlines() 

for sa_ in sa: 
    sa_ = sa_.strip() 
    sa_ = model.parse(sa_) 
    model.predict(sa_) 
    print(sa_.get_partial_prediction()) 
```

```                                                                                                                                                                     
-1.7377768754959106
0.6366648077964783
-2.001380443572998
4.879732608795166
-0.7182058691978455
```

**Comment by jackgerrits** [comment]
Can you additionally provide the input model `m` and the datafile `sa`?

**Comment by oleg131** [comment]
I was doing more tests and it seems that the discrepancy was due to not including `--testonly` in the shell command. When running `vw -i m -d sa -r sc --testonly`, it produces same results as the python procedure you suggested. Thanks!

**Comment by jackgerrits** [comment]
Ah I see - so in the command line version it was learning and the updated model was producing different results. Makes sense! Thanks for circling back with the resolution.

**Comment by jackgerrits** [comment]
It looks like this issue is resolved, I'm going to go ahead and close. Feel free to reopen if need be.
