### ISSUE TITLE
Easier access to learned feature weight in python wrapper

### ISSUE THREAD

**Issue by etiennekintzler** [VowpalWabbit/vowpal_wabbit#2474]
### Problem
In the python wrapper, **getting learned (features) weight should be easier**.

Currently the method to get learned weight of a given feature is :
1. find the hash value of the feature name using `pyvw.vw.hash_feature` using the feature name as 1st arg and the _hash_ of the namespace (being 0 for the naked namespace) as 2nd arg.
2. feed the feature name hash value to `pyvw.vw.get_weight`

**These two steps are not straightforward to figure out for newcomers**, and assume one is familiar with the hashing trick (to grasp why the learned feature are not at location 0, 1, 2, 3). 
 
### Solution

The solution is easy, just define the following function/method:
```python
def get_weight_from_name(model, name, namespace=""):
    return model.get_weight(model.hash_feature(name, model.hash_space(namespace)))
```

### Working example

Below is a quick example. I use _monkey patching_ on the second line (`pyvw.vw.get_weight_from_name = get_weight_from_name`) to add the method to the class at runtime but of course this method should be written directly in the class.

```python
from vowpalwabbit import pyvw
pyvw.vw.get_weight_from_name = get_weight_from_name
model = pyvw.vw(quiet=True)

train_examples = [
  "0 | price:.23 sqft:.25 age:.05 2006",
  "1 | price:.18 sqft:.15 age:.35 1976",
  "0 | price:.53 sqft:.32 age:.87 1924",
]

for example in train_examples:
    model.learn(example)
```
Then a quick listcomp to get the tuples _(feature name, learned weight)_: 
```python
[(name, model.get_weight_from_name(name)) for name in ["price", "sqft", "age"]]
```
The output is:
```python
[('price', 0.0018481612205505371),
 ('sqft', 0.021296292543411255),
 ('age', 0.0042297691106796265)]
```

If necessary I can do a PR.

**Comment by Yash621** [comment]
Can I work on this issue?

**Comment by priyanshuone6** [comment]
The `get_weight_from_name` is already implemented, is this still an ongoing issue?

**Comment by jackgerrits** [comment]
You're right this is resolved. Closing
