### ISSUE TITLE
Explicit warning/errors when unsupported argument is ignored (at least for bfgs + save_resume)

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#2479]
#### Describe the bug
There is confusing behavior: save_resume is not supported by bfgs but there is no explicit message about it - it just silently works if you provide it (ignoring --save_resume)
(based on #2006)

#### To Reproduce
echo "2 |
-1 | f1
5 | f2" > data.txt

vw -c --passes 2 -f model1.bin -d data.txt --bfgs
vw -c --passes 2 -f model2.bin -d data.txt --bfgs --save_resume

diff model1.bin model2.bin

#### Expected behavior
Either files should differ (if save_resume mode is supported), or explicit warning/error message of unsupported commandline should be exposed

#### Observed Behavior
Both runs are working in exactly the same way and silently generate same models.

#### Environment
8.8.1 everywhere

**Comment by jackgerrits** [comment]
This [PR](https://github.com/VowpalWabbit/vowpal_wabbit/pull/3504) makes it possible for us to detect things like this. The next step would be to require reductions to always query for things they need out of the options interface instead of getting the information from `all`
