### ISSUE TITLE
In pyvw.vw, argument --passes not taken into account

### ISSUE THREAD

**Issue by etiennekintzler** [VowpalWabbit/vowpal_wabbit#2491]
I am trying to do multiple passes on data using the argument `--passes` along with the cache argument `--c`. However **it does not seem to have any effect**.

I am using vowpalwabbit 8.8.1 installed from pip, python 3.7 and Ubuntu 18.04.4 LTS.

Below is a reproducible example : 
```python
from vowpalwabbit import pyvw

examples = [
    "1 | x:-1",
    "0 | x:1",
    "0 | x:2",
    "1 | x:-1.5",
    "0 | x:1.5",
]

model = pyvw.vw()
for ex in examples:
    model.learn(ex)
model.get_weight(model.hash_feature("x", 0)) # -0.24721133708953857 without pass

model_passes = pyvw.vw("--passes 3 -c")
for ex in examples:
    model_passes.learn(ex)
model_passes.get_weight(model.hash_feature("x", 0)) # -0.24721133708953857 with 3 passes
```

The learnt weight of `model` is the same as `model_passes`. 

Another way to see that it doesn't have any effect is to inspect the output from the console after the executing the Python code for the `model_passes`:
```
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = .cache
Reading datafile = 
num sources = 1

finished run
number of examples = 5
weighted example sum = 5.000000
weighted label sum = 2.000000
average loss = undefined (no holdout)
best constant = 0.400000
best constant's loss = 0.240000
total feature number = 10
1.000000 1.000000            1            1.0   1.0000   0.0000        2
0.500000 0.000000            2            2.0   0.0000   0.0000        2
0.283570 0.067140            4            4.0   1.0000   0.6336        2
```

And this is what I obtain when I use the following CLI `vw fake_train.dat --passes 3 -c`.

```
(base) etienne@inspiron:~/PROJETS/SPF_BANDIT$ vw fake_train.dat --passes 3 -c 
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
using cache_file = fake_train.dat.cache
ignoring text input in favor of cache input
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
1.000000 1.000000            1            1.0   1.0000   0.0000        2
0.500000 0.000000            2            2.0   0.0000   0.0000        2
0.283570 0.067140            4            4.0   1.0000   0.6336        2
 **unknown  unknown            8            8.0   0.0000   0.0000        2 h**

finished run
number of examples per pass = 5
passes used = 3
weighted example sum = 15.000000
weighted label sum = 6.000000
average loss = undefined (no holdout)
best constant = 0.400000
best constant's loss = 0.240000
total feature number = 30
```

**Comment by jackgerrits** [comment]
When manually driving the learning process as you are the `--passes` argument does not make sense.

I agree it is confusing, but that argument is exposed so that if you created the pyvw instance with a datafile then it would first do multiple passes of learning of that datafile when then instance is initialized.

**Comment by etiennekintzler** [comment]
> When manually driving the learning process as you are the --passes argument does not make sense.

Yep I see. It make sense since you expect multiple pass on a whole datafile, not multiple passes per line example. For the same reasons I assume holdout_period won't make sense either ?

I have few questions : 
- is there any plan to make `pyvw.vw.model` support list of examples as input. In that cases passes would make sense.
- is the following code a good way to emulate passes: 
```python
model = pyvw.vw()
passes = 3
for _ in range(passes) 
    for ex in examples:
        model.learn(ex)
```

> I agree it is confusing, but that argument is exposed so that if you created the pyvw instance with a datafile then it would first do multiple passes of learning of that datafile when then instance is initialized.

I have never seen instanciation of pyvw.vw with a datafile ; do you have any example ?

**Comment by jackgerrits** [comment]
Yes, there are some arguments that wont make sense. I agree on holdout_period.

> is there any plan to make pyvw.vw.model support list of examples as input. In that cases passes would make sense.

I think yes. Currently it is a little tricky because multi_exs are lists of examples so you need a way to distinguish between a multi_ex and a list of single_exs. We've been thinking about better encapsulation here. But yes, passing a list and being able to do multipass and all of that on it seems very attractive to me.

> is the following code a good way to emulate passes:

Off the top of my head I can't say for sure. I can't remember what things VW does at the end of the pass. @pmineiro  do you know off the top of your head?


> I have never seen instanciation of pyvw.vw with a datafile ; do you have any example ?

All of these would be equivalent:
```Python
model = pyvw.vw("-d datafile")
model = pyvw.vw("--data datafile")
model = pyvw.vw(d="datafile")
model = pyvw.vw(data="datafile")
```

**Comment by etiennekintzler** [comment]
> I think yes. Currently it is a little tricky because multi_exs are lists of examples so you need a way to distinguish between a multi_ex and a list of single_exs.  We've been thinking about better encapsulation here.

Yes I noticed that too. You could pass a bool to a `multilines` parameter at init, or defined a special method `learn_multilines`/`learn_from_multilines` or if the code is really different maybe create a special namespace (you'd then use `from vowpalwabbit.pyvw.multilines import vw for example`)

> But yes, passing a list and being able to do multipass and all of that on it seems very attractive to me.

Yes ! It would certainly be faster than learning example by example and would enable hyper parameter tuning.
