### ISSUE TITLE
[Proposal] Flatbuffers as input to VW - file format

### ISSUE THREAD

**Issue by olgavrou** [VowpalWabbit/vowpal_wabbit#2499]
# Flatbuffers as input to VW - file format

## Motivation

In adding flatbuffer support in VW there is a need to be able to read an input file one serialized object at a time. Flatbuffers don't support storing adjacent serialized objects in a (binary) file and reading them one by one. Objects can be serialized as part of an object collection. For the objects to be deserialized the entire collection needs to be loaded and deserialized before accessing the internal objects (in our case examples) one by one.

To be able to store adjacent serialized objects in a file and read them one by one, the size (and potentially the type) of the object needs to be known beforehand. The serialized objects can then be loaded one at a time from the file, deserialized and processed one by one. New object types should be able to be added without affecting existing files created by a previous flatbuffer schema.

## Proposal

Below I am examining two ways of storing serialized flatbuffer objects:
 - Creating one file and storing the serialized objects with a flatbuffer-specific preamble
    - using flatbuffer's built-in support for prefixing objects with their size
    - using flatbuffers's built-in `union` type - root object will be a union, supporting multiple and future object types
 - Creating two files one as an object index and one storing the serialized objects
   - index file that will hold a (size, type) tuple per line or a (position_in_file, size, type) tuple per line
   - object file containing the serialized objects

### One file approach 
------------------------

**example schema**

<details>

```
namespace VW.parsers.flatbuffer;

table Feature {
  name:string;
  value:float;
  hash:uint64;
}

table Namespace {
  name:string;
  hash:uint8;
  features:[Feature];
}

table SimpleLabel {
  label:float;
  weight:float;
}

union Label {SimpleLabel}

table Example {
  namespaces:[Namespace];
  label:Label;
  tag:string;
}

table ExampleCollection {
  examples:[Example];
}

union ExampleType {Example, ExampleCollection}

table ExampleRoot
{
  example_obj:ExampleType;
}

root_type ExampleRoot;

```

</details>

By wrapping the final object to be serialized in the `ExampleRoot` table which has only a union field, more example types (or other objects) can be added and flatbuffers will know how to serialize/deserialize them without affecting any files created with a previous shema.

Serializing a flatbuffer object with `FinishSizePrefixed()` precedes the fb buffer with a 32 bit size field (in little-endian format like the rest of the serialized data).

#### Serializing and storing to file

Output file will look like (binary file, no newlines):

**object_file**
```
{uint32: size}{serialized object}{uint32: size}{serialized object}
```

<details>

```
std::ofstream outfile;
outfile.open("file.fb", std::ios::binary | std::ios::out);
flatbuffers::FlatBufferBuilder builder;
// get the flatbuffer object
flatbuffers::Offset<ExampleRoot> root_ex_obj = create_example_obj(builder);

// serialize the example with size prefix
builder.FinishSizePrefixed(root_ex_obj);
uint8_t* buf = builder.GetBufferPointer();
size_t size = builder.GetSize();
// write the data to a file
outfile.write(reinterpret_cast<char*>(buf), size);

```

</details>

#### Reading from file and deserializing

Reading consists of:
 - reading the first 4 bytes from the file that indicate the object size
 - reading the object we want to deserialize

<details>

```
std::ifstream data_file("file.fb", std::ios::binary | std::ios::in);
size_t prefix_len = sizeof(uint32_t);
uint32_t prefix;
flatbuffers::uoffset_t object_size;

while (!data_file.fail())
{
   // read the prefix from the file
   data_file.read((char*)&prefix, prefix_len);
 
   // take care of endianess
   object_size = flatbuffers::ReadScalar<flatbuffers::uoffset_t>(&prefix);

   // read one object, object size defined by the read prefix
   std::vector<char> fb_obj(object_size);
   data_file.read(&fb_obj[0], object_size);

   auto flatbuffer_pointer = reinterpret_cast<u_int8_t*>(&fb_obj[0]);
   // get the root object
   auto data = GetExampleRoot(flatbuffer_pointer);

   switch (data->example_obj_type())
   {
      case ExampleType_Example:
      {
         const auto example = data->example_obj_as_Example();
         // use example
      }
      break;
      case ExampleType_ExampleCollection:
      {
         const auto example_coll = data->example_obj_as_ExampleCollection();
         // use example collection
      }
      break;
   }
}
```

</details>

You can find a cpp and python example [here](https://github.com/olgavrou/vowpal_wabbit/tree/fb_input_options/demo/flatbuffer_input_data) under the `one_file` directory.

### Two file approach 
------------------------

**example schema**

<details>

```

[... as before ...]

table Example {
  namespaces:[Namespace];
  label:Label;
  tag:string;
}

root_type Example;

--- different file - usually one root per file ---

[... as before ...]

table ExampleCollection {
  examples:[Example];
}

root_type ExampleCollection;

```

</details>

Here, if not using a wrapper object as the root supporting unions, the different object types will need to be tracked explicitly. All serialized objects get stored in one (or more) file without the size prefix. There is an extra index file holding the metadata needed to deserialize.

#### Serializing and storing to file

Output files will look like:

**index_file**

```
{size, type}
{size, type}
{size, type}
```

**OR**

```
{position_in_file, size, type}
{position_in_file, size, type}
{position_in_file, size, type}
```

**object_file**

```
{serialized object}{serialized object}{serialized object}
```

<details>

```

// track the different object types
enum class object_type
{
  example = 0,
  example_collection
};

std::ofstream outfile;
outfile.open("obj_file.fb", std::ios::binary | std::ios::out);

std::ofstream index_file;
index_file.open("index_file.txt");

flatbuffers::FlatBufferBuilder builder;
flatbuffers::Offset<ExampleRoot> root_ex_obj = create_example_obj(builder);

builder.Finish(root_ex_obj);
uint8_t* buf = builder.GetBufferPointer();
size_t size = builder.GetSize();

outfile.write(reinterpret_cast<char*>(buf), size);
prefix_file << size << " " << static_cast<int>(object_type::example) << std::endl;

```

</details>

#### Reading from file and deserializing

Reading consists of:
 - reading a line from the index file indicating size and type
 - reading the object from the object file and deserialize it

<details>

```
std::ifstream data_file("obj_file.fb", std::ios::binary | std::ios::in);
std::ifstream index_file("index_file.txt");

size_t obj_size;
object_type obj_type;

// read the index file for the next objects size and type
while (index_file >> obj_size >> obj_type)
{
   // could optionally skip over examples and read only example collections
   if (obj_type == object_type::example)
    {
      // skip
      data_file.ignore(obj_size);
      continue;
    }

   // read next object from object file
   std::vector<char> fb_obj(obj_size);
   data_file.read(&fb_obj[0], obj_size);

   auto flatbuffer_pointer = reinterpret_cast<u_int8_t*>(&fb_obj[0]);

   switch (obj_type)
   {
      case object_type::example:
      {
         const auto example = GetExampleRoot(flatbuffer_pointer);
         // use example
      }
      break;
      case object_type::example_collection:
      {
         const auto example_collection = GetExampleCollectionRoot(flatbuffer_pointer);
         // use example collection
      }
   }
```

Of course we could utilize flatbuffer unions here too.

</details>

You can find a cpp and python example [here](https://github.com/olgavrou/vowpal_wabbit/tree/fb_input_options/demo/flatbuffer_input_data) under the `two_file` directory.

## Trade-offs

**One file approach**

Pros: 
 - An object can be explicitly serialized and deserialized with the size prefix preceding it. Data alignment and endianess is taken care of by [flatbuffers](https://google.github.io/flatbuffers/classflatbuffers_1_1_flat_buffer_builder.html#a7ba8462e408431054c99d25120326220).
 - The `union` type allows for new object types to be added while having flatbuffers manage them
 - Only one file to handle
 - Object file differs only by adding the fb built-in prefix

Cons:
 - Can't index the file or filter out objects without deserializing them first
 - Future un-seen use case that will not allow for us to mutate the object format?

**Two files approach**

Pros:
 - Permitting indexing and filtering of the objects without deserializing them beforehand. The much smaller index can be loaded and processed and used to index different objects (e.g. give me the second example) or filter out object types (e.g. read only example collections, not examples)
 - The index file representation is easily changed without having to modify the object file

Cons:
 - Two files need to be managed instead of one (naming, transferring, storing)
 - Need to read/write two files
 - If the index file is lost it is harder to deserialize the object file (although could also use the flatbuffer union type and the prefix size here too)

## Questions

 - Is there a use case for indexing/filtering the input file or do input files always get processed sequentially?

**Comment by jackgerrits** [comment]
> Is there a use case for indexing/filtering the input file or do input files always get processed sequentially?

Is it correct that the only field that could be filtered on would be the values in the index file? So, position_in_file, size and type? I doubt this is super useful in filtering but I'm sure examples could be thought of. This will depend on what type specifies. Right now practically every file is sequentially processed.

In my mind I am asking is this worth requiring two files to be passed around and associated? My hunch is no. So my vote goes for the one file approach.

**Comment by lalo** [comment]
We need to keep in mind the security implications of the **implementation** of this proposal (emphasis on implementation). A bad actor can easily craft a payload that declares the size to be huge, and depending on how the implementation works a buffer might be allocated blindly trusting that user endpoint and crash. This might or not be a concern depending on the scenarios for  this (after all VW is not a service), but if this later gets adopted by an upstream cloud service endpoint that receives this schema, that is troublesome.

At least we should provide guidance for our customers on possible threat vectors.
