### ISSUE TITLE
Windows MSI Install -- new version request

### ISSUE THREAD

**Issue by wangtianyu61** [VowpalWabbit/vowpal_wabbit#2506]
Hi,

I have installed Vowpal Wabbit using MSI Installer for windows from the https://github.com/eisber/vowpal_wabbit/releases. It works fine but it seems that it is in the newest version as several commands such as cbify-ldf and regcb do not exist. (I tried to compile source codes but it failed). I am wondering if there is the newest version of that MSI installer?

Thanks you.

Best
Tianyu

**Comment by jackgerrits** [comment]
Hi @wangtianyu61,

Looks like @eisber maintained those in the past.

What components of the installer do you use? `vw.exe` or the C# DLLs?

**Comment by eisber** [comment]
You'll have to build either setup or setup_bundle project (https://github.com/VowpalWabbit/vowpal_wabbit/tree/master/cs/setup_bundle)

Here's the list of items packaged:

https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/cs/setup/Product.wxs#L39

**Comment by wangtianyu61** [comment]
Thanks for the reply. I just used the installer of vw.exe before from @eisber and it runs well. However, as the version was maintained in 2018, it seems to be short of some new algorithms such as RegCB. Is there a new version of vw.exe? Or I still need to build based on VS2017?

**Comment by eisber** [comment]
@jackgerrits I'm a bit out of the loop in terms of VS version.

**Comment by jackgerrits** [comment]
I wasn't sure if there were users of the MSI, so this is helpful to know! The MSI hasn't been updated for some time so you'll need to do a source build for now.

To do a from source build you can follow the instructions in the wiki: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#windows

**Comment by wangtianyu61** [comment]
Ok, thank you. (Actually at first I encountered some problems in source build so I turned to others:) Anyway thanks.

**Comment by jackgerrits** [comment]
Let me know if you have problems with those instructions and I can help out

**Comment by lalo** [comment]
@wangtianyu61 if you're able to share the build error log here that would be great for future reference.

**Comment by wangtianyu61** [comment]
The build error/warning log there contains: 1)Some metadata file cannot be found in out\target\Debug\x64\VowpalWabbit.**.dll (Core, JSON, Parallel) 2) About 60 warnings are the reference component could not be found such as Systems/WindowsBase/Systems.core etc.  3) Cannot open the file of out\target\Debug\x64\vw_core.lib (libvw.lib) 4) Cannot open the file of rapidjson/reader.h (no such file or repository) 5) Cannot find the identifier "parse_outcome" and lack function title in ccb_label.cc  6)Cannot open the source file boost/version.hpp and boost/utility/string_ref.hpp in vw_string_view.h.
I thought I have followed and satisfied the dependencies of VS2017 in windows correctly except restoring Nuget dependencies. Is it possible that the problems above arise due to this? (Sorry for the stupid problem as I did not do the similar things before maybe:) Thanks very much if you can help.

**Comment by lalo** [comment]
From a couple of those, I assume either the dependencies are missing or you might have ommited the "--recursive" from the git clone command.

Make sure you clone with `git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git` to pull the submodules (rapidjson).

Here's the list of dependencies per OS. https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies

**Comment by wangtianyu61** [comment]
Actually I thought I did all of them after check the list and dependencies. Could you release a new version of vowpalwabbit (vw.exe) online if possible?

**Comment by jackgerrits** [comment]
While this can change as we work on making it easier to get VW, at this point we don't distribute `vw.exe` as a binary. However, one of the experimental nightly pipelines produces it for Windows. You can give that a try? But keep in mind at this point it is "unofficial".

It is in the `target` artifact: https://dev.azure.com/vowpalwabbit/Vowpal%20Wabbit/_build/results?buildId=11433&view=artifacts&type=publishedArtifacts
