### ISSUE TITLE
TestJsonDictClass fails randomly

### ISSUE THREAD

**Issue by olgavrou** [VowpalWabbit/vowpal_wabbit#2527]
Example of failed run [here](https://dev.azure.com/vowpalwabbit/Vowpal%20Wabbit/_build/results?buildId=11736&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997)

**Comment by jackgerrits** [comment]
@lokitoth I remember you looked into this a while back. What did you discover?

**Comment by jackgerrits** [comment]
Closing as duplicate of  #1978
