### ISSUE TITLE
Python tests fail on Windows

### ISSUE THREAD

**Issue by peterychang** [VowpalWabbit/vowpal_wabbit#2528]
The python tests fail on windows. Most of the failures appear to happen in the DFtoVW converter, specifically when doing type checking.

After some investigation it looks like the problem is that the python `int` type is converted badly on Windows.

Instead of the `int`->`int64` conversion that happens on Linux, Windows does `int`->`int32`

**Comment by jackgerrits** [comment]
Is this fixed now that #2530 is merged?

**Comment by peterychang** [comment]
Fixed in https://github.com/VowpalWabbit/vowpal_wabbit/pull/2530
