### ISSUE TITLE
Please make v8.8 available via apt-get; Build description does not work for ubuntu 18.04.5

### ISSUE THREAD

**Issue by pransito** [VowpalWabbit/vowpal_wabbit#2545]
#### Describe the bug
The description for building on ubuntu (18.04.5) does not work: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#ubuntu
On apt-get currently only version 8.5.0 is available.

#### Expected behavior
Please make current version available via apt-get for ubuntu so that everyone can simply run:
sudo apt-get install -y vowpal-wabbit

**Comment by jackgerrits** [comment]
Could you provide a description of the issue you faced when building based on the wiki?

The version is tied to OS release, so newer Ubuntu versions have newer releases. I'd like to look into an official PPA to make this easier on Ubuntu but that's just a thought at the moment. (There are other avenues we're exploring here too)

**Comment by pransito** [comment]
Hi,

Thank you for your quick reply!

I am working on an AWS EC2 instance. Changing the ubuntu version comes with a big overhead.

I think I have gotten it to work now but maybe improve some small things in the description to make it clearer for people unexperienced with building from source (like me):

on: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#ubuntu

everything works up to:

`cd flatbuffers-v1.12.0`

it must be:

`cd flatbuffers-1.12.0`

Afterwards everything works up to:
`make install -j$(nproc)`

failing with:
```
...
[100%] Linking CXX executable flatc
[100%] Built target flatc
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/include/flatbuffers
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot set permissions on "/usr/local/include/flatbuffers"


Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
```

Running instead:
`sudo make install -j$(nproc)`
...produces no error.

Afterwards I move on to: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Building#linux

This site is confusing... should I just run:

`make`

?

There are also cmake code snippets, cmake .. -DSTATIC_LINK_VW=ON... All do not work, flags are not recognized. So I just run:

`make`

Maybe make it more explicit that is the only thing needed, the other code snippets are all optional alternatives...

The big issue here was that I did not know that you have to go back up the directory tree to `~/vowpal-wabbit/` and there run: `make`

Then actually the build happens (this did not happen before)!

Then I move on to https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Installing#linux

...and it worked. I did not even have to add the path. I hadn't deinstalled the ubuntu vowpal wabbit (8.5.0) but running:

`vw --version`
returns:
`8.8.1 (git commit: dbdfde1fd)`

So it seems to be installed now. I am trying to run my models now... Does not yet work... but if the errors there persist I'll open a new issue.

**Comment by pransito** [comment]
so you may close this, as there is no bug; just maybe improve build description with the suggested changes

**Comment by jackgerrits** [comment]
Building from source is a bit of a process, I agree. There are lots of options, so working out a clear way to present this is the wiki has been a journey. Thank you for the feedback though, it is much appreciated! Helps us improve!

Because `make install` often installs to system directories that's why the `sudo` is needed, but that is system dependent which is why we don't have it as `sudo` in the instructions.

Did `-DSTATIC_LINK_VW=ON` not work for you? This one is even more system dependent because you required position independent code `-fPIC` compiled dependencies and static libs to be able to do it.

@olgavrou looks like some of the recent flatbuffer additions to the build process created some friction here. Would you be able to take a look at those?

**Comment by olgavrou** [comment]
@jackgerrits  yes I have made it explicit that the flatubuffers are not needed for `master`, apologies @pransito for the confusion. I have also made it explicit in the `Building` documentation that you should run `make` from `build` directory. Thank's @pransito for the feedback
