### ISSUE TITLE
Memory leak in Python interface:

### ISSUE THREAD

**Issue by andreacimino** [VowpalWabbit/vowpal_wabbit#2567]
`####` Describe the bug
Once a model is created in the python interface, this is never properly released from memory.

#### To Reproduce

```
from vowpalwabbit import pyvw
import resource
CMD = "--cb_explore_adf -q UA --quiet --epsilon=0.3"

START_MEM_USAGE = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss


for x in range(0, 10000000):
  if x % 1000 == 1:
    print("Memory : %r Kb" % (resource.getrusage(resource.RUSAGE_SELF).ru_maxrss - START_MEM_USAGE,))
  pyvw.vw(CMD)
```

#### Environment
8.8.1 (Ubuntu 20.04), Pip installation
Requirement already satisfied: vowpalwabbit in /home/andrea/.local/lib/python3.8/site-packages (8.8.1)

**Comment by jackgerrits** [comment]
Using 8.8.1 from pip I get:
```
Memory : 8616 Kb
Memory : 148604 Kb
Memory : 284564 Kb
Memory : 420788 Kb
Memory : 556748 Kb
Memory : 692708 Kb
Memory : 828668 Kb
Memory : 964628 Kb
Memory : 1100852 Kb
Memory : 1236812 Kb
Memory : 1372772 Kb
Memory : 1508732 Kb
...
```

Using current master I get:
```
Memory : 8052 Kb
Memory : 16660 Kb
Memory : 16660 Kb
Memory : 16660 Kb
Memory : 16660 Kb
Memory : 16660 Kb
...
```

Looks like the leak was definitely real and is now resolved in master. We'll be doing a release soon, but in the meantime it can be installed from master using:
```sh
python -m pip install git+https://github.com/VowpalWabbit/vowpal_wabbit.git
```

**Comment by jackgerrits** [comment]
Closing as this is resolved in master, if you still experience the issue with that code please reopen!
