### ISSUE TITLE
Unable to do make in VW (due to unknown option: --enable-new-dtags)

### ISSUE THREAD

**Issue by saisr-media** [VowpalWabbit/vowpal_wabbit#2589]
[ 81%] Building CXX object java/CMakeFiles/vw_jni.dir/src/main/c++/util.cc.o
[ 81%] Building CXX object java/CMakeFiles/vw_jni.dir/__/vowpalwabbit/spanning_tree.cc.o
[ 82%] Linking CXX shared library libvw_jni.dylib
ld: unknown option: --enable-new-dtags
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [java/libvw_jni.dylib] Error 1
make[1]: *** [java/CMakeFiles/vw_jni.dir/all] Error 2

failing in this if I do make 

CMAkE flags are : default + -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_JAVA=ON  -DVW_INSTALL=ON -DBoost_NO_BOOST_CMAKE=ON

**Comment by jackgerrits** [comment]
Hi @saisr-media, currently the Java bindings are only setup for Linux. You can see this issue for a discussion https://github.com/VowpalWabbit/vowpal_wabbit/issues/2521. Closing as duplicate.
