### ISSUE TITLE
make java error for v8.8.1

### ISSUE THREAD

**Issue by ssujr** [VowpalWabbit/vowpal_wabbit#2598]
Hi,

I ran make java and got below error. It works fine for v8.4.1. 

mkdir -p build
cd build; cmake ..
-- VowpalWabbit Version: 8.8.1
-- Using C++ standard: 11
-- Git Version: 8963c2f9a
-- Number of processors: 4
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   system
-- Submodule update
-- help2man not found, please install it to generate manpages
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vowpal_wabbit/build
cd build; make -j4 vw_jni
make[1]: Entering directory '/home/vowpal_wabbit/build'
make[1]: *** No rule to make target 'vw_jni'.  Stop.
make[1]: Leaving directory '/home/vowpal_wabbit/build'
Makefile:42: recipe for target 'java_build' failed
make: *** [java_build] Error 2

**Comment by jackgerrits** [comment]
Hi @ssujr,

In order for the Java build files to be generated you need to set the option `BUILD_JAVA` to on. For example:

```sh
cmake .. -DBUILD_JAVA=On
```
