### ISSUE TITLE
REMOVE the possibility in DFtoVW to provide constant values (i.e values that are not from the dataframe)

### ISSUE THREAD

**Issue by etiennekintzler** [VowpalWabbit/vowpal_wabbit#2600]
Using DFtoVW types we can provide constant values (i.e values not from the dataframe).

For instance : 
```python
Feature(value=1.2, name="x", value_from_df=False)
```
would return a column of `x:1.2` when converting the dataframe.

The feature could be remove since : 
- **it doesn't seem really useful**: if the user really want to add constant value he could always create constant column in his dataframe (e.g `df['x'] = 1.2`)
- **Simplify the API**: no `name_from_df` or `value_from_df` arguments.
- **Simplify the underlying code**: the class `AttributeDescriptor` is much shorter + no need to handle the uncertainty about the argument being either a column or a constant value.

I'm working on the PR already.

**Comment by lalo** [comment]
Closing since it's been addressed in PR #2601
