### ISSUE TITLE
models will differ (very very) slightly when trained with json vs text

### ISSUE THREAD

**Issue by olgavrou** [VowpalWabbit/vowpal_wabbit#2606]
#### Describe the bug
When training a model with the same data it makes a **very slight** difference in the end model whether that data was parsed via json or via text. This is probably due to the fact that text parsing uses the `parseFloat` method to parse strings to floats where as json parsing will use the `rapidjson` float parsing. 

As far as I have tested this (using full examples in `0001.dat` and `0001.json` files) predictions were *not* affected and the difference is so small not even sure it is worth being filed as a bug.

#### To Reproduce
Train with JSON
 - using first line of `0001.json` file
<details>

```
{"_label":1,"features":{"13":3.9656971e-02,"24":3.4781646e-02,"69":4.6296168e-02,"85":6.1853945e-02,"140":3.2349996e-02,"156":1.0290844e-01,"175":6.8493910e-02,"188":2.8366476e-02,"229":7.4871540e-02,"230":9.1505975e-02,"234":5.4200061e-02,"236":4.4855952e-02,"238":5.3422898e-02,"387":1.4059304e-01,"394":7.5131744e-02,"433":1.1118756e-01,"434":1.2540409e-01,"438":6.5452829e-02,"465":2.2644201e-01,"468":8.5926279e-02,"518":1.0214076e-01,"534":9.4191484e-02,"613":7.0990764e-02,"646":8.7701865e-02,"660":7.2289191e-02,"709":9.0660661e-02,"752":1.0580081e-01,"757":6.7965068e-02,"812":2.2685185e-01,"932":6.8250686e-02,"1028":4.8203137e-02,"1122":1.2381379e-01,"1160":1.3038123e-01,"1189":7.1542501e-02,"1530":9.2655659e-02,"1664":6.5160148e-02,"1865":8.5823394e-02,"2524":1.6407280e-01,"2525":1.1528353e-01,"2526":9.7131468e-02,"2536":5.7415009e-01,"2543":1.4978983e-01,"2848":1.0446861e-01,"3370":9.2423186e-02,"3960":1.5554591e-01,"7052":1.2632671e-01,"16893":1.9762035e-01,"24036":3.2674628e-01,"24303":2.2660980e-01,"const":0.01}}
```

</details>
- command run: 

```
./vowpalwabbit/vw -k -l 20 --initial_t 128000 --power_t 1 -d ../test/train-sets/0001.json --json -f 0001json.model  --invariant --ngram 3 --skips 1 --holdout_off --audit
```
Train with TEXT
- using first line of `0001.dat` file
<details>

```
1 |features 13:3.9656971e-02 24:3.4781646e-02 69:4.6296168e-02 85:6.1853945e-02 140:3.2349996e-02 156:1.0290844e-01 175:6.8493910e-02 188:2.8366476e-02 229:7.4871540e-02 230:9.1505975e-02 234:5.4200061e-02 236:4.4855952e-02 238:5.3422898e-02 387:1.4059304e-01 394:7.5131744e-02 433:1.1118756e-01 434:1.2540409e-01 438:6.5452829e-02 465:2.2644201e-01 468:8.5926279e-02 518:1.0214076e-01 534:9.4191484e-02 613:7.0990764e-02 646:8.7701865e-02 660:7.2289191e-02 709:9.0660661e-02 752:1.0580081e-01 757:6.7965068e-02 812:2.2685185e-01 932:6.8250686e-02 1028:4.8203137e-02 1122:1.2381379e-01 1160:1.3038123e-01 1189:7.1542501e-02 1530:9.2655659e-02 1664:6.5160148e-02 1865:8.5823394e-02 2524:1.6407280e-01 2525:1.1528353e-01 2526:9.7131468e-02 2536:5.7415009e-01 2543:1.4978983e-01 2848:1.0446861e-01 3370:9.2423186e-02 3960:1.5554591e-01 7052:1.2632671e-01 16893:1.9762035e-01 24036:3.2674628e-01 24303:2.2660980e-01 const:.01
```

</details>
- command run:

```
./vowpalwabbit/vw -k -l 20 --initial_t 128000 --power_t 1 -d ../test/train-sets/0001.dat -f 0001dat.model  --invariant --ngram 3 --skips 1 --holdout_off --audit
```

#### Observed Behavior
Differences spotted in audit (highlighting the float differences)

- JSON features^234:13921:0.0542001:0        `features^236:13923:0.044856:0`   features^238:13925:0.0534229:0  
- TEXT  features^234:13921:0.0542001:0        `features^236:13923:0.0448559:0`  features^238:13925:0.0534229:0 

- JSON `features^646:14333:0.0877019:0`               features^660:14347:0.0722892:0   `features^709:14396:0.0906607:0`  
- TEXT `features^646:14333:0.0877018:0`               features^660:14347:0.0722892:0   `features^709:14396:0.0906606:0`

**Comment by jackgerrits** [comment]
There isn't much we can do here since I don't think Rapidjson allows the float parsing to be changed. The minor differences are akin to floating point differences across environments and so should be of little real world impact.
