### ISSUE TITLE
Implement probabilities predictions for Java API

### ISSUE THREAD

**Issue by fshabashev** [VowpalWabbit/vowpal_wabbit#2614]
## Short description
Java API doesn't support probabilities predictions currently. 
It can only predict classes. 

## **How this suggestion will help you/others**

Predicting probabilities is a useful feature, but Java API doesn't support that currently. 

## **Possible solution/implementation details**

Should be quite straightforward

**Comment by lalo** [comment]
This is supported, unless I'm missing something with the terminology. Let me know if this is not what you were expecting.

https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/java/src/test/java/vowpalWabbit/learner/VWProbLearnerTest.java

and 

https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/java/src/main/java/vowpalWabbit/learner/VWLearners.java#L49

**Comment by fshabashev** [comment]
forgot to mention I was actually speaking of VWMulticlassLearner

**Comment by fshabashev** [comment]
VWMulticlassLearner always returns Int, not a list of floats

https://github.com/fakeNetflix/indeedeng-repo-vowpal-wabbit-java/blob/3a9a92ac11a69d265656806e84bc9c05d138ef88/src/main/java/com/indeed/vw/wrapper/learner/VWMulticlassLearner.java

**Comment by lalo** [comment]
what about specifying both `--oaa --probabilities` like the following example: https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/java/src/test/java/vowpalWabbit/learner/VWScalarsLearnerTest.java#L32

feel free to share your VWLearners.create(...) statement.

**Comment by fshabashev** [comment]
model is imported like this:
`val trainedModel: VWMulticlassLearner = VWLearners.create(f"-i $modelLocalFile -t --quiet")`


and trained like that:
`vw data.txt  --passes 3 -c -k --oaa 873 -b 27  --probabilities -f model.vw`

**Comment by lalo** [comment]
can you try this to see if it works?
`VWScalarsLearner vw = VWLearners.create("--oaa 873 --probabilities -i $modelLocalFile -t --quiet ");`

**Comment by fshabashev** [comment]
works well, thank you!
I can add this example to the documentation, would it be useful?

**Comment by lalo** [comment]
yes, it would be good if you contribute this back to documentation :)

I do wonder if this is a bug, since that info should've been obtained from the model file (maybe?)

**Comment by lalo** [comment]
I've verified with the rest of the team and seems like this should also work like this 
`VWScalarsLearner vw = VWLearners.create("--probabilities -i $modelLocalFile -t --quiet ");` the --probabilities flag does not get persisted in the model since it's an output related flag (this is by design) so you have to enable it manually. --oaa should work without entering it again. Feel free to verify this.

**Comment by fshabashev** [comment]
yep, it works well for me

**Comment by fshabashev** [comment]
issue is resolved
