### ISSUE TITLE
[mac] daemon deprecated

### ISSUE THREAD

**Issue by lalo** [VowpalWabbit/vowpal_wabbit#2618]
https://github.com/VowpalWabbit/vowpal_wabbit/blob/19bf14e2a58eb6d73ffe09026da2463b12250e57/cluster/spanning_tree_main.cc#L38

we might use it in other places too

```
[  1%] Building CXX object cluster/CMakeFiles/spanning_tree.dir/spanning_tree_main.cc.o
/Users/runner/work/1/s/cluster/spanning_tree_main.cc:38:14: warning: 'daemon' is deprecated: first deprecated in macOS 10.5 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
    else if (daemon(1, 1))
             ^
/Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:292:6: note: 'daemon' has been explicitly marked deprecated here
int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
```

see any build results for more info https://dev.azure.com/vowpalwabbit/Vowpal%20Wabbit/_build/results?buildId=14934&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=35f53584-79fc-539f-463c-6471d0663a3a&l=68

**Comment by jackgerrits** [comment]
Daemon mode on MacOS is no longer supported. If this is an issue for an end user we can revisit how to handle this. A note has been added to a wiki to call this out too: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Daemon-example#running-vw-in-daemon-mode
