### ISSUE TITLE
"--dsjson --cb_explore_adf ..." in pyvw does not work properly

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#2653]
#### Describe the bug
 cb_explore_adf predict method for example with shared features and k actions always returns probability distribution over (k+1) choices (while it should be over k)

#### To Reproduce
1) predict

from vowpalwabbit import pyvw
 
vw = pyvw.vw('--cb_explore_adf --epsilon 0.2 --dsjson')
 
ex='{"_label_cost":-1.0,"_label_probability":0.5,"_label_Action":1,"_labelIndex":0,"o":[{"v":1.0,"EventId":"38cbf24f-70b2-4c76-aa0c-970d0c8d388e","ActionTaken":false}],"Timestamp":"2020-11-15T17:09:31.8350000Z","Version":"1","EventId":"38cbf24f-70b2-4c76-aa0c-970d0c8d388e","a":[1,2],"c":{ "GUser":{"id":"person5","major":"engineering","hobby":"hiking","favorite_character":"spock"}, "_multi": [ { "TAction":{"topic":"SkiConditions-VT"} }, { "TAction":{"topic":"HerbGarden"} } ] },"p":[0.5,0.5],"VWState":{"m":"N/A"}}\n'
 
vw.predict(ex)
 
 
>>
[0.3333333432674408, 0.3333333432674408, 0.3333333432674408]

 
2) learn-then-predict:

from vowpalwabbit import pyvw
 
vw = pyvw.vw('--cb_explore_adf --epsilon 0.2 --dsjson')
 
ex_l='{"_label_cost":-1.0,"_label_probability":0.5,"_label_Action":1,"_labelIndex":0,"o":[{"v":1.0,"EventId":"38cbf24f-70b2-4c76-aa0c-970d0c8d388e","ActionTaken":false}],"Timestamp":"2020-11-15T17:09:31.8350000Z","Version":"1","EventId":"38cbf24f-70b2-4c76-aa0c-970d0c8d388e","a":[1,2],"c":{ "GUser":{"id":"person5","major":"engineering","hobby":"hiking","favorite_character":"spock"}, "_multi": [ { "TAction":{"topic":"SkiConditions-VT"} }, { "TAction":{"topic":"HerbGarden"} } ] },"p":[0.5,0.5],"VWState":{"m":"N/A"}}\n'
 
vw.learn(ex_l)
 
ex_p='{"_label_cost":-1.0,"_label_probability":0.5,"_label_Action":1,"_labelIndex":0,"o":[{"v":1.0,"EventId":"38cbf24f-70b2-4c76-aa0c-970d0c8d388e","ActionTaken":false}],"Timestamp":"2020-11-15T17:09:31.8350000Z","Version":"1","EventId":"38cbf24f-70b2-4c76-aa0c-970d0c8d388e","a":[1,2],"c":{ "GUser":{"id":"person5","major":"engineering","hobby":"hiking","favorite_character":"spock"}, "_multi": [ { "TAction":{"topic":"SkiConditions-VT"} }, { "TAction":{"topic":"HerbGarden"} } ] },"p":[0.5,0.5],"VWState":{"m":"N/A"}}\n'
 
vw.predict(ex_p)
 
>>
[0.8666666746139526, 0.06666667014360428, 0.06666667014360428]

#### Expected behavior
Expected distributions should be [0.5, 0.5] in 1) and [0.9, 0.1] (or [0.1, 0.9]) in 2)
 
#### Observed Behavior
How did VW behave? Please include any stack trace, log messages or crash logs.

#### Environment
pyvw 8.8, 8.8.1, 8.9 - windows

**Comment by jackgerrits** [comment]
@ataymano I am not able to get this to reproduce anymore (I also hit this in the past), so I am not sure exactly how to get this bug to happen.

I've added a test for this in #2699. Could you take a look and see if that makes sense?

**Comment by ataymano** [comment]
hm, just double checked - now i see it being reproducible only for 8.8/8.8.1, but not in 8.9.0. Probably I had some caching issue before.
So it seems good now.
