### ISSUE TITLE
Some headers and Boost component requirements missing from 8.9.0 CMake install target

### ISSUE THREAD

**Issue by orktes** [VowpalWabbit/vowpal_wabbit#2669]
#### Describe the bug
https://github.com/VowpalWabbit/vowpal_wabbit/blob/8.9.0/vowpalwabbit/CMakeLists.txt#L24 (same in master) is missing at least `fast_pow10.h`, `reductions_fwd.h`, `json_utils.h` and `io/io_adapter.h` so those headers wont be included/installed on `make install`.

#### To Reproduce
Build the shared library and try to
```c
 #include <vowpalwabbit/vw.h>
```

#### Expected behavior
Headers can be included without an issue

#### Observed Behavior
```
/usr/local/include/vowpalwabbit/parse_primitives.h:16:10: fatal error: fast_pow10.h: No such file or directory
 #include "fast_pow10.h"
          ^~~~~~~~~~~~~~
````

#### Environment
ubuntu:bionic docker container with vowpal wabbit build from "8.9.0" tag

**Comment by orktes** [comment]
Seems that https://github.com/VowpalWabbit/vowpal_wabbit/commit/c6164209d082acce095f7296d23ce3e45b1c9110 also creates a regression where Boost::program will no longer be included in the created pc file for libvw

**Comment by jackgerrits** [comment]
Thanks for picking up on this
