### ISSUE TITLE
CCB inverthash/readable model should display slot interactions

### ISSUE THREAD

**Issue by slahabar** [VowpalWabbit/vowpal_wabbit#2672]
#### Describe the bug
For CCB data, invert hash only contains slot features, but no slot interactions.
For CCB model, generating readable model only contains slot features, but no slot interactions.

#### To Reproduce
1. Generate CCB data similar to below, slots contain some slot features:
{"Timestamp":"2020-11-28T22:47:53.8640000Z","Version":"1","c":{ "GUser":{"id":"mk","major":"psychology","hobby":"kids","favorite_character":"7of9"}, "_multi": [ { "TAction":{"topic":"SkiConditions-VT"} }, { "TAction":{"topic":"HerbGarden"} }, { "TAction":{"topic":"BeyBlades"} }, { "TAction":{"topic":"NYCLiving"} }, { "TAction":{"topic":"MachineLearning"} } ], "_slots": [ { "size":"large"}, { "size":"medium"}, { "size":"small"}]  },"_outcomes":[{"_label_cost":-0.0,"_id":"b9b22788-3906-4078-a02c-131cab0c3d98_0","_a":[0,1,2,3,4],"_p":[1.0,0.0,0.0,0.0,0.0],"_o":[{"v":0.0,"EventId":"b9b22788-3906-4078-a02c-131cab0c3d98","Index":"0","ActionTaken":false}]},{"_label_cost":-1.0,"_id":"b9b22788-3906-4078-a02c-131cab0c3d98_1","_a":[1,2,3,4],"_p":[1.0,0.0,0.0,0.0],"_o":[{"v":1.0,"EventId":"b9b22788-3906-4078-a02c-131cab0c3d98","Index":"1","ActionTaken":false}]},{"_label_cost":-0.0,"_id":"b9b22788-3906-4078-a02c-131cab0c3d98_2","_a":[2,3,4],"_p":[1.0,0.0,0.0],"_o":[{"v":0.0,"EventId":"b9b22788-3906-4078-a02c-131cab0c3d98","Index":"2","ActionTaken":false}]}],"VWState":{"m":"N/A"}}

2. Run the following command to create invert hash file from log
vw --ccb_explore_adf --epsilon 0.2 --power_t 0 -l 0.001 --cb_type mtr -q :: --dsjson --data ccbdatafile.json --quite --invert_hash -f inverthashdatafile.txt

inverthashdatafile.txt only contains below features for slots but no interactions with context or actions. 
		"sizemedium"
 		"sizelarge",
		"sizesmall"

3. Run the following command to create a readable model from ccb model
vw --ccb_explore_adf --epsilon 0.2 --power_t 0 -l 0.001 --cb_type mtr -q :: --dsjson --data ccbdatafile.json --quite --readable_model -i ccbdatamodel -f readablemodelfile.txt

readablemodelfile.txt only contains below features for slots but not interactions with context or actions. 
		"sizemedium"
 		"sizelarge",
		"sizesmall"

#### Expected behavior
Expected to see interactions for slot features with actions/context features. 
Similar to below, from the same file.
"GUser^majorpsychology**",
"GUser^majorpsychology*TAction^topicHerbGarden",

#### Observed Behavior
There was no error or log message.

#### Environment
What version of VW did you use?
VW 8.8.1 on windows with python language

**Comment by olgavrou** [comment]
I'll take a look
