### ISSUE TITLE
Execution should fail gracefully when # slots > # actions in CCB call in debug mode

### ISSUE THREAD

**Issue by SchuylerGoodman** [VowpalWabbit/vowpal_wabbit#2675]
https://github.com/VowpalWabbit/vowpal_wabbit/blob/3f5793d9920fdff44f674cd4252180411da1cff5/vowpalwabbit/conditional_contextual_bandit.cc#L113-L120

In debug mode, when the number of slots input to CCB exceeds the number of actions, execution logs the issue to `cerr` in and exits `learn_and_predict`. This results in an unallocated `action_ids` array later in [rl::fb_serializer](https://github.com/VowpalWabbit/reinforcement_learning/blob/82e74e122c6ff44046dbe1e94333894278738b19/rlclientlib/serialization/fb_serializer.h#L134), which causes a crash.

**Comment by ataymano** [comment]
Yes, have to be fixed.

**Comment by ataymano** [comment]
Although, looks like there are 2 issues here:
- bad error handling inside vw
- bad error handling inside rlclientlib (although I am not sure yet why is it unallocated, it seems to be just empty)

**Comment by jackgerrits** [comment]
Ill handle reporting the error in VW
