### ISSUE TITLE
Inconsistent prediction usage in cs_active

### ISSUE THREAD

**Issue by peterychang** [VowpalWabbit/vowpal_wabbit#2681]
cs_active currently uses the prediction in an inconsistent way.
There are 3 elements of the prediction that are used
[scalar](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/cs_active.cc#L169) as an input
[multilabels](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/cs_active.cc#L269) as an output
[multiclass](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/cs_active.cc#L298) as an output

It appears the multilabels usage is incorrect as the union is never initialized as a v_array and would still be a scalar at that point in time

**Comment by jackgerrits** [comment]
The multiclass usage is the proper usage of prediction.

However, the multilabels usage is a hack for search. It allows the search reduction to dig out which labels need more queries as can be seen in the commit which added it https://github.com/VowpalWabbit/vowpal_wabbit/commit/989cde76a683e7d0102e42544137a43107653b09.

It is not clear to me the best way to fix this. Either we can enrich the prediction type to include this information but then we are probably going to break something we are not aware of which is using the return value. Or, we can add an escape hatch to all to allow search to dig this value out. This is less risky but still a poor design.

**Comment by jackgerrits** [comment]
It uses the `scalar` from a predict call internally, so I don't think it fits with reduction_features
