### ISSUE TITLE
Predictions for cb data and cb data transformed to single slot ccb should match.

### ISSUE THREAD

**Issue by slahabar** [VowpalWabbit/vowpal_wabbit#2685]
#### Describe the bug
Predictions from cb data converted to single slot ccb data gives different values with ccb_explore_adf. 

#### To Reproduce
1. Run CB format data file cb.json 
./vw.exe --ccb_explore_adf --epsilon 0 --power_t 0 -l 0.001 --cb_type mtr -q :: --dsjson -d cb.json -p cb.pred

2. Transform CB format cb.json to single slot ccb format file ccb_0index.json
./vw.exe --ccb_explore_adf --epsilon 0 --power_t 0 -l 0.001 --cb_type mtr -q :: --dsjson -d ccb_0index.json -p cb_0index.pred

cb.pred and cb_0index.pred have different predictions.

**cb.json example**
{"_label_cost":-0.0,"_label_probability":0.20000000298023224,"_label_Action":1,"_labelIndex":0,"o":[{"v":0.0,"EventId":"00c5870e-951b-41d7-b34e-b82a68979fc4","ActionTaken":false}],"Timestamp":"2020-11-28T00:04:25.2770000Z","Version":"1","EventId":"00c5870e-951b-41d7-b34e-b82a68979fc4","a":[**1,2,3,4,5**],"c":{ "GUser":{"id":"mk","major":"psychology","hobby":"kids","favorite_character":"7of9"}, "_multi": [ { "TAction":{"topic":"SkiConditions-VT"} }, { "TAction":{"topic":"HerbGarden"} }, { "TAction":{"topic":"BeyBlades"} }, { "TAction":{"topic":"NYCLiving"} }, { "TAction":{"topic":"MachineLearning"} } ] },"p":[0.2,0.2,0.2,0.2,0.2],"VWState":{"m":"N/A"},"_original_label_cost":-0.0}
 
**ccb_0index.json example** 
{"Timestamp":"2020-11-28T00:04:25.2770000Z","Version":"1","c":{"GUser":{"id":"mk","major":"psychology","hobby":"kids","favorite_character":"7of9"},"_multi":[{"TAction":{"topic":"SkiConditions-VT"}},{"TAction":{"topic":"HerbGarden"}},{"TAction":{"topic":"BeyBlades"}},{"TAction":{"topic":"NYCLiving"}},{"TAction":{"topic":"MachineLearning"}}],"_slots":[{}]},"_outcomes":[{"_label_cost":-0.0,"_id":"00c5870e-951b-41d7-b34e-b82a68979fc4_0","_a":[**0,1,2,3,4**],"_p":[0.2,0.2,0.2,0.2,0.2],"_o":[{"v":0.0,"EventId":"00c5870e-951b-41d7-b34e-b82a68979fc4","Index":"0","ActionTaken":false}]}],"VWState":{"m":"N/A"}}

Interestingly, if the ccb format indexes start with 1 the predictions are same (evaluations run into error because index is off by 1 here). 
./vw.exe --ccb_explore_adf --epsilon 0 --power_t 0 -l 0.001 --cb_type mtr -q :: --dsjson -d ccb_1index.json -p cb_1index.pred

ccb_1index.json example
{"Timestamp":"2020-11-28T00:04:25.2770000Z","Version":"1","c":{"GUser":{"id":"mk","major":"psychology","hobby":"kids","favorite_character":"7of9"},"_multi":[{"TAction":{"topic":"SkiConditions-VT"}},{"TAction":{"topic":"HerbGarden"}},{"TAction":{"topic":"BeyBlades"}},{"TAction":{"topic":"NYCLiving"}},{"TAction":{"topic":"MachineLearning"}}],"_slots":[{}]},"_outcomes":[{"_label_cost":-0.0,"_id":"00c5870e-951b-41d7-b34e-b82a68979fc4_0","_a":[**1,2,3,4,5**],"_p":[0.2,0.2,0.2,0.2,0.2],"_o":[{"v":0.0,"EventId":"00c5870e-951b-41d7-b34e-b82a68979fc4","Index":"0","ActionTaken":false}]}],"VWState":{"m":"N/A"}}

cb.pred and cb_1index.pred match exactly. 
cb.pred and cb_0index.pred are very different.

#### Expected behavior
Expected cb.pred and cb_0index.pred to match. i.e., cb json and single slot ccb (with 0 index) behaves exactly same. 

#### Observed Behavior
Plots of loss_per_example from cb data fed into cb reduction vs ccb reduction do not converge as well. 

#### Environment
What version of VW did you use?
What OS or language did you use?

VW 8.8.1 on windows with python language

**Comment by ataymano** [comment]
#2689

**Comment by olgavrou** [comment]
Closing this as the related PR has been merged. Feel free to re-open if the problem persists
