### ISSUE TITLE
LBFGS is broken

### ISSUE THREAD

**Issue by kroburg** [VowpalWabbit/vowpal_wabbit#2745]
Hi!

I believe this change breaks lbfgs:

https://github.com/VowpalWabbit/vowpal_wabbit/commit/ef13913af2f06f7bc4e5c609ae8f3fa96d57cd6b#diff-734f84d3a7f4280dd78e794ac1e9983b6d1b585039f300d4c294adfaadac8702L441

**Comment by lokitoth** [comment]
Hi @kroburg, thanks for looking at this. Could you expand a bit about what broken behaviour you are observing with LBFGS? In other words: Are you seeing a crash? Is there an issue with the learning?

**Comment by kroburg** [comment]
> Hi @kroburg, thanks for looking at this. Could you expand a bit about what broken behaviour you are observing with LBFGS? In other words: Are you seeing a crash? Is there an issue with the learning? As well, what is the environment / code version you are using?

Hi!

This is a learning issue. I'm using version from year ~2015 (may be older. I don't known exact revision, it is just commited by someone many years ago) and it works great. But any "recent" version from github fails to compete and learn to significantly worse loss (on some datasets).

So after some research I found that commit from 2016. I think it should be
if (infpattern((&(*w))[W_COND]) || (&(*w))[W_COND] >max_precond)
instead of 
if (infpattern(*w) || *w >max_precond)

**Comment by JohnLangford** [comment]
This was part of work to abstract the definition of the weights so that both dense and sparse weights could be supported (via a flag).  Hence, any change in what happens (even an order of operations change) is an error.   Apparently, we did not have the right tests in place here.

**Comment by bassmang** [comment]
Hi @kroburg we've just fixed this bug, please let us know if you are still running into a similar issue.
