### ISSUE TITLE
 C# binding library for linux

### ISSUE THREAD

**Issue by pardont** [VowpalWabbit/vowpal_wabbit#2764]
Is it possible to get the C# binding library to run on Linux?  more and more c# server app run on linux now.

**Comment by jackgerrits** [comment]
The current bindings are implemented with C++/CLI and so won't work on Linux. We're planning on replatforming onto a C API and use core, but this work is a ways out.

**Comment by pardont** [comment]
Great, may be a .NET5 package? 
is it possible to  support arm and win32?

**Comment by lalo** [comment]
arm support is being tracked here https://github.com/VowpalWabbit/vowpal_wabbit/issues/2284

**Comment by pardont** [comment]
I built a win32 version. 
1.  vw_unit_test all tests SUCCESS
2.  cs_unittest some test FAILED,  such as:

>  CommandLine_Test132
   Source: RunTests.cs line 2057
   Duration: 468 ms
  Message: 
    Assert.Fail Failed。3.79971694946289 vs 3.79753088951111: delta=0.00218605995178223 > Epsilon=0.0001: Prediction mismatch
  Stack Trace: 
    VWTestHelper.FuzzyEqual(Nullable`1 expected, Double actual, Double epsilon, String message) line 145
    RunTestsHelper.ExecuteTest(Int32 testCaseNr, String args, String input, String stderr, String predictFile) line 97
    RunTests.CommandLine_Test132() line 2058

**Comment by kumpera** [comment]
Linux support will come through bindings using dotnet core. 
The tracking issue is the following: https://github.com/VowpalWabbit/vowpal_wabbit/issues/2272

**Comment by jackgerrits** [comment]
Closing as completed via https://github.com/VowpalWabbit/vowpal_wabbit/pull/3969
