### ISSUE TITLE
[ci] use ccache to speed up CI builds

### ISSUE THREAD

**Issue by lalo** [VowpalWabbit/vowpal_wabbit#2773]
- [x] add ccache to docker image
- [ ] dockerfile specify ccache volume
- [ ] enable cache in .pipelines/
- [ ] add ccache flag to cmake

**Comment by jackgerrits** [comment]
Is the intention to cache (pipeline caching) the ccache cache between runs?

**Comment by lalo** [comment]
yes

**Comment by lalo** [comment]
just realized windows is the only slow one, this might not be required
