### ISSUE TITLE
ccb_explore_adf: missing newline at end of file throws memory errors if --passes > 1

### ISSUE THREAD

**Issue by maxpagels** [VowpalWabbit/vowpal_wabbit#2782]
#### Describe the bug
Leaving out a newline at the end of a ccb dataset causes memory-related errors to be thrown is passes > 1

#### To Reproduce

Download 
[test.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/5831429/test.txt) (note that the end of the file has two line returns i.e. one blank line).

1. Run `vw --ccb_explore_adf -d test.txt --passes 10 -c -k`

#### Expected behavior
Normal progress printout, possibly skipping learning on the very last example if ambiguous where one example begins and another ends.

#### Observed Behavior
```
vw --ccb_explore_adf -d test.txt --passes 10 -c -k
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = test.txt.cache
Reading datafile = test.txt
num sources = 1
Enabled reductions: gd, scorer, csoaa_ldf, cb_adf, cb_explore_adf_greedy, cb_sample, shared_feature_merger, ccb_explore_adf
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0  0:0,1:0      0,1       18
0.000000 0.000000            2            2.0  0:0,1:0      0,1       18
0.000000 0.000000            4            4.0  0:0,1:0      0,1       18
0.000000 0.000000            8            8.0  0:0,1:0      0,1       18
0.000000 0.000000           16           16.0  0:0,1:0      0,1       18
0.000000 0.000000           32           32.0  0:0,1:0      0,1       18 h
0.000000 0.000000           64           64.0  0:0,1:0      0,1       18 h

finished run
number of examples per pass = 18
passes used = 4
weighted example sum = 72.000000
weighted label sum = 0.000000
average loss = 0.000000 h
total feature number = 1350
vw(31122,0x10bc4ae00) malloc: *** error for object 0x7fc39e40d2e0: pointer being freed was not allocated
vw(31122,0x10bc4ae00) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
#### Environment
VW version: 8.9.0
OS: Mac Big Sur, CLI version of VW

**Comment by olgavrou** [comment]
Hi @maxpagels 

This is not actually a bug but I am guessing the result of unclear documentation. Downloading and opening the file it looks like the last multiline example does not have an extra newline at the end. Internally VW distinguishes the end of a multiline example by creating an empty internal example where the newline is read. If that happens to coincide with the end of the file then it will stop parsing the file and VW will omit the last empty-example, causing memory errors. I believe that if you add another line at the end of the file this will not happen. I will update the documentation.

**Comment by maxpagels** [comment]
Yeah, it doesn't happen if you add an addition newline, was just wondering if this error is the most graceful way of informing the user that there is a newline missing.

**Comment by maxpagels** [comment]
Feel free to close if not considered an issue.

**Comment by olgavrou** [comment]
You raise a good point so I will leave this open a bit longer. Documentation updated

**Comment by jackgerrits** [comment]
This has been a bit of a nasty gotcha for a while. The lib really should be able to handle this but it's a bit tricky to make work with how it's structured now.
