### ISSUE TITLE
Compatibility with M1 Macbook

### ISSUE THREAD

**Issue by ClementeOcejo** [VowpalWabbit/vowpal_wabbit#2785]
When I try to run an example training file through the debugger in clion, I am quickly met with EXC_ BAD_ACCESS errors from the assembly code. I assume this is because of the different chip architecture but am unsure how to get around this, since the library seems to run fine when I am not debugging I figure there must be a way.
Thanks!

**Comment by ClementeOcejo** [comment]
I recloned the library with new dependencies installed and now when I attempt to build I get this:
`ld: warning: ignoring file /usr/local/lib/libboost_program_options-mt.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "boost::program_options::validators::check_first_occurrence(boost::any const&)", referenced from:
      void boost::program_options::validate<unsigned int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, unsigned int*, long) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, int*, long) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<unsigned long, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, unsigned long*, long) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<unsigned long long, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, unsigned long long*, long) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<long long, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, long long*, long) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<float, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, float*, long) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<double, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, double*, long) in libvw.a(options_boost_po.cc.o)
      ...
  "boost::program_options::to_internal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > boost::program_options::to_internal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in libvw.a(parse_args.cc.o)
      std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > boost::program_options::to_internal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::variables_map::variables_map()", referenced from:
      VW::config::options_boost_po::add_and_parse(VW::config::option_group_definition const&) in libvw.a(options_boost_po.cc.o)
      VW::config::options_boost_po::get_positional_tokens() const in libvw.a(options_boost_po.cc.o)
  "boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::options_description::add_options()", referenced from:
      VW::config::options_boost_po::get_positional_tokens() const in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<unsigned int>(std::__1::shared_ptr<VW::config::typed_option<unsigned int> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<int>(std::__1::shared_ptr<VW::config::typed_option<int> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<unsigned long>(std::__1::shared_ptr<VW::config::typed_option<unsigned long> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<unsigned long long>(std::__1::shared_ptr<VW::config::typed_option<unsigned long long> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<long long>(std::__1::shared_ptr<VW::config::typed_option<long long> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<float>(std::__1::shared_ptr<VW::config::typed_option<float> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      ...
  "boost::program_options::options_description::m_default_line_length", referenced from:
      VW::config::options_boost_po::options_boost_po(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in main.cc.o
      merge_options_from_header_strings(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, VW::config::options_i&) in libvw.a(parse_args.cc.o)
      VW::config::options_boost_po::options_boost_po(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in libvw.a(parse_args.cc.o)
      VW::config::options_boost_po::add_and_parse(VW::config::option_group_definition const&) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::options_description::options_description(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, unsigned int)", referenced from:
      merge_options_from_header_strings(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, VW::config::options_i&) in libvw.a(parse_args.cc.o)
      VW::config::options_boost_po::add_and_parse(VW::config::option_group_definition const&) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::options_description::options_description(unsigned int, unsigned int)", referenced from:
      VW::config::options_boost_po::options_boost_po(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in main.cc.o
      VW::config::options_boost_po::options_boost_po(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in libvw.a(parse_args.cc.o)
  "boost::program_options::invalid_option_value::invalid_option_value(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      void boost::program_options::validate<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*, int) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<bool, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<bool, std::__1::allocator<bool> >*, int) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<unsigned int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >*, int) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<unsigned int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, unsigned int*, long) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<int, std::__1::allocator<int> >*, int) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, int*, long) in libvw.a(options_boost_po.cc.o)
      void boost::program_options::validate<unsigned long, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >*, int) in libvw.a(options_boost_po.cc.o)
      ...
  "boost::program_options::error_with_option_name::error_with_option_name(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)", referenced from:
      VW::config::options_boost_po::get_positional_tokens() const in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<unsigned int>(std::__1::shared_ptr<VW::config::typed_option<unsigned int> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<int>(std::__1::shared_ptr<VW::config::typed_option<int> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<unsigned long>(std::__1::shared_ptr<VW::config::typed_option<unsigned long> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<unsigned long long>(std::__1::shared_ptr<VW::config::typed_option<unsigned long long> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<long long>(std::__1::shared_ptr<VW::config::typed_option<long long> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      void VW::config::options_boost_po::add_to_description<float>(std::__1::shared_ptr<VW::config::typed_option<float> >, boost::program_options::options_description&) in libvw.a(options_boost_po.cc.o)
      ...
  "boost::program_options::positional_options_description::add(char const*, int)", referenced from:
      VW::config::options_boost_po::get_positional_tokens() const in libvw.a(options_boost_po.cc.o)
  "boost::program_options::positional_options_description::positional_options_description()", referenced from:
      VW::config::options_boost_po::get_positional_tokens() const in libvw.a(options_boost_po.cc.o)
  "boost::program_options::arg", referenced from:
      boost::program_options::typed_value<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, char>::name() const in libvw.a(options_boost_po.cc.o)
      boost::program_options::typed_value<std::__1::vector<bool, std::__1::allocator<bool> >, char>::name() const in libvw.a(options_boost_po.cc.o)
      boost::program_options::typed_value<std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >, char>::name() const in libvw.a(options_boost_po.cc.o)
      boost::program_options::typed_value<std::__1::vector<int, std::__1::allocator<int> >, char>::name() const in libvw.a(options_boost_po.cc.o)
      boost::program_options::typed_value<std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >, char>::name() const in libvw.a(options_boost_po.cc.o)
      boost::program_options::typed_value<std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >, char>::name() const in libvw.a(options_boost_po.cc.o)
      boost::program_options::typed_value<std::__1::vector<long long, std::__1::allocator<long long> >, char>::name() const in libvw.a(options_boost_po.cc.o)
      ...
  "boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool)", referenced from:
      VW::config::options_boost_po::add_and_parse(VW::config::option_group_definition const&) in libvw.a(options_boost_po.cc.o)
      VW::config::options_boost_po::get_positional_tokens() const in libvw.a(options_boost_po.cc.o)
  "boost::program_options::detail::cmdline::allow_unregistered()", referenced from:
      boost::program_options::basic_command_line_parser<char>::allow_unregistered() in libvw.a(parse_args.cc.o)
      boost::program_options::basic_command_line_parser<char>::allow_unregistered() in libvw.a(options_boost_po.cc.o)
  "boost::program_options::detail::cmdline::set_positional_options(boost::program_options::positional_options_description const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::positional(boost::program_options::positional_options_description const&) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::detail::cmdline::set_options_description(boost::program_options::options_description const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::options(boost::program_options::options_description const&) in libvw.a(parse_args.cc.o)
      boost::program_options::basic_command_line_parser<char>::options(boost::program_options::options_description const&) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::detail::cmdline::get_canonical_option_prefix()", referenced from:
      boost::program_options::basic_command_line_parser<char>::run() in libvw.a(parse_args.cc.o)
      boost::program_options::basic_command_line_parser<char>::run() in libvw.a(options_boost_po.cc.o)
  "boost::program_options::detail::cmdline::run()", referenced from:
      boost::program_options::basic_command_line_parser<char>::run() in libvw.a(parse_args.cc.o)
      boost::program_options::basic_command_line_parser<char>::run() in libvw.a(options_boost_po.cc.o)
  "boost::program_options::detail::cmdline::style(int)", referenced from:
      boost::program_options::basic_command_line_parser<char>::style(int) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::detail::cmdline::cmdline(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in libvw.a(parse_args.cc.o)
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::notify(boost::program_options::variables_map&)", referenced from:
      VW::config::options_boost_po::add_and_parse(VW::config::option_group_definition const&) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::validate(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int)", referenced from:
      void boost::program_options::validate<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*, int) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::validate(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool*, int)", referenced from:
      void boost::program_options::validate<bool, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<bool, std::__1::allocator<bool> >*, int) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::options_description::print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, unsigned int) const", referenced from:
      VW::config::options_boost_po::add_and_parse(VW::config::option_group_definition const&) in libvw.a(options_boost_po.cc.o)
  "boost::program_options::abstract_variables_map::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      boost::program_options::variables_map::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libvw.a(options_boost_po.cc.o)
  "boost::program_options::error_with_option_name::substitute_placeholders(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for boost::wrapexcept<boost::program_options::invalid_option_value> in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::invalid_option_value in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::validation_error in libvw.a(options_boost_po.cc.o)
      vtable for boost::wrapexcept<boost::program_options::validation_error> in libvw.a(options_boost_po.cc.o)
  "boost::program_options::error_with_option_name::what() const", referenced from:
      vtable for boost::wrapexcept<boost::program_options::invalid_option_value> in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::invalid_option_value in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::validation_error in libvw.a(options_boost_po.cc.o)
      vtable for boost::wrapexcept<boost::program_options::validation_error> in libvw.a(options_boost_po.cc.o)
  "boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool) const", referenced from:
      vtable for boost::program_options::typed_value<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, char> in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::typed_value<std::__1::vector<bool, std::__1::allocator<bool> >, char> in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::typed_value<std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >, char> in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::typed_value<std::__1::vector<int, std::__1::allocator<int> >, char> in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::typed_value<std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >, char> in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::typed_value<std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >, char> in libvw.a(options_boost_po.cc.o)
      vtable for boost::program_options::typed_value<std::__1::vector<long long, std::__1::allocator<long long> >, char> in libvw.a(options_boost_po.cc.o)
      ...
  "typeinfo for boost::program_options::ambiguous_option", referenced from:
      GCC_except_table61 in libvw.a(options_boost_po.cc.o)
      typeinfo for boost::exception_detail::error_info_injector<boost::program_options::ambiguous_option> in libvw.a(options_boost_po.cc.o)
  "typeinfo for boost::program_options::error_with_option_name", referenced from:
      typeinfo for boost::program_options::validation_error in libvw.a(options_boost_po.cc.o)
  "typeinfo for boost::program_options::value_semantic_codecvt_helper<char>", referenced from:
      typeinfo for boost::program_options::typed_value<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, char> in libvw.a(options_boost_po.cc.o)
      typeinfo for boost::program_options::typed_value<std::__1::vector<bool, std::__1::allocator<bool> >, char> in libvw.a(options_boost_po.cc.o)
      typeinfo for boost::program_options::typed_value<std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >, char> in libvw.a(options_boost_po.cc.o)
      typeinfo for boost::program_options::typed_value<std::__1::vector<int, std::__1::allocator<int> >, char> in libvw.a(options_boost_po.cc.o)
      typeinfo for boost::program_options::typed_value<std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >, char> in libvw.a(options_boost_po.cc.o)
      typeinfo for boost::program_options::typed_value<std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >, char> in libvw.a(options_boost_po.cc.o)
      typeinfo for boost::program_options::typed_value<std::__1::vector<long long, std::__1::allocator<long long> >, char> in libvw.a(options_boost_po.cc.o)
      ...
  "vtable for boost::program_options::variables_map", referenced from:
      boost::program_options::variables_map::~variables_map() in libvw.a(options_boost_po.cc.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for boost::program_options::error_with_option_name", referenced from:
      boost::program_options::error_with_option_name::error_with_option_name(boost::program_options::error_with_option_name const&) in libvw.a(options_boost_po.cc.o)
      boost::program_options::error_with_option_name::~error_with_option_name() in libvw.a(options_boost_po.cc.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for boost::program_options::value_semantic_codecvt_helper<char>", referenced from:
      boost::program_options::value_semantic_codecvt_helper<char>::value_semantic_codecvt_helper() in libvw.a(options_boost_po.cc.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [vowpalwabbit/vw] Error 1
make[2]: *** [vowpalwabbit/CMakeFiles/vw-bin.dir/all] Error 2
make[1]: *** [vowpalwabbit/CMakeFiles/vw-bin.dir/rule] Error 2
make: *** [vw-bin] Error 2`

**Comment by lalo** [comment]
how are you installing boost? thanks for iterating on the arm build.

This also might be helpful for boost: https://github.com/faithfracture/Apple-Boost-BuildScript

related: https://github.com/VowpalWabbit/vowpal_wabbit/issues/2284

**Comment by ClementeOcejo** [comment]
installing boost using home-brew. It looks like the build fails like that when It try to build the library using the CLion built for the new m1 chip but when I use the intel-based CLion under Rosetta it allows me to build but does not allow me to use the debugger successfully.

**Comment by ClementeOcejo** [comment]
Update: I was able to build on the ARM CLIon by specifying CMAKE_OSX_ARCHITECTURES=x86_64. When I use the debugger now I reach here: 
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/35938632/105217412-d32e3000-5b21-11eb-873c-cdfaaacf4dd8.png">

**Comment by lalo** [comment]
Related https://github.com/Homebrew/homebrew-core/pull/72409

**Comment by jackgerrits** [comment]
There is an ARM bottle for the newly released 8.10.0. You should now be able to simply `brew install vowpal-wabbit`.

I suspect the issues you were seeing were due to mismatch between attempting to build for ARM but referencing x86 dependencies. Perhaps the brew packages for boost weren't quite ready at the time?

Please let me know and reopen if you are still having trouble on the M1 macbook
