### ISSUE TITLE
VowpalWabbit.data-science or module inside pyvw?

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#2786]
## Short description
There is some python code which helps to run vw binary in a way that is friendly for hyper parameter sweeps.
Example: https://github.com/VowpalWabbit/data-science/blob/master/from_mwt_ds/DataScience/getting_started.ipynb
Originally it supposed to be released as separate pip package, but maybe we should do it as module inside existing pyvw package.

Cons:
- it is in some sense orthogonal to pyvw since it is only about wrapping vw binaries

Pros:
- It is nice to have all vw-dependent tooling in one place.

**Comment by jackgerrits** [comment]
If we were to bundle it in pyvw then I feel like we would be forced to package the VW binary into the python package. This is probably not the worst thing, and people have asked for it before.

**Comment by lalo** [comment]
not sure why we need to package the binary here, best case scenario:

- this api (should) work with pyvw
- allow overriding using api with a custom binary set by a local location (user provides that binary)

the tooling that uses vw binary can live in its own submodule pyvw.binary_adapter or whatever, the rest of the code that is agnostic can be its own submodule

if we fix this:
https://github.com/VowpalWabbit/vowpal_wabbit/issues/2777
and using this:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/18e1dc8260ebaf33cfb771a4354fdd0a20684051/python/vowpalwabbit/pyvw.py#L613

**Comment by ataymano** [comment]
released as separate pip package with optional dependency on pyvw
