### ISSUE TITLE
Actions without features are not supported.

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#2793]
#### Describe the bug
Actions without features are not supported.

#### To Reproduce
Example:
1) {"_label_cost":-1.0,"_label_probability":0.5,"_label_Action":1,"_labelIndex":0,"Timestamp":"2020-12-08T23:25:52.1830000Z","Version":"1","event_id":"12","a":[0,1],"c":{"A":{"F":1.0},"_multi":[{"B": {"f":1}},{"B": {"f":1}}]},"p":[0.5,0.5],"VWState":{"m":"N/A"},"_original_label_cost":-0.0}

Command line: vw --cb_explore_adf --dsjson -d input.txt --ignore B -p pred.txt

2) {"_label_cost":-1.0,"_label_probability":0.5,"_label_Action":1,"_labelIndex":0,"Timestamp":"2020-12-08T23:25:52.1830000Z","Version":"1","event_id":"12","a":[0,1],"c":{"A":{"F":1.0},"_multi":[{},{}]},"p":[0.5,0.5],"VWState":{"m":"N/A"},"_original_label_cost":-0.0}

Command line:  vw --cb_explore_adf --dsjson -d input.txt -p pred.txt

#### Expected behavior
Although both scenarios do not make much sense from learning point of view, there is no much difference between them and having multiple actions with non-empty, but equal feature objects (which is handled correctly).
So it feels like this corner case (which could happen in real system with complex feature generation pipeline) should at least not violate contract about returning probability distribution over proper number of actions.

So prediction file should be:
0:0.5,1:0.5 
And that is what we see in case of "_multi":[{"f":1},{"f":1}]

#### Observed Behavior
In both cases pred.txt will have 0:1

#### Environment
VW 8.9 windows

**Comment by olgavrou** [comment]
@ataymano running this I get a critical error and failure `cb_adf: At least one action must be provided for an example to be valid.` from both cases.

**Comment by ataymano** [comment]
oh sorry, I believe description is incorrect. Let me fix it.

**Comment by ataymano** [comment]
Looks like severity of error message has changed - previously I was able to get N invalid prediction if I am providing N examples - and now I am seeing only one prediction before failure.

Here is updated bug description (dwould love to keep previous version for record in case if we want to track changes in error messages):

#### Describe the bug
Actions without non-zero features are not supported.

#### To Reproduce
Example:
1) {"_label_cost":-1.0,"_label_probability":0.5,"_label_Action":1,"_labelIndex":0,"Timestamp":"2020-12-08T23:25:52.1830000Z","Version":"1","event_id":"12","a":[0,1],"c":{"A":{"F":1.0},"_multi":[{"B": {"f":1}},{"B": {"f":1}}]},"p":[0.5,0.5],"VWState":{"m":"N/A"},"_original_label_cost":-0.0}

Command line: vw --cb_explore_adf --dsjson -d input.txt -p pred.txt
Execution is successful


1) {"_label_cost":-1.0,"_label_probability":0.5,"_label_Action":1,"_labelIndex":0,"Timestamp":"2020-12-08T23:25:52.1830000Z","Version":"1","event_id":"12","a":[0,1],"c":{"A":{"F":1.0},"_multi":[{"B": {"f":0}},{"B": {"f":0}}]},"p":[0.5,0.5],"VWState":{"m":"N/A"},"_original_label_cost":-0.0}

Command line: vw --cb_explore_adf --dsjson -d input.txt -p pred.txt
vw (shared_feature_merger.cc:40): cb_adf: At least one action must be provided for an example to be valid.

#### Expected behavior
Although both scenarios do not make much sense from learning point of view, there is no much difference between them and there is no reason for scenario 2 to be not supported.


#### Observed Behavior
In both cases pred.txt will have 0:1

#### Environment
VW 8.9 windows
