### ISSUE TITLE
Brew install still stuck with vw 8.8.1

### ISSUE THREAD

**Issue by pavithraks** [VowpalWabbit/vowpal_wabbit#2799]
Installing using homebrew results in installing vw 8.8.1. 

Environment
Mac OS

**Comment by lalo** [comment]
Not sure what is the process to update homebrew, but we probably need to update this file: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vowpal-wabbit.rb

**Comment by lalo** [comment]
related: https://github.com/Homebrew/homebrew-core/pull/70445

**Comment by lalo** [comment]
blocked until this PR CI's passes: https://github.com/VowpalWabbit/vowpal_wabbit/pull/2802

**Comment by lalo** [comment]
The fix is in master, but to get homebrew to update we need to release the next version 8.9.2

**Comment by lalo** [comment]
https://github.com/Homebrew/homebrew-core/pull/72409

**Comment by lalo** [comment]
Homebrew should now have 8.8.2 VW version available. See previous comment and reference to the homebrew PR.
