### ISSUE TITLE
[test] skipped flatbuffer test are shown as success in the printout

### ISSUE THREAD

**Issue by lalo** [VowpalWabbit/vowpal_wabbit#2804]
The test that are skipped using the python runtest driver are shown as successfully ran when they should be reported as skipped. 

See any of the skipped tests and verify with the output: https://github.com/VowpalWabbit/vowpal_wabbit/blob/cb37da4553c475b4d563e22f43194adc8f127cd2/test/run_tests.py#L521

**Comment by olgavrou** [comment]
Yeah that means that they ran but as they were, not with the flatbuffer conversion.

Might be better to say they are not converted instead of saying that they are skipped (or actually skip them)

**Comment by lalo** [comment]
True, but right now its a bit misleading since they are ran under the 'flatbuffer' job
