### ISSUE TITLE
Proposal: Extended metrics

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2805]
When consuming VW DSJSON logs there are extra pieces of information/metrics that would be useful to be able to extract from the data. We need to add support for these new metrics as well as getting at existing metrics in a machine readable format.

## Extended required metrics
```C++
// The ID of the event in the cooked logs that has the
// earliest time.
string FirstEventId;

// The ID of the event in the cooked logs that has the
// latest time.
string LastEventId;

// The earliest event time.
DateTime FirstEventTime;

// The latest event time.
DateTime LastEventTime;

// The number of entries present in the cooked logs.
// This includes events as well as other entities
// like dangling observations.
long NumberOfCookedLogEntries;

// The number of events present in the cooked logs.
// This includes events that may not be used for learning.
long NumberOfEvents;

// The number of events present in the cooked logs that are used for learning.
// Does not include events that are skipped.
long NumberOfLearnedEvents;

// The number of events in the cooked logs that are skipped for learning.
long NumberOfSkippedEvents;

// The number of events in the cooked logs that are faulty or have an error.
long NumberOfFaultyEvents;

// The number of dangling observations present in the log.
// Dangling observations are not considered events.
long NumberOfDanglingObservations;

// The number of events learned where the first/baseline action was the chosen action.
// Does not include events that are skipped.
long NumberOfLearnedEventsWithBaselineActionChosen;

// The number of events learned where the first/baseline action was not the chosen action.
// Does not include events that are skipped.
long NumberOfLearnedEventsWithBaselineActionNotChosen;

// They number of rewards for events used for learning.
// Does not include skipped events or dangling rewards.
long NumberOfLearnedRewards;

// Sum of rewards for events that were used for learning.
// Does not included skipped events or dangling observations.
float SumOfLearnedRewards;

// Sum of rewards for events where the chosen action is the first/baseline action.
// Does not included skipped events or dangling observations.
float SumOfLearnedRewardsWithBaselineActionChosen;

long NumberOfFeatures;
long NumberOfNamespaces;
long NumberOfActions;
```

These required metrics are considerably more involved than what the VW parser has done up until this point. There has been some affordance for extra info to produced with the `DecisionServiceInteraction` type that only DSJson produces. However, with the addition of Flatbuffer formats the usage of this must be generalised.

Almost all of these metrics are produced by the parser directly. However, some metrics must be produced as part of the output sequence and additionally they require extra information in the baseline actions sequence.

## Existing metrics
VW has metrics that already exist and are outputted:
```
number of examples per pass
passes used
weighted example sum
weighted label sum
average loss
best constant
total feature number
```

Overlap: `number of examples per pass`, `total feature number`

We should merge the existing metrics system with the proposed new metrics to ensure consistency.

### Collection locations
Optional metrics output step that can be hooked into in several places:
- During parsing (parser impl dependent)
    - Required for `FirstEventId`,`LastEventId`,`FirstEventTime`,`LastEventTime``NumberOfCookedLogEntries`, `NumberOfEvents`, `NumberOfSkippedEvents`, `NumberOfFaultyEvents`, `NumberOfDanglingObservations`
- After parsing (generic)
    - `NumberOfLearnedEvents`, `NumberOfFeatures`, `NumberOfNamespaces`
- After parsing (CB label type dependent)
    - `NumberOfLearnedRewards`, `SumOfLearnedRewards`, `NumberOfActions`
- During output_example (reduction dependent)
    - `NumberOfLearnedEventsWithBaselineActionChosen`, `NumberOfLearnedEventsWithBaselineActionNotChosen`, `SumOfLearnedRewardsWithBaselineActionChosen`

`NumberOfFaultyEvents` can potentially be upleveled into the generic after parsing step if we can properly signal errors.

Should the metric output not be turned on then the collection can be skipped

### Options

`--metrics_file <file>`
This will write the existing metrics VW already collects to a JSON file.

`--extended_metrics`
This will turn on the additional set of metrics proposed in this design. It requires `--metrics_file` to be turned on.

## Open questions
1. Current VW metrics are values that are synced during all reduce. Do these values participate in that?

**Comment by kumpera** [comment]
I think we should investigate using standard telemetry tools and formats instead of creating something entirely new.

**Comment by jackgerrits** [comment]
Sounds good to me. Do you have anything in mind?

**Comment by kumpera** [comment]
Yes, we should look into open telemetry.

**Comment by kumpera** [comment]
or https://opentracing.io/ as well

**Comment by jackgerrits** [comment]
This isn't really telemetry though. It is characteristics of the dataset for the most part

**Comment by kumpera** [comment]
if the goal is to produce some summary statistics of the dataset, this can be done outside of VW and I don't get why we're adding this at all.

**Comment by jackgerrits** [comment]
This is certainly a good point and something I agree with. 

There are a couple which depend on the results of the learning process. However, these could be calculated with the prediction files as well.

I would strongly be in favour of an external tool for fulfilling this requirement too then

**Comment by rajan-chari** [comment]
Doing two passes on the input file doubles the throughput cost.   There are situations where this is a very high cost to pay.
