### ISSUE TITLE
Search Neighbor Features locking/crashing vw process

### ISSUE THREAD

**Issue by dvbarnes** [VowpalWabbit/vowpal_wabbit#2810]
#### Describe the bug
I'm attempting to do learning 2 search with vw on verion 8.9.0 but when I pass in the --search_neighbor_features as the parameter it locks the process and after a bit runs out of memory.

#### To Reproduce

`vw -k -c -d train.vw --passes 2 --search_rollout ref --search_alpha 1e-8 --search_task sequence --search 5 --holdout_off -f model.vw --search_neighbor_features -3:w,-2:w,-1:w,1:w,2:w,3:w,-3:e,-2:e,-1:e,1:e,2:e,3:e,-3:s,-2:s,-1:s,1:s,2:s,3:s`

I did try to pull back params to see if any combo was causing this issue, but it seems adding the --search_neighbor_features is what's causing vw to crash.

#### Expected behavior
When doing this on older versions of vw it doesn't seem to cause issues

#### Observed Behavior
No crash logs that I could find.

#### Environment
What version of VW did you use?
- 8.9.0 (git commit: 58c3a8949) (cli)
- C# binding on same version seems to fail as well

What OS or language did you use?
- ubuntu 18.04.5 LTS (cli)
- Windows 10 for C# binding

#### Additional context
This was working on 8.5 for cli but causing issues with the C# binding no matter what version of the C# binding I use.

**Comment by jackgerrits** [comment]
Looks like this option wasn't covered by tests and was broken in a refactor. I've added a test to cover it and fixed it in this PR #2811. If you're able to build from source let me know if this unblocks you. Otherwise it will be in the next release.
