### ISSUE TITLE
AttributeError: 'vw' object has no attribute 'finished'

### ISSUE THREAD

**Issue by JuiP** [VowpalWabbit/vowpal_wabbit#2820]
#### Traceback:
```Exception ignored in: <bound method vw.__del__ of <vowpalwabbit.pyvw.vw object at 0x7fbd0e2caea0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/vowpalwabbit/pyvw.py", line 516, in __del__
    self.finish()
  File "/usr/local/lib/python3.6/dist-packages/vowpalwabbit/pyvw.py", line 482, in finish
    if not self.finished:
AttributeError: 'vw' object has no attribute 'finished'
```

#### How to Reproduce
I am not sure what caused it, it just happened once. I tried investigating the cause; looked at the source code [here](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/vowpalwabbit/pyvw.py) but no progress.
My guess is it is a race condition.

#### Environment
Version of vw: `8.9.0`
I was using the python wrapper in jupyter notebook (OS: Ubuntu 18.04)

**Comment by jackgerrits** [comment]
What code did you run to cause this?

**Comment by JuiP** [comment]
This is the code I was repeatedly executing with different exploration algorithms and parameters. Like I mentioned before, it happened once and on re-executing it worked with no tracebacks.

```# Instantiate learner in VW
vw = pyvw.vw("--cb_explore_adf -q UA --quiet --epsilon 0.1")

num_iterations = 5000
ctr = run_simulation(vw, num_iterations, users, times_of_day, actions, get_cost)

plot_ctr(num_iterations, ctr)

**Comment by ataymano** [comment]
Got similar message on this yesterday. Way to reproduce.
```
try:
    _vw = pyvw.vw('--cb_explore_adf --epsilon 0.2 --some_unrecognized_option')
except Exception as e:
    print("Ignore exception")
```
Can take a look.

**Comment by ataymano** [comment]
It is clear why is it reproduced in my case, but the one reported seems different.
As long as init is successful, finished should be there.
If you see it next time, can you please:
1) check if it is reproducible without run_simulation / plot_ctr and with constructor only. By the way, is the snippet you shared wrapped into try/except?
2) maybe double check if there is any pyvw object construction/copying inside run_simulation?

**Comment by JuiP** [comment]
Hi @ataymano, thanks for looking at this issue.
Checked #2826, I think that should probably fix this.

> 1. check if it is reproducible without run_simulation / plot_ctr and with constructor only. By the way, is the snippet you shared wrapped into try/except?

Well that's queer but unfortunately, can't reproduce; tried multiple times. And no it is not wrapped into try/except block.

> 2. maybe double check if there is any pyvw object construction/copying inside run_simulation?

There is a call to `vw.parse(to_vw_example_format(context, actions, (action, cost, prob)),pyvw.vw.lContextualBandit)` inside run_simulation.

**Comment by jackgerrits** [comment]
Closing this as the PR is now merged.
