### ISSUE TITLE
Predictions not returned on-line

### ISSUE THREAD

**Issue by Venousek** [VowpalWabbit/vowpal_wabbit#2832]
#### Describe the bug
In latest version 8.9.x of VW, there seems to be a problem with returning predictions for every line of input as they come. Instead, a "batch" of predictions is returned to a file or `/dev/stdout` after undefined number of lines are written to input or when VW process is closed. Seems like some buffer is not flushed with every prediction. Version 8.8.1 does not have this problem and returns prediction right after a line is written to input, as can be shown by changing the version to 8.8.1 in reproduction Dockerfile. The Dockerfile contains a simple model example based on [this blog post](http://www.philippeadjiman.com/blog/2018/04/03/deep-dive-into-logistic-regression-part-3/).

#### To Reproduce
1. Create following `Dockefile` in a new folder:
```
FROM debian

WORKDIR /root

RUN apt-get update \
    && apt-get install -y libboost-dev libboost-thread-dev libboost-program-options-dev libboost-system-dev libboost-math-dev libboost-test-dev zlib1g-dev cmake g++ git wget unzip ipython3 \
    && wget https://github.com/google/flatbuffers/archive/v1.12.0.tar.gz \
    && tar -xzf v1.12.0.tar.gz \
    && cd flatbuffers-1.12.0 \
    && mkdir build_dir \
    && cd build_dir \
    && cmake -G "Unix Makefiles" -DFLATBUFFERS_BUILD_TESTS=Off -DFLATBUFFERS_INSTALL=On -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_BUILD_FLATHASH=Off .. \
    && make install -j$(nproc) \
    && cd /root \
    && git clone --depth 1 --branch 8.9.1 https://github.com/VowpalWabbit/vowpal_wabbit.git \
    && cd vowpal_wabbit \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j $(nproc) \
    && make install

ENV PATH=/usr/local/bin:$PATH

RUN wget www.philippeadjiman.com/blog/wp-content/uploads/2018/03/bankTrainingSet.zip \
    && unzip bankTrainingSet.zip \
    && vw train.vw -f model.vw --loss_function logistic

CMD ["/bin/bash"]
```
2. In this folder, build and run the docker:
```
docker pull debian && docker build -t vw_bug . && docker run -it vw_bug
```
3. Inside docker, run `ipython3` and run following code:
```
import subprocess

line = "-1 |i F0:58 F5:2143 F11:261 F12:1 F13:-1 F14:0 |c F1=management F2=married F3=tertiary F4=no F6=yes F8=unknown F9=5 F10=may F15=unknown"
vw_args = ['vw', '-p', 'predictions.txt', '-i', 'model.vw', '-t', '--link', 'logistic']
vw = subprocess.Popen(vw_args, stdin=subprocess.PIPE, stdout=None)

vw.stdin.write(bytes(line + "\n", 'utf-8'))
vw.stdin.flush()

! cat predictions.txt
! wc predictions.txt # no predictions written to the file

for _ in range(1000): vw.stdin.write(bytes(line + "\n", 'utf-8'))
vw.stdin.flush()
    
! cat predictions.txt
! wc predictions.txt # some predictions are written to file, not all of them

vw.stdin.close() # close the process

! cat predictions.txt
! wc predictions.txt # all 1001 predictions are written to file
```
4. The same problem appears when using `-p /dev/stdout` and trying to `vw.stdout.readline()` - it just hangs.

#### Expected behavior
A prediction is written to output after each line written to output. Can be achieved by switching version to 8.8.1 in Dockerfile.

#### Observed Behavior
Predictions are written to output after undefined number of lines written to input.

#### Environment
Latest Debian, VW 8.9.1.

#### Additional context
Using older version is not an option for me as I would like to use the cool new Probabilistic Label Tree feature, where this problem also appears. With the `rcv1x_2K` dataset from [PLT demo](https://github.com/VowpalWabbit/vowpal_wabbit/tree/master/demo/plt), with `--top_k 5`, I have to write 21 lines to get first 20 predictions.

**Comment by jackgerrits** [comment]
Hi @Venousek, thanks for the detailed report! I will look into this and get back to you.

**Comment by jackgerrits** [comment]
I ran some tests using both 8.8.1 and 8.9.1. I modified your code slightly to run without ipython:

```Python
import os
import subprocess
import time

def file_len(fname):
    try:
        return sum(1 for line in open(fname))
    except:
        return ""

os.remove("predictions.txt")

line = "-1 |i F0:58 F5:2143 F11:261 F12:1 F13:-1 F14:0 |c F1=management F2=married F3=tertiary F4=no F6=yes F8=unknown F9=5 F10=may F15=unknown"
vw_args = ['vowpalwabbit/vw', '-p', 'predictions.txt', '-i', 'model.vw', '-t', '--link', 'logistic', "--quiet"]
vw = subprocess.Popen(vw_args, stdin=subprocess.PIPE, stdout=None)

vw.stdin.write(bytes(line + "\n", 'utf-8'))
vw.stdin.flush()

print(f"1: {file_len('predictions.txt')}")

for _ in range(1000): vw.stdin.write(bytes(line + "\n", 'utf-8'))
vw.stdin.flush()

print(f"2: {file_len('predictions.txt')}")

vw.stdin.close() # close the process

print(f"3: {file_len('predictions.txt')}")

time.sleep(0.5)
print(f"4: {file_len('predictions.txt')}")
```

How many times did you run the test? Running this script several times, I notice inconsistency with both versions of VW. **This is expected** because there is no form of synchronization occurring and different hardware, environments, OSs etc will produce different results. After the stdin flush occurs VW still needs some amount of time to produce a result. The Python code asynchronously kicks off a VW process and periodically we poke at the file to see what's been put there so far. 

There is no minimum number of lines that must be processed. This can be witnessed by placing some tiny wait after the `print("1: ...` call and seeing that the predictions file contains 1 prediction.

I also went back and looked at the changes between the versions and as best I can tell, there was no flush removed for predictions. The writes are buffered by VW, so the only buffering that would occur is at the OS level.

`/dev/stdout` should work - but could you try just `-p stdout` and see if that resolves that particular issue?

**Comment by Venousek** [comment]
Thank you very much, @jackgerrits, for looking into this so quickly. I have probably better example of code that runs just fine with 8.8.1, but hangs with 8.9.1. To be run similarly as described above, but just with `python3`:

```
import subprocess

line = "-1 |i F0:58 F5:2143 F11:261 F12:1 F13:-1 F14:0 |c F1=management F2=married F3=tertiary F4=no F6=yes F8=unknown F9=5 F10=may F15=unknown"
vw_args = ['vw', '-p', 'stdout', '-i', 'model.vw', '-t', '--link', 'logistic', "--quiet"]
vw = subprocess.Popen(vw_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)

vw.stdin.write(bytes(line + "\n", 'utf-8'))
vw.stdin.flush()

print(vw.stdout.readline())
```
Even if I put a long sleep of 5s between flush and printing the stdout, with VW 8.9.1, this code hangs on waiting for the stdout and does nothing, while 8.8.1 works fine without any sleep at all.

Can you try this one, please?

**Comment by jackgerrits** [comment]
Okay, so for 8.8.1 we get the output and on 8.9.1 it hangs. Thanks for the repro, I'll look into it further.

It seems as though the parser is not giving through to the learner as we don't get any of the other progress print outs yet.

**Comment by jackgerrits** [comment]
I've put out a fix in #2835. It seems as though when I changed the stdin reading code to go from a file descriptor to using `std::cin` that it stopped returning data from the read as early as `read` did. This could be a buffering thing or maybe it treats newlines as a opportunity to return data.

Thanks again for the great repro's. Made this significantly easier to find.

If you're able to try out the branch let me know if it fixes things for you.

**Comment by Venousek** [comment]
@jackgerrits It works for me! Thank you very much for this rapid fix, Should I close this issue now? I will use your branch for now and will be looking forward to next release. Cheers!

**Comment by jackgerrits** [comment]
Ah very glad to hear it works. Don't worry, I'll close this issue when I get this PR merged.
