### ISSUE TITLE
--coin --synthcover is not working

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#2834]
#### Describe the bug
--cb_explore_adf --coin --synthcover is not working in many simple cases

#### To Reproduce
```
def generate(fname, count):
    examples = [
            [
                'shared |s f1',
                '0:-3:0.5 |a f1',
                '|a f2'
            ],
            [
                'shared |s f1',
                '|a f1',
                '1:-1:0.5 |a f2'
            ]
        ]
    with open(fname, 'w') as f:
        for i in range(count):
            for l in examples[i % 2]:
                f.write(l + '\n')
            f.write('\n')
```

#### Expected behavior
We should learn that action 0 is the best and average loss should converge to 3 (or 3 - exploration)

#### Observed Behavior
--coin --synthcover stuck in [0.5, 0.5] state
![image](https://user-images.githubusercontent.com/41013086/109837463-3330ef80-7c13-11eb-8e7a-ea3e9245d80c.png)

####  How did VW behave? Please include any stack trace, log messages or crash logs.
Here:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/4ac29b313299900e5eca36e747cfdc49f250761c/vowpalwabbit/cb_explore_adf_synthcover.cc#L102
we are clipping our predicted cost by min/max of logged costs which make sense only under assumption that predicted cost should converge to the real one.
That seems to be not true for --coin - we have some constant factor there. In this specific case it seems to tend to [-9, -3] which is going out of [-3, -1] and causing both costs to be clipped to -3.

```
generate('test.txt, 100000)

vw --cb_explore_adf -d test.txt --invert_hash inv_hash.txt --coin --synthcover


inv_hash.txt:
:0
a^f1:47870:-4.92344
a^f2:91850:1.07656
Constant:116060:-2.03828
s^f1:205995:-2.03828
```

Haven't checked yet what is going on inside coin, but is it fair to rely on that convergence in synthcover (@pmineiro)?

**Comment by pmineiro** [comment]
synthcover has a hyperparameter which is the "reward difference allowed to
explore over".  this might need a setting different than default for this
problem.  let's discuss.
