### ISSUE TITLE
Contextual Memory Tree fails to load models

### ISSUE THREAD

**Issue by manzilz** [VowpalWabbit/vowpal_wabbit#2907]
#### Describe the bug

Contextual memory tree not working. I think the error is because some parts of VW have been changed API and this part of the code hasn't seen the reflection yet.

#### To Reproduce

Just following instructions on `https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/demo/memory_tree/README.md`

I test two examples. Neither of `python aloi_script_progerror.py` nor `python aloi_script.py` works. I think none of the remaining examples works anymore either.

#### Expected behavior

The model to train and perform eval on test.

#### Observed Behavior
How did VW behave? Please include any stack trace, log messages or crash logs.

VW just gets stuck and I think it even parses the arguments incorrectly.

#### Environment
What version of VW did you use?
What OS or language did you use?

`VW 8.9.0 on Ubuntu 18`

**Comment by jackgerrits** [comment]
Will take a look

**Comment by jackgerrits** [comment]
The demo incorrectly used integers for boolean flag command line parameters. This caused issues with reading the datafile positional parameter.

I fixed the usage of the flags and explicitly used `-d` for the datafile in PR #2908

**Comment by manzilz** [comment]
Is the eval working with this fix? for example is this line https://github.com/VowpalWabbit/vowpal_wabbit/blob/20cff7b0e581f279d1942c37075708007a475235/demo/memory_tree/aloi_script.py#L47 executing?

**Comment by jackgerrits** [comment]
There are some issues there too - investigating
