### ISSUE TITLE
A SquareCB model fails to perform well after saving & loading

### ISSUE THREAD

**Issue by daraya123** [VowpalWabbit/vowpal_wabbit#2943]
#### Describe the bug
When a trained SquareCB model is saved and loaded again, it does not perform like before.
Using pyvw, I trained the model in this way :
`vw = pyvw.vw("--cb_explore_adf -q UA -f squarecb.model --save_resume --quiet --squarecb")`
and loaded the model:
`vw_loaded=pyvw.vw('--cb_explore_adf -q UA -i squarecb.model')`
then the model looks like doing a random exploration.
I had no problem with saving & loading other algorithms like epsilon-greedy or bagging, so I think this is particularly related to the SquareCB implementation.

#### To Reproduce
A notebook file attached.
Used pyvw 8.10.0 from pypi.
[squarecb_issue.zip](https://github.com/VowpalWabbit/vowpal_wabbit/files/6301846/squarecb_issue.zip)

#### Expected behavior
I expect the loaded model has no difference with original

#### Observed Behavior
It performs much worse than the original model

![image](https://user-images.githubusercontent.com/54830178/114511818-5c618880-9c73-11eb-8995-4f9674701335.png)

#### Environment
pyvw 8.10.0 on window

**Comment by bassmang** [comment]
Issue also present for --regcb

**Comment by jackgerrits** [comment]
This should now be resolved by #2988
