### ISSUE TITLE
build fails following instructions on Ubuntu 20.04: Imported target "Boost::program_options" includes non-existent path  "/include"

### ISSUE THREAD

**Issue by arielf** [VowpalWabbit/vowpal_wabbit#3003]
#### Describe the bug

Following the build instructions on Linux:

- https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#ubuntu
- https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Building#linux

```
git clone ssh://github.com/VowpalWabbit/vowpal_wabbit vw
cd vw
mkdir -p build
cd build
cmake ..
# fails here

make vw-bin
```

Results in an error from cmake.
 
#### To Reproduce

Follow build instructions (see previous section). Result:

```
% cmake  ..
-- VowpalWabbit Version: 8.11.0
-- Setting build type to 'Release' as none was specified.
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using C++ standard: 11
-- Found Git: /bin/git (found version "2.25.1") 
-- Git Version: b5939a84b
-- Number of processors: 16
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options system 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Submodule update
Submodule 'ext_libs/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'ext_libs/fmt'
Submodule 'rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path 'ext_libs/rapidjson'
Submodule 'ext_libs/spdlog' (https://github.com/gabime/spdlog.git) registered for path 'ext_libs/spdlog'
Cloning into '/home/src/vw/vw/ext_libs/fmt'...
Cloning into '/home/src/vw/vw/ext_libs/rapidjson'...
Cloning into '/home/src/vw/vw/ext_libs/spdlog'...
Submodule path 'ext_libs/fmt': checked out '835b910e7d758efdfdce9f23df1b190deb3373db'
Submodule path 'ext_libs/rapidjson': checked out 'f54b0e47a08782a6131cc3d60f94d038fa6e0a51'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'ext_libs/rapidjson/thirdparty/gtest'
Cloning into '/home/src/vw/vw/ext_libs/rapidjson/thirdparty/gtest'...
Submodule path 'ext_libs/rapidjson/thirdparty/gtest': checked out '0a439623f75c029912728d80cb7f1b8b48739ca4'
Submodule path 'ext_libs/spdlog': checked out 'de0dbfa3596a18cd70a4619b6a9766847a941276'
-- Version: 7.1.3
-- Build type: Release
-- CXX_STANDARD: 11
-- Performing Test has_std_11_flag
-- Performing Test has_std_11_flag - Success
-- Performing Test has_std_0x_flag
-- Performing Test has_std_0x_flag - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Success
-- Required features: cxx_variadic_templates
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Build spdlog: 1.8.2
-- Build type: Release
-- Generating install
-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: unit_test_framework 
-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options 
-- Configuring done
CMake Error in cluster/CMakeLists.txt:
  Imported target "Boost::program_options" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

[... several more errors like this ...]
```

#### Expected behavior

Build works, cmake step completes without errors

#### Observed Behavior

Error from `cmake` preventing the build from proceeding.

#### Environment

What version of VW did you use?

Latest from source:
```
commit b5939a84b16d27dfe6ab9cec7360be415899026f (HEAD -> master, origin/master, origin/HEAD)
Author: Jack Gerrits <jackgerrits@users.noreply.github.com>
Date:   Mon May 17 14:17:02 2021 -0400

    Update dev environment to use new image (#3001)
```

What OS or language did you use?

Linux, Ubuntu 20.04 LTS

**Comment by jackgerrits** [comment]
Very weird, it seems kind of like a broken environment. 

- Are there any environment variables that may be impacting the cmake search process?
- Was boost installed through apt? Can you try uninstalling it and reinstalling it?


```
 Imported target "Boost::program_options" includes non-existent path

    "/include"
```

This sort of looks like a variable was expanded to an empty string when it was meant to be an absolute path. Can you run 
```
cmake .. --trace-expand
```
 and post the output?

**Comment by arielf** [comment]
Thanks for looking at this.

I can find anything in my env that's out of the ordinary.
I'm running a vanilla 20.04 Ubuntu (with many packages installed).

```
% which cmake
/bin/cmake
% which gcc
/bin/gcc
% which cc
/bin/cc
% echo $CC

% echo $GCC

% cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

% dpkg -l | grep 'libboost-program-options'
ii  libboost-program-options-dev:amd64            1.71.0.0ubuntu2                             amd64        program options library for C++ (default version)
ii  libboost-program-options1.71-dev:amd64        1.71.0-6ubuntu6                             amd64        program options library for C++
ii  libboost-program-options1.71.0:amd64          1.71.0-6ubuntu6                             amd64        program options library for C++
```

Attaching the output from `cmake .. --trace-expand` (almost 10000 lines) next.

**Comment by arielf** [comment]
[cmake-trace.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/6511401/cmake-trace.txt)

**Comment by jackgerrits** [comment]
I see that Boost is installed to `/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/` rather than `/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/`. 

In your trace file I see:
```
/lib/x86_64-linux-gnu/cmake/boost_system-1.71.0/boost_system-config.cmake(13):  get_filename_component(_BOOST_INCLUDEDIR /lib/x86_64-linux-gnu/cmake/../../../include/ ABSOLUTE )
```
Results in `_BOOST_INCLUDEDIR` being set to `/include/`

Compared to when I run trace on my Ubuntu 20.04 system:
```
/usr/lib/x86_64-linux-gnu/cmake/boost_unit_test_framework-1.71.0/boost_unit_test_framework-config.cmake(13):  get_filename_component(_BOOST_INCLUDEDIR /usr/lib/x86_64-linux-gnu/cmake/../../../include/ ABSOLUTE )
```

Results in  `_BOOST_INCLUDEDIR` being set to `/usr/include/`


At least on my machine the Boost headers do in fact live in `/usr/include/`.

1. It looks like your setup is kind of non-standard and is tripping up Boost's search scripts. Where do the boost headers reside on your disk?
2. Do you know why your libs are installed to `/` instead of `/usr` ?

**Comment by arielf** [comment]
Thanks Jack,

This is very helpful.

On this system `/lib` is actually a symlink to `usr/lib`:

```
% ls -l /lib
lrwxrwxrwx 1 root root 7 Feb 28 11:40 /lib -> usr/lib/
```
And this seems to be pretty standard on Ubuntu:

https://askubuntu.com/questions/980871/are-bin-lib-sbin-symlinks-into-usr-in-ubuntu

So the `cmake/Boost*` dir is the same via both paths:
```
$ ls -ldi /*/lib/x86_64-linux-gnu/cmake/Boost-1.71.0
66458462 drwxr-xr-x 2 root root 4096 Feb 28 12:25 /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/
```
But this symlinking doesn't include `/include`.

Maybe relevant: in all the `/etc/ld.so.conf.d/*` files  `/lib/...` precedes `/usr/lib/...` in resolution order.

I wasn't able to build by forcing ` _BOOST_INCLUDEDIR=/usr/include/` in the cmake invocation.
But adding a symlink:  /include -> /usr/include (ugh! really hate doing this) solved this particular issue.

Might be incorrect assumption in the boost/cmake include dir discovery heuristic,

Thanks so much for your help!

**Comment by jackgerrits** [comment]
Looks like this is resolved, feel free to open another if you have further problems @arielf

**Comment by jackgerrits** [comment]
The target name has changed to `vw_cli_bin`
Please instead run:
```
cmake --build build --target vw_cli_bin
```

**Comment by xiasun** [comment]
> I see that Boost is installed to `/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/` rather than `/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/`.
> 
> In your trace file I see:
> 
> ```
> /lib/x86_64-linux-gnu/cmake/boost_system-1.71.0/boost_system-config.cmake(13):  get_filename_component(_BOOST_INCLUDEDIR /lib/x86_64-linux-gnu/cmake/../../../include/ ABSOLUTE )
> ```
> 
> Results in `_BOOST_INCLUDEDIR` being set to `/include/`
> 
> Compared to when I run trace on my Ubuntu 20.04 system:
> 
> ```
> /usr/lib/x86_64-linux-gnu/cmake/boost_unit_test_framework-1.71.0/boost_unit_test_framework-config.cmake(13):  get_filename_component(_BOOST_INCLUDEDIR /usr/lib/x86_64-linux-gnu/cmake/../../../include/ ABSOLUTE )
> ```
> 
> Results in `_BOOST_INCLUDEDIR` being set to `/usr/include/`
> 
> At least on my machine the Boost headers do in fact live in `/usr/include/`.
> 
> 1. It looks like your setup is kind of non-standard and is tripping up Boost's search scripts. Where do the boost headers reside on your disk?
> 2. Do you know why your libs are installed to `/` instead of `/usr` ?

Hello jack, I have exactly the same error for 
```
CMake Error in cluster/CMakeLists.txt:
  Imported target "Boost::program_options" includes non-existent path

    "/include"
```

But my boost install is at `/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/`, and `/usr/include/boost` do exists.

I have to make a symlink to make cmake find include properly.
```
sudo ln -s /usr/include /include
```

Do you have any idea what should be a nicer solution? My boost was installed via Ubuntu apt.

Many thanks!

**Comment by wjwwood** [comment]
For what it's worth, I found that this issue (or a similar one for pybind11) was being caused by having `/bin` on my `PATH` ahead of other directories. Removing that entry in the `PATH` allowed me to avoid this issue without the symlink.
