### ISSUE TITLE
Option to Install v141 toolset no longer exists 

### ISSUE THREAD

**Issue by m6gmjmjwfw** [VowpalWabbit/vowpal_wabbit#3018]
Microsoft no longer offers the ability to install the Visual Studio 2017 toolset.  VowpalWabbit does not compile under 2019.

**Comment by jackgerrits** [comment]
The checked in solution file is out dated as you've pointed out. The current recommended way to build on Windows is using CMake (the docs need to be updated to reflect this). By using CMake you can target whichever toolchain you wish. We use v142  for our Windows CI builds and testing.

For some docs on how to do this you can see:
1. [Dependencies using vcpkg](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#experimental-cmake-build-system-on-windows)
2. [Generating a solution](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Building#command-line)
    - Depending on your system you may need to add `-A x64 -G "Visual Studio 16 2019"` to specify 64 bit vs2019/v142

**Comment by m6gmjmjwfw** [comment]
Thanks I'll try that

On 2021-05-21 16:08, Jack Gerrits notifications-at-github.com 
|Github/Example Allow| wrote:

> The checked in solution file is out dated as you've pointed out. The 
> current recommended way to build on Windows is using CMake (the docs 
> need to be updated to reflect this). By using CMake you can target 
> whichever toolchain you wish. We use v142 for our Windows CI builds and 
> testing.
> 
> For some docs on how to do this you can see:
> 
> * Dependencies using vcpkg [1]
> 
> * Generating a solution [2]
> 
> * Depending on your system you may need to add -A x64 -G "Visual Studio 
> 16 2019" to specify 64 bit vs2019/v142
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].


Links:
------
[1] 
https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#experimental-cmake-build-system-on-windows
[2] 
https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Building#command-line
[3] 
https://github.com/VowpalWabbit/vowpal_wabbit/issues/3018#issuecomment-846260552
[4]

**Comment by jackgerrits** [comment]
Closing this as it seems resolved, if you have further issues please open a new issue with specific details of the failure/issue faced.
