### ISSUE TITLE
Label accessors for CCB, Slates, and Continuous Actions missing in pyvw

### ISSUE THREAD

**Issue by lokitoth** [VowpalWabbit/vowpal_wabbit#3043]
The pylibvw example object has accessors for most labels ~and predictions~, except for the newest ones: CCB, Slates and Continuous Actions. We should ensure these are implemented ~, and backfill [`pyvw.get_prediction()`]~(https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/vowpalwabbit/pyvw.py#L211) with them.

**Comment by jackgerrits** [comment]
Predictions are implemented: 
- CCB, Slates - [decision_scores](https://github.com/VowpalWabbit/vowpal_wabbit/blob/8786469ee0b062c6c443c10b86c6c9cedd6e47b7/python/vowpalwabbit/pyvw.py#L256)
- Continuous actions - [PDF and PDF_Value](https://github.com/VowpalWabbit/vowpal_wabbit/blob/8786469ee0b062c6c443c10b86c6c9cedd6e47b7/python/vowpalwabbit/pyvw.py#L257)

Labels are indeed missing

**Comment by jonpsy** [comment]
Would like to take a stab at this, since I don't see much progress here.

**Comment by jackgerrits** [comment]
#2500 is a bit different, it is for the Pandas to VW converter.

An example for this PR would be: https://github.com/VowpalWabbit/vowpal_wabbit/blob/a95be782de07d7a1619eef3b704c062aea12100b/python/vowpalwabbit/pyvw.py#L1031

**Comment by jonpsy** [comment]
Okay, but it looks like I need to define the accessors in the `pyvwlib.cc` file as well? Then I have to register them to be exportable as python functions.

**Comment by jackgerrits** [comment]
Yes, there will need to be some new functions available in the binding layer

**Comment by jonpsy** [comment]
Let's continue the discussion over the PR. Thanks.
