### ISSUE TITLE
Remove `ezexample`

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#3091]
#### Feature to be deprecated

I propose to remove the `ezexample` class and [header](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/ezexample.h).

`ezexample` was [added in 2014](https://github.com/VowpalWabbit/vowpal_wabbit/commit/e9ff4d9904bfca3261b59bbfc5414944bcdebc74). It is a builder abstraction for examples and also a re-export of the VW api (setup, predict/learn, finish, etc). However, it suffers from several issues:
- The API makes heavy use of `operator()` making it hard to understand
- It does not allow for namespaces to be specified as an entire string, making it not with parity to the text format
    - In addition this means it will not work with the full name interactions work
- It duplicates logic exposed elsewhere `mini_setup_example`, `predict`, etc
- It does not support non scalar prediction types

It was created at a time when the standard example object was harder to use and I am sure it was useful then, but we should standardize on the standard entrypoints and functions.

Example:
```C++
ezexample ex(vw, false);
ex(vw_namespace('s'))
("p^the_man")
("w^the")
("w^man");
```

#### Value proposition

This removal is motivated under several principles:
- Maintainability: this class is hard to use and maintain and it duplicates much of VW's functionality
- Compatibility: this class will not work with new style full name interactions
- Better alternative available: the standard example object supports these operations already

#### User impact and mitigation

All functionality of `ezexample` is provided through the equivalent standard classes which it is wrapping.

```c++
vw* vw = VW::initialize(init_string);
ezexample ex(vw, false);
ex(vw_namespace('s'))
("p^the_man")
("w^the")
("w^man");
ex.set_label("1");
std::cout << ex.predict_partial() << std::endl;
```

Changes to:
```c++
auto& vw = *VW::initialize(init_string);
example ex;
auto ns_hash = VW::hash_space(vw, "s");
auto& fs = ex.feature_space.get_or_create_feature_space(ns_hash, 's');
fs.push_back(1.f, VW::hash_feature("p^the_man", ns_hash);
fs.push_back(1.f, VW::hash_feature("p^the", ns_hash);
fs.push_back(1.f, VW::hash_feature("p^man", ns_hash);
ex.l.simple = label_data(1.f);
VW::setup_example(vw, &ex);
vw.predict(ex);
std::cerr << ex.pred.scalar << std::endl;
```

#### Schedule
- Deprecated in release: 8.11
    - https://github.com/VowpalWabbit/vowpal_wabbit/pull/3128
- Removed in release: 9.0
    - #3164 
    - Archive available here: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/EZExample-Archive

#### Additional context
This proposal is created as a way to communicate the plan. If this affects you then please join the discussion so we can best work out how to support your use case.

**Comment by lokitoth** [comment]
The implementation for it could be turned into a gist for those interested in continuing to use it, since it is a fair ways more readable than the push_back APIs.

**Comment by kumpera** [comment]
Good point @lokitoth. As long as it's reachable by the release info, we're golden.

**Comment by jackgerrits** [comment]
Discussed in open source meeting, this is going to be removed and the implementation will be available as a gist/example in wiki.
