### ISSUE TITLE
Can't do multiple passes with --cb_adf format

### ISSUE THREAD

**Issue by rangi513** [VowpalWabbit/vowpal_wabbit#3106]
I am attempting to do multiple passes over a cb_adf dataset to hopefully improve the quality of my q function. I'm thinking of trying an offline bandit using the whole dataset and multiple passes instead of online with iterative updates. However, I get the following error after the first pass:
```
libc++abi.dylib: terminating with uncaught exception of type VW::vw_exception: cb_adf: badly formatted example, only one line can have a cost
[1]    90720 abort      vw --cb_adf --passes 2 -c -d train.dat
```
Here is my command and dataset for reproducibility:
`vw --cb_adf --passes 2 -c -d train.dat`

train.dat
```
shared | a:1 b:0.5
0:0.1:0.75 | a:0.5 b:1 c:2
| a:1 c:3

shared | s_1 s_2
0:1.0:0.5 | a:1 b:1 c:1
| a:0.5 b:2 c:1
```
I'm using version 8.10.1 on OSX. I found this [SO post](https://stackoverflow.com/questions/59466988/vowpal-wabbit-contextual-bandit-simulation-error) and commit https://github.com/VowpalWabbit/vowpal_wabbit/commit/431c270742e76c7524413c33e76e47851cba549e by @jackgerrits that maybe was supposed to fix this but also could be unrelated.

Are multiple passes not supported for --cb_adf? If so, maybe some better error messaging might be useful here?

**Comment by lokitoth** [comment]
What is happening under the hood to cause this behaviour:

1. During construction of the second example's `multi_ex`, the newline at the very end gets processed as an "endpass" in [`try_complete_multi_ex`](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/learner.cc#L183). 
2. This does not terminate constructing the multi_ex in [`complete_multi_ex`](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/learner.cc#L175), and we resume with the first three examples coming from the second pass.
3. The constructed multi_ex has two labeled examples, which is not valid for cb_adf

What should probably happen on an endpass is we first process the example as normal, then run the endpass, just need to ensure that `VW::finish_example` is not called twice. 

Going to see if I can understand when this got introduced, too.

**Comment by lalo** [comment]
This also affects cb_to_cb_adf, since --cb will now use cb_adf code path

**Comment by lokitoth** [comment]
There is another bug I discovered which is exposed after fixing this one. It can be reproed without --passes: With the same data file, run without `--passes 2` but with `-c`. This will work the first time, and importantly it will result in:

```
finished run
number of examples = 2
weighted example sum = 2.000000
weighted label sum = 0.000000
average loss = 1.066667
total feature number = 21
```

But the second time running with the cache (it reads examples from cache), it will run with:

```
finished run
number of examples = 2
weighted example sum = 0.000000
weighted label sum = 0.000000
average loss = n.a.
total feature number = 21
```

Not sure what is happening, on the second run.

**Comment by lokitoth** [comment]
Created #3139 to track above; it is blocking verifying that this bug is fixed, so going to finish addressing that one first.
