### ISSUE TITLE
Online Learning through Python Interface

### ISSUE THREAD

**Issue by adr-arroyo** [VowpalWabbit/vowpal_wabbit#3107]
Hi!

### Description and documentation links

I am looking for ways to solve an *__Online Learning__* problem in *python* (with timeseries data although it is not relevant here). I saw in the [features](https://vowpalwabbit.org/features.html) and [documentation](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Examples) that VowpalWabbit supports the OnlineLearning paradigm. However, I do not understand (or I have not found) how to use the python interface to train a model for this task. I saw some examples in the doc as the [OjaNewton](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Efficient-Second-Order-Online-Learning) but I have not been able to reproduce it to the python API.

My question is, could you provide an example/brief code sample of this OjaNewton implementation (or any other Online Learning implementations) so that I can test it against my data?

BR!

**Comment by jackgerrits** [comment]
Hi @adr-arroyo , the Python basics tutorial is doing online learning. The defaults of VW are generally geared towards an online learning setting.

https://vowpalwabbit.org/tutorials/python_first_steps.html

Let me know if that is not quite what you're after.

**Comment by adr-arroyo** [comment]
Hi,

thanks for the reply. I didn't know that the default's way of working was already online learning. Sorry for the misunderstanding!

I think that I can follow the examples to start working 👍 

BR

**Comment by adr-arroyo** [comment]
Just one more question.

is the sklearn interface in `from vowpalwabbit import sklearn_vw` also configured towards online learning?

Thank you!

**Comment by jackgerrits** [comment]
I'm not super familiar with the sklearn interface, but I would say it is probably more geared towards batch learning as that is what sklearn leans towards.

**Comment by adr-arroyo** [comment]
Hi,

Actually I ran some tests and yeah, the sklearn interface does not work very well when in `online learning` processing. On the contrary, VowpalWabbit seems to work pretty well (and fast):

![image](https://user-images.githubusercontent.com/11291505/124083283-f86a8700-da4d-11eb-9eef-e3046bebfe1c.png)


Thank you for the help!
