### ISSUE TITLE
Implicit feedback for recommendation systems

### ISSUE THREAD

**Issue by dminovski0** [VowpalWabbit/vowpal_wabbit#3112]
### Description

> I need to make a recommender based on implicit feedback, like views, page visits. Another package with ALS supports this, but that package doesn't have online (streaming) learning. Does Vowpal Wabbit support work with implicit feedback?
Also, the ALS algorithm doesn't use feature columns, and it works mostly with user-item matrices. Can Vowpal Wabbit add content filtering to the collaborative filtering methods? Or use a hybrid model? There are some mentions of recommendations with the Contextual Bandits, but it's not much.

### Link to Documentation Page

> No documentation for implicit feedback recommendation systems.
There is an example with explicit feedback:
https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Matrix-factorization-example
On getstream.io is another recommender sample:
https://getstream.io/blog/recommendations-activity-streams-vowpal-wabbit

**Comment by JohnLangford** [comment]
The standard way to deal with implicit feedback is to define some function which translates this into a reward value, and then apply the contextual bandit learning routines.  There are more esoteric things that we are thinking about (https://arxiv.org/abs/2106.04887), but those do not yet have an implementation.

One trickiness with 'content filtering' in general is that the exploration algorithms in VW tend to only work over a relatively small number of choices (essentially, divide your data samples by the number of choices to think about how much data you have) or require continuity.   There are research projects underway to expand the set of possibilities here.  

Hybrid approaches which use a more conventional first stage collaborative filtering system paired with contextual bandits on a subset of actions make quite a bit of sense.

**Comment by jackgerrits** [comment]
I'm going to close this as it seems as though John has answered it. Please feel free to reopen or open a new issue if you need. Thanks!

**Comment by dminovski0** [comment]
@JohnLangford @jackgerrits Thanks.
