### ISSUE TITLE
Drop support for Python 2.7 and Python 3.5

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#3118]
#### Feature to be deprecated

The current level of support of Python 2.7 and Python 3.5.

#### Value proposition

These versions are no longer supported, even for security releases. To reduce maintenance burden we will be dropping them. Additionally, this will allow us to use Python 3.6 features such as type hints and f-strings.

#### User impact and mitigation
Any user depending on Python 2.7 or 3.5 will either need to upgrade or stick with version 8.11

#### Schedule
- Deprecated in release: 8.11
- Removed in release: 9.0
    - #3104

**Comment by lokitoth** [comment]
Can this issue be closed now that our build has dropped support? Or is the plan to close this when 9 releases? @jackgerrits

**Comment by jackgerrits** [comment]
Yeah let's close it. It seems reasonable for the removal commit to close the issue.
