### ISSUE TITLE
[python] Improve modules names and import

### ISSUE THREAD

**Issue by etiennekintzler** [VowpalWabbit/vowpal_wabbit#3127]
**Module names**
The modules names could be improved: 
- `DFtoVW` is not [pep8 compliant](https://www.python.org/dev/peps/pep-0008/#package-and-module-names):
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability.

It could be renamed `dftovw` (baring pep8 it's really rare to see capitals in module name).
- `sklearn_vw` could just be renamed `sklearn`: the "_vw" doesn't bring much information as one already knows he's using vowpalwabbit package.

A simple warning could be issued so it doesn't break the backward compatibility.

**Import**
This might be more a question of taste by why not import directly `vw` from the _root_ of the package (i.e from `vowpalwabbit`), since it's the main class that people are expected to use in the package ? To be more clear, in `__init__.py` you'd import vw from .pyvw so you could then do `from vowpalwabbit import vw`.

**Comment by jackgerrits** [comment]
I've been thinking for a while the import situation is unnecessarily confusing. We'd love your help improving this! :)

Is it possible to do all of these things in a way that doesn't break people but allows us to warn/deprecate on the old way?
