### ISSUE TITLE
Prevent users from training a loaded model without save_resume

### ISSUE THREAD

**Issue by bassmang** [VowpalWabbit/vowpal_wabbit#3155]
#### Describe the bug
If a user would like to save a model, then load it and continue training, they should use the --save-resume flag. Currently a user can do this without this flag, but the result will not be as expected. VW should either give the user a warning, or cause a failure if they try to continue training on a loaded model without --save-resume.

#### To Reproduce
Run some VW command to save a model without --save_resume flag:
`vw -d train-sets/0001.dat -f models/cannot_learn.model`

Try to load the model, and continue learning while producing predictions
`vw -d train-sets/0001.dat -i models/cannot_learn.model -p out.predict`

#### Expected behavior
Running the second command should throw an error, or inform the user that the model file cannot continue learning as expected.

**Comment by jackgerrits** [comment]
There are legitimate reasons to load a model that was saved without save_resume, but it does seem to be that most commonly users expect the save_resume behavior. I think we should default to save_resume and opt in to non-save_resume. We should not prevent users as this is a valid use case.
