### ISSUE TITLE
proplem in implemnted VWRegressor

### ISSUE THREAD

**Issue by m3bbass** [VowpalWabbit/vowpal_wabbit#3199]
hello,
I tried to implement VWRegressor like in the following code, but it doesn't give me the correct prediction for the output.
how can i solve this problem?
```python
from vowpalwabbit.sklearn_vw import VWRegressor
from sklearn import datasets

# Load the diabetes dataset
diabetes = datasets.load_diabetes()
X = diabetes.data
y = diabetes.target

#model = VWRegressor(l=100)
model = VWRegressor(convert_to_vw=True, loss_function = 'quantile',learning_rate=0.5,holdout_off=0,passes=50,quantile_tau=0.05, l2=0.00005)
model.fit(X, y)
```

![Screen Shot 2021-07-31 at 11 13 18 AM](https://user-images.githubusercontent.com/46040260/127735184-de99089a-6610-45c5-884d-daae0105db73.png)

**Comment by jackgerrits** [comment]
Hi @m3bbass, can you please share the notebook so I can test it out myself?

**Comment by jackgerrits** [comment]
I'm going to go ahead and close this since I don't think there is a bug here. Please feel free to ask questions if you would like though.
