### ISSUE TITLE
Index out of bounds in test 125

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#3241]
#### Describe the bug
There is an out of bounds access bug in test 125.

#### To Reproduce
1. Replace `v_array`'s `operator[]` with:
```c++
  T& operator[](size_t i) const
  {
    assert(i < size());
    return _begin[i];
  }
```
2. Run test 125 with a VW built in debug: `-k -c -d train-sets/wsj_small.dparser.vw.gz -b 20 --search_task dep_parser --search 26 --search_alpha 1e-5 --search_rollin mix_per_roll --search_rollout oracle --one_learner --search_history_length 3 --root_label 8 --transition_system 2 --passes 8`
3. Observe crash at https://github.com/VowpalWabbit/vowpal_wabbit/blob/782273b028005dc756e0277f9487b3c25f661a7c/vowpalwabbit/search_dep_parser.cc#L406
Where `gold_heads` is size 50 and index `50` is accessed.

#### Expected behavior
No out of bounds access.

#### Environment
What version of VW did you use? Latest master
What OS or language did you use? Windows and Ubuntu

**Comment by lokitoth** [comment]
Putting this here for the reference of whoever picks up this issue: Here's a paper related to the dependency parser in VW: https://arxiv.org/pdf/1503.05615.pdf, along with the original(?) code for it.

**Comment by lalo** [comment]
Could be relevant: https://github.com/VowpalWabbit/vowpal_wabbit/commit/f525cab1db0e86c30fba311ba98046a88dc1875f

**Comment by JohnLangford** [comment]
This does not reproduce for me with a fresh clone of the master branch.
