### ISSUE TITLE
feature request: options: add one_of(...) method

### ISSUE THREAD

**Issue by lalo** [VowpalWabbit/vowpal_wabbit#3318]
There’s a class of options, including `cb_type`, that should be defined as follows:
 
```
      .add(make_option("cb_type", type_string)
               .keep()
               .one_of(“ips”, “dr”, “mtr”)
               .help("contextual bandit method to use in {ips,dr,mtr}. Default: mtr"));
```
 
This way we can bake in a validation step on the parser from one of the pre-defined options. There’s a couple of other flags that are set between different pre-defined values. The help message can be auto-generated based on the one_of arguments.
 
The error would still need to be handled instead of doing the printing warning and picking a default.

current impl: we manually have to check if the user selected one of the correct options
https://github.com/VowpalWabbit/vowpal_wabbit/blob/40285770d918fb181ddff5d0a89c86b940b69d60/vowpalwabbit/cb_adf.cc#L503

update options_i to have one_of method:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/40285770d918fb181ddff5d0a89c86b940b69d60/vowpalwabbit/options.h#L62

add logic to check that the user's input matches the known options ("ips", "dr", "mtr") fail if they dont match.
https://github.com/VowpalWabbit/vowpal_wabbit/blob/40285770d918fb181ddff5d0a89c86b940b69d60/vowpalwabbit/options_boost_po.cc#L145

**Comment by Yash621** [comment]
can I work on it ?

**Comment by olgavrou** [comment]
Hi @Yash621 yes feel free to tackle any `Good first issue` issue. Just say which one you are working on so that others don't start working on it, and if you open a PR please reference the issue on the PR description

**Comment by Yash621** [comment]
okay so I will be working on this ,thnx ;)

**Comment by Yash621** [comment]
@olgavrou can you guide me through this ,i have modified the files containing "cb_type" but i am not able to understand that how to implement one_of ?
