### ISSUE TITLE
Ignored namespace keeps duplicating in vw output when using ignore_linear with save_resume.

### ISSUE THREAD

**Issue by zwd-ms** [VowpalWabbit/vowpal_wabbit#3335]
#### Describe the bug
When using both --ignore_linear and --save_resume, there are duplicated ignored namespace letters in vw output, see below:
"ignoring linear terms for namespaces beginning with: T T T T T T T T T"

~~~
...

$ cat xai | ./vw --ignore_linear T --save_resume -i weights -f weights
ignoring linear terms for namespaces beginning with: T T T T T T T T T
...

$ cat xaj | ./vw --ignore_linear T --save_resume -i weights -f weights
ignoring linear terms for namespaces beginning with: T T T T T T T T T T
...
~~~

#### To Reproduce
1. `split -l 100 train-sets/0002.dat`
2. run vw with --save_resume over the file chunks one by one

#### Expected behavior
ignoring linear terms for namespaces beginning with: T

#### Observed Behavior
ignoring linear terms for namespaces beginning with: T T T T T T T T T
The list keeps repeating for each save_resume call.

#### Environment
Latest master build.

**Comment by zwd-ms** [comment]
okay, should not use "--ignore_linear T" any more when already using "--save_resume".

**Comment by olgavrou** [comment]
@zwd-ms should this be added to the documentation somewhere (the args wiki page for example) if there isn't going to be a warning about it?

**Comment by zwd-ms** [comment]
yes there should be a warning similar to the others:
`WARNING: model file has set of {-q, --cubic, --interactions} settings stored, but they'll be OVERRIDEN by set of {-q, --cubic, --interactions} settings from command line.`

**Comment by jackgerrits** [comment]
Does it just keep adding `--ignore_linear` terms to the model? It should be simple to do a deduplication on model parse to address this.

**Comment by zwd-ms** [comment]
1. Is the expected behavior to add the `ignore_linear` term, or override the saved model (like the interactions)? especially if some different terms are provided
2. Need also to check `ignore` and perhaps `keep`

**Comment by jackgerrits** [comment]
We have deduped other options in the past - I think it makes sense to
