### ISSUE TITLE
Setup should fail if an option is passed which is not used by the activated reductions

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#3351]
There are many command line options and a major point of confusion is knowing if an option is being used. Is it hard to know which reduction an option belongs to without looking at code.

We have enough information in the setup process to determine if an option is passed by the user but the `necessary` option of the option group in which it resides was not activated. If this is the case we should exit with an error message stating the option was passed but the required reduction which consumes it was not enabled.

**Comment by Yash621** [comment]
@jackgerrits Hi, I would like to work on this, can it assigned to me?
