### ISSUE TITLE
VW on ubuntu 18.04 JNI static build fails (dynamic linking works fine)

### ISSUE THREAD

**Issue by ramkumarrani** [VowpalWabbit/vowpal_wabbit#3361]
I have been trying to build Vowpal Wabbit (VW) JNI on ubuntu 18.04 using Java static build option enabled.  It fails.

Description:
Reference material: https://stackoverflow.com/questions/62537391/vowpal-wabbit-for-ubuntu-18-java-1-8

Ubuntu version:
```sh
$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

Using above reference, I tried following:

step 1: sudo apt install libboost-dev libboost-thread-dev libboost-program-options-dev libboost-system-dev libboost-math-dev libboost-test-dev zlib1g-dev cmake g++ default-jdk
step 2: git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git
step 3: cd vowpal_wabbit
step 4: mkdir build; cd build
step 5: sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DWARNINGS=Off -DBUILD_JAVA=On -DBUILD_DOCS=Off -DBUILD_PYTHON=Off -DSTATIC_LINK_VW_JAVA=On -DBUILD_TESTS=Off
step 6: sudo make vw_jni -j 2

The make process fails toward Linking CXX at the end:
```
[ 91%] Linking CXX shared library libvw_jni.so
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_program_options.a(options_description.o): relocation R_X86_64_PC32 against symbol `_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEED1Ev' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
java/CMakeFiles/vw_jni.dir/build.make:327: recipe for target 'java/libvw_jni.so' failed
make[3]: *** [java/libvw_jni.so] Error 1
CMakeFiles/Makefile2:674: recipe for target 'java/CMakeFiles/vw_jni.dir/all' failed
make[2]: *** [java/CMakeFiles/vw_jni.dir/all] Error 2
CMakeFiles/Makefile2:681: recipe for target 'java/CMakeFiles/vw_jni.dir/rule' failed
make[1]: *** [java/CMakeFiles/vw_jni.dir/rule] Error 2
Makefile:384: recipe for target 'vw_jni' failed
make: *** [vw_jni] Error 2
```
Note that dynamic linking (instead of static linking, that is not using -DSTATIC_LINK_VW_JAVA parameter7) works fine.  

Please suggest how to fix this issue.

**Comment by jackgerrits** [comment]
You need to have a copy of boost which has been compiled with `-fPIC` in order to statically link VW. Relevant line of your output:
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_program_options.a(options_description.o): relocation R_X86_64_PC32 against symbol `_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEED1Ev' can not be used when making a shared object; recompile with -fPIC
```
We do this in the Docker image used for the Java packaging and CI: https://github.com/VowpalWabbit/docker-images/blob/master/vowpal_wabbit/centos7_6_1810-build.Dockerfile

**Comment by jackgerrits** [comment]
I think we've answered your question so I am going to go ahead and close this. If you would like to discuss more or feel it isn't answered then please feel free to open a new issue or reopen this one.

**Comment by ramkumarrani** [comment]
thanks. please go ahead.
