### ISSUE TITLE
where is option do add namespaces in csv2vw?

### ISSUE THREAD

**Issue by Sandy4321** [VowpalWabbit/vowpal_wabbit#3385]
## Short description

where is option do add namespaces in csv2vw?
https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/utl/csv2vw

**Comment by Sandy4321** [comment]
great friends

Thank you very much
VowpalWabbit is the best package in internet !!!!!!!!!!!!!!!

**Comment by jackgerrits** [comment]
Closing this issue since csv2vw is not really a focus and is effectively replaced by DFtoVW.
