### ISSUE TITLE
cmd vs pyvw

### ISSUE THREAD

**Issue by grigoriysol** [VowpalWabbit/vowpal_wabbit#3417]
I can't repeat the example using the command line.
https://github.com/VowpalWabbit/jupyter-notebooks/blob/master/Simulating_a_news_personalization_scenario_using_Contextual_Bandits.ipynb

Previously, I always use command line interface for regression and classification.
Now I want to deal with contextual bandits and I just couldn't train the model. At the same time, if I use pyvw, everything learns quickly and works fine.
Can you tell me what commands to use to repeat this example?

**Comment by jackgerrits** [comment]
The tutorial is interactive and involves creating a simple simulator to be able to label each chosen action. Using the command line involves processing a given datafile. The closest thing would be to simply generate some amount of data and label each example with the simulator. VW will first calculate and record loss before learning from the given label

**Comment by jackgerrits** [comment]
I think we've answered your question so I am going to go ahead and close this. If you would like to discuss more or feel it isn't answered then please feel free to open a new issue or reopen this one.
