### ISSUE TITLE
In-VW option documentation is wrong for some gd options

### ISSUE THREAD

**Issue by lokitoth** [VowpalWabbit/vowpal_wabbit#3447]
The GD-reduction options `sparse_l2`, `l1_state`, and  `l2_state` have copy-pasted help strings from `normalized`. 

From [gd.cc#L1175-L1183](https://github.com/VowpalWabbit/vowpal_wabbit/blob/52cfba671753623ae67bb9f1f4dfb451511111e9/vowpalwabbit/gd.cc#L1175-L1183):

```
      .add(make_option("normalized", normalized).help("use per feature normalized updates").keep(all.save_resume))
      .add(make_option("sparse_l2", g->sparse_l2).default_value(0.f).help("use per feature normalized updates"))
      .add(make_option("l1_state", all.sd->gravity)
               .keep(all.save_resume)
               .default_value(0.)
               .help("use per feature normalized updates"))
      .add(make_option("l2_state", all.sd->contraction)
               .keep(all.save_resume)
               .default_value(1.)
               .help("use per feature normalized updates"));
```

**Comment by JohnLangford** [comment]
for l1_state, maybe something like: "amount of accumulated implicit l1 (or l2) regularization".

for spare_l2, maybe something like: "degree of l2 regularization applied to activated sparse parameters"
