### ISSUE TITLE
python execution got stuck for cache_file = 'my_VW_2.cache',

### ISSUE THREAD

**Issue by Sandy4321** [VowpalWabbit/vowpal_wabbit#3460]
#### Describe the bug
vowpalwabbit.__version__
'8.11.0'
|||||||||||||||||||||||||||||||||||||
this does not work
```Python
VWmodel_simple = pyvw.vw(
cache_file = 'my_VW_2.cache',
passes = 3,
learning_rate = 0.1,
l2 = ridge_lambda,
loss_function = loss_function,
)
```
||||||||||||||||||||||||||||||||||
never finish to run
python execution got stuck

#### To Reproduce
![image](https://user-images.githubusercontent.com/11426119/141374484-6e544cd3-ff6f-4cc9-8193-622108aa7c0f.png)

|||||||||||||||||||||||||||||||||||||
this does not work
```Python
VWmodel_simple = pyvw.vw(
cache_file = 'my_VW_2.cache',
passes = 3,
learning_rate = 0.1,
l2 = ridge_lambda,
loss_function = loss_function,
)
```
||||||||||||||||||||||||||||||||||
never finish to run

but this works
```Python
from vowpalwabbit import pyvw

#lasso_lambda
ridge_lambda = 0.001
loss_function = 'squared'
q=0
VWmodel_simple  = pyvw.vw(
    learning_rate = 0.1,
    l2 = ridge_lambda,
    loss_function = loss_function,    
)
```

this works
```Python
model_VWRegressor_from_sklearnVW = VWRegressor(convert_to_vw = False ,normalized = True , passes = 4, readable_model = 'my_VW.model' , cache_file =  'my_VW.cache' , learning_rate = 0.1, loss_function = 'squared' , l2 = 0.001)
```

```Python
model_VWRegressor_from_sklearnVW
VWRegressor(cache_file: my_VW.cache, convert_labels: False, convert_to_vw: False, l2: 0.001, learning_rate: 0.1, loss_function: squared, normalized: True, passes: 4, quiet: True, readable_model: my_VW.model)
```

#### Observed Behavior
How did VW behave? Please include any stack trace, log messages or crash logs.

#### Environment
What version of VW did you use?
vowpalwabbit.__version__
'8.11.0'
What OS or language did you use?
windows 10
python
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]

e.g. `VW 8.6.1 on Linux with the Python bindings`

**Comment by jackgerrits** [comment]
When you say "passes" for PyVW it is expecting you to have supplied a datafile. When you don't supply a data file (`-d`) VW implicitly uses stdin. So what you are seeing is VW sitting waiting to read stdin.

It's counterintuitive because in the way you are invoking PyVW it is sort of behaving like a command line invocation.

If you wish to use PyVW interactively instead of using it to process a file then you must avoid passing `-d` or `--passes`. See here for the check: https://github.com/VowpalWabbit/vowpal_wabbit/blob/e72cad55fb558389b51303d071377eb0ad1a2078/python/vowpalwabbit/pyvw.py#L372

I think to avoid this weird behavior the Python bindings should really use `--no_stdin`. I had a try recently and I wasn't even able to send data to the stdin VW is expecting in this case. CC @lalo @bassmang what do you think about adding `--no_stdin`?

**Comment by Sandy4321** [comment]
@jackgerrits 
thanks for soon answer
then may you clarify how to use
pywv 
by analogy with 
    model_VWRegressor_from_sklearnVW = VWRegressor(convert_to_vw = False ,normalized = True , passes = 4, readable_model = 'my_VW.model' , cache_file =  'my_VW.cache' , learning_rate = 0.1, loss_function = 'squared' , l2 = 0.001)
   
    model_VWRegressor_from_sklearnVW.fit(data_VW_Format_with_NameSpaces)

where
label_VW_format = SimpleLabel('target')
converter_advanced = DFtoVW(df=  data_all_rows_df, namespaces=[C, N ], label=label_VW_format)

data_VW_Format_with_NameSpaces = converter_advanced.convert_df()

**Comment by jackgerrits** [comment]
It looks like the sklearn interface has special handling of passes. After all it is just a wrapper around `pyvw`. I would recommend looking at how it handles it.

https://github.com/VowpalWabbit/vowpal_wabbit/blob/e72cad55fb558389b51303d071377eb0ad1a2078/python/vowpalwabbit/sklearn_vw.py#L556

**Comment by Sandy4321** [comment]
I see
            for n in range(passes):
                if n >= 1:
                    examples = shuffle(X)
                else:
                    examples = X
                for idx, example in enumerate(examples):
                    self.vw_.learn(example)

then if X can be created like this
label_VW_format = SimpleLabel('target')
converter_advanced = DFtoVW(df= data_all_rows_df, namespaces=[C, N ], label=label_VW_format)

X= converter_advanced.convert_df()

**Comment by Sandy4321** [comment]
but seems to be passes in not problem at all
since I get error when provide passes
VWmodel_simple  = pyvw.vw(
    learning_rate = 0.1,
    l2 = ridge_lambda,
    passes = 3,
    loss_function = loss_function,    
)

Traceback (most recent call last):
  Debug Console, prompt 18, line 1
    #S_VW_with_2d_and_3d_interactions_Oct24
  File "e:\Python environemnts\MYENVS\may9_sklearn0242\Lib\site-packages\vowpalwabbit\pyvw.py", line 348, in __init__
    super(vw, self).__init__(" ".join(l))
builtins.RuntimeError: need a cache file for multiple passes : try using --cache_file

**Comment by Sandy4321** [comment]
then is not weird behavior it is just not correct parameter to use

**Comment by Sandy4321** [comment]
and using cache_file  without passes is not problem neither - works perfectly , no error

VWmodel_simple  = pyvw.vw(
    cache_file =  'my_VW_2.cache',
    learning_rate = 0.1,
    l2 = ridge_lambda,
    loss_function = loss_function,    
)
![image](https://user-images.githubusercontent.com/11426119/141387039-5474823a-120e-4ade-abac-d34c0dd05c8a.png)

**Comment by Sandy4321** [comment]
I see
for n in range(passes):
if n >= 1:
examples = shuffle(X)
else:
examples = X
for idx, example in enumerate(examples):
self.vw_.learn(example)

then if X can be created like this
label_VW_format = SimpleLabel('target')
converter_advanced = DFtoVW(df= data_all_rows_df, namespaces=[C, N ], label=label_VW_format)

X= converter_advanced.convert_df()

THEN ONLY QUESTOIN IS CAN BE X CREATED LIKE THIS
X= converter_advanced.convert_df() 
???

**Comment by jackgerrits** [comment]
The sklearn interface expects a list of examples which it processes one by one.

The pyvw interface when you call learn/predict expects a single example. So you need to iterate over X and pass it to VW individually.

**Comment by Sandy4321** [comment]
but then pyvw  is slower than sklearn interface

**Comment by Sandy4321** [comment]
is it true that
then pyvw is slower than sklearn interface

since for pyvw we use loop , what actually slow in python 
but for 
model_VWRegressor_from_sklearnVW = VWRegressor(convert_to_vw = False ,normalized = True , passes = 4, readable_model = 'my_VW.model' , cache_file = 'my_VW.cache' , learning_rate = 0.1, loss_function = 'squared' , l2 = 0.001)

we use data by inner processing by vowpalwabbit
what is written in C++?

**Comment by jackgerrits** [comment]
> is it true that then pyvw is slower than sklearn interface?
No, I wouldnt say it is slower. The sklearn interface just uses the pyvw interface anyway.

When `-d` is passed to the pyvw instance it will use the C++ driver, just like the command line, which is probably faster but I haven't tested it.

**Comment by Sandy4321** [comment]
@jackgerrits 

sorry can not understand about -d
If you wish to use PyVW interactively instead of using it to process a file then you must avoid passing -d 
can you share code example for -d using

**Comment by jackgerrits** [comment]
```Python
from vowpalwabbit import pyvw

my_vw = pyvw.vw(
    data="mydatafile.txt",
    passes=3
)

# Or

my_vw = pyvw.vw("--data mydatafile.txt --passes 3")
```

**Comment by Sandy4321** [comment]
@jackgerrits 
thanks for soon answer 
but this code gives error
from vowpalwabbit import pyvw
my_vw = pyvw.vw(
    data="mydatafile.txt",
    passes=3
)

Traceback (most recent call last):
  Debug Console, prompt 23, line 1
 
  File "e:\Python environemnts\MYENVS\may9_sklearn0242\Lib\site-packages\vowpalwabbit\pyvw.py", line 348, in __init__
    super(vw, self).__init__(" ".join(l))
builtins.RuntimeError: need a cache file for multiple passes : try using --cache_file

**Comment by Sandy4321** [comment]
this works wo error
from vowpalwabbit import pyvw
my_vw = pyvw.vw(
    cache_file =  'my_VW_45.cache',
data="mydatafile.txt",
passes=3
)

but how to use now created object
my_vw
1
to train 
2
to predict
??

**Comment by jackgerrits** [comment]
Apologies for the malformed snippet. When using passes a cache file must be used, this can be resolved like so:

```Python
from vowpalwabbit import pyvw

my_vw = pyvw.vw(
    data="mydatafile.txt",
    passes=3,
    cache=True
)
```

(I've also updated the previous response)

**Comment by Sandy4321** [comment]
great thanks,

but now how to use this code
1
how to do training 
when I run 
my_vw = pyvw.vw(
    data="mydatafile.txt",
    passes=3,
    cache=True
)
and file mydatafile.txt not existing 
I do not have error, then seems to be 
additional training code needed    
2
how to do predictions

**Comment by jackgerrits** [comment]
It's up to you how you wish to structure your code, I am explaining though that VW sort of has two modes. Command line and interactive and mixing them accidentally produces surprising results sometimes. As seen here.

`mydatafile.txt` could be a datafile in [VW text format](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Input-format) if you wish to use that.

Through the command line predictions can be produced with an options `-p file.pred` which will produces predictions for each input example from the datafile.

If using interactive mode, predictions are produced from the [`predict`](https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/reference/vowpalwabbit.pyvw.html?highlight=predict#vowpalwabbit.pyvw.vw.predict) function.

**Comment by Sandy4321** [comment]
for example for this simple data 
simple_data =  [ [ '0.1 | 4, 17' ]  , [ '0.9 |  23, 45'    ]    ]


this code works correctly 
my_vw = pyvw.vw(
    data= simple_data[0],
    passes=3,
    cache=True
)

but this code gives error
my_vw = pyvw.vw(
    data= simple_data,
    passes=3,
    cache=True
)

Traceback (most recent call last):
  Debug Console, prompt 49, line 1

  File "e:\Python environemnts\MYENVS\may9_sklearn0242\Lib\site-packages\vowpalwabbit\pyvw.py", line 348, in __init__
    super(vw, self).__init__(" ".join(l))
builtins.RuntimeError: Disagreeing option values for 'data': '['0.1' vs '['0.9


when data seems to be OK
simple_data
[['0.1 | 4, 17'], ['0.9 |  23, 45']]

**Comment by Sandy4321** [comment]
if I change data like this, then no error for training 
simple_data =  [  "0.1 | a:4 b:17'   ,  0.9 | a:23 b:45" ]


my_vw = pyvw.vw(
    data= simple_data,
    passes=3,
    cache=True
)

but error for predict 
my_vw.predict(simple_data)
Traceback (most recent call last):
  Debug Console, prompt 66, line 1
    #S_VW_with_2d_and_3d_interactions_Oct24
  File "e:\Python environemnts\MYENVS\may9_sklearn0242\Lib\site-packages\vowpalwabbit\pyvw.py", line 593, in predict
    raise TypeError("Expecting a multiline Learner.")
builtins.TypeError: Expecting a multiline Learner.

**Comment by Sandy4321** [comment]
corrected error example - data format changed :  ' was removed 
simple_data =  [  "0.1 | a:4 b:17   ,  0.9 | a:23 b:45" ]


my_vw = pyvw.vw(
    data= simple_data,
    passes=3,
    cache=True
)
my_vw.predict(simple_data)
Traceback (most recent call last):
  Debug Console, prompt 70, line 1
    #S_VW_with_2d_and_3d_interactions_Oct24
  File "e:\Python environemnts\MYENVS\may9_sklearn0242\Lib\site-packages\vowpalwabbit\pyvw.py", line 593, in predict
    raise TypeError("Expecting a multiline Learner.")
builtins.TypeError: Expecting a multiline Learner.

**Comment by jackgerrits** [comment]
`data` is a string parameter. It specifies the filename to read. Granted, the error messages you are getting are really bad and impossible to understand. Sorry about that.

If you **do** want to use data in the way you are presenting it then you'll need to save the contents to a file first.
```Python
from vowpalwabbit import pyvw

with open("mydatafile.txt", "w") as text_file:
    text_file.write("0.1 | a:4 b:17")
    text_file.write("0.9 | a:23 b:45")

my_vw = pyvw.vw(
    data="mydatafile.txt",
    passes=3,
    cache=True
)
```

If you want to process this interactively then you might want something like:
```Python
from vowpalwabbit import pyvw

data_lines = ["0.1 | a:4 b:17", "0.9 | a:23 b:45"]
my_vw = pyvw.vw()

for line in data_lines:
    print(my_vw.predict(line))
    my_vw.learn(line)

my_vw.finish()
```

**Comment by Sandy4321** [comment]
great thanks
but will be used data shuffling for each pass for
my_vw = pyvw.vw(
    data="mydatafile.txt",
    passes=3,
    cache=True
)

**Comment by jackgerrits** [comment]
No the VW command line driver does not do data shuffling.

**Comment by jackgerrits** [comment]
Hi @Sandy4321, I'm going to go ahead and close this one as I think we've answered your Qs. Please feel free to open another issue if you have more questions. Thanks!
