### ISSUE TITLE
Add label weight for cb

### ISSUE THREAD

**Issue by olgavrou** [VowpalWabbit/vowpal_wabbit#3472]
We can set importance weight for simple label, it makes sense to add it to other label types too (e.g. `cb`)

**Comment by olgavrou** [comment]
we could potentially implement multiple tags and use that to set label weights

**Comment by musram** [comment]
Hi @olgavrou. Is it straightforward to extend the weighted option to cb?

**Comment by olgavrou** [comment]
Hi @musram the simplest way to implement this for cb is to add the `weight` parsing to the cb label (see [here](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/cb.cc#L37)) similarly to the simple_label parser (see [here](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/simple_label_parser.cc#L75)) 

The catch with this approach is that we also have to add this change to other parsers (json, dsjson, flatbuffer) that we support, to be consistent. Hence the idea above to add this information though an enhanced tag. 

That been said if this is a blocker to you any contribution is welcome

**Comment by musram** [comment]
@olgavrou It is a blocker. Currently, we have found some workaround but it would be nice to have this feature implemented. I will like to try to add this feature.
Could you be more clear on this statement "Hence the idea above to add this information though an enhanced tag".  ?

**Comment by olgavrou** [comment]
Hi @musram,

After a bit of digging was able to verify that the importance of an example is currently proportional to `1 / label_prob` so what you can do is set the label probability as `label_prob = label_prob / desired_weight` and that should be a good enough workaround without needing to change the code (it's a bit of a complicated change).

Let me know if that helps

**Comment by musram** [comment]
Hi @olgavrou ,
Sorry for the late reply. I was traveling so the delay. I understood the workaround. Thanks for the help.

**Comment by olgavrou** [comment]
Closing as this is not currently on our roadmap, feel free to reopen if needed
