### ISSUE TITLE
Large output space

### ISSUE THREAD

**Issue by arita37** [VowpalWabbit/vowpal_wabbit#3482]
Hello,

Just wondering
if VW can handleLarge output space
like classification into 10**6 categories.
or any workaround to manage large output space ?

**Comment by jackgerrits** [comment]
For extreme multiclass classification Probabalistic Label Tree is a good option, used with `--plt`. You can learn more about how to use it here: https://github.com/VowpalWabbit/vowpal_wabbit/tree/master/demo/plt

However, the number of classes you are using may be a problem so I am not certain if it will work.

Another possible avenue for you to look into could be: https://www.microsoft.com/en-us/research/blog/everything-you-always-wanted-to-know-about-extreme-classification-but-were-afraid-to-ask/

**Comment by arita37** [comment]
Thanks for your reply.
Yes, my output space is a bit large….
Scratching how to make it compound hieqrchical
like this (to reduce 10 mio into block of smaller size)
    C1 (1000) —> C2 (10000)

Having 2 models each of those class groups…..

In general, it would be nice to have in VW,
although not trivial at all…..

**Comment by jackgerrits** [comment]
It looks like `plt` and `log_multi` both use a sort of hierarchical approach. But I am not sure if they are the same as what you are thinking.

**Comment by arita37** [comment]
Sure,
Just wondering if they can work 
(ie designed/tested)
with 10 million output labels….

Thx for your replies while busy.

**Comment by jackgerrits** [comment]
Honestly, I'm not sure. I don't know if they've been tested at that scale.

**Comment by arita37** [comment]
Sure thanks you.

For the infos,
found this paper on that topic
presented at Neurips:

http://proceedings.mlr.press/v139/sen21a/sen21a.pdf

**Comment by olgavrou** [comment]
Closing this issue, feel free to reopen if needed
