### ISSUE TITLE
Overflowing handling in coin

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#3501]
#### Describe the bug
It is possible to turn coin weights into inf with single example

#### To Reproduce
data.txt
```
shared |User device:10000000000
0:-1:0.5 |Action ad:1
|Action ad:1
```
command line:
`vw --cb_explore_adf --coin -d data.txt -q ::  --invert_hash weights.txt`

weights.txt:
```
Version 8.11.0
Id 
Min label:-1
Max label:0
bits:18
lda:0
0 ngram:
0 skip:
options: --cb_adf --cb_explore_adf --cb_type mtr --coin --csoaa_ldf multiline --csoaa_rank --quadratic ::
Checksum: 970181571
event_sum 1
action_sum 2
:0
User^device:10281:-nan(ind)
Constant:116060:-nan(ind)
Action^ad:119437:-nan(ind)
Action^ad*User^device:154590:-nan(ind)
User^device*User^device:200866:-nan(ind)
Action^ad*Action^ad:237946:-nan(ind)
```

#### Expected behavior
Weights should not be nan since it is unrecoverable

#### Observed Behavior
Weights are nan => Any further learning on good data is impossible

#### Environment
Windows 11, master 12/02/2021

**Comment by ataymano** [comment]
@bremen79, could you please suggest the right fix here?
Root cause is that all weights depend on average feature vector norm, so once we overflow it, nan(ind) is propagated to all weights.
I have prepared naive fix candidate - validating norm_sum before committing it and skipping example in case of overflowing:
https://github.com/VowpalWabbit/vowpal_wabbit/pull/3532 
but happy to hear other options.

**Comment by bremen79** [comment]
Sorry, I am bit rusty on this code and I don't see immediately why it overflows.
Moreover, if I remember correctly, this part of the code is taken with minor changes from the gd code, see gd.cc lines 576-587.
So, does it overflow there as well?

**Comment by ataymano** [comment]
oh you are right - it can be fixed with just operation order change. Let me send new PR

**Comment by bremen79** [comment]
Nice, it seems good to me.
