### ISSUE TITLE
Bug report on vowpal_wabbit( AddressSanitizer: FPE)

### ISSUE THREAD

**Issue by afosscontact** [VowpalWabbit/vowpal_wabbit#3542]
Describe the bug
A bug was found within the vowpal_wabbit. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using as vowpal wabbit. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "otc_algo_learn_2_action_separate_2_bandwidth_2". 
This may cause problems in the use of libraries

How To Reproduce
1. Download the attached file
2. Execute  make_vowpal_wabbit_bug1.sh
3. vowpal_wabbit/build/test/unit_test/vw-unit-test.out -t otc_algo_learn_2_action_separate_2_bandwidth_2

==44917==ERROR: AddressSanitizer: FPE on unknown address 0x000000d1d3ff (pc 0x000000d1d3ff bp 0x7ffcb468e550 sp 0x7ffcb468de40 T0)
    #0 0xd1d3ff in VW::cats_tree::min_depth_binary_tree::build_tree(unsigned int, unsigned int) vowpal_wabbit/vowpalwabbit/cats_tree.cc:97:46

Platform (please complete the following information):
OS: Ubuntu 18.04

[vowpal_bug1.tar.gz](https://github.com/VowpalWabbit/vowpal_wabbit/files/7765921/vowpal_bug1.tar.gz)

**Comment by bassmang** [comment]
Hi @afosscontact ,
Thanks for pointing this out. The issue was caused by an overflow from a large bandwidth in cats_tree, which resulted in division by 0. The PR above resolves the issue.

**Comment by junsik-kim0** [comment]
Thank you for the fast fix
This bug found in Fuzzing technology we are studying
If you have completed the modification for this bug, I want to issue CVE ID
Is it possible to issue CVE ID?
If you are enabled, you want to be issued under the name Autofuzz.
Because I am being issued as a NickName called Autofuzz in CVEs found by this Fuzzing technology.
