### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [VowpalWabbit/vowpal_wabbit#3547]
I’m trying to build vowpalwabbit aarch64 wheels but it requires `vowpalwabbit/manylinux2010-build` image which is not available for aarch64. 

@jackgerrits, Could you please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by jackgerrits** [comment]
Hey @odidev, aarch64 wheels would be excellent. Thanks for your help here!

**Comment by jackgerrits** [comment]
With your two PRs this is now complete, I'll be including these wheels in the upcoming release. Thanks again for your work here @odidev
