### ISSUE TITLE
Minibatch batch option missing

### ISSUE THREAD

**Issue by lengstrom** [VowpalWabbit/vowpal_wabbit#355]
Hi,

There seems to be no minibatch option, is there any way to set minibatch size on sgd?

Error:

```
>vw --sgd --holdout_off --l1 1 --l2 0 -k -d data_in.tsv -f ./0.hashed_regressor --cache_file ./0.cache --passes 1000 --initial_weight 0 --initial_t 0.01 --minibatch 20
using l1 regularization = 1e+28
final_regressor = ./0.hashed_regressor
Num weight bits = 18
learning rate = 1
initial_t = 0.01
power_t = 0.5
decay_learning_rate = 1
vw: unrecognised option '--minibatch'
```

`vw --version` reports 7.7.0

**Comment by rleonid** [comment]
Would you welcome a PR that changes this (enable batch size arguments for sgd) or do you generally find it not that useful as one can tweak the `decay_learning_rate` instead?

**Comment by JohnLangford** [comment]
Supporting minibatching has some value in the sense that many learning
algorithms need a minibatch (example: GPU based one).   Nevertheless, I'd
like to see tests showing this is useful before complicating the code with
it, and I'd like to see a design which avoids as much complication as
possible.  Minibatching can become messy quickly with the wrong design.

**Comment by rleonid** [comment]
Those are good points and when I looked through the vw code base I quickly realized the difficulty of such a change. I mistakenly assumed that logic for handling mini-batches was already implemented but that the command-line parsing was broken. The argument is still in the wiki in the Update Rule options and I hadn't noticed the "and it's only enabled there" part. Maybe it makes more sense to have that paragraph only under the LDA section?

**Comment by JohnLangford** [comment]
That makes sense.

-John
