### ISSUE TITLE
Bug while building from source

### ISSUE THREAD

**Issue by musram** [VowpalWabbit/vowpal_wabbit#3640]
#### Describe the bug
We followed the instruction provided by the https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Building, but were unable to build the binary.

#### To Reproduce

git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git
cd vowpal_wabbit

sudo apt install libboost-dev libboost-thread-dev libboost-program-options-dev libboost-system-dev libboost-math-dev libboost-test-dev zlib1g-dev cmake g++

sudo apt install libflatbuffers-dev

sudo apt install libboost-python-dev

cmake -S . -B build

#### Expected behavior
build directory should be there.

#### Observed Behavior
CMake Error: The source directory "/home/contributor/vowpal_wabbit/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

#### Environment
What version of VW did you use?
8.11.0
What OS or language did you use?
Linux

`VW 811.0 on Linux with the Python bindings`

#### Additional context
We also tried :
make 

but it gives the error, after building the directory build it gives error
CMake Error: The source directory "/home/contributor/vowpal_wabbit/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by jackgerrits** [comment]
What version is the cmake you used?

**Comment by musram** [comment]
@jackgerrits  we resolved it like this
mv vowpal_wabbit build
rm /home/contributor/build/CMakeCache.txt
cmake -S . -B build
cmake --build /home/contributor --target vw-bin

Its working. We were still using old version of CMake
