### ISSUE TITLE
Development Guide

### ISSUE THREAD

**Issue by tallalnparis4ev** [VowpalWabbit/vowpal_wabbit#3662]
Hey everyone, I'm looking to start contributing to VW. 

I'm wanting to setup my dev machine (I'm on Mac using VSCode typically) so that I can debug VW. I haven't setup any C++ projects before. I was just wondering if there is a contributors guide that I could youse. If it doesn't exist already would it be possible someone could help me get setup? Then I could then add some documentation to help other future developers.

**Comment by jackgerrits** [comment]
Welcome! For some general info you can check out [CONTRIBUTING.md](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/CONTRIBUTING.md)

You can see [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#macos) for what dependencies are required to build for MacOS. We use CMake for the build definition you can learn more about that [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Building#linux). But once you have the dependencies it's as simple as:
```sh
cmake -S . -B build
cmake --build build --parallel $(nproc) --target vw-bin
```

The [CMake Tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools) extension is quite good and makes it easy to debug the executable. There's a docs page on how to use that extension for debugging [here](https://code.visualstudio.com/docs/cpp/cmake-linux#_debug-hello-world).

There is some more useful info on [this page](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Maintainer-Info).

**Comment by jackgerrits** [comment]
I'm going to go ahead and close this, if you have any more questions please don't hesitate to reach out.
