### ISSUE TITLE
run_tests.py --fuzzy_compare fails on on ppc, aarch, and arm due to numerical tolerance

### ISSUE THREAD

**Issue by ngam** [VowpalWabbit/vowpal_wabbit#3674]
#### Describe the bug
Running `python run_tests.py --fuzzy_compare` fails on macos arm64 (m1 macs) as well as aarch64 (linux arm) and ppc64le (linux powerpc). In all cases, the failures are to do with numerical accuracy.

#### To Reproduce
1. build for arm64, aarch64 or ppc64le
2. run `python run_tests.py --fuzzy_compare` 
3. see failures due to numerical accuracy

#### Expected behavior
Running `python run_tests.py --fuzzy_compare` on x86_64 macos (intel macs) and linux works fine.

#### Observed Behavior
sumamry
```
# Success: 294
# Fail: 76
# Skip: 24
```
with failures like: 
```diff
Test 384: Fail
	Description: Marginal --invert_hash features check
	vw _command: "$PREFIX/bin/vw --marginal f -d train-sets/marginal_features --noconstant --initial_numerator 0.5 --initial_denominator 1.0 --decay 0.001 --invert_hash marginal_invert_hash_readable_model.txt "
	[marginal_invert_hash_readable_model.txt] Fail: Diff not OK, Floats don't match 0.886106 0.886291

--- train-sets/ref/marginal_invert_hash_readable_model.txt
+++ marginal_invert_hash_readable_model.txt
@@ -19,7 +19,7 @@
 initial_t 0
 norm normalizer 7.56231
 t 4
-sum_loss 0.886291
+sum_loss 0.886106
 sum_loss_since_last_dump 0
 dump_interval 8
 min_label 0
@@ -34,5 +34,5 @@
 current_pass 1
 l1_state 0
 l2_state 1
-f^constant:17187:0.527579 0.886291 0.5
-f^constant2:261506:0.516337 0.883632 0.5
+f^constant:17187:0.527469 0.886106 0.5
+f^constant2:261506:0.51619 0.883434 0.5
```
#### Environment

VW 9.0.0 on Linux and MacOS with the Python bindings.

#### Additional context
Part of the effort to improve the build at conda-forge: https://github.com/conda-forge/vowpalwabbit-feedstock.

**Comment by jackgerrits** [comment]
They likely need a more lenient tolerance `--epsilon`. The default is currently `1e-4`.

We have an issue to explore some sort of stable math mode but this is not currently being worked on and not clear if it'll work. https://github.com/VowpalWabbit/vowpal_wabbit/issues/3589

**Comment by jackgerrits** [comment]
I'm going to close this as it's a known issue that math seems to not be exactly stable on other platforms. Based on the diff it is within some acceptable tolerance. #3589 looks to address this but for now this is accepted behavior.
