### ISSUE TITLE
square cb exploration outputs non-pmf predictions

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#3680]
#### Describe the bug
It is possible to get non-pmf predictions using "--cb_explore_adf --squarecb ..." kind of command lines

#### To Reproduce
data.json
```
{"_label_cost":-0.2,"_label_probability":0.5,"_label_Action":1,"_labelIndex":0,"a":[1,2],"c":{"shared":{"f":"1"},"_multi":[{"a":{"f":"0"}},{"a":{"f":"1"}}]},"p":[0.5,0.5]}
{"_label_cost":-0.3,"_label_probability":0.5,"_label_Action":2,"_labelIndex":1,"a":[2,1],"c":{"shared":{"f":"0"},"_multi":[{"a":{"f":"0"}},{"a":{"f":"1"}}]},"p":[0.5,0.5]}
```
command line:
```
vw --cb_explore_adf --dsjson --squarecb -p pred.txt -d data.json
```

#### Expected behavior
pred.txt has valid probabilities (between 0 and 1, summing up to 1)

#### Observed Behavior
pred.txt:
```
0:0,1:0

0:-0.127094,1:-0.0635469
```

#### Environment
Windows, 9.0.0 (git commit: ce5d82b22)

**Comment by jackgerrits** [comment]
Closed in #3683
