### ISSUE TITLE
What differs between the Python API and the Command Line implementation when applying multipass?

### ISSUE THREAD

**Issue by phate09** [VowpalWabbit/vowpal_wabbit#3691]
#### Describe the bug
When training a supervised learning regressor, the behaviour (and results) change when using the command line interface as opposed to the python API. This is made worse in the case of multipass. Why is this happening? shouldn't they return the same values?

#### To Reproduce
1. run `simple_toy_linear.py`
2. change number of `passes` or disable shuffling
3. notice the differences in RMSE

#### Expected behavior
RMSE should be the same between the 2 implementations. 

#### Observed Behavior
This behaviour gets worse with bigger dataset and non-linear models

#### Environment
[simple_toy_linear.py.zip](https://github.com/VowpalWabbit/vowpal_wabbit/files/7996499/simple_toy_linear.py.zip)

 `vowpalwabbit=8.11.0 on Linux with the Python bindings` and
 `VW 8.11.0 (git commit: 13b307354) on Linux with the Command Line`

**Comment by jackgerrits** [comment]
Using [this](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/test/train-sets/0002.dat) datafile I get the same results for each version.

```
Python
RMSE:0.12237292248702325 R2:0.9396103149187821
CLI
RMSE:0.12237292248702325 R2:0.9396103149187821
```

Would you be able to share the datafile you used?

**Comment by phate09** [comment]
Maybe a change that went undetected was on line 67 with the number of passes. 
[simple_toy_linear.py.zip](https://github.com/VowpalWabbit/vowpal_wabbit/files/7997077/simple_toy_linear.py.zip)
I've updated the code example using your dataset and I get the following values (I've also changed line 35 and 38 to calculate the RMSE):
```
Python
RMSE:0.05605489953218184 R2:0.4621069010281076
CLI
RMSE:0.0273055182904848 R2:0.8723650348501524
```
just by executing the file as is

**Comment by jackgerrits** [comment]
I see, thanks for the clarification. Looking now.

**Comment by jackgerrits** [comment]
It looks like doing multiple passes in the Python code is consuming the file iterator on the first pass and then not working on subsequent passes. If you reorder the two lines such that the file is opened for each pass then I was able to get identical results.

```Python
for epoch in range(passes):
    with open(file_path, "r") as f:
        lines = []
        for line in f:
            lines.append(line)
        if shuffle:
            np.random.shuffle(lines)
        for line in lines:
            model.learn(line)
```

**Comment by phate09** [comment]
I see, such a silly mistake from my side.  Thanks for the help in resolving this issue. Getting the same results on both implementations also helped me shed some light over the inner workings of VW.
All the bests

**Comment by jackgerrits** [comment]
Not a problem at all. Happy to help!
