### ISSUE TITLE
VW 8.11.0 not available anymore from PIP

### ISSUE THREAD

**Issue by andreacimino** [VowpalWabbit/vowpal_wabbit#3718]
#### Describe the bug
VW 8.11.0 is not avialable from pip anymore, breaking previosly functioning code.

#### To Reproduce
pip3 install vowpalwabbit==8.11.0
ERROR: Could not find a version that satisfies the requirement vowpalwabbit==8.11.0 (from versions: 8.2.0, 8.2.1, 8.3.2, 8.4.0, 8.5.0, 8.7.0, 8.7.0.post1, 8.8.0, 8.8.1, 8.9.0, 8.10.0, 8.10.1, 8.10.2, 9.0.0, 9.0.1)
ERROR: No matching distribution found for vowpalwabbit==8.11.0

**Comment by andreacimino** [comment]
Sorry, i was in a ARM platform, just noticed that is ok (obviously having this package version on ARM would be nice).

**Comment by jackgerrits** [comment]
8.11.0 is particular had an issue where the source distribution was broken so we had to yank it. Since there was no ARM wheels before 9.0.0 it didn't have any artifacts that could be used on that platform for that specific version
