### ISSUE TITLE
Consider supporting JS NaN values in JSON datasets

### ISSUE THREAD

**Issue by Ark-kun** [VowpalWabbit/vowpal_wabbit#3738]
## Short description

While `NaN` (and `Infinity`) is not directly supported by the JSON specification, they are valid Javascript and multiplt JSON libraries produce such values when serializing to JSON. One example is Python's built-in JSON serializer which produces `naN` values by default: https://docs.python.org/3/library/json.html#infinite-and-nan-number-values

```js
{"_label": 1, "features": {"f1": NaN}}
```

Currently, `vw` fails with the following error:
```
[error] vw example #7(parse_example_json.h:1730): JSON parser error at 129: Invalid value.. Handler: State: Default
[critical] vw (parse_example_json.h:1730): JSON parser error at 129: Invalid value.. Handler: State: Default
```

**Comment by jackgerrits** [comment]
I believe not supporting `NaN` was an intentional choice. If `NaN`s make it into the model they tend to spread and poison the model since anything multiplied by a `NaN` also becomes a `NaN`. It seems like being able to use `NaN` doesn't really allow for anything extra to be achieved. If you think `NaN`s could serve a purpose then please explain the use case.

The error message is clearly uninformative though. It should explain that `NaN` is the issue here and why it is a disallowed value.

**Comment by jackgerrits** [comment]
Reading over this again I realize the extra part that NaN is not valid JSON despite being supported in some implementations. RapidJSON does support NaN but given the fact that I cant see a compelling reason to allow NaNs to be parsed I am still not sure it is a good idea to turn it on.

**Comment by jackgerrits** [comment]
We're not planning on supporting NaN as input value in the JSON format as VW doesn't know what the user expects to do with it. My recommendation would be convert NaNs based on intended semantics:

- Feature does not exist or should be ignored-> `0`
- Feature does exist `1`

Closing as by-design for now. If you feel strongly or have a use case that is not covered then please feel free to reopen or continue the discussion.

**Comment by Ark-kun** [comment]
The reason I decided to suggest this feature was because I saw the existing
[Support interpreting the string NaN as a float nan in dsjson](https://github.com/VowpalWabbit/vowpal_wabbit/pull/2256) feature PR. I thought that since one encoding of NaN is supported, why not another. Especially given that the parser is custom.

**Comment by jackgerrits** [comment]
I had forgotten about this sorry! Thanks for referencing to it. Let me have a think and get back to this
