### ISSUE TITLE
Cannot learn from multiline contextual bandit (--cb_explore_adf) in Python

### ISSUE THREAD

**Issue by chanind** [VowpalWabbit/vowpal_wabbit#3757]
#### Describe the bug
I cannot get the VW Python wrapper to accept the multiline input format needed for `--cb_explore_adf` either as a string, or list of strings, or list of dicts. When using strings, I get the error `RuntimeError: cb_adf: badly formatted example, only one line can have a cost`. When using dicts, I get the error `TypeError: sequence item 0: expected str instance, dict found`.

The input formats are what's shown in the Wiki for JSON and string: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/JSON

#### To Reproduce

```python
import vowpalwabbit

vw = vowpalwabbit.Workspace("--cb_explore_adf --cover 3 ")


data_strs = [
"""
shared | UserAge:15
| elections maine SourceTV
0:-1:.3 | Sourcewww topic:4
""",
"""
shared | UserAge:13
| elections maine SourceWeb
0:0:.3 | Sourcewww topic:3
""",
]

vw.learn(data_strs)
# ERROR: RuntimeError: cb_adf: badly formatted example, only one line can have a cost

vw.learn("\n\n".join(data_strs))
# ERROR: RuntimeError: cb_adf: badly formatted example, only one line can have a cost


data_dicts = [
    {
        "UserAge": 15,
        "_multi": [
            {"_text": "elections maine", "Source": "TV"},
            {"Source": "www", "topic": 4, "_label": "0:-1:.3"},
        ],
    },
    {
        "UserAge": 13,
        "_multi": [
            {"_text": "elections maine", "Source": "Web"},
            {"Source": "www", "topic": 3, "_label": "0:0:.3"},
        ],
    },
]
vw.learn(data_dicts)
# ERROR: TypeError: sequence item 0: expected str instance, dict found

vw.learn([vw.example(ex) for ex in data_dicts])
# ERROR: TypeError: sequence item 0: expected str instance, dict found
```

#### Expected behavior
Surely one or all of these formats should work successfully? These formats work when saved to a file and loaded with the `-d` command, so I'm confident the format is correct. Or does the Python wrapper not support `--cb_explore_adf` at all?

#### Observed Behavior
For the string inputs, it crashes with `ERROR: RuntimeError: cb_adf: badly formatted example, only one line can have a cost`
For the dict inputs, it crashes with `ERROR: TypeError: sequence item 0: expected str instance, dict found`

#### Environment
`VW 9.0.1 on OSX with the Python bindings`

**Comment by jackgerrits** [comment]
The [`Workspace.learn`](https://vowpalwabbit.org/docs/vowpal_wabbit/python/9.0.0/reference/vowpalwabbit.html#vowpalwabbit.Workspace.learn) function expects to be called once per example. It does not currently support being given all examples at once.

So you can change your code to:
```python
import vowpalwabbit

vw = vowpalwabbit.Workspace("--cb_explore_adf --cover 3")

data_strs = [
"""
shared | UserAge:15
| elections maine SourceTV
0:-1:.3 | Sourcewww topic:4
""",
"""
shared | UserAge:13
| elections maine SourceWeb
0:0:.3 | Sourcewww topic:3
""",
]

for item in data_strs:
    vw.learn(item)
```

For the the JSON example. You unfortunately cannot supply DSJSON format directly as a Python dictionary. If you wish to use DSJSON from Python you can send it as a string. You also need to let the workspace know that you're using this format. This could be done like so:

```python
import vowpalwabbit
import json

vw = vowpalwabbit.Workspace("--cb_explore_adf --cover 3 --dsjson")
data_dicts = [
    {
        "UserAge": 15,
        "_multi": [
            {"_text": "elections maine", "Source": "TV"},
            {"Source": "www", "topic": 4, "_label": "0:-1:.3"},
        ],
    },
    {
        "UserAge": 13,
        "_multi": [
            {"_text": "elections maine", "Source": "Web"},
            {"Source": "www", "topic": 3, "_label": "0:0:.3"},
        ],
    },
]

for item in data_dicts:
    vw.learn(json.dumps(item))
```

**Comment by chanind** [comment]
Interesting, the MyPy types say it accepts a `List[str]` or `List[Example]` as valid inputs, is that a mistake? Is the end result identical feeding in each example 1 by 1 to `.learn()` compared with importing everything as a single file the `-d` option?

**Comment by jackgerrits** [comment]
The typing is correct but the docstring could do better to explain why. `List[str]` corresponds to the format you have given, multiline format, where each input example spans multiple lines (context, actions). It can be supplied either in a string with newlines or a list of lines themselves. If you were to supply multiple lines of single line format (simple regression for example) you would receive an error stating that a single line learner expects a single input example.

The end result is identical except for if when using the CLI you did something like multiple passes.

**Comment by chanind** [comment]
OK, I'll close this then. Thank you for the quick response and great explanation!
