### ISSUE TITLE
The MSVC team recently test VowpalWabbit project failed to run "vw_unit_test" test on release and debug configuration on Windows_x86 and windows_x64.

### ISSUE THREAD

**Issue by rachelhe123** [VowpalWabbit/vowpal_wabbit#3767]
Hi All,

The MSVC team recently test VowpalWabbit project failed to run "vw_unit_test" test on release and debug configuration on Windows_x86 and windows_x64. Below are details of this issue:

**Describe the bug**

VowpalWabbit failed to run run "vw_unit_test" test on release and debug configuration with MSVC on windows x86 and x64. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**Error message**
    Start 1: vw_unit_test
1/1 Test #1: vw_unit_test .....................***Failed    1.71 sec
Running 289 test cases...
F:/gitP/VowpalWabbit/vowpal_wabbit/test/unit_test/automl_weights_test.cc(93): error: in "automl_weight_operations": check ARE_SAME: expected: 0.0105546 not equal to 0.010579
F:/gitP/VowpalWabbit/vowpal_wabbit/test/unit_test/automl_weights_test.cc(110): error: in "automl_weight_operations": check ARE_SAME: expected: 0.0105546 not equal to 0.010579
F:/gitP/VowpalWabbit/vowpal_wabbit/test/unit_test/automl_weights_test.cc(128): error: in "automl_weight_operations": check ARE_SAME: expected: 0.0105546 not equal to 0.010579
F:/gitP/VowpalWabbit/vowpal_wabbit/test/unit_test/automl_weights_test.cc(129): error: in "automl_weight_operations": check ARE_SAME: expected: 0.0105546 not equal to 0.010579

*** 4 failures are detected in the test module "Main"
0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.79 sec
The following tests FAILED:
          1 - vw_unit_test (Failed)
Errors while running CTest

**Expected behavior**
For Vowpal_wabbit x86 and x64, "vw_unit_test" test should be run pass on the windows.

**To Reproduce on Windows**
	1. git clone [(https://github.com/VowpalWabbit/vowpal_wabbit)](https://github.com/VowpalWabbit/vowpal_wabbit) F:\gitP\VowpalWabbit
	2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
	3. cd F:\gitP\Microsoft\vcpkg
	4. bootstrap-vcpkg.bat 2>&1
	5. vcpkg.exe install --recurse zlib boost-system boost-program-options boost-test boost-align boost-foreach boost-math boost-python python3 flatbuffers --triplet x64-windows --clean-after-build 2>&1
	6. mkdir F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64
	7. cd F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64
	8. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DUSE_LATEST_STD=ON -Dvw_BUILD_NET_FRAMEWORK=OFF -DBUILD_FLATBUFFERS=ON -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .. 2>&1
	9. msbuild /m /p:Platform=x64 /p:Configuration=Release vowpal_wabbit.sln /t:Rebuild /p:BuildInParallel=true 2>&1
	10. cd F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64
	12. ctest --build-config Release --output-on-failure  2>&1

**Setup**
VS 2019 + Windows Server 2019

**Additional context**
test logs
[test.log](https://github.com/VowpalWabbit/vowpal_wabbit/files/8177122/test.log)
[test.log.2.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/8177123/test.log.2.txt)

**Comment by jackgerrits** [comment]
@lalo looks like there is a too tight of a tolerance in the AutoML tests for Windows here?
