### ISSUE TITLE
[MSVC][std:c++latest] Vowpal_wabbit failed to build with error C7595 on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [VowpalWabbit/vowpal_wabbit#3861]
### Describe the bug

Hi all,

The MSVC team added Vowpal_wabbit as part of RWC testing. Recently we found error C7595 when building Vowpal_wabbit with '/std:c++latest'. I opened a internal bug and the developer considered this to be a source issue. Could you please take a quick look at the issue? Thanks in advance.

I attached the repro code and it includes our workaround. I was going to apply this patch at first, but many lines are triggering this issue, could you fix it?

**Refer to the developer's explanation:**
A C string argument is passed to the call to logger_impl::err_critical(), and the body of the function attempts to convert the string to a fmt::basic_format_string using the consteval constructor. The folding of the consteval constructor call rightfully fails, since the constructor argument is fmt, a function parameter that has unknown value outside of the invocation of its function. To avoid this error, the conversion to fmt::basic_format_string needs to occur at the call site for logger_impl::err_critical(), which can be forced by changing the function signature for logger_impl::err_critical() so that it takes a fmt::basic_format_string parameter. The other functions in logger_impl may need to be similarly changed to avoid similar issues.

### How to reproduce

**Repro:**
1. open VS2019 v16.11.11  x64 tools command
2. cl.exe /std:c++latest bug_1505946.cpp

Repro code: [bug_1505946.cpp.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/8471307/bug_1505946.cpp.txt)
Build log on MSVC: [build.log](https://github.com/VowpalWabbit/vowpal_wabbit/files/8471426/build.log)

**Error**:
Correspond https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/io/logger.h#L135

```bug_1505946.cpp
bug_1505946.cpp(132): error C7595: 'fmt::basic_format_string<char,size_t &>::basic_format_string': call to immediate function is not a constant expression
bug_1505946.cpp(132): note: failure was caused by a read of a variable outside its lifetime
bug_1505946.cpp(132): note: see usage of 'fmt'
bug_1505946.cpp(160): note: see reference to function template instantiation 'void VW::io::details::logger_impl::err_critical<char[90],size_t&>(const FormatString (&),size_t &)' being compiled
        with
        [
            FormatString=char [90]
        ]
bug_1505946.cpp(135): error C7595: 'fmt::basic_format_string<char,size_t &>::basic_format_string': call to immediate function is not a constant expression
bug_1505946.cpp(135): note: failure was caused by a read of a variable outside its lifetime
bug_1505946.cpp(135): note: see usage of 'fmt'
bug_1505946.cpp(139): error C7595: 'fmt::basic_format_string<char,size_t &>::basic_format_string': call to immediate function is not a constant expression
bug_1505946.cpp(139): note: failure was caused by a read of a variable outside its lifetime
bug_1505946.cpp(139): note: see usage of 'fmt'```

### Version

master branch 7916bd4

### OS

Windows

### Language

C++

### Additional context

_No response_

**Comment by jackgerrits** [comment]
Thanks for the detailed report! Should be fixed by #3862

**Comment by QuellaZhang** [comment]
@jackgerrits. Thanks for the quick fix. I tried your fix and found there still are many errors `logger.h` which using `template <typename... Args>` , after I fixed them then I got the same errors in other files, attached the build log.

[build_fix.log](https://github.com/VowpalWabbit/vowpal_wabbit/files/8477887/build_fix.log)

**Comment by jackgerrits** [comment]
I've pushed another commit resolving what looks to be the 3 more build issues in that log. Could you let me know if that fixes things?

**Comment by QuellaZhang** [comment]
Yes, errors in the last build log have been fixed. New errors:

```
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\io\include\vw/io/logger.h(143,81): error C7595: 'fmt::v8::basic_format_string<char,size_t &>::basic_format_string': call to immediate function is not a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\io\vw_io.vcxproj]
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\io\include\vw/io/logger.h(146,39): error C7595: 'fmt::v8::basic_format_string<char,size_t &>::basic_format_string': call to immediate function is not a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\io\vw_io.vcxproj]
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\io\include\vw/io/logger.h(150,39): error C7595: 'fmt::v8::basic_format_string<char,size_t &>::basic_format_string': call to immediate function is not a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\io\vw_io.vcxproj]
```

```
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\cost_sensitive.cc(243,27): error C3615: constexpr function 'fmt::v8::basic_format_parse_context<char,fmt::v8::detail::error_handler>::on_error' cannot result in a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\vw.vcxproj]
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\parse_example.cc(106,34): error C7595: 'fmt::v8::basic_format_string<char>::basic_format_string': call to immediate function is not a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\vw.vcxproj]
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\parse_args.cc(417,62): error C7595: 'fmt::v8::basic_format_string<char>::basic_format_string': call to immediate function is not a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\vw.vcxproj]
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\reductions\boosting.cc(367,39): error C3615: constexpr function 'fmt::v8::basic_format_parse_context<char,fmt::v8::detail::error_handler>::on_error' cannot result in a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\vw.vcxproj]
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\reductions\bs.cc(259,27): error C3615: constexpr function 'fmt::v8::basic_format_parse_context<char,fmt::v8::detail::error_handler>::on_error' cannot result in a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\vw.vcxproj]
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\reductions\cb\cb_adf.cc(538,9): error C3615: constexpr function 'fmt::v8::basic_format_parse_context<char,fmt::v8::detail::error_handler>::on_error' cannot result in a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\vw.vcxproj]
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\reductions\search\search.cc(2499,21): error C7595: 'fmt::v8::basic_format_string<char>::basic_format_string': call to immediate function is not a constant expression [F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64\vowpalwabbit\vw.vcxproj]
```

**Comment by jackgerrits** [comment]
Accidentally auto-closed this by the PR. I think this is fixed now, as this CI is running the windows build with C++20 enabled.

https://github.com/VowpalWabbit/vowpal_wabbit/pull/3872

**Comment by QuellaZhang** [comment]
@jackgerrits Fixed. Thanks!!!

**Comment by jackgerrits** [comment]
Great! Thanks for your help with this!
