### ISSUE TITLE
Zlib missing when building a statically linked VowpalWabbit on MacOs 12

### ISSUE THREAD

**Issue by rami-lv** [VowpalWabbit/vowpal_wabbit#3879]
### Describe the bug

I am trying to build a statically linked version on my MacOs 12.1 arm64. 
CMake is not able to find the correct location of zlib library. 

Changing the zlib location here: https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/CMakeLists.txt#L188
to 
```
zsh> brew --prefix zlib 
/opt/homebrew/opt/zlib
```
seems to fix the problem. 

### How to reproduce

Build command:  
`cmake -S . -B build -DSTATIC_LINK_VW=ON  -DCMAKE_BUILD_TYPE=Release` 

Output: 
```
CMake Error at /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindZLIB.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  ext_libs/ext_libs.cmake:70 (find_package)
  CMakeLists.txt:223 (include)

```

### Version

9.1.0

### OS

macOS12.1 arm64

### Language

Cmake

**Comment by jackgerrits** [comment]
You can specify where CMake should search by specifying `ZLIB_ROOT`. So in your situation your command would be:
```
cmake -S . -B build -DSTATIC_LINK_VW=ON -DCMAKE_BUILD_TYPE=Release -DZLIB_ROOT=/opt/homebrew/opt/zlib/
```

**Comment by rami-lv** [comment]
Thanks that works for me

**Comment by jackgerrits** [comment]
Great! I'm going go ahead and close this then. Feel free to reopen or make a new issue if you have other problems.
