### ISSUE TITLE
[MSVC][permissive-] Vowpal_wabbit failed to run test on windows_x86 with MSVC option /permissive-

### ISSUE THREAD

**Issue by Zhaojun-Liu** [VowpalWabbit/vowpal_wabbit#3886]
### Describe the bug

Hi All,

The MSVC team added Vowpal_wabbit as part of RWC testing. Recently it failed to run test on Windows_x86 with msvc option /permissive-. Below are details of this issue:

**Error Message**
Start 5: vw_slim_test
5/6 Test #5: vw_slim_test .....................***Failed    0.27 sec

[ RUN      ] VowpalWabbitSlim/PredictTest.Run/14
F:\gitP\VowpalWabbit\vowpal_wabbit\vowpalwabbit\slim\test\ut_util.cc(103): error: Expected equality of these values:
  0
  vw.load((const char*)td.model, td.model_len)
    Which is: 1
[  FAILED  ] VowpalWabbitSlim/PredictTest.Run/14, where GetParam() = regression_data_6 regression_data_3.txt sparse (0 ms)
......
[  FAILED  ] 1 test, listed below:
[  FAILED  ] VowpalWabbitSlim/PredictTest.Run/14, where GetParam() = regression_data_6 regression_data_3.txt sparse

 1 FAILED TEST

    Start 6: vw_unit_test
6/6 Test #6: vw_unit_test .....................   Passed    1.61 sec

83% tests passed, 1 tests failed out of 6

Label Time Summary:
VWTestList    =   2.03 sec*proc (6 tests)

Total Test time (real) =   2.08 sec

The following tests FAILED:
	  5 - vw_slim_test (Failed)
Errors while running CTest

**Expected behavior**
run test pass on windows_x86 with msvc option /permissive-

**Detailed log :**
[test.log](https://github.com/VowpalWabbit/vowpal_wabbit/files/8510508/test.log)
[test.log.2.out.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/8510509/test.log.2.out.txt)

### How to reproduce

1. git clone [(https://github.com/VowpalWabbit/vowpal_wabbit)](https://github.com/VowpalWabbit/vowpal_wabbit) F:\gitP\VowpalWabbit
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86 & set _CL_= /permissive-
3. cd F:\gitP\Microsoft\vcpkg
4. bootstrap-vcpkg.bat 2>&1
5. vcpkg.exe install --recurse zlib boost-system boost-program-options boost-test boost-align boost-foreach boost-math boost-python python3 flatbuffers --triplet x64-windows --clean-after-build 2>&1
6. mkdir F:\gitP\VowpalWabbit\vowpal_wabbit\build_x86
7. cd F:\gitP\VowpalWabbit\vowpal_wabbit\build_x86
8. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DUSE_LATEST_STD=ON -Dvw_BUILD_NET_FRAMEWORK=OFF -DBUILD_FLATBUFFERS=OFF -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows .. 2>&1
9. msbuild /m /p:Platform=Win32 /p:Configuration=Release vowpal_wabbit.sln /t:Rebuild /p:BuildInParallel=true 2>&1
10. ctest --build-config Release --output-on-failure 2>&1

### Version

git commit : 465c1b05e86957b4a16ee2f6327f74fd9764d98d

### OS

Windows 

### Language

C++

**Comment by jackgerrits** [comment]
VW is not officially currently supported on x86. There is a CI tracking compile warnings for this target https://github.com/VowpalWabbit/vowpal_wabbit/actions/workflows/build_windows_x86.yml. It is not certain whether we wish to support 32 bit builds officially or not.

**Comment by Zhaojun-Liu** [comment]
Ok, I got it, thanks for your reply. I will disable it on x86 until you support 32 bit builds officially.
