### ISSUE TITLE
Failing to persist model's metrics after saving and reloading (Python API) 

### ISSUE THREAD

**Issue by Bernardo-Favoreto** [VowpalWabbit/vowpal_wabbit#3918]
### Describe the bug

I'm using the Python API to train, save, and load a model. After training, the model stores important metrics via the methods `.get_sum_loss()` and `get_weighted_examples()`. However, when I try to load the model I've just saved, VW returns 0 for both of the methods. 

I expected VW to preserve the previous state (before saving the model) so that I could evaluate my loaded model. For example, when I want to test different policies against the production policy, I need to load the production one and assess how well it is performing, and that should become the baseline to beat.

**Note:** I tried to add `--preserver_performance_counters` when defining the initial model but that was no help.

### How to reproduce

1. Instantiate a CB model: `vw = vowpalwabbit.Workspace("--cb_explore_adf -q UA --quiet --cb_type ips --preserve_performance_counters")`
2. Use the following labeled example: `train_data = ['shared |User user=Bernardo time_of_day=afternoon',
 '|Action article=politics',
 '|Action article=sports',
 '|Action article=music',
 '|Action article=formulaOne',
 '|Action article=finance',
 '|Action article=health',
 '0:-1.0:0.9571428557458732 |Action article=tennis']`
3. Learn this example: `vw.learn(train_data)`
4. Print `vw.get_sum_loss()` (yields -0.149) and `vw.get_weighted_examples()` (yields 1)
5. Save the model: `vw.save("./vw.model") `
6. Load the model: `loaded_model = vowpalwabbit.Workspace("-i vw.model")`
7. Print `vw.get_sum_loss()` (yields 0) and `vw.get_weighted_examples()` (yields 0)

### Version

9.1.0

### OS

Linux

### Language

Python

### Additional context

I'm trying to evaluate the performance of a saved model, but VW fails to persist the required information.

**Comment by jackgerrits** [comment]
I started looking into this and it seems like `--preserve_performance_counters` is required for the model load as well. Can you try adding that and see if it resolves the issue?

**Comment by jackgerrits** [comment]
I believe this is resolved, please feel free to reopen if there are further issues or questions
