### ISSUE TITLE
Issue with predictions with nn and lrqfa or lrq

### ISSUE THREAD

**Issue by thmavri** [VowpalWabbit/vowpal_wabbit#3921]
Let's say you have a file named vwinputsample.txt with these 4 rows

```
1 'A |a b=1 |b c=0 d=2 e=0 |c f:10 
-1 'B |a b=0 |b c=0 d=2 e=2 |c f:0 
1 'C |a b=3 |b c=0 d=2 e=0 |c f:6 
-1 'D |a b=0 |b c=0 d=2 e=1 |c f:2
```

And a python script vwproduceinput.py that prints these 4 rows 1000 times 

```
f = open("vwinputsample.txt")

lines = []
for l in f:
   lines.append(l.strip("\n"))

for i in range(0,1000):
   for k in lines:
      print(k)
```
And you train a model with lrqfa and nn as following

```
python3 vwproduceinput.py | vw -f model_sample.vw --nn 10 --lrqfa abc2 --link logistic --loss_function logistic -b 27 --l2 1e-7 --l1 1e-7;
```

If you do 
```
cat vwinputsample.txt | vw -i model_sample.vw -t --progress 1 -p preds.txt;
less preds.txt;
```
you get
```
0.999988 A
0.000059 B
0.999948 C
0.000112 D
```
While if you do 
```
cat vwinputsample.txt | tail -r | vw -i model_sample.vw -t --progress 1 -p predsr.txt;
less predsr.txt;
```
you get
```
0.000043 D
0.999700 C
0.000018 B
0.999926 A
```

If you go and get only one line from the file each time and predict 
```
cat vwinputsample.txt | while read p; do echo "$p" | vw -i model_sample.vw -t --progress 1 -p /dev/stdout >> predsline.txt; done;
less predsline.txt;
```
you get

```
0.999988 A
0.000018 B
0.999948 C
0.000043 D
```

So when you predict in the whole file, lines 1 and 3 correspond to the predictions line by line, and not in lines 2 and 4.

The same issue holds when you use lrq e.g.  --lrq ab2 instead of lrqfa. It does not appear when you use -q ab.

**Comment by olgavrou** [comment]
Thank you for opening the issue @thmavri 

The bug seems to be with lrqfa. For reference there is a variable used ([here](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/core/src/reductions/lrqfa.cc#L56) ) which is dependent on the internal example counter, and therefore the order of examples will affect the prediction
