### ISSUE TITLE
Counterintuitive namespaces collision

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#3925]
### Describe the bug

Because of internally root namespace is represented as " " it actually collides with any nontrivial namespace started with ' ' which is confusing.

Potential workaround: represent root namespace internally using some unprintable character similarly to slot namespace (although it is breaking change in terms of feature hashes)

### How to reproduce

data.json:
```
{"_label_cost":-1.0,"_label_probability":0.5,"_label_Action":2,"_labelIndex":1,"a":[2,1],"c":{"feature": 1, " ": {"feature": 2},"_multi":[{"action":{"f":"1"}},{"action":{"f":"2"}}]},"p":[0.5,0.5]}
```

command line:
```
vw --cb_explore_adf --dsjson -d data.json --invert_hash model.txt
```

model.txt (there is only one "feature" since root/feature and " "/feature got collided):
```
Version 9.0.0
Id 
Min label:-1
Max label:0
bits:18
lda:0
0 ngram:
0 skip:
options: --cb_adf --cb_explore_adf --cb_type mtr --csoaa_ldf multiline --csoaa_rank
Checksum: 3590524534
event_sum 1
action_sum 2
:1
initial_t 0
norm normalizer 4
t 1
sum_loss -1
sum_loss_since_last_dump 0
dump_interval 2
min_label -1
max_label 0
weighted_labeled_examples 1
weighted_labels 0
weighted_unlabeled_examples 0
example_number 1
total_features 8
total_weight 1
sd::oec.weighted_labeled_examples 1
current_pass 1
l1_state 0
l2_state 1
Constant:116060:-0.159763 4 1
feature:118880:-0.107182 20 2
action^f2:257122:-0.159763 4 1
```

### Version

9.1.0

### OS

Windows

### Language

CLI

**Comment by jackgerrits** [comment]
Document that default == " " and that has ramifications for other inputs than text

**Comment by olgavrou** [comment]
Closing as known issue
