### ISSUE TITLE
FALCON

### ISSUE THREAD

**Issue by bhattaca** [VowpalWabbit/vowpal_wabbit#3926]
## Short description

Is it possible to get an implementation of Falcon ? 

## **How this suggestion will help you/others**
Latest algo after SquareCB, lots of interesting work done along this. 

## **Possible solution/implementation details**

https://pubsonline.informs.org/doi/abs/10.1287/moor.2021.1193

## **Example/links if any**

https://pubsonline.informs.org/doi/abs/10.1287/moor.2021.1193

**Comment by olgavrou** [comment]
Closing as this isn't currently on our roadmap, if this feature has high demand we can reopen it
