### ISSUE TITLE
Feature weights of the prediction

### ISSUE THREAD

**Issue by oleg131** [VowpalWabbit/vowpal_wabbit#3934]
VW version: 8.10.1

I'd like to get weights associated with different words of the input text during inference for interpretability. What I'm currently doing is: 

```
example = classifier.parse(vw_text.strip())
classifier.predict(example)
score = example.get_partial_prediction()
```

where `classifier` is the VW model  loaded with

```
from vowpalwabbit import pyvw

pyvw.vw(
  initial_regressor=vw_artifacts_path, testonly=True, quiet=True
)
```

Then to get weights, I use the following function:

```
def _get_weight_string(e):
    weight_string = ""

    for ns_id in range(e.num_namespaces()):
        weight_string += " |"
        ns = e.get_ns(ns_id)
        for feature_id in range(e.num_features_in(ns)):
            weight = e.feature_weight(ns, feature_id)
            weight_string += f" {weight}"

    return weight_string

_get_weight_string(example)
```

However, this ends up with all weights being `1.0`. Am I doing something wrong?

**Comment by oleg131** [comment]
This method doesn't exist in v8.10.1, does it?

**Comment by oleg131** [comment]
Is there a similar api for v8.10.1? I thought `feature_weight` was supposed to server this purpose, but I guess I was wrong.

**Comment by jackgerrits** [comment]
Are you looking for the model weight or feature value/weight in the given example?

If you're looking for model weight you can use [`get_weight_from_name`](https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/reference/vowpalwabbit.html?highlight=get_weight_from_name#vowpalwabbit.Workspace.get_weight_from_name) which was added in 8.11.0.

If feature, then it looks like your original example was correct. I don't know what what your input is but if you don't specify an explicit feature value the default is 1. https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Input-format

**Comment by oleg131** [comment]
I was looking for model weight. Is there a way to do this for 8.10.1?

**Comment by jackgerrits** [comment]
I am not sure about 8.10.1, that snippet looks reasonable.

**Comment by bassmang** [comment]
@oleg131 wanted to check have you resolved this issue on your end?

**Comment by oleg131** [comment]
Yeah i managed to get the token weights using the above function.

Full code for future reference:
```
def get_example_weights(vw_text, classifier):
    """
    vw_text: input vw data
    classifier: pyvw.vw model
    """
    namespace_to_features = {}
    namespaces = vw_text.split("|")
    for namespace in namespaces[1:]:
        feature_names = pd.unique(namespace.split(" "))
        namespace_to_features[feature_names[0]] = [
            i for i in feature_names[1:] if len(i)
        ]

    res = {"header": namespaces[0], "namespaces": []}

    for namespace_name, feature_names in namespace_to_features.items():
        res["namespaces"].append(
            {"name": namespace_name, "features": []}
        )

        for feature_name in feature_names:
            space_hash = classifier.hash_space(namespace_name)
            feat_hash = classifier.hash_feature(feature_name, space_hash)
            weight = classifier.get_weight(feat_hash)

            res["namespaces"][-1]["features"].append(
                {"name": feature_name, "weight": weight}
            )
            
    return res
```

**Comment by bassmang** [comment]
Great! If you are interested in upgrading to VW 9.2 you can now use the `json_weights` function outlined here to access the model weights:
https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/reference/vowpalwabbit.pyvw.pylibvw.html
