### ISSUE TITLE
Indexing 0 wrong output order

### ISSUE THREAD

**Issue by FabianKaiser** [VowpalWabbit/vowpal_wabbit#3935]
### Describe the bug

While trying to use 0 indexing when migrating to VW 9.1, I noticed the performance was much worse than when using 1 indexing.
This seems to not be an error of the model, but of the way the 0 indexed model outputs its probabilities.

The predictions of the 0 indexed model looked like this (data and code below)
[0.399, 0.038, 0.125, 0.111, 0.327]
[0.249, 0.095, 0.185, 0.147, 0.324]
[0.244, 0.102, 0.209, 0.159, 0.286]
[0.321, 0.136, 0.16, 0.184, 0.199]

While the predictions of the 1 indexed model looked like this.
[0.326, 0.4, 0.038, 0.126, 0.111]
[0.323, 0.249, 0.096, 0.185, 0.147]
[0.286, 0.245, 0.102, 0.21, 0.159]
[0.199, 0.322, 0.136, 0.16, 0.184]

It seems the 0 index classifier outputs its results at the last index of the output list, not the first (which would be expected). Therefore a conversion of index to classifier (and such class) does not work correctly with 0 indexed models.

### How to reproduce

```python
from vowpalwabbit import Workspace

texts = [
    'a b c d',
    'a b c e',
    'a b d e',
    'a b c',
    'a c d',
    'a b c d e f',
    'a b d',
    'a d e',
    'a b d',
    'c d e',
    'a c',
]
labels = [
    0,
    1,
    1,
    0,
    3,
    4,
    3,
    1,
    0,
    1,
    0,
]

tata = [
    'a b c d e',
    'a b',
    'c d',
    'e'
]

for ind in [0, 1]:

    print('------------')
    print(ind)
    print('------------')

    test = f'{ind}_data.vw'
    path = f'{ind}_model.vw'

    with open(test, "wb") as f:
        for label, text in zip(labels, texts):
            example = f'{label + ind} |text {text}\n'
            f.write(example.encode())

    params = {
        'loss_function': 'logistic',
        'data': test,
        'probabilities': True,
        'c': True,
        'k': True,
        'f': path,
        'compressed': True,
        'oaa': 5
    }
    model = Workspace(**params)

    for t in tata:
        print([round(p, 3) for p in model.predict(f'|text {t}')])
    print('------------')

    model.finish()

    del model

    params = {
        'loss_function': 'logistic',
        'probabilities': True,
        'predict_only_model': True,
        'i': path
    }

    model = Workspace(**params)
    for t in tata:
        print([round(p, 3) for p in model.predict(f'|text {t}')])
    print('------------')
```

### Version

9.1.0

### OS

Windows

### Language

Python

**Comment by lalo** [comment]
1) can you share the result of calling model.get_enabled_reductions()
2) have you played around with this argument --indexing https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/command_line_args.html#indexing ? I don't see it on your params dict

**Comment by FabianKaiser** [comment]
Hello, 
Sorry for the late reply.
1. ['gd', 'scorer-identity', 'oaa-prob'] in both cases
2. I did not, because the problem occured in a setting where the indexing should be detected automatically
  I tried it out now and it does not make any difference. The prediction indexes still seem to be swapped.

**Comment by bassmang** [comment]
Hi @FabianKaiser,
Thanks for pointing out this bug. The indexing feature has not yet been properly integrated into pyvw. I am working now on refactoring this feature so it reports correctly in pyvw.

**Comment by bassmang** [comment]
Hi @FabianKaiser,

The issue should be resolved with the last PR. Let me know if you experience similar issues.
