### ISSUE TITLE
Is it possible to pass softmax  parameter lambda with the features, action , cost , probablity?

### ISSUE THREAD

**Issue by musram** [VowpalWabbit/vowpal_wabbit#3962]
## Short description

This is the current format of passing the param lambda for softmax 
 vw --data " + textDataForPredictionLocalPath +" --initial_regressor /tmp/cbmodel --testonly --cb_explore_adf --softmax --lambda 1 --predictions " + rawPredictionFile.

So here we need different lambda for different features i.e passing lambda at each data point level.  This is not possible currently using the above command as we have to run the above command for each data point separately.

If we can pass lambda also in the data then we don't have to run the above command for each data point separately.

**Comment by JohnLangford** [comment]
If you have individual features, then you can just rescale features to simulate the lambda.

However, I'm curious---why is this desirable?

**Comment by musram** [comment]
Hi @JohnLangford 

As per your suggestion, I made the changes.
 
Below is the data point for prediction where  I am passing the lambda as 0.000000. 

All my features are contextual, eg F1=104:0.000000  with lambda included.

shared |Country F1=104:0.000000 |Hour F2=3:0.000000 |Rest F3=3:0.000000 F4=mobi.bgn.launcher:0.000000 F5=2:0.000000 F6=3:0.000000 F7=0:0.000000 F8=3:0.000000

But in prediction, I am not getting uniform distribution as lambda=0

5:0.128844$7:0.0510558$3:0.0490752$4:0.0435394$12:0.0430435$11:0.0417436$2:0.0416692$10:0.0413245$13:0.0386737$9:0.0363735$8:0.0347968$14:0.0346298$20:0.0315756$22:0.0299757$17:0.0286215$15:0.0285478$18:0.0274565$19:0.0268806$16:0.0261551$21:0.0243559$0:0.017465$1:0.0174402

$ is the seperator.
I have checked very low values of lambda like .000001 but still I am not getting a uniform distribution over the actions.

**Comment by JohnLangford** [comment]
You likely need to turn off the constant features (via --noconstant).  You can see what features are hitting the core via --audit.

**Comment by musram** [comment]
I passed --noconstant during the training as 

/tmp/vw --data /tmp/data.dat -f /tmp/cb.model --hash all --bit_precision 28 -k --passes 1 --onethread  -q CH -q CA -q HA -q RA --cb_explore_adf  --cb_type dr  --save_resume --holdout_off --audit  --noconstant

and  because of --audit able to see 

Action^BP=0:125505153:1:0@0	Country^F1=236:171965903:1:0@0	Hour^F2=1:164375985:1:0@0	Rest^F3=3:59415475:1:0@0	Rest^F4=jp.gocro.smartnews.android:118861717:1:0@0	Rest^F5=5:255544171:1:0@0	Rest^F6=1:156190699:1:0@0	Rest^F7=0:226321467:1:0@0	Rest^F8=3:181152487:1:0@0	Country^F1=236*Hour^F2=1:158377723:1:0@0	Country^F1=236*Action^BP=0:130516427:1:0@0	Hour^F2=1*Action^BP=0:185655953:1:0@0	Rest^F3=3*Action^BP=0:38279095:1:0@0	Rest^F4=jp.gocro.smartnews.android*Action^BP=0:207121277:1:0@0	Rest^F5=5*Action^BP=0:53262687:1:0@0	Rest^F6=1*Action^BP=0:112540639:1:0@0	Rest^F7=0*Action^BP=0:18860495:1:0@0	Rest^F8=3*Action^BP=0:35423891:1:0@0
0
	Action^BP=1:95304055:1:0@0	Country^F1=236:171965903:1:0@0	Hour^F2=1:164375985:1:0@0	Rest^F3=3:59415475:1:0@0	Rest^F4=jp.gocro.smartnews.android:118861717:1:0@0	Rest^F5=5:255544171:1:0@0	Rest^F6=1:156190699:1:0@0	Rest^F7=0:226321467:1:0@0	Rest^F8=3:181152487:1:0@0	Country^F1=236*Hour^F2=1:158377723:1:0@0	Country^F1=236*Action^BP=1:85111357:1:0@0	Hour^F2=1*Action^BP=1:163960167:1:0@0	Rest^F3=3*Action^BP=1:10297409:1:0@0	Rest^F4=jp.gocro.smartnews.android*Action^BP=1:244145291:1:0@0	Rest^F5=5*Action^BP=1:33132201:1:0@0	Rest^F6=1*Action^BP=1:73403433:1:0@0	Rest^F7=0*Action^BP=1:63635001:1:0@0	Rest^F8=3*Action^BP=1:13218149:1:0@0

But still  I am not getting the required results for lambda=0 in prediction.

I think I also need to pass for actions eg  BP=1:0.0. 

Pls correct me if I am wrong.

Thanks @JohnLangford

**Comment by JohnLangford** [comment]
Yes, you would need to do this for every feature.   Also, you would need to expand quadratics externally (except for lamba=0) since quadratics multiply feature value by default.

**Comment by musram** [comment]
I am not clear with the statement  "Also, you would need to expand quadratics externally (except for lamba=0) since quadratics multiply feature value by default".

This is my prediction file
hared |Country F1=104:0.000000 |Hour F2=3:0.000000 |Rest F3=3:0.000000 F4=mobi.bgn.launcher:0.000000 F5=2:0.000000 F6=3:0.000000 F7=0:0.000000 F8=3:0.000000
|Action action=0:0.000000
|Action action=1:0.000000 
|Action action=2:0.000000 
|Action action=3:0.000000

**Comment by JohnLangford** [comment]
If you use '-q' to create interactions between features, then, in general, the scaling of features will be _squared_ rather than linear (since x * y -> x*s*y*s = x*y*s^2).

Square vs. linear does not matter if the scale is zero.

**Comment by musram** [comment]
HI @JohnLangford.

When I scale the features by lambda=0, I am getting the uniform distribution over the actions. This is correct.

But when I scale by lambda=10, I am still getting the uniform distribution over the actions. 

My prediction file is 
shared |Country F1=104:10 |Hour F2=0:10 |Rest F3=3:10 F4=com.playstrom.dop4:10 F5=4:10 F6=4:10 F7=0:10 F8=2:10
|Action BP=30:10
|Action BP=31:10
|Action BP=32:10
|Action BP=33:10
|Action BP=34:10
|Action BP=35:10
|Action BP=36:10
|Action BP=37:10
|Action BP=38:10
|Action BP=39:10
|Action BP=40:10
|Action BP=41:10
|Action BP=42:10
|Action BP=43:10
|Action BP=44:10
|Action BP=45:10
|Action BP=46:10
|Action BP=47:10
|Action BP=48:10
|Action BP=49:10
|Action BP=50:10
|Action BP=51:10
|Action BP=52:10
|Action BP=53:10
|Action BP=54:10
|Action BP=55:10
|Action BP=56:10
|Action BP=57:10

My prediction command is 
/tmp/vw --data /tmp/checkOneDatapointWith100.txt --initial_regressor /tmp/cbmodel --testonly --cb_explore_adf --softmax --lambda 1 --predictions /tmp/checkOneDatapointOutputWith100.txt

The distribution is still uniform
0:0.0357143,1:0.0357143,2:0.0357143,3:0.0357143,4:0.0357143,5:0.0357143,6:0.0357143,7:0.0357143,8:0.0357143,9:0.0357143,10:0.0357143,11:0.0357143,12:0.0357143,13:0.0357143,14:0.0357143,15:0.0357143,16:0.0357143,17:0.0357143,18:0.0357143,19:0.0357143,20:0.0357143,21:0.0357143,22:0.0357143,23:0.0357143,24:0.0357143,25:0.0357143,26:0.0357143,27:0.0357143

I might be missing something.

@JohnLangford

**Comment by musram** [comment]
Thanks, @JohnLangford.
It is working.  
I will close the issue.
