### ISSUE TITLE
Vowpal Wabbit C API getting 0 as prediction

### ISSUE THREAD

**Issue by 0110G** [VowpalWabbit/vowpal_wabbit#4012]
### Describe the bug

I am trying to write a C program that loads a trained vw model and returns predictions in real time. For this, I am using libvw_c_wrapper and using methods described [here][1]. 

The model was trained and saved with following configurations in python:
```
vw = vowpalwabbit.Workspace(
    "--cats "
    + str(num_actions)
    + "  --bandwidth "
    + str(bandwidth)
    + " --min_value {} --max_value {} --json --chain_hash --coin --epsilon 0.1".format(min_val, max_val)
```

And saved as: ```vw.save('nadwwadw.model')```

This is my C program (vw_client.c):
```
#include "/Users/../C_VW_Test/vwdll.h"
#include <stdio.h>

int main()
{
    VW_HANDLE vw;
    char vw_arg[] = "-i nadwwadw.model";
    vw = VW_InitializeA(vw_arg);

    char vw_example[] = "ca | ";

    for (int i=0; i<1000 ; i++) {
        VW_EXAMPLE example = VW_ReadExampleA(vw, vw_example);
        
        float pred = VW_Predict(vw, example);
        printf("VW_Predict: %f\n", pred);
    }


    return 0;

}
```

and compile using ```gcc vw_client.c -L. -lvw_c_wrapper -o test```

When I load this model in jupyter notebook as ```new_vw = vowpalwabbit.Workspace("-i nadwwadw.model")``` and make predictions as ```new_vw.predict("ca | ")```, I get the output as (0.2624061703681946, 230.43333435058594). 

However, my C code returns prediction as 0.00000 even for all iterations. 

My requirements involve only predictions for now. 

Can someone please help me understand 
1. Why am i getting different results in C and how do I solve it?
2. Am I using the correct dylib/so file? If no, steps to build the correct one.

Thanks in Advance

  [1]: https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/c_wrapper/include/vw/c_wrapper/vwdll.h

### How to reproduce

Described above

### Version

9.0.1

### OS

MacOS

### Language

C

**Comment by jackgerrits** [comment]
The function `VW_Predict` returns the scalar prediction, however, you need the pdf value prediction produced by continuous actions. Unfortunately this is not available from the C API you referenced. 

The reason Python works is it automatically determines what prediction type is returned by a given VW workspace and returns the correct type.

**Comment by jackgerrits** [comment]
So a C++ solution would look something like this (I haven't tested it):

```C++
auto* ws = VW::initialize("-i nadwwadw.model");
auto* ex = VW::read_example(*ws, "ca | ");
ws->predict(*ex);
auto& prediction = ex->pred.pdf_value;
VW::finish_example(*ex);
VW::finish(*ws);
```

**Comment by 0110G** [comment]
Can you please provide some documentation/pointers on required .so/.a/.dylib and steps to build them inorder to use the above mentioned solution.

**Comment by 0110G** [comment]
I plan to add cats support in C Wrapper API, I did the following for a basic code check:

1. Added ```VW_DLL_PUBLIC void VW_CALLING_CONV Print() {printf("Random\n");}``` in vowpal_wabbit/vowpalwabbit/c_wrapper/src/vwdll.cc

2. Added ```  VW_DLL_PUBLIC void VW_CALLING_CONV Print();``` in vowpal_wabbit/vowpalwabbit/c_wrapper/include/vw/c_wrapper/vwdll.h

3. Build using  ```cd vowpal_wabbit``` -> ```cmake -S . -B build``` -> ```cd build``` -> ```make vw_c_wrapper```

4. Add dylib Try to run Print() in code mentioned in C issue using same method. However I get the following error:
```
dyld: lazy symbol binding failed: Symbol not found: _Print
  Referenced from: /Users/bhavya.sa/Desktop/C_VW_Test/./a.out
  Expected in: /usr/local/lib/libvw_c_wrapper.dylib

dyld: Symbol not found: _Print
  Referenced from: /Users/bhavya.sa/Desktop/C_VW_Test/./a.out
  Expected in: /usr/local/lib/libvw_c_wrapper.dylib

zsh: abort      ./a.out
```

**Comment by 0110G** [comment]
https://github.com/VowpalWabbit/vowpal_wabbit/pull/4021

**Comment by 0110G** [comment]
Is there any way we can read json format using C/C++ APIs for cats mode ?

**Comment by 0110G** [comment]
@jackgerrits

**Comment by jackgerrits** [comment]
Support for the CATS pdf value prediction type was merged in this PR: https://github.com/VowpalWabbit/vowpal_wabbit/pull/4021
