### ISSUE TITLE
VW 9 runs much longer for PLT than VW 8 and results in worse performance

### ISSUE THREAD

**Issue by FabianKaiser** [VowpalWabbit/vowpal_wabbit#4055]
### Describe the bug

After upgrading to vowpalwabbit 9, we noticed a sharp increase in training time.
I tested this with several datasets I unfortunately cannot share here, this one with 2729 classes and 75061 documents.

Both runs use the exact same python code with the same parameters.

The vw 8 run runs about 2297.77s and has metrics of (precision, recall, f1, accuracy) 0.57 0.59 0.56 0.59.
The vw 9 run runs about 6935.01s and has metrics of (precision, recall, f1, accuracy) 0.48 0.49 0.44 0.49.

The two logs are posted below. What strikes me is weird is that the vw8 run has much more passes, but runs way faster.

Am I missing a new required parameter, or a default parameter I did have to set in vw 9? Or does anyone have another idea?

VW 8

{'b': 27, 'passes': 50, 'ring_size': 256, 'learning_rate': 0.5}
final_regressor = models/model.vw
PLT k = 2729
kary_tree = 2
Num weight bits = 27
learning rate = 0.5
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = VW.vw.cache
Reading datafile = VW.vw
num sources = 1
Enabled reductions: gd, scorer, plt
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
1.000000 1.000000            1            1.0     2678               206
1.000000 1.000000            2            2.0     1029               226
1.000000 1.000000            4            4.0      170                88
1.000000 1.000000            8            8.0     2226               186
1.000000 1.000000           16           16.0     1654              1260
1.000000 1.000000           32           32.0      387              5592
1.000000 1.000000           64           64.0      412               456
1.000000 1.000000          128          128.0      767               709
1.781250 2.562500          256          256.0       90  463 345 464 795 465 466 501 346 468 469 470 467 344 343 719 456 461 458 455 459 457 460 462 350 348 349 347 441 445 454 440 444 443 442 450 453 447 448 452 451 449 439 446 1029 796 356 358 355 353 357 354 352 351 1654 409 427 435 423 415 407 431 410 425 422 429 433 420 412 421 417 437 411 419 438 413 424 414 436 416 434 430 426 408 432 428 418 1541 720 798 797 367 371 374 373 361 365 364 372 370 359       43
7.640625 13.500000          512          512.0      563  795 1209 170 172 796 1029 803 171 36 169 174 173 798 797 116 1210 501 408 167 168 35 804 2678 943 1030 38 37 1208 1207 115 794 792 791 793 604 806 805 34 32 31 33 22 20 16 12 8 4 21 18 11 2 19 7 6 15 3 17 13 14 9 10 5 1 0 118 117 176 180 178 182 177 179 175 181 1028 1027 30 24 28 26 23 27 29 25 802 800 799 801 407 387 1212 1214 1211 1213 1127 502 112 114 113 111      325
19.457031 31.273438         1024         1024.0     1530              4531
32.436523 45.416016         2048         2048.0      352                83
38.931152 45.425781         4096         4096.0     1829               186
42.187256 45.443359         8192         8192.0     1974  160 161 159 181 156 243 138 289 1092 320 182 247 180 179 290 311 1081 291 165 140 278 1979 306 158 286 326 157 276 195 280 249 2414 220 287 292 297 88 248 244 293 1091 1982 246 196 2413 325 285 308 2410 115 116 2662 219 119 298 1085 117 294 300 139 129 118 282 1107 305 33 162 2391 283 222 275 296 299 301 2638 284 330 1099 197 1104 149 321 288 2406 2408 2404 920 2417 2407 2632 1879 281 198 150 2416 1093 2640 191 307 103      148
43.810791 45.434326        16384        16384.0      767  165 168 172 156 170 158 348 169 171 446 280 160 362 194 344 1727 359 196 1599 284 159 1572 164 281 408 278 1541 90 193 199 2317 282 346 163 2178 157 2385 195 411 285 161 2223 350 167 191 1591 140 88 1729 2171 2174 360 1566 82 36 343 162 286 439 1634 249 2309 483 198 221 2176 1565 116 84 1587 351 1544 2315 1543 2301 1597 1598 553 2306 2136 407 447 2175 349 138 1702 551 2208 283 1630 1228 1532 1527 32 202 2316 1559 1592 2207 1538       91
44.621704 45.432617        32768        32768.0     2036  653 650 940 651 647 649 510 525 648 455 654 526 652 509 508 514 671 456 675 110 657 505 116 664 511 447 503 115 715 682 504 674 457 655 512 517 470 506 458 656 680 673 462 102 686 685 936 118 681 507 718 524 134 932 923 2524 109 1209 107 129 663 684 666 676 2455 720 123 516 460 122 119 430 463 108 124 2548 99 518 466 2537 519 2463 217 515 677 103 411 2545 419 528 117 459 267 658 691 2519 2535 424 679 922      269
100.099300 100.099300        65536        65536.0      158  352 675 671 32 359 116 447 959 350 344 36 680 681 115 345 169 117 170 247 446 140 349 682 348 1230 346 1353 664 362 201 677 351 439 361 360 1363 1331 1332 160 42 936 172 199 358 659 922 118 674 483 1209 2651 1104 685 944 1333 31 33 203 71 343 940 437 202 679 222 440 943 84 88 1166 209 87 436 156 686 684 408 676 1334 1164 514 2471 2516 220 1142 923 45 715 691 357 1330 278 579 1161 1232 663 678 73 212 690     1896 h
100.014763 99.930239       131072       131072.0      352               407 h
99.920277 99.825791       262144       262144.0      160  735 243 286 280 1538 172 287 247 170 1014 1544 308 219 2385 220 169 326 1548 1532 1609 297 1005 1724 222 325 290 1579 1738 1587 320 1556 309 289 181 2584 229 2240 1600 1586 1566 2642 1574 2338 1554 1599 246 1748 1560 2368 199 1543 1551 1012 1558 1601 1099 1562 2000 115 278 284 1739 230 2243 2235 1602 1686 1572 281 2306 2230 1883 282 2234 310 2623 306 1999 299 279 1555 1375 2343 1683 888 285 201 2233 1379 291 212 288 1575 2205 887 1684 214 1797 1740 213      172 h
99.842909 99.765544       524288       524288.0     2220  1150 1351 169 172 170 1178 487 1269 138 352 1091 195 196 1176 1151 532 118 1121 219 311 344 349 1185 1093 772 140 1979 116 348 1081 1353 2235 345 1710 343 1122 346 861 813 31 145 32 1950 129 351 320 1697 280 350 1216 1334 1724 531 135 278 1352 2234 1702 1180 852 840 1883 325 33 1257 811 1186 501 1363 500 439 1175 243 533 1152 1190 1179 2238 281 1331 1230 1981 814 1267 1092 1544 115 846 2678 1213 911 534 1153 244 1189 1263 1181 832 795 246      217 h
99.783960 99.725010      1048576      1048576.0     1140               568 h

finished run
number of examples per pass = 54136
passes used = 28
weighted example sum = 1515808.000000
weighted label sum = 0.000000
average loss = 99.707230 h
total feature number = 1541987300

VW 9

{'b': 27, 'passes': 50, 'example_queue_limit': 256, 'learning_rate': 0.5}
final_regressor = models/model.vw
PLT k = 2729
kary_tree = 2
[warning] Option 'probabilities' depends on another option (or combination of options) which was not supplied. Possible combinations of options which would enable this option are:
	csoaa_ldf
	multilabel_oaa
	oaa

creating cache_file = VW.vw.cache
Reading datafile = VW.vw
num sources = 1
Num weight bits = 27
learning rate = 0.5
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
Enabled reductions: gd, scorer-identity, plt
Input label = multilabel
Output pred = multilabels
average  since         example        example        current        current  current
loss     last          counter         weight          label        predict features
1.000000 1.000000            1            1.0            169                      95
1.000000 1.000000            2            2.0            159                    1269
1.000000 1.000000            4            4.0            277                     298
1.000000 1.000000            8            8.0           2141                    2476
1.000000 1.000000           16           16.0           1544                     244
1.000000 1.000000           32           32.0            160                    2516
1.000000 1.000000           64           64.0             88                     292
1.000000 1.000000          128          128.0            138                     376
1.000000 1.000000          256          256.0            150                     387
1.001953 1.003906          512          512.0           2010                     619
1.018555 1.035156         1024         1024.0           1853                     192
1.042480 1.066406         2048         2048.0            116                     479
1.067139 1.091797         4096         4096.0            690                     634
1.084839 1.102539         8192         8192.0           2017                     838
1.099060 1.113281        16384        16384.0           2613                    4827
1.122711 1.146362        32768        32768.0             93            116      925
6.844664 6.844664        65536        65536.0 1138,640,20... 1269,1164,1...       89 h
139.7847 272.7065       131072       131072.0 2003,361,25...                    1514 h

finished run
number of examples per pass = 54136
passes used = 4
weighted example sum = 216544.000000
weighted label sum = 0.000000
average loss = 1.037905 h
total feature number = 220214548

### How to reproduce

Used python 3.8 for both

The probabilitiesis parameter does nothing for plt but it is set as we use a similar parameter set for ooa.

vw8: {'b': 27, 'passes': 50, 'ring_size': 256, 'learning_rate': 0.5, 'plt': 2729, 'loss_function': 'logistic', 'probabilities': True, 'c': True, 'k': True, 'compressed': True}
vw9: {'b': 27, 'passes': 50, 'example_queue_limit': 256, 'learning_rate': 0.5, 'plt': 2729, 'loss_function': 'logistic', 'probabilities': True, 'c': True, 'k': True, 'compressed': True}

This is way more obvious for larger datasets - we used 2729 classes and 75061 documents here. The dataset simply consists of preprocessed texts.

### Version

9.1 and 8.11

### OS

Ubuntu (docker image mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20220708.v1)

### Language

Python

**Comment by bassmang** [comment]
Hey @FabianKaiser the one big change in vw-9 is that `--save_resume` is now the default whereas it used to be manually specified (you can see the other major changes here: https://vowpalwabbit.org/blog/vowpalwabbit-9.0.0.html). Is there a chance you could attach a smaller/similar dataset so we can reproduce the results?

**Comment by FabianKaiser** [comment]
Hello @bassmang 
Thanks for the reply and sorry for taking so long.
I am currently searching for suitable datasets - which is quite hard, as we have a lot of classes, a lot of documents and (and this seems to be an important aspect as well) really long texts.
The only thing which is really consistent over all data I tried, is that the PLT in VW 9 will never go over 4 passes.

**Comment by FabianKaiser** [comment]
Hello @bassmang,

I found one that works for me.
https://www.kaggle.com/datasets/mswarbrickjones/reddit-selfposts (rspct.tsv)
I just used the content (I only removed all non-alnum and non-space chars) as input and the subreddit as class.

For python 3.8 and VW 8 it trained for about 800s with 7 passes.

For python 3.8 and VW 9 it trained for about 7500s with 4 passes.


Th final metrics were quite similar (precision, recall, f1, accuracy):
VW 8: 0.59, 0.58, 0.58, 0.58 
VW 9: 0.59, 0.57, 0.57, 0.57

A bit worse on the VW 9 side but not really mesaurable here - but the time is vastly different.

VW 8 output:

{'b': 27, 'passes': 50, 'ring_size': 256, 'learning_rate': 0.5}
final_regressor = models/test_principal/test_principal_ReferenceNumber_DocumentText_27_0_model.vw
PLT k = 1013
kary_tree = 2
Num weight bits = 27
learning rate = 0.5
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = test_principal_DocumentText_ReferenceNumber_train_VW.vw.cache
Reading datafile = test_principal_DocumentText_ReferenceNumber_train_VW.vw
num sources = 1
Enabled reductions: gd, scorer, plt
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
1.000000 1.000000            1            1.0      613               197
1.000000 1.000000            2            2.0      505               129
1.000000 1.000000            4            4.0      893               270
1.000000 1.000000            8            8.0      885                64
1.000000 1.000000           16           16.0      691               102
1.000000 1.000000           32           32.0      412                59
1.000000 1.000000           64           64.0      163                70
1.000000 1.000000          128          128.0      367               126
1.781250 2.562500          256          256.0      678  374 685 377 691 613 996 650 353 5 893 373 686 885 11 15 378 692 505 526 371 372 684 683 417 375 376 693 694 107 614 354 995 649 6 811 688 690 687 689 894 12 696 697 695 698 16 352 351 611 612 886 998 997 3 4 648 647 525 506 13 14 891 892 17 18 363 364 370 365 367 366 368 369 347 349 350 348 883 884 617 615 616 618 418 7 9 10 8 999 1001 1002 1000 108 643 646 645 644 523 524 503       87
7.640625 13.500000          512          512.0      304  5 874 526 84 200 870 15 377 374 11 725 628 873 727 6 893 996 685 236 913 184 869 203 353 885 871 872 199 16 12 691 83 373 378 613 525 3 4 867 868 650 627 726 201 202 13 14 17 18 335 85 86 183 728 894 371 372 375 376 107 235 417 995 686 524 523 204 886 811 914 10 8 7 9 630 629 186 185 195 197 196 198 354 892 891 692 724 723 729 730 90 88 87 89 238 237 412 860 864 862      111
19.453125 31.265625         1024         1024.0      602                51
32.439453 45.425781         2048         2048.0      402                63
38.934082 45.428711         4096         4096.0      934                72
42.194092 45.454102         8192         8192.0      676  359 85 314 358 313 83 357 607 311 799 86 800 310 360 324 726 535 555 538 817 806 109 138 783 604 818 110 484 79 826 564 341 801 108 115 390 12 402 782 112 974 423 399 356 524 404 745 342 480 780 527 797 560 116 362 84 326 825 403 325 795 602 447 611 823 644 904 533 640 749 361 559 76 103 526 561 941 525 536 318 530 312 534 412 603 132 1000 131 11 562 847 768 424 810 328 98 769 104 776 133      154
43.817383 45.440674        16384        16384.0      689  108 107 190 162 114 264 15 237 263 289 102 113 49 331 257 368 103 192 80 79 273 351 193 250 356 161 249 84 256 92 134 194 86 226 268 112 271 76 77 47 300 53 191 85 361 159 363 270 78 258 274 413 238 367 12 104 522 131 438 172 189 262 354 82 121 94 352 132 67 269 16 340 69 188 52 494 195 342 54 364 299 290 105 332 109 173 149 275 348 174 956 156 100 412 336 341 454 362 90 277      199
44.627686 45.437988        32768        32768.0       95  49 47 50 1008 54 53 46 74 44 24 22 51 67 70 364 52 148 16 43 1007 806 68 794 71 230 211 800 823 69 149 363 150 7 325 365 825 950 25 804 366 916 214 300 273 179 367 324 61 790 789 810 73 931 791 370 915 555 949 154 15 57 384 180 301 9 802 842 333 635 62 140 10 45 141 48 182 314 40 21 142 918 35 479 293 72 899 181 901 803 824 326 163 8 948 788 820 65 151 59 28      152
45.032593 45.437500        65536        65536.0      326                64
45.235977 45.439362       131072       131072.0      508               141
45.337502 45.439026       262144       262144.0      267                55
99.809764 99.809764       524288       524288.0      370  151 727 5 911 563 242 729 10 217 913 551 544 546 553 152 265 541 283 1 756 45 163 272 373 930 236 244 649 1009 857 750 474 795 836 965 977 211 225 6 908 245 548 728 652 459 135 660 147 672 259 526 934 740 725 787 167 8 442 777 7 539 976 328 758 552 990 142 291 441 1008 681 215 648 201 776 993 528 56 932 223 470 784 910 669 39 440 160 118 216 688 336 353 462 176 759 797 543 975 937 656       66 h
99.728053 99.646342      1048576      1048576.0      577  235 145 803 205 211 213 170 216 146 206 217 365 209 804 853 848 208 857 214 379 812 851 852 144 257 138 819 128 266 366 168 163 883 782 991 259 164 210 894 258 880 178 254 797 167 212 885 265 203 805 389 150 148 806 855 868 143 19 155 12 850 242 986 199 367 414 154 123 421 784 260 985 236 380 1002 860 292 881 818 811 849 14 250 21 386 156 642 984 993 255 165 368 422 149 635 229 983 961 381 172       53 h
99.684168 99.640282      2097152      2097152.0      313  866 861 203 208 205 864 204 51 227 905 207 221 802 938 253 947 801 222 865 254 863 903 117 927 937 246 216 228 214 167 148 950 225 226 257 902 899 872 243 912 928 780 791 717 862 217 15 119 136 860 724 137 782 220 122 155 795 838 252 118 164 837 131 219 943 901 728 929 69 46 944 206 911 566 867 910 584 894 576 653 786 789 595 245 904 70 885 870 573 682 170 914 948 565 211 258 701 67 668 133      126 h

finished run
number of examples per pass = 455850
passes used = 7
weighted example sum = 3190950.000000
weighted label sum = 0.000000
average loss = 99.640396 h
total feature number = 439805604


VW 9 output:


{'b': 27, 'passes': 50, 'example_queue_limit': 256, 'learning_rate': 0.5}
final_regressor = models/test_principal/test_principal_ReferenceNumber_DocumentText_27_0_model.vw
PLT k = 1013
kary_tree = 2
[warning] Option 'probabilities' depends on another option (or combination of options) which was not supplied. Possible combinations of options which would enable this option are:
	csoaa_ldf
	multilabel_oaa
	oaa

creating cache_file = test_principal_DocumentText_ReferenceNumber_train_VW.vw.cache
Reading datafile = test_principal_DocumentText_ReferenceNumber_train_VW.vw
num sources = 1
Num weight bits = 27
learning rate = 0.5
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
Enabled reductions: gd, scorer-identity, plt
Input label = multilabel
Output pred = multilabels
average  since         example        example        current        current  current
loss     last          counter         weight          label        predict features
1.000000 1.000000            1            1.0            720                     303
1.000000 1.000000            2            2.0            545                     119
1.000000 1.000000            4            4.0            332                     157
1.000000 1.000000            8            8.0            705                      82
1.000000 1.000000           16           16.0            938                      66
1.000000 1.000000           32           32.0            395                     172
1.000000 1.000000           64           64.0            290                     107
1.000000 1.000000          128          128.0            476                     195
1.000000 1.000000          256          256.0            543                     134
1.000000 1.000000          512          512.0            200                     105
1.000000 1.000000         1024         1024.0            553                     113
1.000000 1.000000         2048         2048.0            620                     180
1.000977 1.001953         4096         4096.0            235                     176
1.000977 1.000977         8192         8192.0            841                      60
1.001221 1.001465        16384        16384.0            991                     125
1.002197 1.003174        32768        32768.0            824                      76
1.004013 1.005829        65536        65536.0            965                      56
1.009087 1.014160       131072       131072.0            925                     103
1.018211 1.027336       262144       262144.0            271                     174
21.08260 21.08260       524288       524288.0 846,244,508...     591,443,60      435 h
1089.121 2157.160      1048576      1048576.0 973,867,908... 9,10,7,8,5,...       77 h

finished run
number of examples per pass = 455850
passes used = 4
weighted example sum = 1823400.000000
weighted label sum = 0.000000
average loss = 0.943850 h
total feature number = 251211176

**Comment by bassmang** [comment]
Hi @FabianKaiser 
Could you please attach either a Python notebook or snippet you are using for reproducibility, as well as the dataset after cleaning alnum characters etc?

**Comment by FabianKaiser** [comment]
``` python
data: pd.DataFrame

target_var = 'target'
training_var = 'text'

cleaned_targets = data[target_var].dropna()
unique_labels = cleaned_targets.unique().tolist()
num_classes = len(unique_labels)
numbers = list(range(num_classes))
mapping = dict(zip(unique_labels, numbers))

training_data = data.sample(frac=0.9, random_state=25)
testing_data = data.drop(training_data.index)

training_data = training_data.dropna(subset=[training_var]).sample(frac=1).reset_index(drop=True)

vw_training_file_name = 'train.vw'

with open(vw_training_file_name, "wb") as f:
    for text, label in zip(training_data[training_var], training_data[target_var]):
        vw_label = mapping[label]
        example = to_vw_format(
            text, vw_label) + ' \n'
        f.write(example.encode())

os.mkdir('model')

params = {
    'loss_function': 'logistic',
    'data': vw_training_file_name,
    'probabilities': True,
    'c': True,
    'k': True,
    'f': 'model',
    'compressed': True,
    'plt': num_classes,
    'b': 27,
    'passes': 50,
    'learning_rate': 0.5,
    'top_k': 10
}

# VW 8
# params.update({'ring_size': 256})
# start = time()
# model = pyvw.vw(**params)
# end = time()

# VW 9
params.update({'example_queue_limit': 256})
start = time()
model = Workspace(**params)
end = time()

model.finish()

predictions = testing_data.text.apply(lambda x: model.predict(to_vw_format(x))[0]).rename('pred')

evaluate(pd.concat([predictions, testing_data.target.apply(lambda x: mapping[x])], axis=1))
print(f'train time {round(end - start, 2)}s')

```

I would attach the dataset but it is about 750 mb - any idea how to upload it (max filesize here seems to be 25 mb)?

**Comment by bassmang** [comment]
Hey @FabianKaiser 
Would it be possible to send a file within this size limit that would exhibit the same statistical and performance differences?

**Comment by FabianKaiser** [comment]
Hey @bassmang 
Not that I know of. I did try smaller datasets, and at least the number of passes differs between VW 8 and VW 9, but the longer training time is not noticable. I imagine it it possible with a dataset smaller than 750 mb, but I doubt at less than 25 mb.

**Comment by FabianKaiser** [comment]
Hello @bassmang,
I was wrong. A smaller dataset shows already a longer training time, worse performance and capped passes at 4. I uplaoded it here.
[reddit_data_sample.csv](https://github.com/VowpalWabbit/vowpal_wabbit/files/9218764/reddit_data_sample.csv)

**Comment by bassmang** [comment]
Hey @FabianKaiser 
The issue seems to be that multilabels were not being cleared after being loaded from a saved model. Thanks for pointing this out!
