### ISSUE TITLE
Fix grammar/spelling errors in README.md

### ISSUE THREAD

**Issue by AMetIR** [VowpalWabbit/vowpal_wabbit#4068]
### Description

> A brief description of the error, missing documentation or what you would like added
Fixed a couple of grammar/spelling errors in README.md

### Link to Documentation Page

> Where is the documentation in question?

**Comment by jackgerrits** [comment]
Thanks for the suggestions. We want to do a larger overhaul of the readme at some point, so we will re-evaluate at that point.
