### ISSUE TITLE
The MSVC team recently test VowpalWabbit project failed with 'Exit code 0xc0000135' when run "vw_c_wrapper_test" test, on release and debug ASAN mode, Windows_amd64

### ISSUE THREAD

**Issue by rachelhe123** [VowpalWabbit/vowpal_wabbit#4076]
### Describe the bug

Hi All,

VowpalWabbit failed with 'Exit code 0xc0000135' when run "vw_c_wrapper_test" test, on release and debug configuration, Windows_amd64. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**Error message:**
Test project F:/gitP/VowpalWabbit/vowpal_wabbit/build_amd64
    Start 1: vw_c_wrapper_test
1/6 Test #1: vw_c_wrapper_test ................Exit code 0xc0000135
***Exception:   0.05 sec

    Start 2: vw_config_test
2/6 Test #2: vw_config_test ...................   Passed    0.17 sec
    Start 3: vw_core_test
3/6 Test #3: vw_core_test .....................   Passed    0.81 sec
    Start 4: vw_explore_test
4/6 Test #4: vw_explore_test ..................   Passed    0.31 sec
    Start 5: vw_io_test
5/6 Test #5: vw_io_test .......................   Passed    0.15 sec
    Start 6: vw_slim_test
6/6 Test #6: vw_slim_test .....................   Passed    4.92 sec

83% tests passed, 1 tests failed out of 6

Label Time Summary:
VWTestList    =   6.40 sec*proc (6 tests)

Total Test time (real) =   6.43 sec

The following tests FAILED:
	  1 - vw_c_wrapper_test (Exit code 0xc0000135
)
Errors while running CTest

### How to reproduce

1. git clone [(https://github.com/VowpalWabbit/vowpal_wabbit)](https://github.com/VowpalWabbit/vowpal_wabbit) F:\gitP\VowpalWabbit
2. git clone https://github.com/Microsoft/vcpkg F:\gitP\Microsoft
3. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
4. cd F:\gitP\Microsoft\vcpkg
5. bootstrap-vcpkg.bat 2>&1
6. vcpkg.exe install --recurse zlib boost-system boost-program-options boost-test boost-align boost-foreach boost-math boost-python python3 flatbuffers --triplet x64-windows --clean-after-build 2>&1
7. **set _CL_= /fsanitize=address /GS- /wd5072 & set _LINK_= /InferASanLibs /incremental:no /debug**
8. mkdir&cd F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64
9. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DUSE_LATEST_STD=ON -Dvw_BUILD_NET_FRAMEWORK=OFF -DBUILD_FLATBUFFERS=OFF -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .. 2>&1
10. msbuild /m /p:Platform=x64 /p:Configuration=Release vowpal_wabbit.sln /t:Rebuild /p:BuildInParallel=true 2>&1
11. ctest --build-config Release --output-on-failure 2>&1

### Version

git commit : b896f6b

### OS

Windows

### Language

C++

### Additional context

[test.log](https://github.com/VowpalWabbit/vowpal_wabbit/files/9208271/test.log)
[test.log.2.out.txt](https://github.com/VowpalWabbit/vowpal_wabbit/files/9208274/test.log.2.out.txt)

**Comment by rachelhe123** [comment]
Hi @byronxu99 , I used the new commit 8e1f46d , but this issue still repro, could you please help look at this issue again?

**Comment by byronxu99** [comment]
I am unable to locate commit 8e1f46d. Can you re-try using this commit https://github.com/VowpalWabbit/vowpal_wabbit/commit/3f22e3a09411642fce6c4bd9024fa0ef64015b9a in the master branch?

The bug is no longer happening for me after the fix in that commit.

**Comment by rachelhe123** [comment]
Hi @byronxu99 , Sorry I provide you the wrong hash, I try on commit"[fa541bf95c88ff1e6d2e2d1eea433f44d7fa0638](https://github.com/VowpalWabbit/vowpal_wabbit/commit/fa541bf95c88ff1e6d2e2d1eea433f44d7fa0638)" but still failed as above. 
Please set "**set CL= /fsanitize=address /GS- /wd5072 & set LINK= /InferASanLibs /incremental:no /debug**" before build and runtest.

**Comment by byronxu99** [comment]
Apologies for the long wait, but I believe that this bug is now fixed with the latest commit https://github.com/VowpalWabbit/vowpal_wabbit/commit/57a344b7b998cd521f9bb346f3653b729703ae54.

I have also added a CMake option `-DVW_USE_ASAN=On`, which will automatically add the appropriate flags to enable AddressSanitizer.

Please let us know if you still have further issues.
