### ISSUE TITLE
Regression between version 8.5.0 and version 9.3.0 for csoaa model type

### ISSUE THREAD

**Issue by aakashb-kayzen** [VowpalWabbit/vowpal_wabbit#4239]
### Describe the bug

I am observing significant differences in predictions between versions 8.5.0 and version 9.3.0 for csoaa model type for the same training data. 

E.g.
- Input : 0:1.0, 1:1.0, 2:1.0, 3:1.0, 4:1.0, 5:1.0, 6:1.0, 7:1.0, 8:1.0, 9:1.0, 10:1.0, 11:1.0, 12:1.0, 13:1.0, 14:1.0, 15:1.0, 16:1.0, 17:1.0, 18:1.0, 19:1.0, 20:0.03251999999999981, 21:0.0, 22:0.0, 23:0.0, 24:0.0, 25:0.0, 26:0.0, 27:0.0, 28:0.0, 29:0.0, 30:0.0, 31:0.0, 32:0.0, 33:0.0, 34:0.0, 35:0.0, 36:0.0, 37:0.0, 38:0.0, 39:0.0 |anamespace ab_13176 ac_0 ad_1 ae:2.03252 |bnamespace a_1215933788 |cnamespace b_ni |dnamespace c_117340 |enamespace d_1 |fnamespace e_10035 |gnamespace f_am |hnamespace g_21 af_16 |inamespace h_720 i_1280 j_720_1280 k_2 l_5 |lnamespace m_246_16 |mnamespace n_28630 |nnamespace o:0.524756 p:0.11029643989484672 q:26.2378 r:5.514821994742336 s:0.10000999990000001 t:5.239604797855639 |onamespace u_12 |pnamespace v_9b950c0e6534657589298cc8fe139372 |snamespace w:0 |tnamespace x_0 |unamespace y_246 |wnamespace z_ag |xnamespace aa:0.19085408892084

- Class prediction by 8.5.0 : 2

- Class prediction by 9.3.0 : 23

- Raw output for 8.5.0 : 0:-134.206 1:20.9449 2:-162.022 3:881.778 4:1003.33 5:9042.2 6:733.768 7:579.142 8:47.9718 9:-122.808 10:6.01775 11:4.26306 12:6.26668 13:6.98846 14:4.96666 15:3.3984 16:2.69154 17:2.3806 18:1.58989 19:-1.28363 20:-1.4195 21:-1.00908 22:-1.02458 23:-20.5982 24:-9.58284 25:-3.49755 26:0 27:0 28:0 29:0 30:0 31:0 32:0 33:0 34:0 35:0 36:0 37:0 38:0 39:0

- Raw predictions for 9.3.0 : 0:8.15934 1:7.73265 2:7.83237 3:9.78537 4:10.2686 5:6.10672 6:5.99126 7:6.57223 8:6.18434 9:6.14017 10:5.35966 11:6.39278 12:5.68788 13:4.76606 14:4.96666 15:3.3984 16:2.69154 17:2.3806 18:1.58989 19:1.11503 20:0.0598231 21:-0.801441 22:-0.916524 23:-20.5982 24:-9.58284 25:-3.49755 26:0 27:0 28:0 29:0 30:0 31:0 32:0 33:0 34:0 35:0 36:0 37:0 38:0 39:0

I am providing below : 
- A small subset of the training data (examples_10000_anonymous.txt)
- The model files (model_8.5 and model_9.3)
- The predictions received (predictions8 and predictions9)
- The raw predictions (raw_predictions8 and raw_predictions9)
- The exact commands used for training and prediction.

Commit id for 8.5.0 : 4830cb358adfa4bb013911a08587eb5c656869de
Commit id for 9.3.0 : 36e2335b5234562c1d3c9f71fc6c2936840c45b0

Data files : [csoaa_data.zip](https://github.com/VowpalWabbit/vowpal_wabbit/files/9839193/csoaa_data.zip)

### How to reproduce

Training command : 
- For vw 8.5.0 : vw -d examples_10000_anonymous.txt -f model_8.5 --progress 1.09050773267 -k -c --cache_file cache8 --csoaa 40 -b 24 -q cd -q ce -q cu -q cw -q de -q du -q dw -q eu -q ew -q uw -q n: --ignore a --ignore x

- For vw 9.3.0 : vw -d examples_10000_anonymous.txt -f model_9.3 --progress 1.09050773267 -k -c --cache_file cache9 --csoaa 40 -b 24 -q cd -q ce -q cu -q cw -q de -q du -q dw -q eu -q ew -q uw -q n: --ignore a --ignore x

Prediction commands : 
- For vw 8.5.0 : vw -d examples_10000_anonymous.txt -i model_8.5 -p predictions8
- For vw 9.3.0 : vw -d examples_10000_anonymous.txt -i model_9.3 -p predictions9

### Version

8.5.0 (4830cb358adfa4bb013911a08587eb5c656869de), 9.3.0 (36e2335b5234562c1d3c9f71fc6c2936840c45b0)

### OS

Linux, Mac

### Language

CLI

**Comment by aakashb-kayzen** [comment]
I will be out on vacation till November 1st, 2022. If any additional data is required, I can provide once I am back.

**Comment by ataymano** [comment]
Technically, there is no guarantee to have exactly the same predictions between versions. Do you have any evidence that there is learning performance drop between 2 versions? (in terms of average loss on some dataset).

**Comment by aakashb-kayzen** [comment]
@ataymano : I need to verify the performance drop numbers, I will get back to you with it.

**Comment by jackgerrits** [comment]
@aakashb-kayzen, since we haven't heard from you in some time I am going close this issue. Please feel free to reopen this issue if the numbers show a learning regression here so we can look into it further.
