### ISSUE TITLE
Use CB for campaign recommendation using Vowpal Wabbit when I don't have probabilities in my data

### ISSUE THREAD

**Issue by shubh12et1062** [VowpalWabbit/vowpal_wabbit#4319]
I am working on ad recommendation problem using Contextual bandits . 
I have to recommend ads to my newly onboarded clients based on historical records performance , my train data has actions and cost , with the cost being 1 or 0 ie clicked or not clicked and actions is the arms(aka ads) to recommend , I have 20 ads in my case.

My data looks something like this
`train_data = [{'id' : 'a12','action': 1, 'cost': 1, 'feature1': 'a', 'feature2': 'c', 'feature3': ''},
              {'id' : 'fd2','action': 3, 'cost': 0, 'feature1': 'b', 'feature2': 'd', 'feature3': ''},
              {'id' : 'tr0','action': 4, 'cost': 0, 'feature1': 'a', 'feature2': 'b', 'feature3': ''},
              {'id' : 'y78','action': 2, 'cost': 1, 'feature1': 'a', 'feature2': 'b', 'feature3': 'c'},
              {'id' : 'k565','action': 3, 'cost': 0, 'feature1': 'a', 'feature2': 'd', 'feature3': ''}]
 
test_data = [{'id' : 'f33','feature1': 'b', 'feature2': 'c', 'feature3': ''},
            {'id' : 'q43','feature1': 'a', 'feature2': '', 'feature3': 'b'},
            {'id' : 'r453','feature1': 'b', 'feature2': 'b', 'feature3': ''},
            {'id' : 'r345','feature1': 'a', 'feature2': '', 'feature3': 'b'}]`

From the documentation I can see this:

Context (x): the additional information which helps in choosing action.
Action (a): the action chosen from a set of possible actions A.
Probability (p): the probability of choosing a from A.
Cost/Reward (r): the reward received for action a.

Is the probability parameter necessary in this case or my problem needs to solved by other method ? 

Note this model training and recommendation runs daily

**Comment by olgavrou** [comment]
Closing as duplicate, please feel free to re-open with more details
