### ISSUE TITLE
reporting "current features" with shared features

### ISSUE THREAD

**Issue by martinpopel** [VowpalWabbit/vowpal_wabbit#439]
[shared](http://www.umiacs.umd.edu/~hal/tmp/multiclassVW.html) features are very helpful with `csoaa_ldf`, but the number of "current features" reported by VW is broken.

```
echo '1:0 |T a |S x1 x2 x3
2:1 |T b |S x1 x2 x3

' | vw --csoaa_ldf=m -qST
```

Repeating the shared features on each line manually: reports "current features" = 7 and "total feature number" = 14.

```
echo 'shared |S x1 x2 x3
1:0 |T a
2:1 |T b

' | vw --csoaa_ldf=m -qST
```

Using the "shared" keyword works the same, but the reported number of  "current features" = 1 and "total feature number" = 2.

I would think the two examples above should be equivalent.

Moreover, the "current features" should be equal to the "total feature number" when there is just one (though multiline) example in the dataset ("number of examples per pass" = 1).
- [x] "current features" now include all lines of an ldf example (not just the first line)
- [x] "current features" now include also "shared" features in ldf examples
- [ ] "current features" don't include --quadratic and --cubic features where one namespace is "shared", because VW::setup_example is called before the namespaces from "shared" are added via add_example_namespaces_from_example.

**Comment by JohnLangford** [comment]
Martin, do you see a fix for this?  Seems difficult.

**Comment by JohnLangford** [comment]
Maybe the right thing to do is to move the calculation of the number of features to bottom of the stack rather than the top (as it is at present)?

**Comment by martinpopel** [comment]
Yes, I didn't see any easy solution, so I left this. And yes, moving the calculation in the stack may help, but I was not sure if this does not break other code or make something slower. This is a low priority issue. One solution is just detect shared ldf features and --quadratic or --cubic and report "?" as the number of current features. (I am quite busy next few weeks/months.)

**Comment by JohnLangford** [comment]
The number of features is mostly just used for reporting purposes so moving
it to the bottom of the stack is probably fine w.r.t. the final printout.

However, the intermediate printouts are less clear.  These are typically
handled at the top of the stack, and they report on the example at the top
of the stack for debugging purposes.  In some sense, _all_ the "examples"
which make up an LDF example should be lumped together and reported on
simultaneously.

-John

**Comment by JohnLangford** [comment]
How does this issue interact with Alex's interactionis patch?

**Comment by martinpopel** [comment]
The problem is still here, just with different numbers (because I fixed two of the three issues).

Using *shared* keyword:
```
echo 'shared |S x1 x2 x3
1:0 |T a
2:1 |T b

' | vw --csoaa_ldf=m -qST
```
reports "current features" = 8 and "total feature number" = 8.

Repeating the shared features manually on each line:
```
echo '1:0 |T a |S x1 x2 x3
2:1 |T b |S x1 x2 x3

' | vw --csoaa_ldf=m -qST
```
reports "current features" = 14 and "total feature number" = 14.

I still think the two examples above should be equivalent (report the same number of features).

Analysis:
There is one multi-line example. The first line contains `3+1` single features (S^x1, S^x2, S^x3, T^a) and `3*1` quadratic features `(S^x1*T^a, S^x2*T^a, S^x3*T^a)`, the second line contains also 4 single and 3 quadratic features (just with b instead of a). The constant feature has zero weight (because in csoaa_ldf it is always cancelled out), so it is not included in the counts. So the total number of features of the whole dataset with this one example is `2*7=14`.

When using the *shared* keyword, the quadratic features are not included in the counts, which is an error. 

> How does this issue interact with Alex's interactionis patch?

The problem is still there, but maybe the ways how to fix will be influenced by @trufanov-nok 's patches and `--interactions` code.

**Comment by trufanov-nok** [comment]
Hm, it wasn't supposed to work with features like that...

Let's first find out how big our problem is.
Is it possible that `GD::foreach_feature` could be called for such *shared* example + interactions used?
[Here is](https://github.com/JohnLangford/vowpal_wabbit/search?utf8=%E2%9C%93&q=%22GD%3A%3Aforeach_feature%22&type=Code) a list of modules that uses it.
Bcs `GD::foreach_feature` shoudn't work correctly in such case. The old one shouldn't work either.

**Comment by JohnLangford** [comment]
Martin is correct here---the shared keyword triggers 
"add_example_namespaces_from_example()", and that is not being accounted 
for.

Fixing this however requires some thought.   Presently, the number of 
features in a compound example are added up here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/cost_sensitive.cc#L193
which occurs _after_ del_example_namespaces_from_example().

Perhaps we are computing the number of features in the wrong 
place---instead of computing at the top of the stack, compute when 
features are instantiated and used in predict().

-John

**Comment by trufanov-nok** [comment]
Or we can let reduction to set a new bool setting in vw& that will suppress ft number evaluation in [parser.cc](https://github.com/JohnLangford/vowpal_wabbit/blob/f7cf52ffb7d49bc689898739c59b308d33f5d8fb/vowpalwabbit/parser.cc#L848) and which is off by default. If it's set then the reduction will be accountable for calling
```
size_t new_features_cnt;
  float new_features_sum_feat_sq;
  INTERACTIONS::eval_count_of_generated_ft(all, *ec, new_features_cnt, new_features_sum_feat_sq);
  ec->num_features += new_features_cnt;
  ec->total_sum_feat_sq += new_features_sum_feat_sq;
```
whenever it thinks it's time to do.

**Comment by JohnLangford** [comment]
My feeling is that counting the number of features should not be the responsibility of a reduction.  Instead, it should be managed by the foreach_feature templates which should make it impossible to miscount.

**Comment by JohnLangford** [comment]
I'm keeping this issue alive so it stays on my 'todo' list.  This seems clearly desirable but it touches many pieces of code so it hasn't happened yet.
