### ISSUE TITLE
Testing takes more time than the training

### ISSUE THREAD

**Issue by musram** [VowpalWabbit/vowpal_wabbit#4460]
### Describe the bug

Testing the model with the -t option is taking almost the same time as training the model.

### How to reproduce

for training we use 
/tmp/vw --data " + trainingTextDataLocalPath + " --final_regressor " + newCbModelFileLocalPath + " --hash all --bit_precision 28 -k --passes 5 --holdout_period 7 --onethread --cb_explore_adf -q CH -q CA -q HA -q RA --cb_type dr --save_resume"

for testing we use
"/tmp/vw --data  /tmp/data_test.txt --initial_regressor /tmp/cbmodel -t --hash all --bit_precision 28 -k --passes 1 --onethread -q CH -q CA -q HA -q RA --cb_explore_adf --cb_type dr --save_resume --holdout_off"

### Version

9.0.1

### OS

Linux

### Language

C++

### Additional context

We are using the command for training 
/tmp/vw --data " + trainingTextDataLocalPath + " --final_regressor " + newCbModelFileLocalPath + " --hash all --bit_precision 28 -k --passes 5 --holdout_period 7 --onethread --cb_explore_adf -q CH -q CA -q HA -q RA --cb_type dr --save_resume"

which usually takes 2.3min to build new model

But while testing 

"/tmp/vw --data  /tmp/data_test.txt --initial_regressor /tmp/cbmodel -t --hash all --bit_precision 28 -k --passes 1 --onethread -q CH -q CA -q HA -q RA --cb_explore_adf --cb_type dr --save_resume --holdout_off"

it again takes around 2.3 minutes. I have used -t for testing. It should not take approximately the same time as training.  Maybe we are missing something here.

**Comment by bassmang** [comment]
Hey @musram would you mind attaching the dataset so we can look into this further?

**Comment by bassmang** [comment]
Hi @musram wanted to bring attention to this again. Let me know if you've resolved the issue.

**Comment by peterychang** [comment]
can't repro. Feel free to reopen if this is still a problem and you can provide repro steps
