### ISSUE TITLE
workspace.example() hashes the features differently depending on the input type when a multi-character namespace is used

### ISSUE THREAD

**Issue by ivankolesnikov** [VowpalWabbit/vowpal_wabbit#4478]
### Describe the bug

We observe that `workspace.example(str)` and `workspace.example(dict)` hash the features differently when a multi-character namespace is used.

### How to reproduce

```
from vowpalwabbit import Workspace

ws = Workspace(None)

ex_dict = ws.example({'namespace': {'feature': 1.0}})
ex_dict.setup_example()
print(list(ex_dict.iter_features()))

ex_str = ws.example('|namespace feature:1.0')
print(list(ex_str.iter_features()))
```

outputs different hashes:
```
[(35795, 1.0), (11650396, 1.0)]
[(242309, 1.0), (11650396, 1.0)]
```

But same example with `n` instead of `namespace` produces expected output:
```
[(35795, 1.0), (11650396, 1.0)]
[(35795, 1.0), (11650396, 1.0)]
```

### Version

9.6.0

### OS

macOS

### Language

Python

**Comment by lalo** [comment]
It should use the whole word for the namespace, it uses the first letter for an internal representation.

https://github.com/VowpalWabbit/vowpal_wabbit/blob/07e066fd77350a8ad97de54c36ceac28aacbb043/vowpalwabbit/text_parser/src/parse_example_text.cc#L162

I think the hash [(242309, 1.0), (11650396, 1.0)] produced by ex_str = ws.example('|namespace feature:1.0') should be the one considered 'correct'.

**Comment by lalo** [comment]
It should be fixed, feel free to test again. Either download the latest [wheel](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Python#bleeding-edge-latest-commit-on-master) or wait for the next release.

Thanks for reporting
