### ISSUE TITLE
Version mismatch between Maven and vowpal-wabbit on Mac

### ISSUE THREAD

**Issue by suming** [VowpalWabbit/vowpal_wabbit#4512]
### Describe the bug

Latest artifact on [Maven](https://mvnrepository.com/artifact/com.github.vowpalwabbit/vw-jni) is 9.6.0, but brew install has 9.7.0

### How to reproduce

brew info vowpal-wabbit

### Version

9.6.0

### OS

macOS

### Language

Java

**Comment by suming** [comment]
@jackgerrits any reason the jar it doesn't show up [here](https://mvnrepository.com/artifact/com.github.vowpalwabbit/vw-jni)?

**Comment by jackgerrits** [comment]
Maybe that site takes longer to update. It is available here https://central.sonatype.com/artifact/com.github.vowpalwabbit/vw-jni/9.7.0
