### ISSUE TITLE
Unable to install VowpalWabbit using Python3

### ISSUE THREAD

**Issue by samipak458** [VowpalWabbit/vowpal_wabbit#4541]
### Describe the bug

I'm following the **get started** document, as the document says select configuration then runs a command 
> pip install vowpalwabbit

When I runs the command it shows following error
![image](https://user-images.githubusercontent.com/52650290/228930481-b6adc7f3-0e75-4fc2-8caf-b296f6ba9fd6.png)
![image](https://user-images.githubusercontent.com/52650290/228930626-5e05d569-8529-49e3-9712-0c12e981f8c2.png)

There is might some problem in the package which I'm unable to configure it out. Kindly assist me in this issue.

### How to reproduce

I tried all possible solution but nothing is fixing it.

It also shows a note in the end of the error that *This error originates from a subprocess, and is likely not a problem with pip.*

Here's the screenshot of it:
![image](https://user-images.githubusercontent.com/52650290/228931038-548cb77d-a21f-4517-9a77-43cb03334087.png)

### Version

pip install vowpalwabbit

### OS

Windows

### Language

Python

### Additional context

N/A

**Comment by jackgerrits** [comment]
There are no wheels for Python 3.11 (and so it tries a source build), so downgrading Python should work. There are wheels for 3.6 - 3.10.

You could also try the new experimental bindings which do have 3.11 wheels (https://github.com/VowpalWabbit/py-vowpal-wabbit-next)

**Comment by samipak458** [comment]
I tried 3.11 wheels, it's work and installed but while following the tutorial to get started it showing that **No module named 'vowpalwabbit'**

### Error Screenshot
![image](https://user-images.githubusercontent.com/52650290/229050232-9f542a04-d0d9-42e2-a7de-fc5b56886f10.png)

@jackgerrits can you guide me how to fix it?

Tutorial I followed: https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/tutorials/python_first_steps.html

**Comment by jackgerrits** [comment]
The `vowpal-wabbit-next` package has a similar but different interface to the `vowpalwabbit` package. You can find the docs for the new package here: https://vowpal-wabbit-next.readthedocs.io/en/latest/

**Comment by jackgerrits** [comment]
Closing this, feel free to reopen or open a new issue if you are still facing issues.
