### ISSUE TITLE
[FEATURE]: Pull Request Template

### ISSUE THREAD

**Issue by money8203** [VowpalWabbit/vowpal_wabbit#4545]
## Short description
I would like to suggest that we add a pull request template to the Vowpal's repository to help contributors provide a clear and concise description of their changes. 

## **How this suggestion will help you/others**
This would make it easier for maintainers to review pull requests and ensure that they meet the project's standards.

## **Possible solution/implementation details**
Create a pull_request.md file in .github folder of this repo

## **Example/links if any**
I can work on this if you want!

**Comment by bassmang** [comment]
I think `feat:` / `fix:` is sufficient
