### ISSUE TITLE
Installing problem on M1 MacOS

### ISSUE THREAD

**Issue by HriGrit** [VowpalWabbit/vowpal_wabbit#4551]
### Describe the bug

Upon following the entire detailed [installation](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Building#option-1-using-vcpkg-and-cmake-presets-cmake-320)  process i encountered an error.

I understand the meaning of the error and even asked the same on [stackoverflow](https://stackoverflow.com/questions/75915112/trying-to-fix-the-string-view-lite-package-not-found-error), but couldnt find the solution.

My string-view-lite file is empty and doesnt contain any
string-view-lite-config.cmake file.
<img width="1296" alt="Screenshot 2023-04-04 at 9 51 36 PM" src="https://user-images.githubusercontent.com/86262322/229855354-4de73200-1fbb-45fc-835d-2c56c2eb46aa.png">

### How to reproduce

In the **Option 1** section on the command
```
cmake --preset=vcpkg-release -DBUILD_TESTING=OFF
cmake --build --preset=vcpkg-release
```
The error log came out as
```
CMake Error at ext_libs/ext_libs.cmake:81 (find_package):
  Could not find a package configuration file provided by "string-view-lite"
  with any of the following names:

    string-view-liteConfig.cmake
    string-view-lite-config.cmake

  Add the installation prefix of "string-view-lite" to CMAKE_PREFIX_PATH or
  set "string-view-lite_DIR" to a directory containing one of the above
  files.  If "string-view-lite" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:227 (include)

-- Configuring incomplete, errors occurred!
ninja: error: rebuilding 'build.ninja': 'configure.py', needed by 'build.ninja', missing and no known rule to make it
```

### Version

9.8.0

### OS

macOs

### Language

CLI

**Comment by lalo** [comment]
did you clone with --recursive?

'git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git'

**Comment by HriGrit** [comment]
@lalo i only ran git clone without the recursive tag but, later on i ran 'git submodule update --init --recursive'.

**Comment by jackgerrits** [comment]
For some reason vcpkg didn't run during the configuration step, which is why the packages are not present. Is there an variable in your environment that may have prevented it?

**Comment by jackgerrits** [comment]
Closing this, feel free to reopen or open a new issue if you are still facing issues.
