### ISSUE TITLE
Vowpal_wabbit failed to runtest on MSVC on Windows

### ISSUE THREAD

**Issue by KawasakiNinjaH2R** [VowpalWabbit/vowpal_wabbit#4616]
### Describe the bug

Hi all,

Vowpal_wabbit failed to runtest in release mode and debug mode on Windows, could you please take a look at this issue? Thanks!

### How to reproduce

1. git clone https://github.com/VowpalWabbit/vowpal_wabbit.git F:\gitP\VowpalWabbit\vowpal_wabbit
2. cd F:\gitP\Microsoft\vcpkg
3. bootstrap-vcpkg.bat 2>&1
4. vcpkg.exe install --recurse zlib boost-system boost-program-options boost-test boost-align boost-foreach boost-math boost-python python3 flatbuffers --triplet x64-windows --clean-after-build 2>&1
5. cd F:\gitP\VowpalWabbit\vowpal_wabbit\build_amd64
6. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DUSE_LATEST_STD=ON -Dvw_BUILD_NET_FRAMEWORK=OFF -DBUILD_FLATBUFFERS=OFF -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .. 2>&1
7. msbuild /m /p:Platform=x64 /p:Configuration=Release vowpal_wabbit.sln /t:Rebuild /p:BuildInParallel=true 2>&1
8. ctest --build-config Release --output-on-failure -E "vw_unit_test|vw_c_wrapper_test" > test.log
[test.log](https://github.com/VowpalWabbit/vowpal_wabbit/files/11798281/test.log)

### Version

git commit: 677750e

### OS

Windows + VS2022

### Language

C++

**Comment by bassmang** [comment]
@KawasakiNinjaH2R the problem should be fixed now, let me know if you’re still having issues.

**Comment by KawasakiNinjaH2R** [comment]
Thank you for your fixed. After I updated to the latest commit, I have been able to successfully runtest!
