### ISSUE TITLE
Your domain is only being misused for illegal gambling promotions in Indonesia 

### ISSUE THREAD

**Issue by kutasari** [VowpalWabbit/vowpal_wabbit#4639]
### Describe the bug

Your subdomain is only being misused in Indonesia to promote illegal things 
http://depo25bonus25.vowpalwabbit.org/

### How to reproduce

Ilegal

### Version

9.0.1

### OS

Windows

### Language

Php

**Comment by JohnLangford** [comment]
Thanks.  This is being worked on.  (The situation is a bit complex---it's not a conventional hack.  More like a misappropriation.)
