### ISSUE TITLE
Support for multi-line featuers in --audit_regressor 

### ISSUE THREAD

**Issue by groceryheist** [VowpalWabbit/vowpal_wabbit#4675]
### Describe the bug

I want to analyze a model fit using --cb_explore_adf. I just want to see the feature weights of the final trained model.  I think I can use --invert_hash for this, but I also tried using --audit_regressor and found a bug. 

   [critical] vw (learner.cc:366): Tried to use a multiline learner as a singleline learner. Name: shared_feature_merger

### How to reproduce

Train a model with `--cb_explore_adf`.  
Run 
`./vw -t -i saved_model.model -d saved_data.head --audit_regressor output`

### Version

9.9.0

### OS

Linux

### Language

CLI

**Comment by jackgerrits** [comment]
The error message is correct - when using a multiline learner such as `cb_explore_adf` `--audit_regressor` is not supported. 

`--invert_hash` can be used for inspecting model weights. There is also another set of options for getting this kind of output but in a machine readable JSON format (see [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/JSON-export-of-model-weights)).
