### ISSUE TITLE
Request to daemon hands

### ISSUE THREAD

**Issue by aastafiev** [VowpalWabbit/vowpal_wabbit#4687]
Hello,

While I was reproducing example in [Daemon example](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Daemon-example) I found that after command `echo " abc-example| a b c" | netcat localhost 26542`  the result printed and hands until I Ctrl+C. This happens in python code after I send message and trying to recv.
What I'm doing wrong?

**Comment by aastafiev** [comment]
I put detailed info on [stackoverflow](https://stackoverflow.com/questions/78114882/request-to-vowpal-wabbit-daemon-hands)

**Comment by JohnLangford** [comment]
You need to close the connection so netcat knows to tear things down.  CTRL+C works, but CTRL+D is cleaner.
